// bendrt.h: runtime for C code generated by bendc (the Bend compiler written in Bend).
//
// Values are 64-bit words:
//  - numbers (U32, Char, F32 bits) are stored raw;
//  - a Nat (up to 2^48 - 1, as the official runtime's) is stored raw;
//  - nullary constructors are IMM(tag) = (tag << 3) | 1;
//  - other constructors are pointers to heap nodes {tag, fields...};
//  - closures are pointers to {fn, arity, nargs, args...}.
// A type with one constructor of one field is represented by that field.
//
// Memory is managed by a conservative, non-moving mark-sweep collector. The
// threads that run Bend code (the main thread and the fork-join workers) are
// stopped with a signal while it runs. Parallel lets fork onto a
// work-stealing pool. Effects follow the official Bend runtime's effect ABI
// (Term, Env, IoWork, io_eff, CID_*), so effect sources written for the
// official compiler (Base's own effs/*.c included) compile unchanged.

#ifndef BENDRT_H
#define BENDRT_H

#ifdef __linux__
#define _GNU_SOURCE
#endif
#define _DARWIN_UNLIMITED_SELECT  // select past FD_SETSIZE (io_wait)
#include <stdint.h>
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
#include <pthread.h>
#include <unistd.h>
#include <fcntl.h>
#include <time.h>
#include <errno.h>
#include <setjmp.h>
#include <signal.h>
#include <sched.h>
#include <poll.h>
#include <stdatomic.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/time.h>
#include <sys/select.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <arpa/inet.h>

typedef uint64_t V;
typedef V (*Fn)(V *);
typedef uint64_t u64;
typedef uint32_t u32;
typedef uint16_t u16;
typedef uint8_t u8;
typedef int64_t i64;
typedef int32_t i32;
typedef uint32_t U32;
typedef uint64_t Term;

#define IMM(t) ((((V)(t)) << 3) | 1)
// A node's tag word holds its tag (below 2^20) and two flags (see "Freeing
// on match"): shared, and its fields marked shared too.
#define BEND_SH ((V)1 << 20)
#define BEND_DEEP ((V)1 << 21)
#define BEND_SH_BITS (BEND_SH | BEND_DEEP)
// What a D_ function's node holds where its hole is, until it is filled: a
// word no pointer can be, that the collector looks for (gc_rem).
#define BEND_HOLE IMM(0x7ffff)
// Keeps the compiler from reordering the stores around it (a thread stopped
// by a collection is seen in its program order).
#define BEND_BARRIER() __asm__ volatile("" ::: "memory")
#define FLD(v, i) (((V *)(v))[(i) + 1])
#define BOOL(b) ((b) ? IMM(1) : IMM(0))
// A word's structural view built back: WCon{head, tail} (see Gen.pat.word).
#define word_con(b, r) ((V)(U32)(((U32)(r) << 1) | ((b) == IMM(1))))
#define UNIT IMM(0)
// A call that must compile to a jump (a D_ function's tail call, which
// would otherwise grow the stack by one frame per list element).
#if defined(__has_attribute)
#if __has_attribute(musttail)
#define BEND_MUSTTAIL __attribute__((musttail))
#endif
#endif
#ifndef BEND_MUSTTAIL
#define BEND_MUSTTAIL
#endif
#define LIKELY(x) __builtin_expect(!!(x), 1)
#define UNLIKELY(x) __builtin_expect(!!(x), 0)

#ifdef BEND_DEBUG_FREE
#include <execinfo.h>
// The call stack of each free, by its number (a ring of the last 2^20).
static void *bend_debug_stk[1 << 20][12];
static void bend_debug_record(uint64_t n) {
  void *f[13];
  int k = backtrace(f, 13);
  for (int j = 0; j < 12; j++) bend_debug_stk[n][j] = j + 1 < k ? f[j + 1] : NULL;
}
static void bend_debug_show(uint64_t n) {
  int k = 0;
  while (k < 12 && bend_debug_stk[n][k]) k++;
  fprintf(stderr, "freed from:\n");
  backtrace_symbols_fd(bend_debug_stk[n], k, 2);
}
static inline V TAG(V v) {
  if (v & 1) return v >> 3;
  V t = ((V *)v)[0];
  if ((t >> 48) == 0xDEAD) {
    fprintf(stderr, "bend: a node freed at line %u (free number %llu, thread %02x) is used by thread %02x\n",
      (unsigned)(t & 0xfffff), (unsigned long long)((t >> 20) & 0xfffff), (unsigned)((t >> 40) & 0xff),
      (unsigned)(((uintptr_t)pthread_self() >> 12) & 0xff));
    bend_debug_show((t >> 20) & 0xfffff);
    abort();
  }
  return t & ~BEND_SH_BITS;
}
#define IS_N(v, t) (!((v) & 1) && TAG(v) == (t))
#else
static inline V TAG(V v) { return (v & 1) ? (v >> 3) : ((V *)v)[0] & ~BEND_SH_BITS; }
// A match's test for a constructor with fields: an immediate (a nullary
// constructor) never is one, and a node's tag word is loaded without a
// select, so a match's cases share one load.
static inline int IS_N(V v, V t) { return !(v & 1) && (((V *)v)[0] & ~BEND_SH_BITS) == t; }
#endif

__attribute__((noreturn)) static void bend_fail(const char *msg) {
  fflush(stdout);
  fprintf(stderr, "bend: %s\n", msg);
  exit(1);
}

// Garbage collector
// =================
//
// The heap is one reserved region cut into 64 KB blocks. A small block holds
// slots of one size class; a large object takes whole blocks. Each block
// starts with a header holding an allocation and a mark bitmap. Every word
// of a live object, of a thread's stack and of the registered roots is read
// as a possible pointer; pointers into the middle of an object keep it too.
// A thread allocates from a private free list; the block behind that list
// is not swept until the thread moves on to another one.

#define GC_BLK_SHIFT 16
#define GC_BLK ((uintptr_t)1 << GC_BLK_SHIFT)
#define GC_MAXBLK ((uintptr_t)1 << 22)
#define GC_HDR 64
#define GC_SMALL 2052
#define GC_NCLS 43
#define GC_MAXTHR 256
#define GC_SIG SIGUSR2

typedef struct GcBlk {
  uint32_t words;    // slot size (small) or object size (large), in words
  uint32_t nobj;     // slots in the block (1 for a large object)
  uint32_t nblk;     // blocks spanned
  uint8_t atomic;    // holds no pointers: never scanned
  uint8_t large;
  uint8_t owned;     // in a thread's cache (or being made): not swept, not claimed
  uint8_t cls;
  struct GcBlk *next;
} GcBlk;

// What matches and the collector read most, by block index, in dense tables
// (a block's own header is a page away from most of its objects): a block's
// allocation and mark bits (gc_abits, gc_mbits: 64 words a block), and:
typedef struct GcMeta {
  uint32_t recip;    // 2^32 / slot bytes, rounded up: a slot's index by multiplying
  uint8_t large, pad[3];
} GcMeta;
_Static_assert(sizeof(GcBlk) <= GC_HDR, "GC_HDR holds a block header");

// A thread's allocation cache for one size class: a fresh block is handed out
// by bumping; a partly free one by the free bits of its bitmap, a word at a
// time (the slots are not touched until they are handed out).
typedef struct GcCache {
  V *bump; V *end; GcBlk *blk; V *objs;
  uint8_t reuse;    // the block came from the reuse queue: its slots are not new memory
  uint64_t bits;    // free slots of word j
  uint32_t idx, j, nj;
} GcCache;

struct PDeque;

// Classes of up to 16 words (nodes) reuse the slots matches free.
#define GC_RQCLS 15

typedef struct Thr {
  GcCache cache[2][GC_NCLS];
  uint32_t rcur[GC_RQCLS];  // where the next search for a reuse block starts
  uintptr_t top;
  volatile uintptr_t sp;
  pthread_t id;
  volatile int live;
  struct PDeque *dq;
  uint32_t rng;
  // Claiming a reuse block (gc_refill): a stop signal that comes meanwhile
  // is deferred (deferred is set) until the claim is over.
  volatile sig_atomic_t claiming, deferred;
} Thr;

static void gc_park(Thr *t);

typedef struct { V *p; size_t n; } GcRange;
typedef struct { uint32_t at, len; } GcRun;

static const uint16_t gc_cls_w[GC_NCLS] = {
  2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,
  20, 24, 28, 32, 40, 48, 56, 64, 80, 96, 112, 128, 160, 192, 224, 256,
  320, 384, 448, 516, 640, 768, 896, 1028, 1280, 1536, 1792, 2052};
static uint8_t gc_cls_of[GC_SMALL + 1];

static char *gc_base;
static uint64_t *gc_abits;
static uint64_t *gc_mbits;
static GcMeta *gc_meta;
static uintptr_t gc_top;                // blocks in use (high-water mark)
static uint8_t *gc_kind;                // per block: 0 free, 1 small, 2 large head, 3 large tail
static uint32_t *gc_back;               // large tail: distance back to its head
static GcRun *gc_runs;                  // free block runs below gc_top
static size_t gc_nruns;
static pthread_mutex_t gc_lock = PTHREAD_MUTEX_INITIALIZER;
static GcBlk *gc_partial[2][GC_NCLS];
static _Atomic size_t gc_since;         // bytes handed out since the last collection
static size_t gc_limit = (size_t)256 << 20;
static size_t gc_limit_min = (size_t)256 << 20;
// (Read at start: libc's number parsing takes a lock a stopped thread may hold.)
static double gc_minor_k = 2.0, gc_factor = 0.0;
static size_t gc_slack = (size_t)64 << 20;
static size_t gc_live_bytes;
static size_t gc_major_live;
static int gc_minor;       // this collection keeps the marks of old objects
static int gc_rooting;     // marking from roots (not from objects)
static int gc_all_major;   // BEND_GC_MAJOR: every collection is a major one
static size_t gc_count;
static int gc_stats;
static Thr *gc_thrs[GC_MAXTHR];
static int gc_nthr;
// Nodes with an open hole (BEND_HOLE) that a thread's stack or registers
// pointed to at the last collection, which the next minor collection
// rescans: the only objects written after they are made are the nodes D_
// functions build with a hole, and a node whose hole was open at a
// collection was reachable from a root then (by dst, or, just made, by a
// register of a thread the collection stopped).
static V *gc_rem;
static size_t gc_nrem, gc_caprem;
static V *gc_rem_prev;  // the last collection's, sorted (while this one roots)
static size_t gc_nprev, gc_capprev;
// Per class, a bit per block: matches freed slots in it (GC_CANDW words a
// class).
#define GC_CANDW (GC_MAXBLK / 64)
static uint64_t *gc_cand;
// More than one thread runs Bend code (frees must then be atomic).
static int gc_mt;
// What bend_take and bend_share read, together (one address to load).
typedef struct GcHot {
  uintptr_t base, span;  // the heap: gc_base, and gc_top in bytes
  uint64_t *abits, *cand;
  int mt;
} GcHot;
static GcHot gc_hot;
static GcRange *gc_roots;
static size_t gc_nroots, gc_caproots;
static void (*gc_hooks[16])(void);
static int gc_nhooks;
static _Atomic int gc_stopping, gc_acks, gc_inside;
#ifdef __TINYC__
// tcc has no thread-local storage on every target (none in Mach-O): a
// pthread key holds each thread's slots, and the names stay lvalues.
typedef struct { void *self; int par_depth; } TlsSlots;
static pthread_key_t tls_key;
static pthread_once_t tls_once = PTHREAD_ONCE_INIT;
static void tls_init(void) { pthread_key_create(&tls_key, NULL); }
static TlsSlots *tls_get(void) {
  pthread_once(&tls_once, tls_init);
  TlsSlots *s = (TlsSlots *)pthread_getspecific(tls_key);
  if (!s) {
    s = (TlsSlots *)calloc(1, sizeof *s);
    pthread_setspecific(tls_key, s);
  }
  return s;
}
#define thr_self (*(Thr **)&tls_get()->self)
#define par_depth (tls_get()->par_depth)
#define thr_set(t) (thr_self = (t))
#elif defined(__APPLE__) && defined(__aarch64__)
// A Mach-O thread-local is reached through a call (every allocation reads
// thr_self); a pthread key's slot is one load off the thread's TSD base,
// which is what pthread_getspecific reads.
// (The key is made before main: a thread not registered reads NULL.)
static pthread_key_t thr_key;
__attribute__((constructor)) static void thr_key_init(void) { pthread_key_create(&thr_key, NULL); }
static inline Thr *thr_get(void) {
  uintptr_t tsd;
  __asm__("mrs %0, tpidrro_el0" : "=r"(tsd));
  return ((Thr **)(tsd & ~(uintptr_t)7))[thr_key];
}
#define thr_self (thr_get())
#define thr_set(t) pthread_setspecific(thr_key, (t))
#else
static __thread Thr *thr_self;
#define thr_set(t) (thr_self = (t))
#endif

typedef struct { V *p; size_t n; } GcItem;
static GcItem *gc_stk;
// Per block: an Array in it got a pointer stored since the last collection
// (see arr_put), so a minor one rescans the block's old objects.
static uint8_t *gc_dirty;
static size_t gc_sp, gc_cap;

static void *gc_reserve(size_t bytes, void *hint) {
  void *p = mmap(hint, bytes, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANON | MAP_NORESERVE, -1, 0);
  if (p == MAP_FAILED) { perror("bend: mmap"); exit(1); }
  return p;
}

static void gc_init(void) {
  // A high address keeps small numbers from looking like heap pointers.
  gc_base = gc_reserve(GC_MAXBLK << GC_BLK_SHIFT, (void *)((uintptr_t)1 << 44));
  if ((uintptr_t)gc_base < ((uintptr_t)1 << 32)) bend_fail("the heap must be above 4 GB (bend_share)");
  gc_kind = gc_reserve(GC_MAXBLK, NULL);
  gc_dirty = gc_reserve(GC_MAXBLK, NULL);
  gc_back = gc_reserve(GC_MAXBLK * sizeof(uint32_t), NULL);
  gc_runs = gc_reserve(GC_MAXBLK / 2 * sizeof(GcRun) + 64, NULL);
  gc_cap = ((size_t)1 << 33) / sizeof(GcItem);
  gc_stk = gc_reserve(gc_cap * sizeof(GcItem), NULL);
  gc_abits = gc_reserve(GC_MAXBLK * 64 * sizeof(uint64_t), NULL);
  gc_mbits = gc_reserve(GC_MAXBLK * 64 * sizeof(uint64_t), NULL);
  gc_meta = gc_reserve(GC_MAXBLK * sizeof(GcMeta), NULL);
  gc_cand = gc_reserve(GC_RQCLS * GC_CANDW * sizeof(uint64_t), NULL);
  gc_hot = (GcHot){(uintptr_t)gc_base, 0, gc_abits, gc_cand, 0};
  for (size_t w = 0, c = 0; w <= GC_SMALL; w++) {
    while (gc_cls_w[c] < w) c++;
    gc_cls_of[w] = (uint8_t)c;
  }
  const char *s = getenv("BEND_GC_STATS");
  gc_stats = s && *s;
  gc_all_major = getenv("BEND_GC_MAJOR") != NULL;
  if (getenv("BEND_GC_MINOR")) gc_minor_k = atof(getenv("BEND_GC_MINOR"));
  if (getenv("BEND_GC_FACTOR")) gc_factor = atof(getenv("BEND_GC_FACTOR"));
  if (getenv("BEND_GC_SLACK_MB")) gc_slack = (size_t)atol(getenv("BEND_GC_SLACK_MB")) << 20;
  const char *m = getenv("BEND_GC_MIN_MB");
  if (m && atol(m) > 0) gc_limit = gc_limit_min = (size_t)atol(m) << 20;
}

static inline GcBlk *gc_blk(uintptr_t i) { return (GcBlk *)(gc_base + (i << GC_BLK_SHIFT)); }
static inline uintptr_t gc_bi(const GcBlk *b) { return ((uintptr_t)b - (uintptr_t)gc_base) >> GC_BLK_SHIFT; }
#define GC_ALLOC(b) (gc_abits + gc_bi(b) * 64)
#define GC_MARK(b) (gc_mbits + gc_bi(b) * 64)
#define GC_META(b) (&gc_meta[gc_bi(b)])
static inline V *gc_objs(GcBlk *b) { return (V *)((char *)b + GC_HDR); }

// Takes n contiguous free blocks (gc_lock held).
static uintptr_t gc_take_blocks(size_t n) {
  for (size_t i = 0; i < gc_nruns; i++) {
    if (gc_runs[i].len >= n) {
      uintptr_t at = gc_runs[i].at;
      gc_runs[i].at += (uint32_t)n;
      gc_runs[i].len -= (uint32_t)n;
      if (gc_runs[i].len == 0) gc_runs[i] = gc_runs[--gc_nruns];
      return at;
    }
  }
  if (gc_top + n > GC_MAXBLK) bend_fail("out of memory");
  uintptr_t at = gc_top;
  gc_top += n;
  gc_hot.span = gc_top << GC_BLK_SHIFT;
  return at;
}

static void gc_collect_locked(void);

static GcBlk *gc_new_small(int atomic, unsigned c) {
  uintptr_t at = gc_take_blocks(1);
  GcBlk *b = gc_blk(at);
  memset(b, 0, sizeof(GcBlk));
  memset(GC_ALLOC(b), 0, 64 * sizeof(uint64_t));
  memset(GC_MARK(b), 0, 64 * sizeof(uint64_t));
  b->words = gc_cls_w[c];
  b->nobj = (uint32_t)((GC_BLK - GC_HDR) / (b->words * 8));
  *GC_META(b) = (GcMeta){(uint32_t)(((uint64_t)1 << 32) / (b->words * 8)) + 1, 0, {0}};
  b->nblk = 1;
  b->atomic = (uint8_t)atomic;
  b->cls = (uint8_t)c;
  b->owned = 1;
  __atomic_store_n(&gc_kind[at], 1, __ATOMIC_RELEASE);
  return b;
}

// The next word of free bits in the cache's block; 0 when none is left.
// The free slots' marks go here too: a slot handed out is young (bend_take_at
// leaves a freed slot's mark when other threads run), or a minor collection
// would take the new object for an old one and not trace what it holds.
static inline uint64_t gc_next_bits(GcCache *k) {
  GcBlk *b = k->blk;
  while (++k->j < k->nj) {
    uint64_t f = ~__atomic_load_n(&GC_ALLOC(b)[k->j], __ATOMIC_RELAXED);
    if (k->j == (b->nobj >> 6)) f &= (1ull << (b->nobj & 63)) - 1;
    if (f) {
      uint64_t *m = &GC_MARK(b)[k->j];
      if (__atomic_load_n(m, __ATOMIC_RELAXED) & f) __atomic_fetch_and(m, ~f, __ATOMIC_RELAXED);
      return f;
    }
  }
  return 0;
}

// Slow path: the rest of the block's free words, or another block.
__attribute__((noinline)) static V *gc_refill(GcCache *k, int atomic, unsigned c) {
  size_t sw = gc_cls_w[c];
  if (k->blk && (k->bits = gc_next_bits(k))) {
    int t = __builtin_ctzll(k->bits);
    k->bits &= k->bits - 1;
    uint32_t i = k->j * 64 + (uint32_t)t;
    V *p = k->objs + (size_t)i * sw;
    p[0] = BEND_HOLE;
    BEND_BARRIER();
    GC_ALLOC(k->blk)[i >> 6] |= 1ull << (i & 63);
    if (!k->reuse)
      atomic_fetch_add_explicit(&gc_since, ((size_t)__builtin_popcountll(k->bits) + 1) * sw * sizeof(V),
        memory_order_relaxed);
    return p;
  }
  if (k->blk) { __atomic_store_n(&k->blk->owned, 0, __ATOMIC_RELEASE); k->blk = NULL; }
  // First the next block, in address order, where matches freed slots and a
  // 5th is free: lists built from its free slots stay in order in memory.
  // Candidate bits may be stale; the block is checked here. A block is
  // claimed by setting its owned flag (0 to 1), without gc_lock: no
  // collection runs meanwhile (the thread's stop is deferred), so a block
  // that is a small one stays one, and a new one is owned before it is one.
  GcBlk *b = NULL;
  k->reuse = 0;
  if (!atomic && c < GC_RQCLS) {
    Thr *t = thr_self;
    t->claiming = 1;
    atomic_signal_fence(memory_order_seq_cst);
    uint64_t *cand = gc_cand + (size_t)c * GC_CANDW;
    uintptr_t nw = (gc_top + 63) >> 6;
    uintptr_t at = t->rcur[c] < gc_top ? t->rcur[c] : 0;
    for (uintptr_t n = 0; b == NULL && n <= nw; n++) {
      uintptr_t w = ((at >> 6) + n) % (nw ? nw : 1);
      uint64_t f = cand[w];
      if (n == 0) f &= ~0ull << (at & 63);
      while (f && b == NULL) {
        uintptr_t bi = (w << 6) + (uintptr_t)__builtin_ctzll(f);
        f &= f - 1;
        __atomic_fetch_and(&cand[w], ~(1ull << (bi & 63)), __ATOMIC_RELAXED);
        if (bi >= gc_top || __atomic_load_n(&gc_kind[bi], __ATOMIC_ACQUIRE) != 1) continue;
        GcBlk *q = gc_blk(bi);
        if (q->cls != c || q->atomic || __atomic_load_n(&q->owned, __ATOMIC_RELAXED)) continue;
        uint8_t z = 0;
        if (!__atomic_compare_exchange_n(&q->owned, &z, 1, 0, __ATOMIC_ACQ_REL, __ATOMIC_RELAXED)) continue;
        uint32_t used = 0;
        for (int j = 0; j < 64; j++) used += (uint32_t)__builtin_popcountll(GC_ALLOC(q)[j]);
        if (q->nobj - used < q->nobj / 5) { __atomic_store_n(&q->owned, 0, __ATOMIC_RELEASE); continue; }
        b = q;
        k->reuse = 1;
        t->rcur[c] = (uint32_t)bi + 1;
      }
    }
    atomic_signal_fence(memory_order_seq_cst);
    t->claiming = 0;
    atomic_signal_fence(memory_order_seq_cst);
    if (t->deferred) { t->deferred = 0; gc_park(t); }
  }
  int fresh = 0;
  if (b == NULL) {
    pthread_mutex_lock(&gc_lock);
    if (gc_since >= gc_limit) gc_collect_locked();
    // (A partly free block may have been claimed for reuse since the sweep.)
    b = gc_partial[atomic][c];
    uint8_t z = 0;
    while (b && !__atomic_compare_exchange_n(&b->owned, &z, 1, 0, __ATOMIC_ACQ_REL, __ATOMIC_RELAXED)) {
      b = b->next;
      z = 0;
    }
    fresh = b == NULL;
    if (b) gc_partial[atomic][c] = b->next;
    else b = gc_new_small(atomic, c);
    pthread_mutex_unlock(&gc_lock);
  }
  k->blk = b;
  // A slot's allocation bit is set when the slot is handed out, never
  // before: a stale pointer must not mark a slot that is still free.
  V *objs = gc_objs(b);
  k->objs = objs;
  k->nj = (b->nobj + 63) >> 6;
  if (fresh) {
    // A fresh block is handed out by bumping a pointer.
    atomic_fetch_add_explicit(&gc_since, (size_t)b->nobj * sw * sizeof(V), memory_order_relaxed);
    k->bits = 0;
    k->j = k->nj;
    k->bump = objs + sw;
    k->end = objs + (size_t)b->nobj * sw;
    k->idx = 1;
    objs[0] = BEND_HOLE;
    BEND_BARRIER();
    GC_ALLOC(b)[0] |= 1;
    return objs;
  }
  k->bump = k->end = NULL;
  k->j = (uint32_t)-1;
  k->bits = 0;
  return gc_refill(k, atomic, c);
}

__attribute__((noinline)) static V *gc_alloc_large(size_t w, int atomic) {
  size_t n = (GC_HDR + w * sizeof(V) + GC_BLK - 1) >> GC_BLK_SHIFT;
  pthread_mutex_lock(&gc_lock);
  if (gc_since >= gc_limit) gc_collect_locked();
  uintptr_t at = gc_take_blocks(n);
  GcBlk *b = gc_blk(at);
  memset(b, 0, sizeof(GcBlk));
  memset(GC_ALLOC(b), 0, 64 * sizeof(uint64_t));
  memset(GC_MARK(b), 0, 64 * sizeof(uint64_t));
  *GC_META(b) = (GcMeta){0, 1, {0}};
  b->words = (uint32_t)w;
  b->nobj = 1;
  b->nblk = (uint32_t)n;
  b->atomic = (uint8_t)atomic;
  b->large = 1;
  memset(gc_objs(b), 0, w * sizeof(V));
  gc_objs(b)[0] = BEND_HOLE;
  BEND_BARRIER();
  GC_ALLOC(b)[0] = 1;
  gc_kind[at] = 2;
  for (size_t j = 1; j < n; j++) { gc_kind[at + j] = 3; gc_back[at + j] = (uint32_t)j; }
  atomic_fetch_add_explicit(&gc_since, n * GC_BLK, memory_order_relaxed);
  pthread_mutex_unlock(&gc_lock);
  return gc_objs(b);
}

// A slot is not cleared when freed: the words of a class slot past the
// object's own are cleared here, so stale words never look like pointers.
// hole: a D_ node (a constant): its tag word holds BEND_HOLE before the slot
// is allocated, so no collection sees it without (see gc_rem).
static inline V *gc_alloc_x(size_t w, int atomic, int hole) {
  if (UNLIKELY(w > GC_SMALL)) return gc_alloc_large(w, atomic);
  unsigned c = w >= 2 && w <= 16 ? (unsigned)w - 2 : gc_cls_of[w];
  GcCache *k = &thr_self->cache[atomic][c];
  V *p;
  if (k->bump < k->end) {
    p = k->bump;
    k->bump += gc_cls_w[c];
    uint32_t i = k->idx++;
    if (hole) { p[0] = BEND_HOLE; BEND_BARRIER(); }
    GC_ALLOC(k->blk)[i >> 6] |= 1ull << (i & 63);
  } else if (k->bits) {
    int t = __builtin_ctzll(k->bits);
    k->bits &= k->bits - 1;
    uint32_t i = k->j * 64 + (uint32_t)t;
    p = k->objs + (size_t)i * gc_cls_w[c];
    if (hole) { p[0] = BEND_HOLE; BEND_BARRIER(); }
    GC_ALLOC(k->blk)[i >> 6] |= 1ull << (i & 63);
  } else {
    p = gc_refill(k, atomic, c);
  }
  if (!hole) p[0] = 0;
  p[1] = 0;
  if (!(w >= 2 && w <= 16))
    for (size_t j = w; j < gc_cls_w[c]; j++) p[j] = 0;
  return p;
}

static inline V *gc_alloc(size_t w, int atomic) { return gc_alloc_x(w, atomic, 0); }
static inline V *halloc(size_t words) { return gc_alloc_x(words, 0, 0); }
static inline V *halloc_hole(size_t words) { return gc_alloc_x(words, 0, 1); }

// Freeing on match
// ----------------
//
// Bend values are affine: a value has one owner unless it went through a
// variable used more than once. Generated code marks such values shared
// (bend_share) where the variable is bound, and a match that opens a node
// hands it to bend_take: a shared node stays (and the fields it hands out
// become shared too), any other is dead once its fields are read, so its slot
// goes on the thread's free list, and the next allocation of its size takes
// it. A reused slot's mark is cleared: it holds a young object for minor
// collections. The free lists are roots, so a collection keeps them.

// The small block and slot index of a heap object, or 0 when v is not one.
static inline GcBlk *gc_slot(V v, uint32_t *idx) {
  uintptr_t off = (uintptr_t)v - (uintptr_t)gc_base;
  if (UNLIKELY(off >= (gc_top << GC_BLK_SHIFT))) return NULL;
  uintptr_t bi = off >> GC_BLK_SHIFT;
  if (UNLIKELY(gc_kind[bi] != 1)) return NULL;
  GcBlk *b = gc_blk(bi);
  *idx = (uint32_t)(((uint64_t)((uintptr_t)v - (uintptr_t)gc_objs(b)) * GC_META(b)->recip) >> 32);
  return b;
}

// Marks a value shared: a node by its tag word, a closure by its captured
// values (calling it twice hands them out twice). Anything else (a number
// that falls in the heap, say) is left alone: the value must be the start of
// an allocated object.
__attribute__((noinline)) static void bend_share_slow(V v) {
  uint32_t i;
  GcBlk *b = gc_slot(v, &i);
  if (b == NULL) {
    uintptr_t off = (uintptr_t)v - (uintptr_t)gc_base;
    uintptr_t bi = off >> GC_BLK_SHIFT;
    uint8_t kd = gc_kind[bi];
    if (kd != 2 && kd != 3) return;
    if (kd == 3) bi -= gc_back[bi];
    b = gc_blk(bi);
    i = 0;
  }
  if (i >= b->nobj || b->atomic) return;
  if ((uintptr_t)v != (uintptr_t)gc_objs(b) + (uintptr_t)i * b->words * sizeof(V)) return;
  if (!(GC_ALLOC(b)[i >> 6] & (1ull << (i & 63)))) return;
  V *p = (V *)v;
  V w0 = __atomic_load_n(&p[0], __ATOMIC_RELAXED);
  if (w0 >= ((V)1 << 22)) {
    V n = p[2];
    if (b->words >= 3 && n <= (V)b->words - 3)
      for (V j = 0; j < n; j++)
        if (p[3 + j] >= ((V)1 << 32)) bend_share_slow(p[3 + j]);  // numbers are no nodes
  } else if (!(w0 & BEND_SH)) {
    __atomic_fetch_or(&p[0], BEND_SH, __ATOMIC_RELAXED);
  }
}

// Numbers, characters and nullary constructors are below 2^32, and the heap
// above (gc_init); a node already shared says so in its tag word (reading any
// heap address is safe; writing needs the checks above).
static inline void bend_share(V v) {
  if (v < ((V)1 << 32) || (uintptr_t)v - gc_hot.base >= gc_hot.span) return;
  V w0 = __atomic_load_n((V *)v, __ATOMIC_RELAXED);
  if ((w0 & BEND_SH) && w0 < ((V)1 << 22)) return;
  bend_share_slow(v);
}

// A shared node's fields, marked shared once: after them, the node's
// BEND_DEEP (a thread that sees it sees them marked).
__attribute__((noinline)) static void bend_deep(V v, unsigned w) {
  V *p = (V *)v;
  for (unsigned j = 1; j < w; j++) bend_share(p[j]);
  __atomic_fetch_or(&p[0], BEND_SH | BEND_DEEP, __ATOMIC_RELEASE);
}

// A match opened node v, of w words, after reading its fields: 1 when it is
// shared (its fields are then shared too), else 0 and its slot is freed, and
// its block a reuse candidate for its class (gc_refill takes it when a 5th of
// it is free). Nodes of up to 16 words are in small blocks whose slots are
// exactly their size; larger ones are never freed.
static inline int bend_take_at(V v, unsigned w, unsigned line) {
  const GcHot *h = &gc_hot;
  V w0 = h->mt ? __atomic_load_n((V *)v, __ATOMIC_ACQUIRE) : __atomic_load_n((V *)v, __ATOMIC_RELAXED);
  if (w0 & BEND_SH) {
    if (!(w0 & BEND_DEEP)) bend_deep(v, w);
    return 1;
  }
  uintptr_t off = (uintptr_t)v - h->base;
  if (UNLIKELY(off >= h->span || w > 16)) { bend_deep(v, w); return 1; }
  uintptr_t bi = off >> GC_BLK_SHIFT;
  uint32_t i = (uint32_t)(((off & (GC_BLK - 1)) - GC_HDR) / (w * sizeof(V)));
  uint64_t bit = 1ull << (i & 63);
  uint64_t *aw = &h->abits[bi * 64 + (i >> 6)];
#ifdef BEND_DEBUG_FREE
  // Debugging: the node is poisoned with the line that freed it and the
  // free's number, and kept. BEND_DEBUG_FREE_AT=n aborts at free number n.
  {
    static uint64_t nfreed;
    static long stop = -2;
    if (stop == -2) stop = getenv("BEND_DEBUG_FREE_AT") ? atol(getenv("BEND_DEBUG_FREE_AT")) : -1;
    nfreed++;
    if ((long)nfreed == stop) abort();
    V who = (V)(((uintptr_t)pthread_self() >> 12) & 0xff);
    bend_debug_record(nfreed & 0xfffff);
    for (unsigned j = 0; j < w; j++) ((V *)v)[j] = ((V)0xDEAD << 48) | (who << 40) | ((nfreed & 0xfffff) << 20) | line;
    (void)bit; (void)aw;
  }
  return 0;
#endif
  (void)line;
  uint64_t *cw = &h->cand[(size_t)(w - 2) * GC_CANDW + (bi >> 6)];
  // A freed slot is young when it is handed out again. On one thread its
  // mark goes here; when other threads run, the thread that hands the slot
  // out clears it (gc_next_bits): cleared here, after the allocation bit, it
  // could be the mark of the object another thread made in the slot since
  // and a collection marked old, which the next minor collection would then
  // not trace from (tests/par_reuse.bend).
  uint64_t *mw = &gc_mbits[bi * 64 + (i >> 6)];
  if (UNLIKELY(h->mt)) {
    __atomic_fetch_and(aw, ~bit, __ATOMIC_RELAXED);
    // (a sample of the frees keeps the shared candidate words cool)
    if ((i & 15) == 0 && !(*cw & (1ull << (bi & 63))))
      __atomic_fetch_or(cw, 1ull << (bi & 63), __ATOMIC_RELAXED);
  } else {
    *aw &= ~bit;
    *mw &= ~bit;
    *cw |= 1ull << (bi & 63);
  }
  return 0;
}

// With BEND_DEBUG_FREE, a freed node records the generated C line that
// freed it, and TAG reports a read of one.
#ifdef BEND_DEBUG_FREE
#define bend_take(v, w) bend_take_at(v, w, __LINE__)
#else
#define bend_take(v, w) bend_take_at(v, w, 0)
#endif

// A flat result (a def's U_ function): node t's k fields go out through o,
// then t is taken when matches free (a shared node shares its fields).
static inline void bend_open(V t, V *o, unsigned k, int take) {
  for (unsigned i = 0; i < k; i++) o[i] = FLD(t, i);
  if (take) bend_take(t, k + 1);
}

// Registers words that hold values (a global cache, say) as roots.
static void gc_root_add_locked(V *p, size_t n) {
  if (gc_nroots == gc_caproots) {
    gc_caproots = gc_caproots ? gc_caproots * 2 : 256;
    gc_roots = realloc(gc_roots, gc_caproots * sizeof(GcRange));
  }
  gc_roots[gc_nroots++] = (GcRange){p, n};
}

static void gc_root_add(V *p, size_t n) {
  pthread_mutex_lock(&gc_lock);
  gc_root_add_locked(p, n);
  pthread_mutex_unlock(&gc_lock);
}

static void gc_hook(void (*f)(void)) { gc_hooks[gc_nhooks++] = f; }

// Whether a root's object may still get written: it holds BEND_HOLE, an open
// hole of a D_ node (or it is still being made: see gc_alloc and C2).
static int gc_rem_wants(GcBlk *b, uint32_t i, uint64_t bit, uintptr_t o) {
  (void)bit;
  V *p = (V *)(o + i * (uintptr_t)b->words * sizeof(V));
  for (uint32_t j = 0; j < b->words; j++)
    if (p[j] == BEND_HOLE) return 1;
  return 0;
}

static inline void gc_mark(V w) {
  uintptr_t a = (uintptr_t)(w & 0x7fffffffffffffffull);
  uintptr_t off = a - (uintptr_t)gc_base;
  if (off >= (gc_top << GC_BLK_SHIFT)) return;
  uintptr_t bi = off >> GC_BLK_SHIFT;
  uint8_t kd = gc_kind[bi];
  if (kd == 0) return;
  if (kd == 3) bi -= gc_back[bi];
  GcBlk *b = gc_blk(bi);
  uintptr_t o = (uintptr_t)gc_objs(b);
  // A large object's header counts as the object: gc_alloc_large returns
  // gc_objs(b) after it unlocks, so a thread stopped in the unlock holds b.
  if (a < o && !b->large) return;
  size_t i = 0;
  if (b->large) {
    if (a >= o + (uintptr_t)b->words * sizeof(V)) return;
  } else {
    i = (a - o) / ((uintptr_t)b->words * sizeof(V));
    if (i >= b->nobj) return;
  }
  uint64_t bit = 1ull << (i & 63);
  if (!(GC_ALLOC(b)[i >> 6] & bit)) return;
  if (gc_rooting == 1 && !b->atomic && !b->large && gc_rem_wants(b, i, bit, o)) {
    if (gc_nrem == gc_caprem) {
      gc_caprem = gc_caprem ? gc_caprem * 2 : 256;
      gc_rem = realloc(gc_rem, gc_caprem * sizeof(V));
    }
    gc_rem[gc_nrem++] = (V)(o + i * (uintptr_t)b->words * sizeof(V));
  }
  // A minor collection scans an old object met from a root once more: its
  // fields may have been written after it got old.
  if ((GC_MARK(b)[i >> 6] & bit) && !(gc_minor && gc_rooting)) return;
  GC_MARK(b)[i >> 6] |= bit;
  if (b->atomic) return;
  if (gc_sp == gc_cap) bend_fail("the collector's mark stack overflowed");
  gc_stk[gc_sp++] = (GcItem){(V *)(o + i * (uintptr_t)b->words * sizeof(V)), b->words};
}

static void gc_scan(const void *lo, const void *hi) {
  uintptr_t a = ((uintptr_t)lo + 7) & ~(uintptr_t)7;
  for (const V *p = (const V *)a; (const void *)p < hi; p++) gc_mark(*p);
}

static void gc_drain(void) {
  while (gc_sp > 0) {
    GcItem it = gc_stk[--gc_sp];
    for (size_t j = 0; j < it.n; j++) gc_mark(it.p[j]);
  }
}

// A thread stopped for a collection: its registers on its stack, it waits.
__attribute__((noinline)) static void gc_park(Thr *t) {
  jmp_buf jb;
  setjmp(jb);
  atomic_fetch_add(&gc_inside, 1);
  t->sp = (uintptr_t)&jb;
  atomic_fetch_add(&gc_acks, 1);
  while (atomic_load(&gc_stopping)) sched_yield();
  atomic_fetch_sub(&gc_inside, 1);
}

static void gc_handler(int sig) {
  (void)sig;
  int saved = errno;
  Thr *t = thr_self;
  if (t != NULL && atomic_load(&gc_stopping)) {
    if (t->claiming) t->deferred = 1;
    else gc_park(t);
  }
  errno = saved;
}

static void gc_sweep(void) {
  memset(gc_partial, 0, sizeof gc_partial);
  size_t live = 0;
  for (uintptr_t bi = 0; bi < gc_top; bi++) {
    uint8_t kd = gc_kind[bi];
    if (kd == 1) {
      GcBlk *b = gc_blk(bi);
      if (b->owned) {
        live += GC_BLK;
        continue;
      }
      // What survives stays marked: it is old for the next minor collection.
      size_t used = 0;
      int words = (int)((b->nobj + 63) >> 6);
      for (int j = 0; j < words; j++) {
        GC_ALLOC(b)[j] &= GC_MARK(b)[j];
        used += (size_t)__builtin_popcountll(GC_ALLOC(b)[j]);
      }
      if (used == 0) {
        gc_kind[bi] = 0;
      } else {
        live += used * b->words * sizeof(V);
        if (used < b->nobj) {
          b->next = gc_partial[b->atomic][b->cls];
          gc_partial[b->atomic][b->cls] = b;
        }
      }
    } else if (kd == 2) {
      GcBlk *b = gc_blk(bi);
      if (GC_MARK(b)[0] & 1) {
        live += (size_t)b->nblk * GC_BLK;
      } else {
        for (uint32_t j = 0; j < b->nblk; j++) gc_kind[bi + j] = 0;
      }
      bi += b->nblk - 1;
    }
  }
  // Free runs, rebuilt from the block kinds.
  while (gc_top > 0 && gc_kind[gc_top - 1] == 0) gc_top--;
  gc_hot.span = gc_top << GC_BLK_SHIFT;
  gc_nruns = 0;
  for (uintptr_t bi = 0; bi < gc_top;) {
    if (gc_kind[bi] != 0) { bi++; continue; }
    uintptr_t at = bi;
    while (bi < gc_top && gc_kind[bi] == 0) bi++;
    gc_runs[gc_nruns++] = (GcRun){(uint32_t)at, (uint32_t)(bi - at)};
    // Hand the pages of long runs back to the system when the heap is far
    // larger than what lives in it.
    if (bi - at >= 256 && ((gc_top - bi + at) << GC_BLK_SHIFT) > 4 * live + ((size_t)1 << 30))
      madvise(gc_base + (at << GC_BLK_SHIFT), (bi - at) << GC_BLK_SHIFT, MADV_DONTNEED);
  }
  gc_live_bytes = live;
}

static int gc_rem_cmp(const void *a, const void *b) {
  V x = *(const V *)a, y = *(const V *)b;
  return x < y ? -1 : x > y;
}

// A stack holds many pointers to the same objects: each is kept once.
static void gc_rem_unique(void) {
  if (gc_nrem < 2) return;
  qsort(gc_rem, gc_nrem, sizeof(V), gc_rem_cmp);
  size_t n = 1;
  for (size_t i = 1; i < gc_nrem; i++)
    if (gc_rem[i] != gc_rem[n - 1]) gc_rem[n++] = gc_rem[i];
  gc_nrem = n;
}

// The old objects of blocks an Array store dirtied, rescanned by a minor
// collection (a major one scans everything live); the marks are cleared.
// A store marks its block before it writes, so a collection that stops the
// thread in between rescans the block, and the value about to be stored is
// in the thread's registers or stack: marked then, and old after.
static void gc_rescan_dirty(void) {
  for (uintptr_t bi = 0; bi < gc_top; bi++) {
    if (!gc_dirty[bi]) continue;
    gc_dirty[bi] = 0;
    if (!gc_minor) continue;
    GcBlk *b = gc_blk(bi);
    uint64_t *al = GC_ALLOC(b), *mk = GC_MARK(b);
    if (gc_kind[bi] == 2) {
      if ((al[0] & mk[0] & 1) && !b->atomic) {
        if (gc_sp == gc_cap) bend_fail("the collector's mark stack overflowed");
        gc_stk[gc_sp++] = (GcItem){gc_objs(b), b->words};
      }
    } else if (gc_kind[bi] == 1 && !b->atomic) {
      for (uint32_t i = 0; i < b->nobj; i++) {
        if (!(al[i >> 6] & mk[i >> 6] & (1ull << (i & 63)))) continue;
        if (gc_sp == gc_cap) bend_fail("the collector's mark stack overflowed");
        gc_stk[gc_sp++] = (GcItem){gc_objs(b) + (size_t)i * b->words, b->words};
      }
    }
  }
}

__attribute__((noinline)) static void gc_collect_locked(void) {
  Thr *me = thr_self;
  struct timespec t0, t1;
  if (gc_stats) clock_gettime(CLOCK_MONOTONIC, &t0);
  atomic_store(&gc_acks, 0);
  atomic_store(&gc_stopping, 1);
  int n = 0;
  for (int i = 0; i < gc_nthr; i++) {
    Thr *t = gc_thrs[i];
    if (t != me && t->live) {
      if (pthread_kill(t->id, GC_SIG) == 0) n++;
    }
  }
  while (atomic_load(&gc_acks) < n) sched_yield();
  jmp_buf jb;
  setjmp(jb);
  me->sp = (uintptr_t)&jb;
  // A major collection forgets every mark; a minor one keeps the old
  // objects' (the heap is written only while an object is built, and the
  // exceptions are reached from roots).
  gc_minor = !gc_all_major && gc_major_live > 0 && gc_live_bytes < (size_t)(gc_minor_k * (double)gc_major_live) + gc_slack;
  if (!gc_minor) {
    for (uintptr_t bi = 0; bi < gc_top; bi++) {
      if (gc_kind[bi] == 1 || gc_kind[bi] == 2) memset(gc_mbits + bi * 64, 0, 64 * sizeof(uint64_t));
    }
  }
  gc_rooting = 1;
  {
    // The last collection's list becomes gc_rem_prev (sorted by
    // gc_rem_unique); this one records into gc_rem.
    V *t = gc_rem_prev; gc_rem_prev = gc_rem; gc_rem = t;
    size_t c = gc_capprev; gc_capprev = gc_caprem; gc_caprem = c;
    gc_nprev = gc_nrem;
    gc_nrem = 0;
    gc_rooting = 2;  // rescanned, not recorded again
    if (gc_minor) for (size_t i = 0; i < gc_nprev; i++) gc_mark(gc_rem_prev[i]);
    gc_rooting = 1;
  }
  for (int i = 0; i < gc_nthr; i++) {
    Thr *t = gc_thrs[i];
    if (t->live) gc_scan((const void *)t->sp, (const void *)t->top);
  }
  gc_rem_unique();
  gc_rooting = 3;  // other roots hold no half-made nodes
  for (size_t i = 0; i < gc_nroots; i++) gc_scan(gc_roots[i].p, gc_roots[i].p + gc_roots[i].n);
  for (int i = 0; i < gc_nhooks; i++) gc_hooks[i]();
  gc_rooting = 0;
  gc_rescan_dirty();
  gc_drain();
  gc_sweep();
  atomic_store(&gc_stopping, 0);
  while (atomic_load(&gc_inside) > 0) sched_yield();
  if (!gc_minor) gc_major_live = gc_live_bytes ? gc_live_bytes : 1;
  {
    size_t want = (size_t)(gc_factor * (double)gc_live_bytes);
    gc_limit = want > gc_limit_min ? want : gc_limit_min;
  }
  gc_since = 0;
  gc_count++;
  if (gc_stats) {
    clock_gettime(CLOCK_MONOTONIC, &t1);
    fprintf(stderr, "[gc %zu %s] live %zu MB, heap %zu MB, next at +%zu MB, %zu rescans next, %.1f ms\n",
      gc_count, gc_minor ? "minor" : "major", gc_live_bytes >> 20, (size_t)(gc_top << GC_BLK_SHIFT) >> 20,
      gc_limit >> 20, gc_nrem,
      (t1.tv_sec - t0.tv_sec) * 1e3 + (t1.tv_nsec - t0.tv_nsec) / 1e6);
  }
}

// Collects now (from a thread that runs Bend code).
static void gc_collect(void) {
  pthread_mutex_lock(&gc_lock);
  gc_collect_locked();
  pthread_mutex_unlock(&gc_lock);
}

static struct PDeque *pdq_new(void);

// Registers the calling thread; top is an address near the base of its stack.
// A fault (a deep recursion past the machine stack, most likely) reports
// as the official runtime does, not as a bare signal; it runs on a stack
// of its own, since the thread's is the one that ran out.
static void bend_fault(int sig) {
  (void)sig;
  static const char msg[] = "bend: memory fault (machine stack overflow?)\n";
  fflush(stdout);
  if (write(2, msg, sizeof msg - 1) < 0) {}
  _exit(1);
}

static void fault_stack(void) {
  stack_t ss;
  ss.ss_size = 1 << 16;
  ss.ss_sp = malloc(ss.ss_size);
  ss.ss_flags = 0;
  if (ss.ss_sp) sigaltstack(&ss, NULL);
}

static void fault_init(void) {
  struct sigaction sa;
  memset(&sa, 0, sizeof sa);
  sa.sa_handler = bend_fault;
  sa.sa_flags = SA_ONSTACK;
  sigemptyset(&sa.sa_mask);
  sigaction(SIGSEGV, &sa, NULL);
  sigaction(SIGBUS, &sa, NULL);
}

static void thr_register(uintptr_t top) {
  fault_stack();
  Thr *t = calloc(1, sizeof(Thr));
  t->top = top;
  t->id = pthread_self();
  t->live = 1;
  t->rng = (uint32_t)(uintptr_t)t ^ 0x9e3779b9u;
  t->dq = pdq_new();
  thr_set(t);
  pthread_mutex_lock(&gc_lock);
  if (gc_nthr == GC_MAXTHR) bend_fail("too many threads");
  gc_thrs[gc_nthr] = t;
  int n1 = gc_nthr + 1;  // tcc's __atomic_store_n evaluates its value twice
  __atomic_store_n(&gc_nthr, n1, __ATOMIC_RELEASE);
  pthread_mutex_unlock(&gc_lock);
}

// Constructors and closures
// =========================

static inline V C1(V t, V a) { V *p = halloc(2); p[0] = t; p[1] = a; return (V)p; }
static inline V C2(V t, V a, V b) { V *p = halloc(3); p[0] = t; p[1] = a; p[2] = b; return (V)p; }
static inline V C3(V t, V a, V b, V c) { V *p = halloc(4); p[0] = t; p[1] = a; p[2] = b; p[3] = c; return (V)p; }
static inline V C4(V t, V a, V b, V c, V d) {
  V *p = halloc(5); p[0] = t; p[1] = a; p[2] = b; p[3] = c; p[4] = d; return (V)p;
}
static inline V CN(V t, int n, const V *xs) {
  V *p = halloc(n + 1); p[0] = t;
  for (int i = 0; i < n; i++) p[i + 1] = xs[i];
  return (V)p;
}

// A D_ node (one field is BEND_HOLE): its tag word holds BEND_HOLE from
// before the slot is allocated until its fields, the hole among them, are
// stored, so a collection that stops the thread in between sees the hole.
static inline V CH1(V t, V a) { V *p = halloc_hole(2); p[1] = a; BEND_BARRIER(); p[0] = t; return (V)p; }
static inline V CH2(V t, V a, V b) { V *p = halloc_hole(3); p[1] = a; p[2] = b; BEND_BARRIER(); p[0] = t; return (V)p; }
static inline V CH3(V t, V a, V b, V c) {
  V *p = halloc_hole(4); p[1] = a; p[2] = b; p[3] = c; BEND_BARRIER(); p[0] = t; return (V)p;
}
static inline V CH4(V t, V a, V b, V c, V d) {
  V *p = halloc_hole(5); p[1] = a; p[2] = b; p[3] = c; p[4] = d; BEND_BARRIER(); p[0] = t; return (V)p;
}
static inline V CHN(V t, int n, const V *xs) {
  V *p = halloc_hole(n + 1);
  for (int i = 0; i < n; i++) p[i + 1] = xs[i];
  BEND_BARRIER();
  p[0] = t;
  return (V)p;
}

// Arrays
// ------
//
// An Array is one node {ARR_HDR(c), 2^c cells}, as the official runtime's
// flat block: Array.get/set/swap and the atomics work on it in place, so
// the handles a share (Array.fork, a +a) makes are one array, and a write
// through one is read through the other. A match on ANode copies the
// halves; ANode{l, r} copies both into a new array; ALeaf{x} is a 1-cell
// one. A shared array's cells are shared as they are copied.
#define ARR_TAG ((V)0xFFF00)
#define ARR_HDR(c) (ARR_TAG | (V)(c))
static inline unsigned arr_cls(V a) { return (unsigned)(((V *)a)[0] & 31); }
static inline V *arr_cells(V a) { return (V *)a + 1; }
static inline int arr_shared(V a) { return (__atomic_load_n((V *)a, __ATOMIC_RELAXED) & BEND_SH) != 0; }

// Marks a's block dirty before a pointer is stored in it (gc_rescan_dirty).
static inline void arr_dirty(V a) {
  uintptr_t bi = ((uintptr_t)a - (uintptr_t)gc_base) >> GC_BLK_SHIFT;
  if (!__atomic_load_n(&gc_dirty[bi], __ATOMIC_RELAXED)) __atomic_store_n(&gc_dirty[bi], 1, __ATOMIC_RELAXED);
  BEND_BARRIER();
}
static inline void arr_put(V a, V *p, V v) {
  if (v >= ((V)1 << 32)) arr_dirty(a);
  *p = v;
}

static V arr_alloc(unsigned c) {
  if (c > 31) bend_fail("an array past the deepest block class 31");
  V *p = halloc(1 + ((size_t)1 << c));
  p[0] = ARR_HDR(c);
  return (V)p;
}

// 2^c cells from src (a shared source's are shared) into a new array.
static V arr_copy(unsigned c, const V *src, int share) {
  size_t n = (size_t)1 << c;
  V a = arr_alloc(c);
  V *d = arr_cells(a);
  arr_dirty(a);
  for (size_t i = 0; i < n; i++) {
    V x = src[i];
    if (share) bend_share(x);
    d[i] = x;
  }
  return a;
}

static V arr_new(V depth, V v) {
  if (depth > 31) bend_fail("an array past the deepest block class 31");
  unsigned c = (unsigned)depth;
  size_t n = (size_t)1 << c;
  V a = arr_alloc(c);
  V *d = arr_cells(a);
  if (c > 0) bend_share(v);
  if (v >= ((V)1 << 32)) arr_dirty(a);
  for (size_t i = 0; i < n; i++) d[i] = v;
  return a;
}

static inline V arr_leaf(V x) { return arr_new(0, x); }

static V arr_node(V l, V r) {
  unsigned c = arr_cls(l);
  if (arr_cls(r) != c || c >= 31) bend_fail("runtime fail-stop");
  size_t n = (size_t)1 << c;
  V a = arr_alloc(c + 1);
  V *d = arr_cells(a);
  int sl = arr_shared(l), sr = arr_shared(r);
  arr_dirty(a);
  for (size_t i = 0; i < n; i++) { V x = arr_cells(l)[i]; if (sl) bend_share(x); d[i] = x; }
  for (size_t i = 0; i < n; i++) { V x = arr_cells(r)[i]; if (sr) bend_share(x); d[n + i] = x; }
  return a;
}

static V arr_half(V a, unsigned hi) {
  unsigned c = arr_cls(a);
  if (c == 0) bend_fail("runtime fail-stop");
  return arr_copy(c - 1, arr_cells(a) + ((size_t)hi << (c - 1)), arr_shared(a));
}

static inline V *arr_at(V a, V i) { return arr_cells(a) + ((uint32_t)i & (((V)1 << arr_cls(a)) - 1)); }

static inline V F_Array_dsize(V a) { return C2(0, a, (V)((uint64_t)1 << arr_cls(a))); }
// The checker's memo cells (check.bend's memo.*): an array of a cell's
// term and, once it is evaluated, its value. The value is stored before
// the term, so a reader that finds the term finds the value.
static inline V F_Chk_dmemo_dnew(V t) {
  (void)t;
  V a = arr_alloc(1);
  arr_cells(a)[0] = arr_cells(a)[1] = 0;
  return a;
}
static inline V F_Chk_dmemo_dhas(V m, V v) {
  V k = __atomic_load_n(&arr_cells(m)[0], __ATOMIC_ACQUIRE);
  return BOOL(k != 0 && k == v);
}
static inline V F_Chk_dmemo_dget(V m) { V x = arr_cells(m)[1]; bend_share(x); return x; }
static inline V F_Chk_dmemo_dset(V m, V v, V x) {
  bend_share(x);
  arr_put(m, &arr_cells(m)[1], x);
  arr_dirty(m);
  __atomic_store_n(&arr_cells(m)[0], v, __ATOMIC_RELEASE);
  return x;
}
static inline V F_Array_dget(V a, V i) { V x = *arr_at(a, i); bend_share(x); return C2(0, a, x); }
static inline V F_Array_dswap(V a, V i, V v) {
  V *p = arr_at(a, i);
  V old = *p;
  arr_put(a, p, v);
  return C2(0, a, old);
}
static inline V F_Array_dset(V a, V i, V v) { arr_put(a, arr_at(a, i), v); return a; }
static inline V F_Array_dnew(V d, V v) { return arr_new(d, v); }
static inline V F_Array_dclone(V a) { return C2(0, a, arr_copy(arr_cls(a), arr_cells(a), 1)); }

// The atomics, on a cell's U32 (its low half: the cell is a U32 below 2^32).
static inline uint32_t *arr_word(V a, V i) { return (uint32_t *)arr_at(a, i); }
#define ARR_ATOMIC(name, op) static inline V F_Array_datomic_d##name(V a, V i, V v) { return C2(0, a, (V)__atomic_##op(arr_word(a, i), (uint32_t)v, __ATOMIC_SEQ_CST)); }
ARR_ATOMIC(add, fetch_add)
ARR_ATOMIC(and, fetch_and)
ARR_ATOMIC(or, fetch_or)
ARR_ATOMIC(xor, fetch_xor)
#ifdef __TINYC__
// tcc lowers __atomic_exchange_n to a call its libtcc1 lacks: a CAS loop.
static inline V F_Array_datomic_dexch(V a, V i, V v) {
  uint32_t *w = arr_word(a, i), o = __atomic_load_n(w, __ATOMIC_RELAXED);
  while (!__atomic_compare_exchange_n(w, &o, (uint32_t)v, 1, __ATOMIC_SEQ_CST, __ATOMIC_RELAXED)) {}
  return C2(0, a, (V)o);
}
#else
ARR_ATOMIC(exch, exchange_n)
#endif
static inline V arr_rmw(V a, V i, V v, int k) {
  uint32_t *w = arr_word(a, i);
  uint32_t o = __atomic_load_n(w, __ATOMIC_RELAXED), n;
  for (;;) {
    union { uint32_t u; float f; } x = {o}, y = {(uint32_t)v};
    if (k == 0) n = o < (uint32_t)v ? o : (uint32_t)v;
    else if (k == 1) n = o > (uint32_t)v ? o : (uint32_t)v;
    else { x.f = x.f + y.f; n = x.u; }
    if (__atomic_compare_exchange_n(w, &o, n, 1, __ATOMIC_SEQ_CST, __ATOMIC_RELAXED)) break;
  }
  return C2(0, a, (V)o);
}
static inline V F_Array_datomic_dmin(V a, V i, V v) { return arr_rmw(a, i, v, 0); }
static inline V F_Array_datomic_dmax(V a, V i, V v) { return arr_rmw(a, i, v, 1); }
static inline V F_Array_datomic_dfadd(V a, V i, V v) { return arr_rmw(a, i, v, 2); }
static inline V F_Array_datomic_dcas(V a, V i, V x, V v) {
  uint32_t o = (uint32_t)x;
  __atomic_compare_exchange_n(arr_word(a, i), &o, (uint32_t)v, 0, __ATOMIC_SEQ_CST, __ATOMIC_SEQ_CST);
  return C2(0, a, (V)o);
}

static inline V mk_clo(Fn f, V arity, V n, const V *args) {
  V *p = halloc(3 + n);
  p[0] = (V)f; p[1] = arity; p[2] = n;
  for (V i = 0; i < n; i++) p[3 + i] = args[i];
  return (V)p;
}

static V apply(V f, V x) {
  V *c = (V *)f;
  V ar = c[1], n = c[2];
  if (n + 1 == ar) {
    V a[n + 1];
    for (V i = 0; i < n; i++) a[i] = c[3 + i];
    a[n] = x;
    return ((Fn)c[0])(a);
  }
  V *p = halloc(4 + n);
  p[0] = c[0]; p[1] = ar; p[2] = n + 1;
  for (V i = 0; i < n; i++) p[3 + i] = c[3 + i];
  p[3 + n] = x;
  return (V)p;
}

// Strings (cons lists of code points)
// -----------------------------------

#define SNIL IMM(0)
#define SCONS(h, t) C2(1, (h), (t))
#define NIL IMM(0)
#define CONS(h, t) C2(1, (h), (t))

// Builds a String from UTF-8 bytes. Strings are built from the end, so no
// cell is written after it is made (minor collections rely on that).
static V mk_str(const char *s, size_t n) {
  uint32_t small[256];
  uint32_t *cps = n <= 256 ? small : malloc(n * sizeof(uint32_t));
  size_t k = 0;
  for (size_t i = 0; i < n;) {
    unsigned char c = (unsigned char)s[i];
    uint32_t cp; int len;
    if (c < 0x80) { cp = c; len = 1; }
    else if ((c >> 5) == 6 && i + 1 < n) { cp = c & 0x1f; len = 2; }
    else if ((c >> 4) == 14 && i + 2 < n) { cp = c & 0x0f; len = 3; }
    else if ((c >> 3) == 30 && i + 3 < n) { cp = c & 0x07; len = 4; }
    else { cp = c; len = 1; }
    for (int j = 1; j < len; j++) cp = (cp << 6) | ((unsigned char)s[i + j] & 0x3f);
    cps[k++] = cp;
    i += len;
  }
  V r = SNIL;
  while (k > 0) { k--; r = SCONS(cps[k], r); }
  if (cps != small) free(cps);
  return r;
}

#define MKS(lit) mk_str(lit, sizeof(lit) - 1)
// The acquire pairs with str_cache's release: a thread that sees the string
// sees it shared.
#define STRC(c, lit) (__atomic_load_n(&(c), __ATOMIC_ACQUIRE) ? (c) : str_cache(&(c), lit, sizeof(lit) - 1))
#define mk_str_heap mk_str

// A string literal, built once (slot is its cache, a root).
__attribute__((noinline)) static V str_cache(V *slot, const char *s, size_t n) {
  V v = mk_str(s, n);
  bend_share(v);  // before another thread can see it
  pthread_mutex_lock(&gc_lock);
  if (*slot == 0) {
    __atomic_store_n(slot, v, __ATOMIC_RELEASE);
    gc_root_add_locked(slot, 1);
  }
  v = *slot;
  pthread_mutex_unlock(&gc_lock);
  return v;
}

// Encodes a String as a malloc'd UTF-8 buffer.
static char *str_to_c(V s, size_t *len) {
  size_t cap = 64, n = 0;
  char *buf = malloc(cap);
  while (TAG(s) == 1) {
    uint32_t cp = (uint32_t)FLD(s, 0);
    if (n + 5 > cap) { cap *= 2; buf = realloc(buf, cap); }
    if (cp < 0x80) buf[n++] = (char)cp;
    else if (cp < 0x800) { buf[n++] = 0xc0 | (cp >> 6); buf[n++] = 0x80 | (cp & 0x3f); }
    else if (cp < 0x10000) {
      buf[n++] = 0xe0 | (cp >> 12); buf[n++] = 0x80 | ((cp >> 6) & 0x3f); buf[n++] = 0x80 | (cp & 0x3f);
    } else {
      buf[n++] = 0xf0 | (cp >> 18); buf[n++] = 0x80 | ((cp >> 12) & 0x3f);
      buf[n++] = 0x80 | ((cp >> 6) & 0x3f); buf[n++] = 0x80 | (cp & 0x3f);
    }
    s = FLD(s, 1);
  }
  buf[n] = 0;
  if (len) *len = n;
  return buf;
}

// Natives: Nat
// -------------

// A Nat is a word up to NAT_IMM = 2^48 - 1, as the official runtime's
// immediate: a result past it stops the program, as there. A foreign
// effect's word past it matches as a successor; only results are checked.
#define NAT_IMM (((V)1 << 48) - 1)
__attribute__((noreturn, cold, noinline)) static void nat_wall(void) {
  bend_fail("a Nat past the largest immediate 2^48-1");
}
static inline V nat_chk(V x) { if (UNLIKELY(x > NAT_IMM)) nat_wall(); return x; }
static inline V nat_add(V a, V b) { return nat_chk(a + b); }
static inline V nat_sub(V a, V b) { return a > b ? a - b : 0; }
static inline V nat_mul(V a, V b) {
  return b != 0 && a > NAT_IMM / b ? (nat_wall(), 0) : a * b;
}
static inline int nat_cmp3(V a, V b) { return a < b ? -1 : a > b; }
static inline void nat_divmod2(V a, V b, V *qo, V *ro) {
  if (b == 0) { *qo = 0; *ro = a; } else { *qo = a / b; *ro = a % b; }
}
static V nat_pow(V a, V n) {
  if (a <= 1) return n == 0 ? 1 : a;
  V r = 1;
  for (; n; n--) r = nat_mul(r, a);
  return r;
}
// Base's Nat.show rebuilds each quotient as a successor, so a word whose
// first quotient is past the cap stops there.
static char *nat_digits(V x) {
  nat_chk(x / 10);
  char *s = malloc(24);
  snprintf(s, 24, "%llu", (unsigned long long)x);
  return s;
}

static inline V nat_addk(V x, V k) { return LIKELY(x + k <= NAT_IMM) ? x + k : (nat_wall(), 0); }
static inline V nat_subk(V x, V k) { return x - k; }
static inline int nat_ge(V x, V k) { return x >= k; }

static inline V F_Nat_ddouble(V a) { return nat_add(a, a); }
static inline V F_Nat_dadd(V a, V b) { return nat_add(a, b); }
static inline V F_Nat_dsub(V a, V b) { return nat_sub(a, b); }
static inline V F_Nat_dmul(V a, V b) { return nat_mul(a, b); }
static inline V F_Nat_ddivmod(V a, V b) { V q, r; nat_divmod2(a, b, &q, &r); return C2(0, q, r); }
static inline V F_Nat_ddiv(V a, V b) { V q, r; nat_divmod2(a, b, &q, &r); return q; }
static inline V F_Nat_dmod(V a, V b) { V q, r; nat_divmod2(a, b, &q, &r); return r; }
static inline V F_Nat_dcmp(V a, V b) { int c = nat_cmp3(a, b); return c < 0 ? IMM(0) : c == 0 ? IMM(1) : IMM(2); }
static inline V F_Nat_dis__eq(V a, V b) { return BOOL(a == b); }
static inline V F_Nat_dis__ne(V a, V b) { return BOOL(a != b); }
static inline V F_Nat_dis__lt(V a, V b) { return BOOL(a < b); }
static inline V F_Nat_dis__le(V a, V b) { return BOOL(a <= b); }
static inline V F_Nat_dis__gt(V a, V b) { return BOOL(a > b); }
static inline V F_Nat_dis__ge(V a, V b) { return BOOL(a >= b); }
static inline V F_Nat_dmin(V a, V b) { return a < b ? a : b; }
static inline V F_Nat_dmax(V a, V b) { return a < b ? b : a; }
static inline V F_Nat_dpow(V a, V n) { return nat_pow(a, n); }
static V F_Nat_dshow(V a) {
  char *s = nat_digits(a);
  V r = mk_str(s, strlen(s));
  free(s);
  return r;
}

// Map.bit(key, pos): bit pos of key as Base's tries read it (char pos / 33;
// offset 0 is "the char exists", offset 1 + b is bit 31 - b of its code),
// with the key handed back. Base rebuilds the key's prefix to hand it back;
// here the key is shared, so a lookup allocates nothing.
#ifdef BEND_NATIVE_MAP_BIT
static inline V F_Map_dbit(V key, V pos) {
  if (pos >> 63) return C2(0, key, IMM(0));
  V ci = pos / 33, off = pos % 33, s = key;
  for (;;) {
    if (s == SNIL) return C2(0, key, IMM(0));
    if (ci == 0) break;
    s = ((V *)s)[2];
    ci--;
  }
  V x = ((V *)s)[1];
  return C2(0, key, off == 0 ? IMM(1) : (((uint32_t)x >> (32 - off)) & 1) ? IMM(1) : IMM(0));
}
#endif

// Natives: U32
// ------------

#define U(x) ((uint32_t)(x))
static inline V nat_low32(V n) { return U(n); }
static inline uint32_t F_U32_dinc(V a) { return U(U(a) + 1u); }
static inline uint32_t F_U32_dadd(V a, V b) { return U(U(a) + U(b)); }
static inline uint32_t F_U32_dsub(V a, V b) { return U(U(a) - U(b)); }
static inline uint32_t F_U32_dmul(V a, V b) { return U(U(a) * U(b)); }
static inline uint32_t F_U32_ddiv(V a, V b) { return b == 0 ? 0 : U(a) / U(b); }
static inline uint32_t F_U32_dmod(V a, V b) { return b == 0 ? a : U(a) % U(b); }
static inline uint32_t F_U32_dnot(V a) { return U(~U(a)); }
static inline uint32_t F_U32_dand(V a, V b) { return U(a) & U(b); }
static inline uint32_t F_U32_dor(V a, V b) { return U(a) | U(b); }
static inline uint32_t F_U32_dxor(V a, V b) { return U(a) ^ U(b); }
static inline uint32_t F_U32_dshl(V a) { return U(U(a) << 1); }
static inline uint32_t F_U32_dshr(V a) { return U(a) >> 1; }
static inline uint32_t F_U32_dshln(V a, V n) { return n >= 32 ? 0 : U(U(a) << U(n)); }
static inline uint32_t F_U32_dshrn(V a, V n) { return n >= 32 ? 0 : U(a) >> U(n); }
static inline V F_U32_dcmp(V a, V b) { return a < b ? IMM(0) : a == b ? IMM(1) : IMM(2); }
static inline uint32_t F_U32_dis__eq(V a, V b) { return BOOL(U(a) == U(b)); }
static inline uint32_t F_U32_dis__ne(V a, V b) { return BOOL(U(a) != U(b)); }
static inline uint32_t F_U32_dis__lt(V a, V b) { return BOOL(U(a) < U(b)); }
static inline uint32_t F_U32_dis__le(V a, V b) { return BOOL(U(a) <= U(b)); }
static inline uint32_t F_U32_dis__gt(V a, V b) { return BOOL(U(a) > U(b)); }
static inline uint32_t F_U32_dis__ge(V a, V b) { return BOOL(U(a) >= U(b)); }
static inline uint32_t F_U32_dis__zero(V a) { return BOOL(U(a) == 0); }
static inline uint32_t F_U32_dis__even(V a) { return BOOL((a & 1) == 0); }
static inline V F_U32_dto__nat(V a) { return a; }
static inline uint32_t F_U32_dfrom__nat(V n) { return nat_low32(n); }
static inline uint32_t F_U32_dmin(V a, V b) { return U(a) < U(b) ? U(a) : U(b); }
static inline uint32_t F_U32_dmax(V a, V b) { return U(a) < U(b) ? U(b) : U(a); }
static inline V F_U32_dpow(V a, V n) {
  // a^n mod 2^32; an odd a has an order dividing 2^30, an even one reaches 0.
  V e = n;
  uint32_t r = 1, b = U(a);
  for (; e; e >>= 1) { if (e & 1) r *= b; b *= b; }
  return r;
}
static inline V F_U32_dlog2(V n) {
  V d = 0;
  while (n > 1) { d++; n >>= 1; }
  return d;
}

// Natives: F32 (stored as IEEE bits)
// ----------------------------------

static inline float FV(V v) { union { uint32_t u; float f; } x; x.u = U(v); return x.f; }
static inline V VF(float f) { union { uint32_t u; float f; } x; x.f = f; return x.u; }
#define F2(name, expr) static inline V F_F32_d##name(V a, V b) { float x = FV(a), y = FV(b); return expr; }
#define F1(name, expr) static inline V F_F32_d##name(V a) { float x = FV(a); return expr; }
F2(add, VF(x + y))
F2(sub, VF(x - y))
F2(mul, VF(x * y))

// x * k + b for a literal k (bendc emits it for F32.add(F32.mul(x, k), b)):
// one fma when k is a power of two and x * k a normal float, for then the
// product is exact and fma rounds once where the two operations would
// round the same sum; else the two, as written. A loop like
// x = x * x * 0.5 + c then waits on two operations a step, not three.
// (The other case is a call, so the compiler branches to it rather than
// computing both and selecting, which would put both on the loop's path.)
__attribute__((noinline, cold)) static float F32_mul_add(float x, float k, float c) {
  float p = x * k;
  return p + c;
}
static inline V F32_mulk_add(V a, V kv, V b) {
  float x = FV(a), k = FV(kv);
  uint32_t e = (U(kv) >> 23) & 0xff;
  float p = fabsf(x * k);
  if ((U(kv) & 0x7fffff) == 0 && e != 0 && e != 0xff && p >= 0x1p-126f && p <= 0x1.fffffep127f) {
    return VF(fmaf(x, k, FV(b)));
  }
  return VF(F32_mul_add(x, k, FV(b)));
}
F2(div, VF(x / y))
F2(mod, VF((float)fmod(x, y)))
F2(pow, VF((float)pow(x, y)))
F2(atan2, VF((float)atan2(x, y)))
F2(is__eq, BOOL(x == y))
F2(is__ne, BOOL(x != y))
F2(is__lt, BOOL(x < y))
F2(is__le, BOOL(x <= y))
F2(is__gt, BOOL(x > y))
F2(is__ge, BOOL(x >= y))
F1(neg, VF(-x))
F1(abs, VF(fabsf(x)))
F1(sqrt, VF(sqrtf(x)))
F1(exp, VF((float)exp(x)))
F1(log, VF((float)log(x)))
F1(log2, VF((float)log2(x)))
F1(log10, VF((float)log10(x)))
F1(sin, VF((float)sin(x)))
F1(cos, VF((float)cos(x)))
F1(tan, VF((float)tan(x)))
F1(asin, VF((float)asin(x)))
F1(acos, VF((float)acos(x)))
F1(atan, VF((float)atan(x)))
F1(sinh, VF((float)sinh(x)))
F1(cosh, VF((float)cosh(x)))
F1(tanh, VF((float)tanh(x)))
F1(floor, VF(floorf(x)))
F1(ceil, VF(ceilf(x)))
F1(trunc, VF(truncf(x)))
static inline V F_F32_dbits(V a) { return U(a); }
static inline V F_F32_dto__u32(V a) { float x = FV(a); return !(x > 0) ? 0 : x >= 4294967296.0f ? 0 : (uint32_t)x; }
static inline V F_U32_dto__f32(V a) { return VF((float)U(a)); }
// The shortest text that reads back, spelled as JavaScript spells a number
// (the official f32_text): plain digits from 1e-6 to 1e21, else d.ddde+x.
static int f32_text(float v, char *buf, size_t n) {
  int k = 0, p = 0;
  if (v != v) return snprintf(buf, n, "nan");
  for (; p < 9; p++) {
    k = snprintf(buf, n, "%.*e", p, (double)v);
    if (strtof(buf, NULL) == v) break;
  }
  char *ep = strchr(buf, 'e');
  if (ep == NULL) return k;
  int ex = atoi(ep + 1);
  if (ex >= 21 || ex <= -7) {
    k = (int)(ep - buf) + snprintf(ep, n - (size_t)(ep - buf), "e%c%d", ex < 0 ? '-' : '+', abs(ex));
  } else if (ex <= p) {
    k = snprintf(buf, n, "%.*f", p - ex, (double)v);
  } else {
    int s = *buf == '-';
    memmove(buf + s + 1, buf + s + 2, (size_t)p);
    memset(buf + s + 1 + p, '0', (size_t)(ex - p));
    k = s + 1 + ex;
    buf[k] = 0;
  }
  return k;
}
static V F_F32_dshow(V a) {
  char buf[64];
  f32_text(FV(a), buf, sizeof buf);
  return mk_str(buf, strlen(buf));
}
static V F_F32_dread(V s) {
  char *c = str_to_c(s, NULL);
  char *end;
  float f = strtof(c, &end);
  int ok = *c && !*end;
  free(c);
  return ok ? C1(1, VF(f)) : IMM(0);
}

// Parallel calls
// ==============
//
// A parallel let `a b = f(x) g(y)` forks every value but the last as a task
// (a closure applied to a dummy argument), evaluates the last one, then joins
// the tasks in reverse. Each thread owns a Chase-Lev deque: it pushes and
// pops at the bottom, idle threads steal from the top. A task nobody stole
// runs inline at its join, so a fork costs little more than a closure.

#define P_LOCAL 0
#define P_QUEUED 1
#define P_DONE 2

typedef struct PTask { V clo; V res; V state; V depth; } PTask;

// The fork depth of the running code, and the frontier past which a def
// with a sequential clone (S_name, see bendc) runs its parallel lets in
// order: below it, forking costs more than it balances.
#ifndef __TINYC__
static __thread int par_depth;
#endif
static int par_front = 0;

typedef struct PDeque {
  _Atomic long top;
  _Atomic long bot;
  long mask;
  PTask **buf;
} PDeque;

static int par_nthreads = 1;
// The pool's size as effect sources name it (IO.thread_count).
#define pool_size ((u32)par_nthreads)
static _Atomic int par_started;
static pthread_mutex_t par_mu = PTHREAD_MUTEX_INITIALIZER;
static pthread_cond_t par_cv = PTHREAD_COND_INITIALIZER;
static _Atomic int par_sleepers;

static PDeque *pdq_new(void) {
  PDeque *d = calloc(1, sizeof(PDeque));
  d->mask = (1 << 16) - 1;
  d->buf = calloc((size_t)d->mask + 1, sizeof(PTask *));
  return d;
}

static PTask *pdq_pop(PDeque *d) {
  long b = atomic_load_explicit(&d->bot, memory_order_relaxed) - 1;
  atomic_store_explicit(&d->bot, b, memory_order_relaxed);
  atomic_thread_fence(memory_order_seq_cst);
  long t = atomic_load_explicit(&d->top, memory_order_relaxed);
  if (t <= b) {
    PTask *x = __atomic_load_n(&d->buf[b & d->mask], __ATOMIC_RELAXED);
    if (t == b) {
      if (!atomic_compare_exchange_strong_explicit(&d->top, &t, t + 1, memory_order_seq_cst,
            memory_order_relaxed))
        x = NULL;
      atomic_store_explicit(&d->bot, b + 1, memory_order_relaxed);
    }
    return x;
  }
  atomic_store_explicit(&d->bot, b + 1, memory_order_relaxed);
  return NULL;
}

static PTask *pdq_steal(PDeque *d) {
  long t = atomic_load_explicit(&d->top, memory_order_acquire);
  atomic_thread_fence(memory_order_seq_cst);
  long b = atomic_load_explicit(&d->bot, memory_order_acquire);
  if (t < b) {
    PTask *x = __atomic_load_n(&d->buf[t & d->mask], __ATOMIC_RELAXED);
    if (!atomic_compare_exchange_strong_explicit(&d->top, &t, t + 1, memory_order_seq_cst,
          memory_order_relaxed))
      return NULL;
    return x;
  }
  return NULL;
}

static void par_exec(PTask *t) {
  int d = par_depth;
  par_depth = (int)t->depth;
  V r = apply(t->clo, 0);
  par_depth = d;
  t->res = r;
  __atomic_store_n(&t->state, P_DONE, __ATOMIC_RELEASE);
}

static PTask *par_steal(void) {
  Thr *me = thr_self;
  int n = __atomic_load_n(&gc_nthr, __ATOMIC_ACQUIRE);
  if (n <= 1) return NULL;
  me->rng = me->rng * 1664525u + 1013904223u;
  int s = (int)(me->rng >> 8) % n;
  for (int i = 0; i < n; i++) {
    Thr *t = gc_thrs[(s + i) % n];
    if (t == me || !t->live || !t->dq) continue;
    PTask *x = pdq_steal(t->dq);
    if (x) return x;
  }
  return NULL;
}

static inline void cpu_relax(void) {
#if defined(__TINYC__)
  // tcc has no pause/yield: a plain spin
#elif defined(__x86_64__)
  __builtin_ia32_pause();
#elif defined(__aarch64__)
  __asm__ __volatile__("yield");
#endif
}

static void *par_worker(void *arg) {
  (void)arg;
  thr_register((uintptr_t)__builtin_frame_address(0) + 16);
  for (int spins = 0;;) {
    PTask *t = par_steal();
    if (t) { par_exec(t); spins = 0; continue; }
    if (++spins < 512) { cpu_relax(); continue; }
    pthread_mutex_lock(&par_mu);
    atomic_fetch_add(&par_sleepers, 1);
    struct timeval now;
    gettimeofday(&now, NULL);
    struct timespec until = {now.tv_sec, now.tv_usec * 1000 + 2000000};
    if (until.tv_nsec >= 1000000000) { until.tv_sec++; until.tv_nsec -= 1000000000; }
    pthread_cond_timedwait(&par_cv, &par_mu, &until);
    atomic_fetch_sub(&par_sleepers, 1);
    pthread_mutex_unlock(&par_mu);
    spins = 0;
  }
  return NULL;
}

static void par_hook(void) {
  for (int i = 0; i < gc_nthr; i++) {
    PDeque *d = gc_thrs[i]->dq;
    if (d) gc_scan(d->buf, d->buf + d->mask + 1);
  }
}

static void par_start(void) {
  pthread_mutex_lock(&par_mu);
  if (!atomic_load(&par_started)) {
    gc_mt = 1;
    gc_hot.mt = 1;
    for (int i = 1; i < par_nthreads; i++) {
      pthread_attr_t attr;
      pthread_attr_init(&attr);
      pthread_attr_setstacksize(&attr, (size_t)1 << 31);
      pthread_t th;
      if (pthread_create(&th, &attr, par_worker, NULL) == 0) pthread_detach(th);
      pthread_attr_destroy(&attr);
    }
    atomic_store(&par_started, 1);
  }
  pthread_mutex_unlock(&par_mu);
}

// Forks clo (a closure taking one dummy argument); returns the task. Only a
// thread whose deque is nearly empty queues it (the oldest tasks, which
// thieves take, are the big ones); otherwise the fork is the closure itself,
// tagged with bit 1, and its join just applies it.
static V par_fork(V clo) {
#ifdef BEND_DEBUG_FREE
  // Debugging, on one thread: BEND_DEBUG_EAGER runs forks as they are made,
  // in the order other threads may run them (the result boxed, tagged 4).
  if (par_nthreads <= 1 && getenv("BEND_DEBUG_EAGER")) {
    V *box = halloc(1);
    box[0] = apply(clo, 0);
    return (V)box | 4;
  }
#endif
  if (par_nthreads <= 1) return clo | 2;
  PDeque *d = thr_self->dq;
  long b = atomic_load_explicit(&d->bot, memory_order_relaxed);
  long tp = atomic_load_explicit(&d->top, memory_order_relaxed);
  if (b - tp >= 4) return clo | 2;
  if (UNLIKELY(!atomic_load_explicit(&par_started, memory_order_relaxed))) par_start();
  PTask *t = (PTask *)halloc(4);
  t->clo = clo;
  t->depth = (V)par_depth;
  t->state = P_QUEUED;
  __atomic_store_n(&d->buf[b & d->mask], t, __ATOMIC_RELAXED);
  atomic_thread_fence(memory_order_release);
  atomic_store_explicit(&d->bot, b + 1, memory_order_relaxed);
  if (atomic_load_explicit(&par_sleepers, memory_order_relaxed) > 0) pthread_cond_signal(&par_cv);
  return (V)t;
}

// Waits for a forked task and returns its value.
static V par_join(V tv) {
  if (tv & 4) return ((V *)(tv & ~(V)4))[0];
  if (tv & 2) return apply(tv & ~(V)2, 0);
  PTask *t = (PTask *)tv;
  PTask *p = pdq_pop(thr_self->dq);
  if (p == t) return apply(t->clo, 0);
  if (p) par_exec(p);
  // With nothing to steal, a joiner spins a little, then yields its core,
  // then naps (the task it waits for may be running on a thread that has no
  // core of its own when there are more threads than cores).
  for (int spins = 0; __atomic_load_n(&t->state, __ATOMIC_ACQUIRE) != P_DONE;) {
    PTask *o = par_steal();
    if (o) { par_exec(o); spins = 0; continue; }
    if (++spins < 64) cpu_relax();
    else if (spins < 256) sched_yield();
    else { struct timespec ts = {0, 20000}; nanosleep(&ts, NULL); }
  }
  return t->res;
}

static int cpu_count(void) {
  long n = sysconf(_SC_NPROCESSORS_ONLN);
  return n < 1 ? 1 : n > 128 ? 128 : (int)n;
}

// Effects
// =======
//
// An effect def compiles to a request node {cid | n << 24, args..., k}. The
// event loop runs each computation's pure code up to its next request, runs
// the effect's host function, then resumes k with the answer. The host
// functions use the official runtime's names and conventions: see
// EFFECTS.md in the Bend guide. A CID encodes how a constructor is laid out
// here: kind << 16 | tag, where kind 0 is a node, 1 a nullary constructor,
// 2 a single-field single-constructor type (the field itself), and 3 an
// effect (its tag is its row in io_eff_rows).

#ifndef CID_TUPLE
#define CID_TUPLE 0u
#endif
#ifndef CID_DONE
#define CID_DONE 1u
#endif
#ifndef CID_FAIL
#define CID_FAIL 0u
#endif
#ifndef CID_SOME
#define CID_SOME 1u
#endif
#ifndef CID_NONE
#define CID_NONE ((1u << 16) | 0u)
#endif
#ifndef CID_TRUE
#define CID_TRUE ((1u << 16) | 1u)
#endif
#ifndef CID_FALSE
#define CID_FALSE ((1u << 16) | 0u)
#endif
#ifndef CID_UNIT
#define CID_UNIT ((1u << 16) | 0u)
#endif

// A request node for effect cid with n fields (its arguments, then k).
static inline V io_req(u64 cid, int n, const V *xs) { return CN(cid | ((V)n << 24), n, xs); }

typedef struct { int unused; } Env;
typedef pthread_mutex_t lock;
#define OUTLINE __attribute__((noinline))
#define IO_READ 1
#define IO_TIME 2
#define IO_HELP 64
static V io_hole_cell;
#define TERM_HOLE ((Term)(uintptr_t)&io_hole_cell)
#define IO_PARK TERM_HOLE
#define io_hand(v) ((Term)(v))
#define io_hand_v(t) ((u64)(t))
#define CID_KIND(c) ((u32)(c) >> 16)
#define CID_TAG(c) ((u32)(c) & 0xffff)

__attribute__((noreturn)) static void err_fail(const char *msg) { bend_fail(msg); }

static inline Term term_pak(u64 cid, Term v) {
  switch (CID_KIND(cid)) {
    case 1: return IMM(CID_TAG(cid));
    case 2: return v;
    default: return C1(CID_TAG(cid), v);
  }
}

// The CID of a constructor value (a node's or a nullary one's).
static inline u64 term_aux(Term t) { return (t & 1) ? ((1u << 16) | (u32)(t >> 3)) : ((V *)t)[0] & ~BEND_SH_BITS; }
#define term_drop(e, t) ((void)(e), (void)(t))
#define term_sink(e, t) ((void)(e), (void)(t))
#define cls_fit(n) 0
#define spare_free(e, c, x) ((void)(e), (void)(c), (void)(x))
#define f32_unbox(t) FV(t)
static inline int ctr_take(Env e, Term t, u32 n, Term *fb) {
  (void)e;
  for (u32 i = 0; i < n; i++) fb[i] = FLD(t, i);
  return 0;
}

struct IoWork;
typedef void (*IoCall)(struct IoWork *w);
typedef Term (*IoPack)(Env e, struct IoWork *w);

typedef struct IoWork {
  intptr_t hand;
  intptr_t made;
  u32 word;
  u64 size;
  char *data;
  char *text;
  u32 code;
  u64 time;
  IoCall call;
  IoPack pack;
} IoWork;

typedef Term (*Effect)(Env e, Term *f, IoWork *w);

typedef struct {
  Effect run;
  u32 ask;
} IoEff;

static IoEff io_eff_rows[1 << 16];
static u32 io_live;
static int io_argc;
static char **io_argv;

static void io_eff(u32 cid, Effect run, u32 need) { io_eff_rows[CID_TAG(cid)] = (IoEff){run, need}; }

static u64 io_tick(void) {
  struct timespec ts;
  clock_gettime(CLOCK_MONOTONIC, &ts);
  return (u64)ts.tv_sec * 1000000000ull + (u64)ts.tv_nsec;
}

OUTLINE void *io_mem(void *mem) {
  if (mem == NULL) err_fail("host allocation failed");
  return mem;
}

static int io_sys_addr(const char *host, u32 port, struct sockaddr_in *at) {
  memset(at, 0, sizeof(*at));
  at->sin_family = AF_INET;
  at->sin_port = htons((uint16_t)port);
  for (const char *p = host; *p != 0; p += 1) {
    bool zero = *p == '0' && p[1] >= '0' && p[1] <= '9';
    if ((p == host || p[-1] == '.') && zero) return -1;
  }
  return port > 65535 || inet_pton(AF_INET, host, &at->sin_addr) != 1 ? -1 : 0;
}

static u64 io_sys_end(IoWork *w, ssize_t n) {
  w->code = n < 0 ? (u32)errno : 0;
  return n < 0 ? 0 : (u64)n;
}

// One computation: cont applied to item is its next request. Leading work
// permits IoWork* to IoAct* casts. Every live act is on a list the collector
// reads.
typedef struct IoAct {
  IoWork work;
  Term cont;
  Term item;
  short evts;
  struct IoAct *next;
  struct IoAct *gprev, *gnext;
} IoAct;

typedef struct {
  IoAct *head;
  IoAct *last;
} IoQue;

static IoQue io_runs;
static IoQue io_park;
static IoQue io_jobs;
static IoAct *io_acts;

static void io_push(IoQue *q, IoAct *a) {
  a->next = NULL;
  *(q->head == NULL ? &q->head : &q->last->next) = a;
  q->last = a;
}

static IoAct *io_pop(IoQue *q) {
  IoAct *a = q->head;
  q->head = a->next;
  return a;
}

static IoAct *io_act_new(void) {
  IoAct *a = io_mem(calloc(1, sizeof(IoAct)));
  pthread_mutex_lock(&gc_lock);
  a->gnext = io_acts;
  if (io_acts) io_acts->gprev = a;
  io_acts = a;
  pthread_mutex_unlock(&gc_lock);
  return a;
}

static void io_act_free(IoAct *a) {
  pthread_mutex_lock(&gc_lock);
  if (a->gprev) a->gprev->gnext = a->gnext;
  else io_acts = a->gnext;
  if (a->gnext) a->gnext->gprev = a->gprev;
  pthread_mutex_unlock(&gc_lock);
  free(a);
}

static V io_start_fn(V *a) { return apply(apply(a[0], 0), a[1]); }
static V io_emit_fn(V *a) { return C1(0, a[0]); }

// Starts m (an IO) as a new computation.
static void io_spawn(Term m) {
  IoAct *a = io_act_new();
  a->cont = mk_clo(io_start_fn, 2, 1, &m);
  a->item = mk_clo(io_emit_fn, 1, 0, NULL);
  io_push(&io_runs, a);
  io_live += 1;
}

// Parks until evts (POLLIN/POLLOUT; 0 ignores fd) or time (0: no deadline).
// The loop calls more: a value resumes, IO_PARK re-parks.
static Term io_wait_on(IoWork *w, int fd, short evts, u64 time, IoPack more) {
  IoAct *a = (IoAct *)w;
  a->work.word = (u32)fd;
  a->work.pack = more;
  a->work.time = time;
  a->evts = evts;
  io_push(&io_park, a);
  return IO_PARK;
}

static u64 io_wait_time(IoWork *w) { return w->time; }

OUTLINE void io_out(FILE *h, const char *data, u64 len) {
  if (fwrite(data, 1, len, h) != len) err_fail("a short write on a standard stream");
}

OUTLINE void io_sync(void) {
  if (fflush(stdout) != 0) err_fail("a short write on a standard stream");
}

static u64 io_utf8(char *buf, u64 c) {
  u64 k = c < 0x80 ? 1 : c < 0x800 ? 2 : c < 0x10000 ? 3 : 4;
  for (u64 i = k; i > 1; i -= 1) {
    buf[i - 1] = (char)(0x80 | (c & 0x3F));
    c >>= 6;
  }
  buf[0] = (char)(k == 1 ? c : (0xF00 >> k) | c);
  return k;
}

OUTLINE char *io_cstr(Env e, Term s, u64 *len) {
  (void)e;
  u64 cap = 64, n = 0;
  char *buf = io_mem(malloc(cap));
  while (!(s & 1) && TAG(s) == 1) {
    if (n + 5 > cap) {
      cap *= 2;
      buf = io_mem(realloc(buf, cap));
    }
    n += io_utf8(buf + n, FLD(s, 0));
    s = FLD(s, 1);
  }
  buf[n] = 0;
  *len = n;
  return buf;
}

// A List of bytes (0..255) as they are, with no UTF-8: NULL if a value is
// past 255. (Strings go through io_cstr: a String's cons and a List's have
// one id here, so cons says nothing.)
OUTLINE char *io_cbuf(Env e, Term s, u64 *len, u64 cons) {
  (void)e;
  (void)cons;
  u64 cap = 64, n = 0, bad = 0;
  char *buf = io_mem(malloc(cap + 1));
  while (!(s & 1) && TAG(s) == 1) {
    if (n + 1 > cap) {
      cap *= 2;
      buf = io_mem(realloc(buf, cap + 1));
    }
    bad |= FLD(s, 0) > 255;
    buf[n++] = (char)FLD(s, 0);
    s = FLD(s, 1);
  }
  buf[n] = 0;
  *len = n;
  if (bad) {
    free(buf);
    return NULL;
  }
  return buf;
}

OUTLINE void io_errs(Env e, Term s) {
  u64 n = 0;
  char *text = io_cstr(e, s, &n);
  io_sync();
  io_out(stderr, text, n);
  io_out(stderr, "\n", 1);
  free(text);
}

#define io_nul(s, n) (strlen(s) != (n))

static Term io_box(Env e, u64 cid, Term v) {
  (void)e;
  switch (CID_KIND(cid)) {
    case 1: return IMM(CID_TAG(cid));
    case 2: return v;
    default: return C1(CID_TAG(cid), v);
  }
}

static Term io_node(Env e, u64 cid, Term a, Term b) {
  (void)e;
  return C2(CID_TAG(cid), a, b);
}

// Decodes UTF-8 as WHATWG does: a byte that breaks a sequence yields one
// U+FFFD and is read again as a lead.
static Term io_str(Env e, const char *p, u64 n) {
  (void)e;
  u32 *cps = io_mem(malloc((n + 1) * sizeof(u32)));
  u64 k = 0;
  u64 c = 0, need = 0, lo = 0x80, hi = 0xBF;
  for (u64 i = 0; i < n || need > 0; i += 1) {
    u64 b = i < n ? (uint8_t)p[i] : 0x100;
    if (need > 0 && (b < lo || b > hi)) {
      need = 0;
      c = 0xFFFD;
      i -= 1;
    } else if (need > 0) {
      lo = 0x80;
      hi = 0xBF;
      c = (c << 6) | (b & 0x3F);
      if (--need > 0) continue;
    } else if (b < 0x80) {
      c = b;
    } else if (b < 0xC2 || b > 0xF4) {
      c = 0xFFFD;
    } else {
      need = b < 0xE0 ? 1 : b < 0xF0 ? 2 : 3;
      lo = b == 0xE0 ? 0xA0 : b == 0xF0 ? 0x90 : 0x80;
      hi = b == 0xED ? 0x9F : b == 0xF4 ? 0x8F : 0xBF;
      c = b & (0x3F >> need);
      continue;
    }
    cps[k++] = (u32)c;
  }
  Term s = SNIL;
  while (k > 0) { k--; s = SCONS(cps[k], s); }
  free(cps);
  return s;
}

// Bytes cross as they are (0..255), one List cell each (Con, tag 1, on
// Nil), with no UTF-8.
static Term io_list(Env e, const char *p, u64 n) {
  (void)e;
  Term xs = IMM(0);
  for (u64 i = n; i > 0; i -= 1) xs = C2(1, (uint8_t)p[i - 1], xs);
  return xs;
}

#define io_tup(e, a, b) io_node(e, CID_TUPLE, a, b)
#define io_done(e, v) io_box(e, CID_DONE, v)

static Term io_fail(Env e, u32 code, const char *text) {
  const char *s = text != NULL ? text : strerror((int)code);
  Term t = io_tup(e, code, io_str(e, s, strlen(s)));
  return io_box(e, CID_FAIL, t);
}

static pthread_mutex_t io_gate = PTHREAD_MUTEX_INITIALIZER;
static pthread_cond_t io_bell = PTHREAD_COND_INITIALIZER;
static u32 io_busy;
static u32 io_size;
static int io_wake_fd[2];

static void io_take(Env e) {
  IoAct *acts[64];
  ssize_t n;
  while ((n = read(io_wake_fd[0], acts, sizeof acts)) > 0) {
    for (u32 i = 0; i < (u32)n / sizeof(IoAct *); i += 1) {
      IoAct *a = acts[i];
      a->item = a->work.pack(e, &a->work);
      io_push(&io_runs, a);
      io_busy -= 1;
    }
  }
}

static void *io_help(void *arg) {
  (void)arg;
  for (;;) {
    pthread_mutex_lock(&io_gate);
    while (io_jobs.head == NULL) pthread_cond_wait(&io_bell, &io_gate);
    IoAct *a = io_pop(&io_jobs);
    pthread_mutex_unlock(&io_gate);
    a->work.call(&a->work);
    while (write(io_wake_fd[1], &a, sizeof a) != sizeof a) {
    }
  }
  return NULL;
}

// Runs call on a helper thread, then pack on the loop to resume the effect.
static Term io_work(IoWork *w, IoCall call, IoPack pack) {
  w->call = call;
  w->pack = pack;
  io_busy += 1;
  if (io_busy > io_size && io_size < IO_HELP) {
    pthread_t tid;
    if (pthread_create(&tid, NULL, io_help, NULL)) err_fail("pthread_create");
    pthread_detach(tid);
    io_size += 1;
  }
  pthread_mutex_lock(&io_gate);
  io_push(&io_jobs, (IoAct *)w);
  pthread_cond_signal(&io_bell);
  pthread_mutex_unlock(&io_gate);
  return IO_PARK;
}

// Takes cont's request node apart; the effect returns a value or IO_PARK.
static Term io_exec(Env e, IoWork *w) {
  IoAct *a = (IoAct *)w;
  Term fs[256];
  u64 tg = TAG(a->cont);
  u32 n = (u32)(tg >> 24);
  for (u32 i = 0; i < n; i++) fs[i] = FLD(a->cont, i);
  a->cont = fs[n - 1];
  return io_eff_rows[CID_TAG(tg)].run(e, fs, w);
}

// macOS poll misses FIFO EOF, so the loop waits with select.
static bool io_bit(u8 *set, int fd, bool put) {
  u8 *at = set + fd / 8;
  *at |= put << fd % 8;
  return *at >> fd % 8 & 1;
}

static void io_wait(Env e) {
  int top = io_wake_fd[0];
  u64 soon = 0;
  for (IoAct *a = io_park.head; a != NULL; a = a->next) {
    if (a->work.time != 0 && (soon == 0 || a->work.time < soon)) soon = a->work.time;
    if (a->evts != 0 && (int)a->work.word > top) top = (int)a->work.word;
  }
  u64 len = (u64)top / 64 * 8 + 8;
  u8 *set[2] = {io_mem(calloc(2, len)), NULL};
  set[1] = set[0] + len;
  io_bit(set[0], io_wake_fd[0], true);
  for (IoAct *a = io_park.head; a != NULL; a = a->next) {
    if (a->evts != 0) io_bit(set[a->evts == POLLOUT], (int)a->work.word, true);
  }
  u64 tick = io_tick();
  u64 ms = soon > tick ? (soon - tick) / 1000000 + 1 : 0;
  struct timeval tv = {(time_t)(ms / 1000), (suseconds_t)(ms % 1000 * 1000)};
  io_sync();
  while (select(top + 1, (fd_set *)set[0], (fd_set *)set[1], NULL, soon == 0 ? NULL : &tv) < 0) {
    if (errno != EINTR) err_fail("the poller failed");
  }
  if (io_bit(set[0], io_wake_fd[0], false)) io_take(e);
  u64 now = io_tick();
  IoQue todo = io_park;
  io_park = (IoQue){0};
  while (todo.head != NULL) {
    IoAct *a = io_pop(&todo);
    bool due = (a->evts != 0 && io_bit(set[a->evts == POLLOUT], (int)a->work.word, false)) ||
      (a->work.time != 0 && a->work.time <= now);
    if (!due) {
      io_push(&io_park, a);
      continue;
    }
    Term x = a->work.pack(e, &a->work);
    if (x != IO_PARK) {
      a->item = x;
      io_push(&io_runs, a);
    }
  }
  free(set[0]);
}

// Runs a computation up to its next park; returns an exit code on a Halt.
static int io_step(Env e, IoAct *a) {
  for (;;) {
    Term req = apply(a->cont, a->item);
    u64 tg = TAG(req);
    if (tg == 0) {
      io_act_free(a);
      io_live -= 1;
      return -1;
    }
    if (tg == 1) {
      io_errs(e, FLD(req, 1));
      return (int)(u32)FLD(req, 0);
    }
    if (CID_KIND(tg & 0xffffff) != 3 || io_eff_rows[CID_TAG(tg)].run == NULL) err_fail("an alien request");
    u32 need = io_eff_rows[CID_TAG(tg)].ask;
    a->cont = req;
    if (need != 0) {
      Term f0 = FLD(req, 0);
      u32 word = (u32)(need & IO_READ ? io_hand_v(f0) : f0);
      io_wait_on(&a->work, (int)word, need & IO_READ ? POLLIN : 0,
        need & IO_TIME ? io_tick() + (u64)word * 1000000ull : 0, io_exec);
      return -1;
    }
    Term x = io_exec(e, &a->work);
    if (x == IO_PARK) return -1;
    a->item = x;
  }
}

// Chan
// ----

typedef struct {
  u32 gen;
  u32 next;
  u32 room;
  u32 size;
  u32 head;
  u32 live;
  u32 shut;
  Term *ring;
  IoQue wait;
} ChanRow;

static ChanRow *chan_rows;
static u32 chan_len;
static u32 chan_idle = ~0u;

#define chan_some(e, v) io_box(e, CID_SOME, v)
#define chan_bool(b) term_pak((b) ? CID_TRUE : CID_FALSE, 0)

static Term chan_open(u32 room) {
  pthread_mutex_lock(&gc_lock);
  u32 i = chan_idle;
  if (i != ~0u) {
    chan_idle = chan_rows[i].next;
  } else {
    if (chan_len == 1u << 24) err_fail("more than 16777216 channels at once");
    if ((chan_len & (chan_len - 1)) == 0)
      chan_rows = io_mem(realloc(chan_rows, (chan_len == 0 ? 1 : 2 * chan_len) * sizeof(ChanRow)));
    i = chan_len;
    chan_len += 1;
    chan_rows[i].gen = 0;
  }
  ChanRow *row = &chan_rows[i];
  row->gen += 1;
  row->room = room;
  row->size = 0;
  row->head = 0;
  row->shut = 0;
  row->ring = room == 0 ? NULL : io_mem(calloc(room, sizeof(Term)));
  row->wait.head = NULL;
  row->wait.last = NULL;
  row->live = 1;
  pthread_mutex_unlock(&gc_lock);
  return io_hand(((u64)row->gen << 24) | i);
}

static ChanRow *chan_at(Term t) {
  u64 v = io_hand_v(t);
  u32 i = (u32)v & 0xFFFFFF;
  ChanRow *row = i < chan_len ? &chan_rows[i] : NULL;
  return row != NULL && row->live && row->gen == (u32)(v >> 24) ? row : NULL;
}

// Parks the effect's activation on row with item: a sent value, or
// TERM_HOLE for a receiver.
static Term chan_park(ChanRow *row, IoWork *w, Term item) {
  IoAct *a = (IoAct *)w;
  a->item = item;
  io_push(&row->wait, a);
  return IO_PARK;
}

static Term chan_wake(ChanRow *row, Term x) {
  IoAct *a = io_pop(&row->wait);
  Term item = a->item;
  a->item = x;
  io_push(&io_runs, a);
  return item;
}

static Term chan_take(ChanRow *row) {
  Term v = row->ring[row->head];
  row->head = (row->head + 1) % row->room;
  row->size -= 1;
  if (row->wait.head != NULL) {
    Term item = chan_wake(row, chan_bool(true));
    row->ring[(row->head + row->size) % row->room] = item;
    row->size += 1;
  }
  return v;
}

static void chan_free(ChanRow *row) {
  pthread_mutex_lock(&gc_lock);
  free(row->ring);
  row->ring = NULL;
  row->live = 0;
  row->next = chan_idle;
  chan_idle = (u32)(row - chan_rows);
  pthread_mutex_unlock(&gc_lock);
}

static void chan_shut(Env e, ChanRow *row) {
  row->shut = 1;
  while (row->wait.head != NULL) {
    bool rcv = row->wait.head->item == TERM_HOLE;
    Term x = rcv ? term_pak(CID_NONE, 0) : chan_bool(false);
    term_sink(e, chan_wake(row, x));
  }
  if (row->size == 0) chan_free(row);
}

static void io_hook(void) {
  for (IoAct *a = io_acts; a != NULL; a = a->gnext) {
    gc_mark(a->cont);
    gc_mark(a->item);
  }
  for (u32 i = 0; i < chan_len; i++) {
    ChanRow *row = &chan_rows[i];
    if (row->live && row->ring) gc_scan(row->ring, row->ring + row->room);
  }
}

static int io_loop(Term m) {
  Env e = {0};
  signal(SIGPIPE, SIG_IGN);
  if (pipe(io_wake_fd) | fcntl(io_wake_fd[0], F_SETFL, O_NONBLOCK)) err_fail("the event loop failed to open");
  io_spawn(m);
  for (u32 n = 0;; n += 1) {
    if (io_runs.head == NULL) {
      if (io_live == 0) return 0;
      if (io_park.head == NULL && io_busy == 0) {
        io_sync();
        fprintf(stderr, "bend: deadlock: every computation waits on a channel\n");
        return 1;
      }
      io_wait(e);
      continue;
    }
    if ((n & 63) == 0 && io_busy != 0) io_take(e);
    int code = io_step(e, io_pop(&io_runs));
    if (code >= 0) return code;
  }
}

// Value printing (for a main that is not IO), in Bend syntax
// ==========================================================

static void pr_s(const char *s) { fputs(s, stdout); }
static void pr_u32(V v) { printf("%u", U(v)); }
static void pr_nat(V v) {
  char *s = nat_digits(v);
  fputs(s, stdout);
  putchar('n');
  free(s);
}
static void pr_f32(V v) {
  char buf[64];
  int n = f32_text(FV(v), buf, sizeof buf);
  char *ep = memchr(buf, 'e', (size_t)n);
  int m = ep == NULL ? n : (int)(ep - buf);
  if (strpbrk(buf, ".ni") == NULL) printf("%.*s.0%s", m, buf, buf + m);
  else fputs(buf, stdout);
}
// As the official term_show spells a character.
static void pr_cp(uint32_t cp, char quote) {
  int k = cp == 10 ? 'n' : cp == 9 ? 't' : cp == 13 ? 'r' : cp == 0 ? '0'
    : cp == 92 || cp == (uint32_t)quote ? (int)cp : 0;
  if (k != 0) {
    printf("\\%c", k);
  } else if (cp < 32 || cp == 127 || (cp >= 0xD800 && cp <= 0xDFFF) || cp > 0x10FFFF) {
    printf("\\u{%x}", cp);
  } else {
    char b[4];
    fwrite(b, 1, io_utf8(b, cp), stdout);
  }
}
static void pr_char(V v) { putchar('\''); pr_cp(U(v), '\''); putchar('\''); }
static void pr_str(V v) {
  putchar('"');
  while (TAG(v) == 1) { pr_cp(U(FLD(v, 0)), '"'); v = FLD(v, 1); }
  putchar('"');
}

// Entry points
// ============

static V (*bend_main_fn)(void);
static void (*bend_print_fn)(V);
static int bend_exit;

static void *bend_thread(void *arg) {
  thr_register((uintptr_t)__builtin_frame_address(0) + 16);
  if (arg) {
    bend_print_fn(bend_main_fn());
    putchar('\n');
  } else {
    bend_exit = io_loop(bend_main_fn());
  }
  fflush(stdout);
  return NULL;
}

static int bend_gpu = 1;
// --gpu SIZE: the device arena's first size in MB (0: the default), so a
// call that needs it does not first fill a smaller one.
static long bend_gpu_mb = 0;

static const char *CLI_HELP =
  "usage: %s [options] [arguments]\n"
  "  --threads N       worker threads, 1 to 128 (default: the CPU count)\n"
  "  --gpu on|off|4GB  where ! calls run: the GPU (the default) or the CPU threads\n"
  "  --bend-help       show this text\n"
  "  --                the rest are the program's arguments (IO.args)\n";

static void cli_fail(const char *msg) {
  fprintf(stderr, "bend: %s\n", msg);
  exit(1);
}

static int bend_start(int argc, char **argv, V (*m)(void), int value) {
  bend_main_fn = m;
  io_argv = calloc((size_t)argc + 1, sizeof(char *));
  io_argv[io_argc++] = argv[0];  // IO.args starts with the program as invoked
  long thr = 0;
  for (int i = 1; i < argc; i++) {
    const char *a = argv[i];
    const char *v = i + 1 < argc ? argv[i + 1] : NULL;
    if (strcmp(a, "--") == 0) {
      while (i + 1 < argc) io_argv[io_argc++] = argv[++i];
    } else if (strcmp(a, "--bend-help") == 0) {
      printf(CLI_HELP, argv[0]);
      return 0;
    } else if (strcmp(a, "--threads") == 0) {
      char *end = NULL;
      thr = v != NULL ? strtol(v, &end, 10) : 0;
      if (thr < 1 || thr > 128 || end == NULL || *end != '\0') cli_fail("expected a thread count of 1 or more after --threads");
      i++;
    } else if (strcmp(a, "--gpu") == 0) {
      if (v == NULL) cli_fail("expected on, off or a size like 4GB after --gpu");
      bend_gpu = strcmp(v, "off") != 0;
      {
        char *end = NULL;
        long n = strtol(v, &end, 10);
        if (end != v && n > 0) {
          if (strcmp(end, "GB") == 0 || strcmp(end, "G") == 0 || strcmp(end, "gb") == 0) bend_gpu_mb = n << 10;
          else if (strcmp(end, "MB") == 0 || strcmp(end, "M") == 0 || strcmp(end, "mb") == 0) bend_gpu_mb = n;
        }
      }
      i++;
    } else {
      io_argv[io_argc++] = argv[i];
    }
  }
  par_nthreads = thr > 0 ? (int)thr : cpu_count();
  // Fork 2^6 tasks a thread deep, then run subtrees in order.
  if (par_nthreads > 1) {
    int f = 0;
    while ((1 << f) < par_nthreads) f++;
    const char *fd = getenv("BEND_FORK_DEPTH");
    par_front = fd && *fd ? atoi(fd) : f + 6;
  }
  gc_init();
  struct sigaction sa;
  memset(&sa, 0, sizeof sa);
  sa.sa_handler = gc_handler;
  sa.sa_flags = SA_RESTART;
  sigemptyset(&sa.sa_mask);
  sigaction(GC_SIG, &sa, NULL);
  fault_init();
  gc_hook(par_hook);
  gc_hook(io_hook);
  pthread_attr_t attr;
  pthread_attr_init(&attr);
  pthread_attr_setstacksize(&attr, (size_t)1 << 32);
  pthread_t th;
  if (pthread_create(&th, &attr, bend_thread, value ? (void *)1 : NULL) != 0) {
    perror("pthread_create");
    return 1;
  }
  pthread_join(th, NULL);
  fflush(stdout);
  return bend_exit;
}

static int bend_run_value(int argc, char **argv, V (*m)(void), void (*p)(V)) {
  bend_print_fn = p;
  return bend_start(argc, argv, m, 1);
}

static int bend_run(int argc, char **argv, V (*m)(void)) { return bend_start(argc, argv, m, 0); }

#endif
