// Generated by tools/rtsplit.py from rt/bendrt.h: do not edit.
// The runtime's definitions: make builds build/bendrt.o from this.
#include "bendrt_split.h"
#if 1
#ifdef __linux__
#define _GNU_SOURCE
#endif
#define _DARWIN_UNLIMITED_SELECT  // select past FD_SETSIZE (io_wait)
#define IMM(t) ((((V)(t)) << 3) | 1)
#define BEND_SH ((V)1 << 20)
#define BEND_DEEP ((V)1 << 21)
#define BEND_SH_BITS (BEND_SH | BEND_DEEP)
#define BEND_HOLE IMM(0x7ffff)
#define BEND_BARRIER() __asm__ volatile("" ::: "memory")
#define FLD(v, i) (((V *)(v))[(i) + 1])
#define BOOL(b) ((b) ? IMM(1) : IMM(0))
#define word_con(b, r) ((V)(U32)(((U32)(r) << 1) | ((b) == IMM(1))))
#define UNIT IMM(0)
#if defined(__has_attribute)
#if __has_attribute(musttail)
#define BEND_MUSTTAIL __attribute__((musttail))
#endif
#endif
#ifndef BEND_MUSTTAIL
#define BEND_MUSTTAIL
#endif
#define LIKELY(x) __builtin_expect(!!(x), 1)
#define UNLIKELY(x) __builtin_expect(!!(x), 0)
#if defined(__clang__)
#define BEND_UINL static inline __attribute__((always_inline))
#elif defined(__TINYC__)
#define BEND_UINL static
#else
#define BEND_UINL static inline
#endif
#ifdef BEND_DEBUG_FREE
void *bend_debug_stk[1 << 20][12];
void bend_debug_record(uint64_t n) {
  void *f[13];
  int k = backtrace(f, 13);
  for (int j = 0; j < 12; j++) bend_debug_stk[n][j] = j + 1 < k ? f[j + 1] : NULL;
}
void bend_debug_show(uint64_t n) {
  int k = 0;
  while (k < 12 && bend_debug_stk[n][k]) k++;
  fprintf(stderr, "freed from:\n");
  backtrace_symbols_fd(bend_debug_stk[n], k, 2);
}
#define IS_N(v, t) (!((v) & 1) && TAG(v) == (t))
#else
#endif
__attribute__((noreturn)) void bend_fail(const char *msg) {
  fflush(stdout);
  fprintf(stderr, "bend: %s\n", msg);
  exit(1);
}
#define GC_BLK_SHIFT 16
#define GC_BLK ((uintptr_t)1 << GC_BLK_SHIFT)
#define GC_MAXBLK ((uintptr_t)1 << 22)
#define GC_HDR 64
#define GC_SMALL 2052
#define GC_NCLS 43
#define GC_MAXTHR 256
#define GC_SIG SIGUSR2
#define GC_RQCLS 15
const uint16_t gc_cls_w[GC_NCLS] = {
  2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,
  20, 24, 28, 32, 40, 48, 56, 64, 80, 96, 112, 128, 160, 192, 224, 256,
  320, 384, 448, 516, 640, 768, 896, 1028, 1280, 1536, 1792, 2052};
uint8_t gc_cls_of[GC_SMALL + 1];
char *gc_base;
uint64_t *gc_abits;
uint64_t *gc_mbits;
GcMeta *gc_meta;
uintptr_t gc_top;                // blocks in use (high-water mark)
uint8_t *gc_kind;                // per block: 0 free, 1 small, 2 large head, 3 large tail
uint32_t *gc_back;               // large tail: distance back to its head
GcRun *gc_runs;                  // free block runs below gc_top
size_t gc_nruns;
pthread_mutex_t gc_lock = PTHREAD_MUTEX_INITIALIZER;
GcBlk *gc_partial[2][GC_NCLS];
_Atomic size_t gc_since;         // bytes handed out since the last collection
size_t gc_limit = (size_t)8 << 20;
size_t gc_limit_min = (size_t)8 << 20;
double gc_minor_k = 2.0, gc_factor = 0.5;
size_t gc_slack = (size_t)8 << 20;
unsigned gc_grow = 1, gc_grow_max = 32, gc_kept_run;
double gc_t_end, gc_t_run, gc_t_stop;  // seconds (see gc_now)
size_t gc_live_bytes;
size_t gc_major_live;
int gc_minor;       // this collection keeps the marks of old objects
int gc_rooting;     // marking from roots (not from objects)
int gc_all_major;   // BEND_GC_MAJOR: every collection is a major one
size_t gc_count;
int gc_stats;
Thr *gc_thrs[GC_MAXTHR];
int gc_nthr;
V *gc_rem;
size_t gc_nrem, gc_caprem;
V *gc_rem_prev;  // the last collection's, sorted (while this one roots)
size_t gc_nprev, gc_capprev;
#define GC_CANDW (GC_MAXBLK / 64)
uint64_t *gc_cand;
int gc_mt;
int bend_rc_req;
GcHot gc_hot;
GcRange *gc_roots;
size_t gc_nroots, gc_caproots;
void (*gc_hooks[16])(void);
int gc_nhooks;
_Atomic int gc_stopping, gc_acks, gc_inside;
#ifdef __TINYC__
pthread_key_t tls_key;
pthread_once_t tls_once = PTHREAD_ONCE_INIT;
void tls_init(void) { pthread_key_create(&tls_key, NULL); }
TlsSlots *tls_get(void) {
  pthread_once(&tls_once, tls_init);
  TlsSlots *s = (TlsSlots *)pthread_getspecific(tls_key);
  if (!s) {
    s = (TlsSlots *)calloc(1, sizeof *s);
    pthread_setspecific(tls_key, s);
  }
  return s;
}
#define thr_self (*(Thr **)&tls_get()->self)
#define par_depth (tls_get()->par_depth)
#define thr_set(t) (thr_self = (t))
#elif defined(__APPLE__) && defined(__aarch64__)
pthread_key_t thr_key;
__attribute__((constructor)) void thr_key_init(void) { pthread_key_create(&thr_key, NULL); }
#define thr_self (thr_get())
#define thr_set(t) pthread_setspecific(thr_key, (t))
#else
__thread Thr *thr_self;
#define thr_set(t) (thr_self = (t))
#endif
GcItem *gc_stk;
uint8_t *gc_dirty;
size_t gc_sp, gc_cap;
void *gc_reserve(size_t bytes, void *hint) {
  void *p = mmap(hint, bytes, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANON | MAP_NORESERVE, -1, 0);
  if (p == MAP_FAILED) { perror("bend: mmap"); exit(1); }
  return p;
}
void gc_init(void) {
  // A high address keeps small numbers from looking like heap pointers.
  gc_base = gc_reserve(GC_MAXBLK << GC_BLK_SHIFT, (void *)((uintptr_t)1 << 44));
  if ((uintptr_t)gc_base < ((uintptr_t)1 << 32)) bend_fail("the heap must be above 4 GB (bend_share)");
  gc_kind = gc_reserve(GC_MAXBLK, NULL);
  gc_dirty = gc_reserve(GC_MAXBLK, NULL);
  gc_back = gc_reserve(GC_MAXBLK * sizeof(uint32_t), NULL);
  gc_runs = gc_reserve(GC_MAXBLK / 2 * sizeof(GcRun) + 64, NULL);
  gc_cap = ((size_t)1 << 33) / sizeof(GcItem);
  gc_stk = gc_reserve(gc_cap * sizeof(GcItem), NULL);
  gc_abits = gc_reserve(GC_MAXBLK * 64 * sizeof(uint64_t), NULL);
  gc_mbits = gc_reserve(GC_MAXBLK * 64 * sizeof(uint64_t), NULL);
  gc_meta = gc_reserve(GC_MAXBLK * sizeof(GcMeta), NULL);
  gc_cand = gc_reserve(GC_NCLS * GC_CANDW * sizeof(uint64_t), NULL);
  gc_hot = (GcHot){(uintptr_t)gc_base, 0, gc_abits, gc_cand, 0, bend_rc_req, 0};
  for (size_t w = 0, c = 0; w <= GC_SMALL; w++) {
    while (gc_cls_w[c] < w) c++;
    gc_cls_of[w] = (uint8_t)c;
  }
  const char *s = getenv("BEND_GC_STATS");
  gc_stats = s && *s;
  gc_all_major = getenv("BEND_GC_MAJOR") != NULL;
  if (getenv("BEND_GC_MINOR")) gc_minor_k = atof(getenv("BEND_GC_MINOR"));
  if (getenv("BEND_GC_FACTOR")) gc_factor = atof(getenv("BEND_GC_FACTOR"));
  if (getenv("BEND_GC_SLACK_MB")) gc_slack = (size_t)atol(getenv("BEND_GC_SLACK_MB")) << 20;
  const char *m = getenv("BEND_GC_MIN_MB");
  // (a heap size set this way stays: BEND_GC_GROW=n lets it grow n times)
  if (m && atol(m) > 0) gc_limit = gc_limit_min = (size_t)atol(m) << 20, gc_grow_max = 1;
  if (getenv("BEND_GC_GROW") && atoi(getenv("BEND_GC_GROW")) > 0) gc_grow_max = (unsigned)atoi(getenv("BEND_GC_GROW"));
  // Reference counting frees every object: the collector never runs.
  if (bend_rc_req) gc_limit = gc_limit_min = (size_t)-1;
}
#define GC_ALLOC(b) (gc_abits + gc_bi(b) * 64)
#define GC_MARK(b) (gc_mbits + gc_bi(b) * 64)
#define GC_META(b) (&gc_meta[gc_bi(b)])
uintptr_t gc_take_blocks(size_t n) {
  for (size_t i = 0; i < gc_nruns; i++) {
    if (gc_runs[i].len >= n) {
      uintptr_t at = gc_runs[i].at;
      gc_runs[i].at += (uint32_t)n;
      gc_runs[i].len -= (uint32_t)n;
      if (gc_runs[i].len == 0) gc_runs[i] = gc_runs[--gc_nruns];
      return at;
    }
  }
  if (gc_top + n > GC_MAXBLK) bend_fail("out of memory");
  uintptr_t at = gc_top;
  gc_top += n;
  gc_hot.span = gc_top << GC_BLK_SHIFT;
  return at;
}
GcBlk *gc_new_small(int atomic, unsigned c) {
  uintptr_t at = gc_take_blocks(1);
  GcBlk *b = gc_blk(at);
  memset(b, 0, sizeof(GcBlk));
  memset(GC_ALLOC(b), 0, 64 * sizeof(uint64_t));
  memset(GC_MARK(b), 0, 64 * sizeof(uint64_t));
  b->words = gc_cls_w[c];
  b->nobj = (uint32_t)((GC_BLK - GC_HDR) / (b->words * 8));
  *GC_META(b) = (GcMeta){(uint32_t)(((uint64_t)1 << 32) / (b->words * 8)) + 1, 0, (uint8_t)c, (uint16_t)b->words};
  b->nblk = 1;
  b->atomic = (uint8_t)atomic;
  b->cls = (uint8_t)c;
  b->owned = 1;
  __atomic_store_n(&gc_kind[at], 1, __ATOMIC_RELEASE);
  return b;
}
__attribute__((noinline)) V *gc_refill(GcCache *k, int atomic, unsigned c) {
  size_t sw = gc_cls_w[c];
  if (k->blk && (k->bits = gc_next_bits(k))) {
    int t = __builtin_ctzll(k->bits);
    k->bits &= k->bits - 1;
    uint32_t i = k->j * 64 + (uint32_t)t;
    V *p = k->objs + (size_t)i * sw;
    p[0] = BEND_HOLE;
    BEND_BARRIER();
    gc_setbit(&k->abits[i >> 6], 1ull << (i & 63));
    if (!k->reuse)
      atomic_fetch_add_explicit(&gc_since, ((size_t)__builtin_popcountll(k->bits) + 1) * sw * sizeof(V),
        memory_order_relaxed);
    return p;
  }
  // Counted, the thread's own frees go back to the block it allocates from:
  // while a 5th of it is free again, it goes on handing out those slots (no
  // lock, and the memory stays warm). Only its owner sets its bits.
  if (gc_hot.rc && k->blk) {
    GcBlk *q = k->blk;
    uint32_t used = 0;
    for (int j = 0; j < 64; j++) used += (uint32_t)__builtin_popcountll(__atomic_load_n(&GC_ALLOC(q)[j], __ATOMIC_RELAXED));
    if (q->nobj - used >= q->nobj / 5) {
      k->bump = k->end = NULL;
      k->j = (uint32_t)-1;
      k->bits = 0;
      return gc_refill(k, atomic, c);
    }
  }
  if (k->blk) { __atomic_store_n(&k->blk->owned, 0, __ATOMIC_RELEASE); k->blk = NULL; }
  // First the next block, in address order, where matches freed slots and a
  // 5th is free: lists built from its free slots stay in order in memory.
  // Candidate bits may be stale; the block is checked here. A block is
  // claimed by setting its owned flag (0 to 1), without gc_lock: no
  // collection runs meanwhile (the thread's stop is deferred), so a block
  // that is a small one stays one, and a new one is owned before it is one.
  GcBlk *b = NULL;
  k->reuse = 0;
  if (!atomic && c < (gc_hot.rc ? GC_NCLS : GC_RQCLS)) {
    Thr *t = thr_self;
    t->claiming = 1;
    atomic_signal_fence(memory_order_seq_cst);
    uint64_t *cand = gc_cand + (size_t)c * GC_CANDW;
    uintptr_t nw = (gc_top + 63) >> 6;
    uintptr_t at = t->rcur[c] < gc_top ? t->rcur[c] : 0;
    for (uintptr_t n = 0; b == NULL && n <= nw; n++) {
      uintptr_t w = ((at >> 6) + n) % (nw ? nw : 1);
      uint64_t f = cand[w];
      if (n == 0) f &= ~0ull << (at & 63);
      while (f && b == NULL) {
        uintptr_t bi = (w << 6) + (uintptr_t)__builtin_ctzll(f);
        f &= f - 1;
        __atomic_fetch_and(&cand[w], ~(1ull << (bi & 63)), __ATOMIC_RELAXED);
        if (bi >= gc_top || __atomic_load_n(&gc_kind[bi], __ATOMIC_ACQUIRE) != 1) continue;
        GcBlk *q = gc_blk(bi);
        if (q->cls != c || q->atomic || __atomic_load_n(&q->owned, __ATOMIC_RELAXED)) continue;
        uint8_t z = 0;
        if (!__atomic_compare_exchange_n(&q->owned, &z, 1, 0, __ATOMIC_ACQ_REL, __ATOMIC_RELAXED)) continue;
        uint32_t used = 0;
        for (int j = 0; j < 64; j++) used += (uint32_t)__builtin_popcountll(GC_ALLOC(q)[j]);
        if (q->nobj - used < q->nobj / 5) { __atomic_store_n(&q->owned, 0, __ATOMIC_RELEASE); continue; }
        b = q;
        k->reuse = 1;
        t->rcur[c] = (uint32_t)bi + 1;
      }
    }
    atomic_signal_fence(memory_order_seq_cst);
    t->claiming = 0;
    atomic_signal_fence(memory_order_seq_cst);
    if (t->deferred) { t->deferred = 0; gc_park(t); }
  }
  int fresh = 0;
  if (b == NULL) {
    pthread_mutex_lock(&gc_lock);
    if (gc_since >= gc_limit) gc_collect_locked();
    // (A partly free block may have been claimed for reuse since the sweep.)
    b = gc_partial[atomic][c];
    uint8_t z = 0;
    while (b && !__atomic_compare_exchange_n(&b->owned, &z, 1, 0, __ATOMIC_ACQ_REL, __ATOMIC_RELAXED)) {
      b = b->next;
      z = 0;
    }
    fresh = b == NULL;
    if (b) gc_partial[atomic][c] = b->next;
    else b = gc_new_small(atomic, c);
    pthread_mutex_unlock(&gc_lock);
  }
  k->blk = b;
  k->abits = GC_ALLOC(b);
  // A slot's allocation bit is set when the slot is handed out, never
  // before: a stale pointer must not mark a slot that is still free.
  V *objs = gc_objs(b);
  k->objs = objs;
  k->nj = (b->nobj + 63) >> 6;
  if (fresh) {
    // A fresh block is handed out by bumping a pointer.
    atomic_fetch_add_explicit(&gc_since, (size_t)b->nobj * sw * sizeof(V), memory_order_relaxed);
    k->bits = 0;
    k->j = k->nj;
    k->bump = objs + sw;
    k->end = objs + (size_t)b->nobj * sw;
    k->idx = 1;
    objs[0] = BEND_HOLE;
    BEND_BARRIER();
    GC_ALLOC(b)[0] |= 1;
    return objs;
  }
  k->bump = k->end = NULL;
  k->j = (uint32_t)-1;
  k->bits = 0;
  return gc_refill(k, atomic, c);
}
__attribute__((noinline)) V *gc_alloc_large(size_t w, int atomic) {
  size_t n = (GC_HDR + w * sizeof(V) + GC_BLK - 1) >> GC_BLK_SHIFT;
  pthread_mutex_lock(&gc_lock);
  if (gc_since >= gc_limit) gc_collect_locked();
  uintptr_t at = gc_take_blocks(n);
  GcBlk *b = gc_blk(at);
  memset(b, 0, sizeof(GcBlk));
  memset(GC_ALLOC(b), 0, 64 * sizeof(uint64_t));
  memset(GC_MARK(b), 0, 64 * sizeof(uint64_t));
  *GC_META(b) = (GcMeta){0, 1, 0, 0};
  b->words = (uint32_t)w;
  b->nobj = 1;
  b->nblk = (uint32_t)n;
  b->atomic = (uint8_t)atomic;
  b->large = 1;
  memset(gc_objs(b), 0, w * sizeof(V));
  gc_objs(b)[0] = BEND_HOLE;
  BEND_BARRIER();
  GC_ALLOC(b)[0] = 1;
  gc_kind[at] = 2;
  for (size_t j = 1; j < n; j++) { gc_kind[at + j] = 3; gc_back[at + j] = (uint32_t)j; }
  atomic_fetch_add_explicit(&gc_since, n * GC_BLK, memory_order_relaxed);
  pthread_mutex_unlock(&gc_lock);
  return gc_objs(b);
}
__attribute__((noinline)) void bend_share_slow(V v) {
  uint32_t i;
  GcBlk *b = gc_slot(v, &i);
  if (b == NULL) {
    uintptr_t off = (uintptr_t)v - (uintptr_t)gc_base;
    uintptr_t bi = off >> GC_BLK_SHIFT;
    uint8_t kd = gc_kind[bi];
    if (kd != 2 && kd != 3) return;
    if (kd == 3) bi -= gc_back[bi];
    b = gc_blk(bi);
    i = 0;
  }
  if (i >= b->nobj || b->atomic) return;
  if ((uintptr_t)v != (uintptr_t)gc_objs(b) + (uintptr_t)i * b->words * sizeof(V)) return;
  if (!(GC_ALLOC(b)[i >> 6] & (1ull << (i & 63)))) return;
  V *p = (V *)v;
  V w0 = __atomic_load_n(&p[0], __ATOMIC_RELAXED);
  if (w0 >= ((V)1 << 22)) {
    V n = p[2];
    if (b->words >= 3 && n <= (V)b->words - 3)
      for (V j = 0; j < n; j++)
        if (p[3 + j] >= ((V)1 << 32)) bend_share_slow(p[3 + j]);  // numbers are no nodes
  } else if (!(w0 & BEND_SH)) {
    __atomic_fetch_or(&p[0], BEND_SH, __ATOMIC_RELAXED);
  }
}
__attribute__((noinline)) void bend_deep(V v, unsigned w) {
  V *p = (V *)v;
  for (unsigned j = 1; j < w; j++) bend_share(p[j]);
  __atomic_fetch_or(&p[0], BEND_SH | BEND_DEEP, __ATOMIC_RELEASE);
}
#ifdef BEND_DEBUG_FREE
#define bend_take(v, w) bend_take_at(v, w, __LINE__)
#else
#define bend_take(v, w) bend_take_at(v, w, 0)
#endif
#define RC_ONE ((V)1 << 48)
#define RC_STICKY ((V)1 << 62)
#define RC_TS ((V)1 << 63)
#define RC_ADDR (RC_ONE - 1)
#define RC_REFS(w0) (((w0) >> 48) & 0x7fff)
#define rc_bmark() 0
#define RC_TMP(...) ((V)(V[]){__VA_ARGS__})
#define RC_TB(b, i, ...) ((i) ^= 1, (V)memcpy((b)[i], (V[]){__VA_ARGS__}, sizeof((V[]){__VA_ARGS__})))
#define rc_bdupFLD(p, i) rc_dup_in(FLD(p, i), rc_bmark())
#define rc_bdup(x) rc_dup_in((x), rc_bmark())
__attribute__((noinline)) void rc_free_large(uintptr_t bi) {
  pthread_mutex_lock(&gc_lock);
  GcBlk *b = gc_blk(bi);
  size_t n = b->nblk;
  GC_ALLOC(b)[0] = 0;
  for (size_t j = 0; j < n; j++) gc_kind[bi + j] = 0;
  gc_runs[gc_nruns++] = (GcRun){(uint32_t)bi, (uint32_t)n};
  pthread_mutex_unlock(&gc_lock);
}
#ifdef BEND_DEBUG_FREE
void rc_poison(V v, unsigned w) {
  static uint64_t nfreed;
  static long stop = -2;
  if (stop == -2) stop = getenv("BEND_DEBUG_FREE_AT") ? atol(getenv("BEND_DEBUG_FREE_AT")) : -1;
  uint64_t k = __atomic_add_fetch(&nfreed, 1, __ATOMIC_RELAXED);
  if ((long)k == stop) abort();
  V who = (V)(((uintptr_t)pthread_self() >> 12) & 0xff);
  bend_debug_record(k & 0xfffff);
  for (unsigned j = 0; j < w; j++) ((V *)v)[j] = ((V)0xDEAD << 48) | (who << 40) | ((k & 0xfffff) << 20);
}
#endif
void rc_push(Thr *t, V v) {
  if (t->rcn == t->rccap) {
    t->rccap = t->rccap ? t->rccap * 2 : 1024;
    t->rcs = realloc(t->rcs, t->rccap * sizeof(V));
    if (!t->rcs) bend_fail("out of memory");
  }
  t->rcs[t->rcn++] = v;
}
__attribute__((noinline)) void rc_free_obj(V v) {
  Thr *t = thr_self;
  size_t base = t->rcn;
  for (;;) {
    uintptr_t bi = ((uintptr_t)v - gc_hot.base) >> GC_BLK_SHIFT;
    size_t w = gc_kind[bi] == 1 ? gc_meta[bi].words : gc_blk(bi)->words;
    V *p = (V *)v;
    V next = 0;
    for (size_t j = 1; j < w; j++) {
      V x = p[j];
      if (rc_obj(x) && rc_release(x)) {
        if (next) rc_push(t, x);
        else next = x;
      }
    }
    rc_free_at(v, 0);
    if (next) { v = next; continue; }
    if (t->rcn == base) return;
    v = t->rcs[--t->rcn];
  }
}
__attribute__((noinline)) void rc_take_shared(V v, unsigned w) {
  V *p = (V *)v;
  V ts = __atomic_load_n(p, __ATOMIC_RELAXED) & RC_TS;
  for (unsigned j = 1; j < w; j++) rc_dup_in(p[j], ts);
  if (rc_release(v)) rc_free_obj(v);
}
__attribute__((noinline)) void rc_take_shared_d(V v, unsigned w, V keep) {
  V *p = (V *)v;
  V ts = __atomic_load_n(p, __ATOMIC_RELAXED) & RC_TS;
  for (unsigned j = 1; j < w; j++)
    if (rc_kept(keep, j)) rc_dup_in(p[j], ts);
  if (rc_release(v)) rc_free_obj(v);
}
#define RU(tok, w) ((tok) ? (V *)(tok) : halloc(w))
void rc_immortal(V v) {
  while (rc_obj(v) && !(*(V *)v & RC_STICKY)) {
    V *p = (V *)v;
    p[0] |= RC_STICKY;
    uintptr_t bi = ((uintptr_t)v - gc_hot.base) >> GC_BLK_SHIFT;
    size_t w = gc_kind[bi] == 1 ? gc_meta[bi].words : gc_blk(bi)->words;
    for (size_t j = 1; j + 1 < w; j++) rc_immortal(p[j]);
    v = w > 1 ? p[w - 1] : 0;
  }
}
__attribute__((noinline)) void rc_publish(V v) {
  Thr *t = thr_self;
  size_t base = t->rcn;
  for (;;) {
    V w0;
    if (rc_obj(v) && !((w0 = *(V *)v) & (RC_TS | RC_STICKY))) {
      V *p = (V *)v;
      p[0] = w0 | RC_TS;
      uintptr_t bi = ((uintptr_t)v - gc_hot.base) >> GC_BLK_SHIFT;
      size_t w = gc_kind[bi] == 1 ? gc_meta[bi].words : gc_blk(bi)->words;
      for (size_t j = 1; j < w; j++)
        if (p[j] >= ((V)1 << 32)) rc_push(t, p[j]);
    }
    if (t->rcn == base) return;
    v = t->rcs[--t->rcn];
  }
}
size_t rc_live(void) {
  size_t n = 0;
  for (uintptr_t bi = 0; bi < gc_top; bi++)
    if (gc_kind[bi] == 1 || gc_kind[bi] == 2)
      for (int j = 0; j < 64; j++) n += (size_t)__builtin_popcountll(gc_abits[bi * 64 + j]);
  return n;
}
void gc_root_add_locked(V *p, size_t n) {
  if (gc_nroots == gc_caproots) {
    gc_caproots = gc_caproots ? gc_caproots * 2 : 256;
    gc_roots = realloc(gc_roots, gc_caproots * sizeof(GcRange));
  }
  gc_roots[gc_nroots++] = (GcRange){p, n};
}
void gc_root_add(V *p, size_t n) {
  pthread_mutex_lock(&gc_lock);
  gc_root_add_locked(p, n);
  pthread_mutex_unlock(&gc_lock);
}
void gc_hook(void (*f)(void)) { gc_hooks[gc_nhooks++] = f; }
int gc_rem_wants(GcBlk *b, uint32_t i, uint64_t bit, uintptr_t o) {
  (void)bit;
  V *p = (V *)(o + i * (uintptr_t)b->words * sizeof(V));
  for (uint32_t j = 0; j < b->words; j++)
    if (p[j] == BEND_HOLE) return 1;
  return 0;
}
void gc_scan(const void *lo, const void *hi) {
  uintptr_t a = ((uintptr_t)lo + 7) & ~(uintptr_t)7;
  for (const V *p = (const V *)a; (const void *)p < hi; p++) gc_mark(*p);
}
void gc_drain(void) {
  while (gc_sp > 0) {
    GcItem it = gc_stk[--gc_sp];
    for (size_t j = 0; j < it.n; j++) gc_mark(it.p[j]);
  }
}
__attribute__((noinline)) void gc_park(Thr *t) {
  jmp_buf jb;
  setjmp(jb);
  atomic_fetch_add(&gc_inside, 1);
  t->sp = (uintptr_t)&jb;
  atomic_fetch_add(&gc_acks, 1);
  while (atomic_load(&gc_stopping)) sched_yield();
  atomic_fetch_sub(&gc_inside, 1);
}
void gc_handler(int sig) {
  (void)sig;
  int saved = errno;
  Thr *t = thr_self;
  if (t != NULL && atomic_load(&gc_stopping)) {
    if (t->claiming) t->deferred = 1;
    else gc_park(t);
  }
  errno = saved;
}
void gc_sweep(void) {
  memset(gc_partial, 0, sizeof gc_partial);
  size_t live = 0;
  for (uintptr_t bi = 0; bi < gc_top; bi++) {
    uint8_t kd = gc_kind[bi];
    if (kd == 1) {
      GcBlk *b = gc_blk(bi);
      if (b->owned) {
        live += GC_BLK;
        continue;
      }
      // What survives stays marked: it is old for the next minor collection.
      size_t used = 0;
      int words = (int)((b->nobj + 63) >> 6);
      for (int j = 0; j < words; j++) {
        GC_ALLOC(b)[j] &= GC_MARK(b)[j];
        used += (size_t)__builtin_popcountll(GC_ALLOC(b)[j]);
      }
      if (used == 0) {
        gc_kind[bi] = 0;
      } else {
        live += used * b->words * sizeof(V);
        if (used < b->nobj) {
          b->next = gc_partial[b->atomic][b->cls];
          gc_partial[b->atomic][b->cls] = b;
        }
      }
    } else if (kd == 2) {
      GcBlk *b = gc_blk(bi);
      if (GC_MARK(b)[0] & 1) {
        live += (size_t)b->nblk * GC_BLK;
      } else {
        for (uint32_t j = 0; j < b->nblk; j++) gc_kind[bi + j] = 0;
      }
      bi += b->nblk - 1;
    }
  }
  // Free runs, rebuilt from the block kinds.
  while (gc_top > 0 && gc_kind[gc_top - 1] == 0) gc_top--;
  gc_hot.span = gc_top << GC_BLK_SHIFT;
  gc_nruns = 0;
  for (uintptr_t bi = 0; bi < gc_top;) {
    if (gc_kind[bi] != 0) { bi++; continue; }
    uintptr_t at = bi;
    while (bi < gc_top && gc_kind[bi] == 0) bi++;
    gc_runs[gc_nruns++] = (GcRun){(uint32_t)at, (uint32_t)(bi - at)};
    // Hand the pages of long runs back to the system when the heap is far
    // larger than what lives in it.
    if (bi - at >= 256 && ((gc_top - bi + at) << GC_BLK_SHIFT) > 4 * live + ((size_t)1 << 30))
      madvise(gc_base + (at << GC_BLK_SHIFT), (bi - at) << GC_BLK_SHIFT, MADV_DONTNEED);
  }
  gc_live_bytes = live;
}
int gc_rem_cmp(const void *a, const void *b) {
  V x = *(const V *)a, y = *(const V *)b;
  return x < y ? -1 : x > y;
}
void gc_rem_unique(void) {
  if (gc_nrem < 2) return;
  qsort(gc_rem, gc_nrem, sizeof(V), gc_rem_cmp);
  size_t n = 1;
  for (size_t i = 1; i < gc_nrem; i++)
    if (gc_rem[i] != gc_rem[n - 1]) gc_rem[n++] = gc_rem[i];
  gc_nrem = n;
}
void gc_rescan_dirty(void) {
  for (uintptr_t bi = 0; bi < gc_top; bi++) {
    if (!gc_dirty[bi]) continue;
    gc_dirty[bi] = 0;
    if (!gc_minor) continue;
    GcBlk *b = gc_blk(bi);
    uint64_t *al = GC_ALLOC(b), *mk = GC_MARK(b);
    if (gc_kind[bi] == 2) {
      if ((al[0] & mk[0] & 1) && !b->atomic) {
        if (gc_sp == gc_cap) bend_fail("the collector's mark stack overflowed");
        gc_stk[gc_sp++] = (GcItem){gc_objs(b), b->words};
      }
    } else if (gc_kind[bi] == 1 && !b->atomic) {
      for (uint32_t i = 0; i < b->nobj; i++) {
        if (!(al[i >> 6] & mk[i >> 6] & (1ull << (i & 63)))) continue;
        if (gc_sp == gc_cap) bend_fail("the collector's mark stack overflowed");
        gc_stk[gc_sp++] = (GcItem){gc_objs(b) + (size_t)i * b->words, b->words};
      }
    }
  }
}
double gc_now(void) {
  struct timespec t;
  clock_gettime(CLOCK_MONOTONIC, &t);
  return (double)t.tv_sec + (double)t.tv_nsec * 1e-9;
}
__attribute__((noinline)) void gc_collect_locked(void) {
  Thr *me = thr_self;
  double t0 = gc_now();
  size_t live0 = gc_live_bytes;
  atomic_store(&gc_acks, 0);
  atomic_store(&gc_stopping, 1);
  int n = 0;
  for (int i = 0; i < gc_nthr; i++) {
    Thr *t = gc_thrs[i];
    if (t != me && t->live) {
      if (pthread_kill(t->id, GC_SIG) == 0) n++;
    }
  }
  while (atomic_load(&gc_acks) < n) sched_yield();
  jmp_buf jb;
  setjmp(jb);
  me->sp = (uintptr_t)&jb;
  // A major collection forgets every mark; a minor one keeps the old
  // objects' (the heap is written only while an object is built, and the
  // exceptions are reached from roots).
  gc_minor = !gc_all_major && gc_major_live > 0 && gc_live_bytes < (size_t)(gc_minor_k * (double)gc_major_live) + gc_slack * gc_grow;
  if (!gc_minor) {
    for (uintptr_t bi = 0; bi < gc_top; bi++) {
      if (gc_kind[bi] == 1 || gc_kind[bi] == 2) memset(gc_mbits + bi * 64, 0, 64 * sizeof(uint64_t));
    }
  }
  gc_rooting = 1;
  {
    // The last collection's list becomes gc_rem_prev (sorted by
    // gc_rem_unique); this one records into gc_rem.
    V *t = gc_rem_prev; gc_rem_prev = gc_rem; gc_rem = t;
    size_t c = gc_capprev; gc_capprev = gc_caprem; gc_caprem = c;
    gc_nprev = gc_nrem;
    gc_nrem = 0;
    gc_rooting = 2;  // rescanned, not recorded again
    if (gc_minor) for (size_t i = 0; i < gc_nprev; i++) gc_mark(gc_rem_prev[i]);
    gc_rooting = 1;
  }
  for (int i = 0; i < gc_nthr; i++) {
    Thr *t = gc_thrs[i];
    if (t->live) gc_scan((const void *)t->sp, (const void *)t->top);
  }
  gc_rem_unique();
  gc_rooting = 3;  // other roots hold no half-made nodes
  for (size_t i = 0; i < gc_nroots; i++) gc_scan(gc_roots[i].p, gc_roots[i].p + gc_roots[i].n);
  for (int i = 0; i < gc_nhooks; i++) gc_hooks[i]();
  gc_rooting = 0;
  gc_rescan_dirty();
  gc_drain();
  gc_sweep();
  atomic_store(&gc_stopping, 0);
  while (atomic_load(&gc_inside) > 0) sched_yield();
  if (!gc_minor) gc_major_live = gc_live_bytes ? gc_live_bytes : 1;
  {
    if (gc_minor) {
      size_t kept = gc_live_bytes > live0 ? gc_live_bytes - live0 : 0;
      gc_kept_run = kept * 4 > gc_since * 3 ? gc_kept_run + 1 : 0;
      if (gc_kept_run >= 2) gc_grow = gc_grow_max;
    }
    double t1 = gc_now();
    if (gc_t_end > 0) gc_t_run += t0 - gc_t_end;
    gc_t_stop += t1 - t0;
    gc_t_end = t1;
    if ((gc_count & 7) == 7) {
      if (gc_t_stop * 10 > gc_t_run + gc_t_stop && gc_grow < gc_grow_max) gc_grow = gc_grow * 2 < gc_grow_max ? gc_grow * 2 : gc_grow_max;
      gc_t_run = gc_t_stop = 0;
    }
    size_t want = (size_t)(gc_factor * (double)gc_live_bytes), least = gc_limit_min * gc_grow;
    gc_limit = want > least ? want : least;
  }
  gc_since = 0;
  gc_count++;
  if (gc_stats) {
    fprintf(stderr, "[gc %zu %s] live %zu MB, heap %zu MB, next at +%zu MB, %zu rescans next, %.1f ms\n",
      gc_count, gc_minor ? "minor" : "major", gc_live_bytes >> 20, (size_t)(gc_top << GC_BLK_SHIFT) >> 20,
      gc_limit >> 20, gc_nrem,
      (gc_t_end - t0) * 1e3);
  }
}
void gc_collect(void) {
  pthread_mutex_lock(&gc_lock);
  gc_collect_locked();
  pthread_mutex_unlock(&gc_lock);
}
void bend_fault(int sig) {
  (void)sig;
  static const char msg[] = "bend: memory fault (machine stack overflow?)\n";
  fflush(stdout);
  if (write(2, msg, sizeof msg - 1) < 0) {}
  _exit(1);
}
void fault_stack(void) {
  stack_t ss;
  ss.ss_size = 1 << 16;
  ss.ss_sp = malloc(ss.ss_size);
  ss.ss_flags = 0;
  if (ss.ss_sp) sigaltstack(&ss, NULL);
}
void fault_init(void) {
  struct sigaction sa;
  memset(&sa, 0, sizeof sa);
  sa.sa_handler = bend_fault;
  sa.sa_flags = SA_ONSTACK;
  sigemptyset(&sa.sa_mask);
  sigaction(SIGSEGV, &sa, NULL);
  sigaction(SIGBUS, &sa, NULL);
}
#define BEND_STK ((uintptr_t)1 << 32)
void thr_stack(pthread_attr_t *attr) {
  uintptr_t pg = (uintptr_t)sysconf(_SC_PAGESIZE);
  char *m = mmap(NULL, 2 * BEND_STK, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANON | MAP_NORESERVE, -1, 0);
  if (m == MAP_FAILED) bend_fail("could not map a thread's stack");
  char *a = (char *)(((uintptr_t)m + BEND_STK - 1) & ~(BEND_STK - 1));
  if (a > m) munmap(m, (size_t)(a - m));
  munmap(a + BEND_STK, (size_t)(m + BEND_STK - a));
  mprotect(a + pg, pg, PROT_NONE);
  pthread_attr_setstack(attr, a + 2 * pg, BEND_STK - 2 * pg);
}
void thr_register(uintptr_t top) {
  fault_stack();
  Thr *t = calloc(1, sizeof(Thr));
  *(Thr **)(top & ~(BEND_STK - 1)) = t;
  t->top = top;
  t->id = pthread_self();
  t->live = 1;
  t->rng = (uint32_t)(uintptr_t)t ^ 0x9e3779b9u;
  t->dq = pdq_new();
  thr_set(t);
  pthread_mutex_lock(&gc_lock);
  if (gc_nthr == GC_MAXTHR) bend_fail("too many threads");
  gc_thrs[gc_nthr] = t;
  int n1 = gc_nthr + 1;  // tcc's __atomic_store_n evaluates its value twice
  __atomic_store_n(&gc_nthr, n1, __ATOMIC_RELEASE);
  pthread_mutex_unlock(&gc_lock);
}
#define RUF(u) do { if (u) rc_free_at(u, 0); } while (0)
#define ARR_TAG ((V)0xFFF00)
#define ARR_HDR(c) (ARR_TAG | (V)(c))
void rc_let_go_arr(V a) {
  if (rc_unique(a)) rc_free_at(a, 0);
  else {
    size_t n = (size_t)1 << arr_cls(a);
    V ts = ((V *)a)[0] & RC_TS;
    for (size_t i = 0; i < n; i++) rc_dup_in(arr_cells(a)[i], ts);
    rc_drop(a);
  }
}
V arr_alloc(unsigned c) {
  if (c > 31) bend_fail("an array past the deepest block class 31");
  V *p = halloc(1 + ((size_t)1 << c));
  p[0] = ARR_HDR(c);
  return (V)p;
}
V arr_copy(unsigned c, const V *src, int share, V ts) {
  size_t n = (size_t)1 << c;
  V a = arr_alloc(c);
  V *d = arr_cells(a);
  arr_dirty(a);
  for (size_t i = 0; i < n; i++) {
    V x = src[i];
    if (share) { if (gc_hot.rc) rc_dup_in(x, ts); else bend_share(x); }
    d[i] = x;
  }
  return a;
}
V arr_new(V depth, V v) {
  if (depth > 31) bend_fail("an array past the deepest block class 31");
  unsigned c = (unsigned)depth;
  size_t n = (size_t)1 << c;
  V a = arr_alloc(c);
  V *d = arr_cells(a);
  if (c > 0) {
    if (gc_hot.rc) rc_dupn(v, n - 1);
    else bend_share(v);
  }
  if (v >= ((V)1 << 32)) arr_dirty(a);
  for (size_t i = 0; i < n; i++) d[i] = v;
  return a;
}
V arr_node(V l, V r) {
  unsigned c = arr_cls(l);
  if (arr_cls(r) != c || c >= 31) bend_fail("runtime fail-stop");
  size_t n = (size_t)1 << c;
  V a = arr_alloc(c + 1);
  V *d = arr_cells(a);
  int sl = !gc_hot.rc && arr_shared(l), sr = !gc_hot.rc && arr_shared(r);
  arr_dirty(a);
  for (size_t i = 0; i < n; i++) { V x = arr_cells(l)[i]; if (sl) bend_dup(x); d[i] = x; }
  for (size_t i = 0; i < n; i++) { V x = arr_cells(r)[i]; if (sr) bend_dup(x); d[n + i] = x; }
  // (counted, the halves' cells moved here, or got a reference each)
  if (gc_hot.rc) { rc_let_go_arr(l); rc_let_go_arr(r); }
  return a;
}
V arr_half(V a, unsigned hi) {
  unsigned c = arr_cls(a);
  if (c == 0) bend_fail("runtime fail-stop");
  return arr_copy(c - 1, arr_cells(a) + ((size_t)hi << (c - 1)), gc_hot.rc || arr_shared(a), ((V *)a)[0] & RC_TS);
}
#define ARR_ATOMIC(name, op) static inline V F_Array_datomic_d##name(V a, V i, V v) { return C2(0, a, (V)__atomic_##op(arr_word(a, i), (uint32_t)v, __ATOMIC_SEQ_CST)); }
#ifdef __TINYC__
#else
#endif
V apply(V f, V x) {
  V *c = (V *)f;
  V ar = c[1], n = c[2];
  Fn fn = (Fn)(uintptr_t)(c[0] & RC_ADDR);
  if (n + 1 == ar) {
    V a[n + 1];
    for (V i = 0; i < n; i++) a[i] = c[3 + i];
    a[n] = x;
    if (gc_hot.rc) rc_let_go(f, (unsigned)(3 + n));
    return fn(a);
  }
  V *p = halloc(4 + n);
  p[0] = (V)(uintptr_t)fn; p[1] = ar; p[2] = n + 1;
  for (V i = 0; i < n; i++) p[3 + i] = c[3 + i];
  p[3 + n] = x;
  if (gc_hot.rc) rc_let_go(f, (unsigned)(3 + n));
  return (V)p;
}
#define SNIL IMM(0)
#define SCONS(h, t) C2(1, (h), (t))
#define NIL IMM(0)
#define CONS(h, t) C2(1, (h), (t))
V mk_str(const char *s, size_t n) {
  uint32_t small[256];
  uint32_t *cps = n <= 256 ? small : malloc(n * sizeof(uint32_t));
  size_t k = 0;
  for (size_t i = 0; i < n;) {
    unsigned char c = (unsigned char)s[i];
    uint32_t cp; int len;
    if (c < 0x80) { cp = c; len = 1; }
    else if ((c >> 5) == 6 && i + 1 < n) { cp = c & 0x1f; len = 2; }
    else if ((c >> 4) == 14 && i + 2 < n) { cp = c & 0x0f; len = 3; }
    else if ((c >> 3) == 30 && i + 3 < n) { cp = c & 0x07; len = 4; }
    else { cp = c; len = 1; }
    for (int j = 1; j < len; j++) cp = (cp << 6) | ((unsigned char)s[i + j] & 0x3f);
    cps[k++] = cp;
    i += len;
  }
  V r = SNIL;
  while (k > 0) { k--; r = SCONS(cps[k], r); }
  if (cps != small) free(cps);
  return r;
}
#define MKS(lit) mk_str(lit, sizeof(lit) - 1)
#define STRC(c, lit) (__atomic_load_n(&(c), __ATOMIC_ACQUIRE) ? (c) : str_cache(&(c), lit, sizeof(lit) - 1))
#define mk_str_heap mk_str
__attribute__((noinline)) V str_cache(V *slot, const char *s, size_t n) {
  V v = mk_str(s, n);
  if (gc_hot.rc) rc_immortal(v);
  else bend_share(v);  // before another thread can see it
  pthread_mutex_lock(&gc_lock);
  if (*slot == 0) {
    __atomic_store_n(slot, v, __ATOMIC_RELEASE);
    gc_root_add_locked(slot, 1);
  }
  v = *slot;
  pthread_mutex_unlock(&gc_lock);
  return v;
}
__attribute__((noinline)) V konst_cache(V *slot, V v) {
  if (gc_hot.rc) rc_immortal(v);
  else bend_share(v);
  pthread_mutex_lock(&gc_lock);
  if (*slot == 0) {
    __atomic_store_n(slot, v, __ATOMIC_RELEASE);
    gc_root_add_locked(slot, 1);
  }
  v = *slot;
  pthread_mutex_unlock(&gc_lock);
  return v;
}
#define KONST(c, e) (__atomic_load_n(&(c), __ATOMIC_ACQUIRE) ? (c) : konst_cache(&(c), (e)))
char *str_to_c(V s, size_t *len) {
  size_t cap = 64, n = 0;
  char *buf = malloc(cap);
  while (TAG(s) == 1) {
    uint32_t cp = (uint32_t)FLD(s, 0);
    if (n + 5 > cap) { cap *= 2; buf = realloc(buf, cap); }
    if (cp < 0x80) buf[n++] = (char)cp;
    else if (cp < 0x800) { buf[n++] = 0xc0 | (cp >> 6); buf[n++] = 0x80 | (cp & 0x3f); }
    else if (cp < 0x10000) {
      buf[n++] = 0xe0 | (cp >> 12); buf[n++] = 0x80 | ((cp >> 6) & 0x3f); buf[n++] = 0x80 | (cp & 0x3f);
    } else {
      buf[n++] = 0xf0 | (cp >> 18); buf[n++] = 0x80 | ((cp >> 12) & 0x3f);
      buf[n++] = 0x80 | ((cp >> 6) & 0x3f); buf[n++] = 0x80 | (cp & 0x3f);
    }
    s = FLD(s, 1);
  }
  buf[n] = 0;
  if (len) *len = n;
  return buf;
}
#define NAT_IMM (((V)1 << 48) - 1)
__attribute__((noreturn, cold, noinline)) void nat_wall(void) {
  bend_fail("a Nat past the largest immediate 2^48-1");
}
V nat_pow(V a, V n) {
  if (a <= 1) return n == 0 ? 1 : a;
  V r = 1;
  for (; n; n--) r = nat_mul(r, a);
  return r;
}
char *nat_digits(V x) {
  nat_chk(x / 10);
  char *s = malloc(24);
  snprintf(s, 24, "%llu", (unsigned long long)x);
  return s;
}
V F_Nat_dshow(V a) {
  char *s = nat_digits(a);
  V r = mk_str(s, strlen(s));
  free(s);
  return r;
}
#ifdef BEND_NATIVE_MAP_BIT
#endif
#ifdef BEND_NATIVE_STR
#endif
#ifdef BEND_NATIVE_MAP
#endif
#define U(x) ((uint32_t)(x))
#define F2(name, expr) static inline V F_F32_d##name(V a, V b) { float x = FV(a), y = FV(b); return expr; }
#define F1(name, expr) static inline V F_F32_d##name(V a) { float x = FV(a); return expr; }
__attribute__((noinline, cold)) float F32_mul_add(float x, float k, float c) {
  float p = x * k;
  return p + c;
}
int f32_text(float v, char *buf, size_t n) {
  int k = 0, p = 0;
  if (v != v) return snprintf(buf, n, "nan");
  for (; p < 9; p++) {
    k = snprintf(buf, n, "%.*e", p, (double)v);
    if (strtof(buf, NULL) == v) break;
  }
  char *ep = strchr(buf, 'e');
  if (ep == NULL) return k;
  int ex = atoi(ep + 1);
  if (ex >= 21 || ex <= -7) {
    k = (int)(ep - buf) + snprintf(ep, n - (size_t)(ep - buf), "e%c%d", ex < 0 ? '-' : '+', abs(ex));
  } else if (ex <= p) {
    k = snprintf(buf, n, "%.*f", p - ex, (double)v);
  } else {
    int s = *buf == '-';
    memmove(buf + s + 1, buf + s + 2, (size_t)p);
    memset(buf + s + 1 + p, '0', (size_t)(ex - p));
    k = s + 1 + ex;
    buf[k] = 0;
  }
  return k;
}
V F_F32_dshow(V a) {
  char buf[64];
  f32_text(FV(a), buf, sizeof buf);
  return mk_str(buf, strlen(buf));
}
V F_F32_dread(V s) {
  char *c = str_to_c(s, NULL);
  bend_drop(s);
  char *end;
  float f = strtof(c, &end);
  int ok = *c && !*end;
  free(c);
  return ok ? C1(1, VF(f)) : IMM(0);
}
#define P_LOCAL 0
#define P_QUEUED 1
#define P_DONE 2
#define P_HELD 3
#ifndef __TINYC__
__thread int par_depth;
#endif
int par_front = 0;
int par_nthreads = 1;
#define pool_size ((u32)par_nthreads)
_Atomic int par_started;
pthread_mutex_t par_mu = PTHREAD_MUTEX_INITIALIZER;
pthread_cond_t par_cv = PTHREAD_COND_INITIALIZER;
_Atomic int par_sleepers;
PDeque *pdq_new(void) {
  PDeque *d = calloc(1, sizeof(PDeque));
  d->mask = (1 << 16) - 1;
  d->buf = calloc((size_t)d->mask + 1, sizeof(PTask *));
  return d;
}
PTask *pdq_pop(PDeque *d) {
  long b = atomic_load_explicit(&d->bot, memory_order_relaxed) - 1;
  atomic_store_explicit(&d->bot, b, memory_order_relaxed);
  atomic_thread_fence(memory_order_seq_cst);
  long t = atomic_load_explicit(&d->top, memory_order_relaxed);
  if (t <= b) {
    PTask *x = __atomic_load_n(&d->buf[b & d->mask], __ATOMIC_RELAXED);
    if (t == b) {
      if (!atomic_compare_exchange_strong_explicit(&d->top, &t, t + 1, memory_order_seq_cst,
            memory_order_relaxed))
        x = NULL;
      atomic_store_explicit(&d->bot, b + 1, memory_order_relaxed);
    }
    return x;
  }
  atomic_store_explicit(&d->bot, b + 1, memory_order_relaxed);
  return NULL;
}
PTask *pdq_steal(PDeque *d) {
  long t = atomic_load_explicit(&d->top, memory_order_acquire);
  atomic_thread_fence(memory_order_seq_cst);
  long b = atomic_load_explicit(&d->bot, memory_order_acquire);
  if (t < b) {
    PTask *x = __atomic_load_n(&d->buf[t & d->mask], __ATOMIC_RELAXED);
    // (x may be gone, when the CAS fails; a task is held only before it
    // is let go)
    if (__atomic_load_n(&x->state, __ATOMIC_ACQUIRE) == P_HELD) {
      if (!atomic_load_explicit(&d->want, memory_order_relaxed))
        atomic_store_explicit(&d->want, 1, memory_order_relaxed);
      return NULL;
    }
    if (!atomic_compare_exchange_strong_explicit(&d->top, &t, t + 1, memory_order_seq_cst,
          memory_order_relaxed))
      return NULL;
    return x;
  }
  return NULL;
}
void par_exec(PTask *t) {
  int d = par_depth;
  par_depth = (int)t->depth;
  V r = apply(t->clo, 0);
  par_depth = d;
  t->res = r;
  __atomic_store_n(&t->state, P_DONE, __ATOMIC_RELEASE);
}
PTask *par_steal(void) {
  Thr *me = thr_self;
  int n = __atomic_load_n(&gc_nthr, __ATOMIC_ACQUIRE);
  if (n <= 1) return NULL;
  me->rng = me->rng * 1664525u + 1013904223u;
  int s = (int)(me->rng >> 8) % n;
  for (int i = 0; i < n; i++) {
    Thr *t = gc_thrs[(s + i) % n];
    if (t == me || !t->live || !t->dq) continue;
    PTask *x = pdq_steal(t->dq);
    if (x) return x;
  }
  return NULL;
}
void *par_worker(void *arg) {
  (void)arg;
  thr_register((uintptr_t)__builtin_frame_address(0) + 16);
  for (int spins = 0;;) {
    PTask *t = par_steal();
    if (t) { par_exec(t); spins = 0; continue; }
    if (++spins < 512) { cpu_relax(); continue; }
    pthread_mutex_lock(&par_mu);
    atomic_fetch_add(&par_sleepers, 1);
    struct timeval now;
    gettimeofday(&now, NULL);
    struct timespec until = {now.tv_sec, now.tv_usec * 1000 + 2000000};
    if (until.tv_nsec >= 1000000000) { until.tv_sec++; until.tv_nsec -= 1000000000; }
    pthread_cond_timedwait(&par_cv, &par_mu, &until);
    atomic_fetch_sub(&par_sleepers, 1);
    pthread_mutex_unlock(&par_mu);
    spins = 0;
  }
  return NULL;
}
void par_hook(void) {
  for (int i = 0; i < gc_nthr; i++) {
    PDeque *d = gc_thrs[i]->dq;
    if (!d) continue;
    long t = atomic_load(&d->top) - 1, b = atomic_load(&d->bot) + 1;
    if (b - t > d->mask + 1) t = b - (d->mask + 1);
    for (long j = t; j < b; j++) gc_mark((V)d->buf[j & d->mask]);
  }
}
void par_start(void) {
  pthread_mutex_lock(&par_mu);
  if (!atomic_load(&par_started)) {
    gc_mt = 1;
    gc_hot.mt = 1;
    gc_hot.rcmt = gc_hot.rc;
    for (int i = 1; i < par_nthreads; i++) {
      pthread_attr_t attr;
      pthread_attr_init(&attr);
      thr_stack(&attr);
      pthread_t th;
      if (pthread_create(&th, &attr, par_worker, NULL) == 0) pthread_detach(th);
      pthread_attr_destroy(&attr);
    }
    atomic_store(&par_started, 1);
  }
  pthread_mutex_unlock(&par_mu);
}
__attribute__((noinline)) void par_serve(PDeque *d) {
  atomic_store_explicit(&d->want, 0, memory_order_relaxed);
  long b = atomic_load_explicit(&d->bot, memory_order_relaxed);
  for (long i = atomic_load_explicit(&d->top, memory_order_acquire); i < b; i++) {
    PTask *x = __atomic_load_n(&d->buf[i & d->mask], __ATOMIC_RELAXED);
    if (__atomic_load_n(&x->state, __ATOMIC_RELAXED) == P_HELD) {
      rc_publish(x->clo);
      __atomic_store_n(&x->state, P_QUEUED, __ATOMIC_RELEASE);
      return;
    }
  }
}
V par_fork(V clo) {
#ifdef BEND_DEBUG_FREE
  // Debugging, on one thread: BEND_DEBUG_EAGER runs forks as they are made,
  // in the order other threads may run them (the result boxed, tagged 4).
  if (par_nthreads <= 1 && getenv("BEND_DEBUG_EAGER")) {
    V *box = halloc(1);
    box[0] = apply(clo, 0);
    return (V)box | 4;
  }
#endif
  if (par_nthreads <= 1) return clo | 2;
  PDeque *d = thr_self->dq;
  par_serve_if(d);
  long b = atomic_load_explicit(&d->bot, memory_order_relaxed);
  long tp = atomic_load_explicit(&d->top, memory_order_relaxed);
  if (b - tp >= 4) return clo | 2;
  if (UNLIKELY(!atomic_load_explicit(&par_started, memory_order_relaxed))) par_start();
  PTask *t = (PTask *)halloc(4);
  t->clo = clo;
  t->depth = (V)par_depth;
  t->state = gc_hot.rc ? P_HELD : P_QUEUED;
  __atomic_store_n(&d->buf[b & d->mask], t, __ATOMIC_RELAXED);
  atomic_thread_fence(memory_order_release);
  atomic_store_explicit(&d->bot, b + 1, memory_order_relaxed);
  if (atomic_load_explicit(&par_sleepers, memory_order_relaxed) > 0) pthread_cond_signal(&par_cv);
  return (V)t;
}
V par_join(V tv) {
  if (tv & 4) return ((V *)(tv & ~(V)4))[0];
  if (tv & 2) return apply(tv & ~(V)2, 0);
  PTask *t = (PTask *)tv;
  PDeque *d = thr_self->dq;
  par_serve_if(d);
  PTask *p = pdq_pop(d);
  if (p == t) {
    V clo = t->clo;
    if (gc_hot.rc) rc_free_at((V)t, 4);
    return apply(clo, 0);
  }
  if (p) par_exec(p);
  // With nothing to steal, a joiner spins a little, then yields its core,
  // then naps (the task it waits for may be running on a thread that has no
  // core of its own when there are more threads than cores).
  for (int spins = 0; __atomic_load_n(&t->state, __ATOMIC_ACQUIRE) != P_DONE;) {
    par_serve_if(d);
    PTask *o = par_steal();
    if (o) { par_exec(o); spins = 0; continue; }
    if (++spins < 64) cpu_relax();
    else if (spins < 256) sched_yield();
    else { struct timespec ts = {0, 20000}; nanosleep(&ts, NULL); }
  }
  V r = t->res;
  if (gc_hot.rc) rc_free_at((V)t, 4);
  return r;
}
int cpu_count(void) {
  long n = sysconf(_SC_NPROCESSORS_ONLN);
  return n < 1 ? 1 : n > 128 ? 128 : (int)n;
}
#ifndef CID_TUPLE
#define CID_TUPLE 0u
#endif
#ifndef CID_DONE
#define CID_DONE 1u
#endif
#ifndef CID_FAIL
#define CID_FAIL 0u
#endif
#ifndef CID_SOME
#define CID_SOME 1u
#endif
#ifndef CID_NONE
#define CID_NONE ((1u << 16) | 0u)
#endif
#ifndef CID_TRUE
#define CID_TRUE ((1u << 16) | 1u)
#endif
#ifndef CID_FALSE
#define CID_FALSE ((1u << 16) | 0u)
#endif
#ifndef CID_UNIT
#define CID_UNIT ((1u << 16) | 0u)
#endif
#define OUTLINE __attribute__((noinline))
#define IO_READ 1
#define IO_TIME 2
#define IO_HELP 64
V io_hole_cell;
#define TERM_HOLE ((Term)(uintptr_t)&io_hole_cell)
#define IO_PARK TERM_HOLE
#define io_hand(v) ((Term)(v))
#define io_hand_v(t) ((u64)(t))
#define CID_KIND(c) ((u32)(c) >> 16)
#define CID_TAG(c) ((u32)(c) & 0xffff)
__attribute__((noreturn)) void err_fail(const char *msg) { bend_fail(msg); }
#define term_drop(e, t) ((void)(e), bend_drop(t))
#define term_sink(e, t) ((void)(e), bend_drop(t))
#define cls_fit(n) 0
#define spare_free(e, c, x) ((void)(e), (void)(c), (void)(x))
#define f32_unbox(t) FV(t)
IoEff io_eff_rows[1 << 16];
u32 io_live;
int io_argc;
char **io_argv;
void io_eff(u32 cid, Effect run, u32 need) { io_eff_rows[CID_TAG(cid)] = (IoEff){run, need}; }
u64 io_tick(void) {
  struct timespec ts;
  clock_gettime(CLOCK_MONOTONIC, &ts);
  return (u64)ts.tv_sec * 1000000000ull + (u64)ts.tv_nsec;
}
OUTLINE void *io_mem(void *mem) {
  if (mem == NULL) err_fail("host allocation failed");
  return mem;
}
int io_sys_addr(const char *host, u32 port, struct sockaddr_in *at) {
  memset(at, 0, sizeof(*at));
  at->sin_family = AF_INET;
  at->sin_port = htons((uint16_t)port);
  for (const char *p = host; *p != 0; p += 1) {
    bool zero = *p == '0' && p[1] >= '0' && p[1] <= '9';
    if ((p == host || p[-1] == '.') && zero) return -1;
  }
  return port > 65535 || inet_pton(AF_INET, host, &at->sin_addr) != 1 ? -1 : 0;
}
u64 io_sys_end(IoWork *w, ssize_t n) {
  w->code = n < 0 ? (u32)errno : 0;
  return n < 0 ? 0 : (u64)n;
}
IoQue io_runs;
IoQue io_park;
IoQue io_jobs;
IoAct *io_acts;
void io_push(IoQue *q, IoAct *a) {
  a->next = NULL;
  *(q->head == NULL ? &q->head : &q->last->next) = a;
  q->last = a;
}
IoAct *io_pop(IoQue *q) {
  IoAct *a = q->head;
  q->head = a->next;
  return a;
}
IoAct *io_act_new(void) {
  IoAct *a = io_mem(calloc(1, sizeof(IoAct)));
  pthread_mutex_lock(&gc_lock);
  a->gnext = io_acts;
  if (io_acts) io_acts->gprev = a;
  io_acts = a;
  pthread_mutex_unlock(&gc_lock);
  return a;
}
void io_act_free(IoAct *a) {
  pthread_mutex_lock(&gc_lock);
  if (a->gprev) a->gprev->gnext = a->gnext;
  else io_acts = a->gnext;
  if (a->gnext) a->gnext->gprev = a->gprev;
  pthread_mutex_unlock(&gc_lock);
  free(a);
}
V io_start_fn(V *a) { return apply(apply(a[0], 0), a[1]); }
V io_emit_fn(V *a) { return C1(0, a[0]); }
void io_spawn(Term m) {
  IoAct *a = io_act_new();
  a->cont = mk_clo(io_start_fn, 2, 1, &m);
  a->item = mk_clo(io_emit_fn, 1, 0, NULL);
  io_push(&io_runs, a);
  io_live += 1;
}
Term io_wait_on(IoWork *w, int fd, short evts, u64 time, IoPack more) {
  IoAct *a = (IoAct *)w;
  a->work.word = (u32)fd;
  a->work.pack = more;
  a->work.time = time;
  a->evts = evts;
  io_push(&io_park, a);
  return IO_PARK;
}
u64 io_wait_time(IoWork *w) { return w->time; }
OUTLINE void io_out(FILE *h, const char *data, u64 len) {
  if (fwrite(data, 1, len, h) != len) err_fail("a short write on a standard stream");
}
OUTLINE void io_sync(void) {
  if (fflush(stdout) != 0) err_fail("a short write on a standard stream");
}
u64 io_utf8(char *buf, u64 c) {
  u64 k = c < 0x80 ? 1 : c < 0x800 ? 2 : c < 0x10000 ? 3 : 4;
  for (u64 i = k; i > 1; i -= 1) {
    buf[i - 1] = (char)(0x80 | (c & 0x3F));
    c >>= 6;
  }
  buf[0] = (char)(k == 1 ? c : (0xF00 >> k) | c);
  return k;
}
OUTLINE char *io_cstr(Env e, Term s, u64 *len) {
  (void)e;
  Term s0 = s;
  u64 cap = 64, n = 0;
  char *buf = io_mem(malloc(cap));
  // (Counted: the cons cells this holds the only reference to are freed
  // as they are read, while in cache; the rest, from the first shared
  // one, is dropped at the end.)
  int own = gc_hot.rc;
  while (!(s & 1) && TAG(s) == 1) {
    if (n + 5 > cap) {
      cap *= 2;
      buf = io_mem(realloc(buf, cap));
    }
    n += io_utf8(buf + n, FLD(s, 0));
    Term t = FLD(s, 1);
    if (own) {
      if ((uintptr_t)s - gc_hot.base < gc_hot.span && rc_unique(s)) rc_free_at(s, 0);
      else { own = 0; s0 = s; }
    }
    s = t;
  }
  buf[n] = 0;
  *len = n;
  if (own) bend_drop(s);
  else bend_drop(s0);
  return buf;
}
OUTLINE char *io_cbuf(Env e, Term s, u64 *len, u64 cons) {
  (void)e;
  Term s0 = s;
  (void)cons;
  u64 cap = 64, n = 0, bad = 0;
  char *buf = io_mem(malloc(cap + 1));
  while (!(s & 1) && TAG(s) == 1) {
    if (n + 1 > cap) {
      cap *= 2;
      buf = io_mem(realloc(buf, cap + 1));
    }
    bad |= FLD(s, 0) > 255;
    buf[n++] = (char)FLD(s, 0);
    s = FLD(s, 1);
  }
  buf[n] = 0;
  *len = n;
  bend_drop(s0);
  if (bad) {
    free(buf);
    return NULL;
  }
  return buf;
}
OUTLINE void io_errs(Env e, Term s) {
  u64 n = 0;
  char *text = io_cstr(e, s, &n);
  io_sync();
  io_out(stderr, text, n);
  io_out(stderr, "\n", 1);
  free(text);
}
#define io_nul(s, n) (strlen(s) != (n))
Term io_box(Env e, u64 cid, Term v) {
  (void)e;
  switch (CID_KIND(cid)) {
    case 1: return IMM(CID_TAG(cid));
    case 2: return v;
    default: return C1(CID_TAG(cid), v);
  }
}
Term io_node(Env e, u64 cid, Term a, Term b) {
  (void)e;
  return C2(CID_TAG(cid), a, b);
}
Term io_str(Env e, const char *p, u64 n) {
  (void)e;
  u32 *cps = io_mem(malloc((n + 1) * sizeof(u32)));
  u64 k = 0;
  u64 c = 0, need = 0, lo = 0x80, hi = 0xBF;
  for (u64 i = 0; i < n || need > 0; i += 1) {
    u64 b = i < n ? (uint8_t)p[i] : 0x100;
    if (need > 0 && (b < lo || b > hi)) {
      need = 0;
      c = 0xFFFD;
      i -= 1;
    } else if (need > 0) {
      lo = 0x80;
      hi = 0xBF;
      c = (c << 6) | (b & 0x3F);
      if (--need > 0) continue;
    } else if (b < 0x80) {
      c = b;
    } else if (b < 0xC2 || b > 0xF4) {
      c = 0xFFFD;
    } else {
      need = b < 0xE0 ? 1 : b < 0xF0 ? 2 : 3;
      lo = b == 0xE0 ? 0xA0 : b == 0xF0 ? 0x90 : 0x80;
      hi = b == 0xED ? 0x9F : b == 0xF4 ? 0x8F : 0xBF;
      c = b & (0x3F >> need);
      continue;
    }
    cps[k++] = (u32)c;
  }
  Term s = SNIL;
  while (k > 0) { k--; s = SCONS(cps[k], s); }
  free(cps);
  return s;
}
Term io_list(Env e, const char *p, u64 n) {
  (void)e;
  Term xs = IMM(0);
  for (u64 i = n; i > 0; i -= 1) xs = C2(1, (uint8_t)p[i - 1], xs);
  return xs;
}
#define io_tup(e, a, b) io_node(e, CID_TUPLE, a, b)
#define io_done(e, v) io_box(e, CID_DONE, v)
Term io_fail(Env e, u32 code, const char *text) {
  const char *s = text != NULL ? text : strerror((int)code);
  Term t = io_tup(e, code, io_str(e, s, strlen(s)));
  return io_box(e, CID_FAIL, t);
}
pthread_mutex_t io_gate = PTHREAD_MUTEX_INITIALIZER;
pthread_cond_t io_bell = PTHREAD_COND_INITIALIZER;
u32 io_busy;
u32 io_size;
int io_wake_fd[2];
void io_take(Env e) {
  IoAct *acts[64];
  ssize_t n;
  while ((n = read(io_wake_fd[0], acts, sizeof acts)) > 0) {
    for (u32 i = 0; i < (u32)n / sizeof(IoAct *); i += 1) {
      IoAct *a = acts[i];
      a->item = a->work.pack(e, &a->work);
      io_push(&io_runs, a);
      io_busy -= 1;
    }
  }
}
void *io_help(void *arg) {
  (void)arg;
  for (;;) {
    pthread_mutex_lock(&io_gate);
    while (io_jobs.head == NULL) pthread_cond_wait(&io_bell, &io_gate);
    IoAct *a = io_pop(&io_jobs);
    pthread_mutex_unlock(&io_gate);
    a->work.call(&a->work);
    while (write(io_wake_fd[1], &a, sizeof a) != sizeof a) {
    }
  }
  return NULL;
}
Term io_work(IoWork *w, IoCall call, IoPack pack) {
  w->call = call;
  w->pack = pack;
  io_busy += 1;
  if (io_busy > io_size && io_size < IO_HELP) {
    pthread_t tid;
    if (pthread_create(&tid, NULL, io_help, NULL)) err_fail("pthread_create");
    pthread_detach(tid);
    io_size += 1;
  }
  pthread_mutex_lock(&io_gate);
  io_push(&io_jobs, (IoAct *)w);
  pthread_cond_signal(&io_bell);
  pthread_mutex_unlock(&io_gate);
  return IO_PARK;
}
Term io_exec(Env e, IoWork *w) {
  IoAct *a = (IoAct *)w;
  Term fs[256];
  u64 tg = TAG(a->cont);
  u32 n = (u32)(tg >> 24);
  for (u32 i = 0; i < n; i++) fs[i] = FLD(a->cont, i);
  // (counted, the effect owns its arguments: the request node goes)
  if (gc_hot.rc) rc_let_go(a->cont, n + 1);
  a->cont = fs[n - 1];
  return io_eff_rows[CID_TAG(tg)].run(e, fs, w);
}
bool io_bit(u8 *set, int fd, bool put) {
  u8 *at = set + fd / 8;
  *at |= put << fd % 8;
  return *at >> fd % 8 & 1;
}
void io_wait(Env e) {
  int top = io_wake_fd[0];
  u64 soon = 0;
  for (IoAct *a = io_park.head; a != NULL; a = a->next) {
    if (a->work.time != 0 && (soon == 0 || a->work.time < soon)) soon = a->work.time;
    if (a->evts != 0 && (int)a->work.word > top) top = (int)a->work.word;
  }
  u64 len = (u64)top / 64 * 8 + 8;
  u8 *set[2] = {io_mem(calloc(2, len)), NULL};
  set[1] = set[0] + len;
  io_bit(set[0], io_wake_fd[0], true);
  for (IoAct *a = io_park.head; a != NULL; a = a->next) {
    if (a->evts != 0) io_bit(set[a->evts == POLLOUT], (int)a->work.word, true);
  }
  u64 tick = io_tick();
  u64 ms = soon > tick ? (soon - tick) / 1000000 + 1 : 0;
  struct timeval tv = {(time_t)(ms / 1000), (suseconds_t)(ms % 1000 * 1000)};
  io_sync();
  while (select(top + 1, (fd_set *)set[0], (fd_set *)set[1], NULL, soon == 0 ? NULL : &tv) < 0) {
    if (errno != EINTR) err_fail("the poller failed");
  }
  if (io_bit(set[0], io_wake_fd[0], false)) io_take(e);
  u64 now = io_tick();
  IoQue todo = io_park;
  io_park = (IoQue){0};
  while (todo.head != NULL) {
    IoAct *a = io_pop(&todo);
    bool due = (a->evts != 0 && io_bit(set[a->evts == POLLOUT], (int)a->work.word, false)) ||
      (a->work.time != 0 && a->work.time <= now);
    if (!due) {
      io_push(&io_park, a);
      continue;
    }
    Term x = a->work.pack(e, &a->work);
    if (x != IO_PARK) {
      a->item = x;
      io_push(&io_runs, a);
    }
  }
  free(set[0]);
}
int io_step(Env e, IoAct *a) {
  for (;;) {
    Term req = apply(a->cont, a->item);
    u64 tg = TAG(req);
    if (tg == 0) {
      bend_drop(req);
      io_act_free(a);
      io_live -= 1;
      return -1;
    }
    if (tg == 1) {
      io_errs(e, FLD(req, 1));
      return (int)(u32)FLD(req, 0);
    }
    if (CID_KIND(tg & 0xffffff) != 3 || io_eff_rows[CID_TAG(tg)].run == NULL) err_fail("an alien request");
    u32 need = io_eff_rows[CID_TAG(tg)].ask;
    a->cont = req;
    if (need != 0) {
      Term f0 = FLD(req, 0);
      u32 word = (u32)(need & IO_READ ? io_hand_v(f0) : f0);
      io_wait_on(&a->work, (int)word, need & IO_READ ? POLLIN : 0,
        need & IO_TIME ? io_tick() + (u64)word * 1000000ull : 0, io_exec);
      return -1;
    }
    Term x = io_exec(e, &a->work);
    if (x == IO_PARK) return -1;
    a->item = x;
  }
}
ChanRow *chan_rows;
u32 chan_len;
u32 chan_idle = ~0u;
#define chan_some(e, v) io_box(e, CID_SOME, v)
#define chan_bool(b) term_pak((b) ? CID_TRUE : CID_FALSE, 0)
Term chan_open(u32 room) {
  pthread_mutex_lock(&gc_lock);
  u32 i = chan_idle;
  if (i != ~0u) {
    chan_idle = chan_rows[i].next;
  } else {
    if (chan_len == 1u << 24) err_fail("more than 16777216 channels at once");
    if ((chan_len & (chan_len - 1)) == 0)
      chan_rows = io_mem(realloc(chan_rows, (chan_len == 0 ? 1 : 2 * chan_len) * sizeof(ChanRow)));
    i = chan_len;
    chan_len += 1;
    chan_rows[i].gen = 0;
  }
  ChanRow *row = &chan_rows[i];
  row->gen += 1;
  row->room = room;
  row->size = 0;
  row->head = 0;
  row->shut = 0;
  row->ring = room == 0 ? NULL : io_mem(calloc(room, sizeof(Term)));
  row->wait.head = NULL;
  row->wait.last = NULL;
  row->live = 1;
  pthread_mutex_unlock(&gc_lock);
  return io_hand(((u64)row->gen << 24) | i);
}
ChanRow *chan_at(Term t) {
  u64 v = io_hand_v(t);
  u32 i = (u32)v & 0xFFFFFF;
  ChanRow *row = i < chan_len ? &chan_rows[i] : NULL;
  return row != NULL && row->live && row->gen == (u32)(v >> 24) ? row : NULL;
}
Term chan_park(ChanRow *row, IoWork *w, Term item) {
  IoAct *a = (IoAct *)w;
  a->item = item;
  io_push(&row->wait, a);
  return IO_PARK;
}
Term chan_wake(ChanRow *row, Term x) {
  IoAct *a = io_pop(&row->wait);
  Term item = a->item;
  a->item = x;
  io_push(&io_runs, a);
  return item;
}
Term chan_take(ChanRow *row) {
  Term v = row->ring[row->head];
  row->head = (row->head + 1) % row->room;
  row->size -= 1;
  if (row->wait.head != NULL) {
    Term item = chan_wake(row, chan_bool(true));
    row->ring[(row->head + row->size) % row->room] = item;
    row->size += 1;
  }
  return v;
}
void chan_free(ChanRow *row) {
  pthread_mutex_lock(&gc_lock);
  free(row->ring);
  row->ring = NULL;
  row->live = 0;
  row->next = chan_idle;
  chan_idle = (u32)(row - chan_rows);
  pthread_mutex_unlock(&gc_lock);
}
void chan_shut(Env e, ChanRow *row) {
  row->shut = 1;
  while (row->wait.head != NULL) {
    bool rcv = row->wait.head->item == TERM_HOLE;
    Term x = rcv ? term_pak(CID_NONE, 0) : chan_bool(false);
    term_sink(e, chan_wake(row, x));
  }
  if (row->size == 0) chan_free(row);
}
void io_hook(void) {
  for (IoAct *a = io_acts; a != NULL; a = a->gnext) {
    gc_mark(a->cont);
    gc_mark(a->item);
  }
  for (u32 i = 0; i < chan_len; i++) {
    ChanRow *row = &chan_rows[i];
    if (row->live && row->ring) gc_scan(row->ring, row->ring + row->room);
  }
}
int io_loop(Term m) {
  Env e = {0};
  signal(SIGPIPE, SIG_IGN);
  if (pipe(io_wake_fd) | fcntl(io_wake_fd[0], F_SETFL, O_NONBLOCK)) err_fail("the event loop failed to open");
  io_spawn(m);
  for (u32 n = 0;; n += 1) {
    if (io_runs.head == NULL) {
      if (io_live == 0) return 0;
      if (io_park.head == NULL && io_busy == 0) {
        io_sync();
        fprintf(stderr, "bend: deadlock: every computation waits on a channel\n");
        return 1;
      }
      io_wait(e);
      continue;
    }
    if ((n & 63) == 0 && io_busy != 0) io_take(e);
    int code = io_step(e, io_pop(&io_runs));
    if (code >= 0) return code;
  }
}
void pr_s(const char *s) { fputs(s, stdout); }
void pr_u32(V v) { printf("%u", U(v)); }
void pr_nat(V v) {
  char *s = nat_digits(v);
  fputs(s, stdout);
  putchar('n');
  free(s);
}
void pr_f32(V v) {
  char buf[64];
  int n = f32_text(FV(v), buf, sizeof buf);
  char *ep = memchr(buf, 'e', (size_t)n);
  int m = ep == NULL ? n : (int)(ep - buf);
  if (strpbrk(buf, ".ni") == NULL) printf("%.*s.0%s", m, buf, buf + m);
  else fputs(buf, stdout);
}
void pr_cp(uint32_t cp, char quote) {
  int k = cp == 10 ? 'n' : cp == 9 ? 't' : cp == 13 ? 'r' : cp == 0 ? '0'
    : cp == 92 || cp == (uint32_t)quote ? (int)cp : 0;
  if (k != 0) {
    printf("\\%c", k);
  } else if (cp < 32 || cp == 127 || (cp >= 0xD800 && cp <= 0xDFFF) || cp > 0x10FFFF) {
    printf("\\u{%x}", cp);
  } else {
    char b[4];
    fwrite(b, 1, io_utf8(b, cp), stdout);
  }
}
void pr_char(V v) { putchar('\''); pr_cp(U(v), '\''); putchar('\''); }
void pr_str(V v) {
  putchar('"');
  while (TAG(v) == 1) { pr_cp(U(FLD(v, 0)), '"'); v = FLD(v, 1); }
  putchar('"');
}
V (*bend_main_fn)(void);
void (*bend_print_fn)(V);
int bend_exit;
void *bend_thread(void *arg) {
  thr_register((uintptr_t)__builtin_frame_address(0) + 16);
  if (arg) {
    bend_print_fn(bend_main_fn());
    putchar('\n');
  } else {
    bend_exit = io_loop(bend_main_fn());
  }
  fflush(stdout);
  return NULL;
}
int bend_gpu = 1;
long bend_gpu_mb = 0;
const char *CLI_HELP =
  "usage: %s [options] [arguments]\n"
  "  --threads N       worker threads, 1 to 128 (default: the CPU count)\n"
  "  --gpu on|off|4GB  where ! calls run: the GPU (the default) or the CPU threads\n"
  "  --bend-help       show this text\n"
  "  --                the rest are the program's arguments (IO.args)\n";
void cli_fail(const char *msg) {
  fprintf(stderr, "bend: %s\n", msg);
  exit(1);
}
int bend_start(int argc, char **argv, V (*m)(void), int value) {
  bend_main_fn = m;
  io_argv = calloc((size_t)argc + 1, sizeof(char *));
  io_argv[io_argc++] = argv[0];  // IO.args starts with the program as invoked
  long thr = 0;
  for (int i = 1; i < argc; i++) {
    const char *a = argv[i];
    const char *v = i + 1 < argc ? argv[i + 1] : NULL;
    if (strcmp(a, "--") == 0) {
      while (i + 1 < argc) io_argv[io_argc++] = argv[++i];
    } else if (strcmp(a, "--bend-help") == 0) {
      printf(CLI_HELP, argv[0]);
      return 0;
    } else if (strcmp(a, "--threads") == 0) {
      char *end = NULL;
      thr = v != NULL ? strtol(v, &end, 10) : 0;
      if (thr < 1 || thr > 128 || end == NULL || *end != '\0') cli_fail("expected a thread count of 1 or more after --threads");
      i++;
    } else if (strcmp(a, "--gpu") == 0) {
      if (v == NULL) cli_fail("expected on, off or a size like 4GB after --gpu");
      bend_gpu = strcmp(v, "off") != 0;
      {
        char *end = NULL;
        long n = strtol(v, &end, 10);
        if (end != v && n > 0) {
          if (strcmp(end, "GB") == 0 || strcmp(end, "G") == 0 || strcmp(end, "gb") == 0) bend_gpu_mb = n << 10;
          else if (strcmp(end, "MB") == 0 || strcmp(end, "M") == 0 || strcmp(end, "mb") == 0) bend_gpu_mb = n;
        }
      }
      i++;
    } else {
      io_argv[io_argc++] = argv[i];
    }
  }
  par_nthreads = thr > 0 ? (int)thr : cpu_count();
  // Fork 2^6 tasks a thread deep, then run subtrees in order.
  if (par_nthreads > 1) {
    int f = 0;
    while ((1 << f) < par_nthreads) f++;
    const char *fd = getenv("BEND_FORK_DEPTH");
    par_front = fd && *fd ? atoi(fd) : f + 6;
  }
  gc_init();
  struct sigaction sa;
  memset(&sa, 0, sizeof sa);
  sa.sa_handler = gc_handler;
  sa.sa_flags = SA_RESTART;
  sigemptyset(&sa.sa_mask);
  sigaction(GC_SIG, &sa, NULL);
  fault_init();
  gc_hook(par_hook);
  gc_hook(io_hook);
  pthread_attr_t attr;
  pthread_attr_init(&attr);
  thr_stack(&attr);
  pthread_t th;
  if (pthread_create(&th, &attr, bend_thread, value ? (void *)1 : NULL) != 0) {
    perror("pthread_create");
    return 1;
  }
  pthread_join(th, NULL);
  fflush(stdout);
  if (gc_hot.rc && getenv("BEND_RC_STATS")) fprintf(stderr, "bend rc: %zu objects live at exit\n", rc_live());
  return bend_exit;
}
int bend_run_value(int argc, char **argv, V (*m)(void), void (*p)(V)) {
  bend_print_fn = p;
  return bend_start(argc, argv, m, 1);
}
int bend_run(int argc, char **argv, V (*m)(void)) { return bend_start(argc, argv, m, 0); }
#endif
