// Generated by tools/rtsplit.py from rt/bendrt.h: do not edit.
// The runtime's declarations, for a program linked with build/bendrt.o.
#define BEND_RT_SPLIT_HEADER 1
// bendrt.h: runtime for C code generated by bendc (the Bend compiler written in Bend).
//
// Values are 64-bit words:
//  - numbers (U32, Char, F32 bits) are stored raw;
//  - a Nat (up to 2^48 - 1, as the official runtime's) is stored raw;
//  - nullary constructors are IMM(tag) = (tag << 3) | 1;
//  - other constructors are pointers to heap nodes {tag, fields...};
//  - closures are pointers to {fn, arity, nargs, args...}.
// A type with one constructor of one field is represented by that field.
//
// Memory is managed by a conservative, non-moving mark-sweep collector. The
// threads that run Bend code (the main thread and the fork-join workers) are
// stopped with a signal while it runs. Parallel lets fork onto a
// work-stealing pool. Effects follow the official Bend runtime's effect ABI
// (Term, Env, IoWork, io_eff, CID_*), so effect sources written for the
// official compiler (Base's own effs/*.c included) compile unchanged.

#ifndef BENDRT_H
#define BENDRT_H

#ifdef __linux__
#define _GNU_SOURCE
#endif
#define _DARWIN_UNLIMITED_SELECT  // select past FD_SETSIZE (io_wait)
#include <stdint.h>
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
#include <pthread.h>
#include <unistd.h>
#include <fcntl.h>
#include <time.h>
#include <errno.h>
#include <setjmp.h>
#include <signal.h>
#include <sched.h>
#include <poll.h>
#include <stdatomic.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/time.h>
#include <sys/select.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <arpa/inet.h>

typedef uint64_t V;
typedef V (*Fn)(V *);
typedef uint64_t u64;
typedef uint32_t u32;
typedef uint16_t u16;
typedef uint8_t u8;
typedef int64_t i64;
typedef int32_t i32;
typedef uint32_t U32;
typedef uint64_t Term;

#define IMM(t) ((((V)(t)) << 3) | 1)
// A word leaf (kind 7, G.li in bendc): a constructor whose one field is a
// word, as that word above its tag. It is odd (no IMM: bit 1 is set) and
// above every heap address, so no test takes it for an object.
#define LI_HI 0xFFFF000000000000ull
#define LI(t, x) (LI_HI | ((V)(uint32_t)(x) << 16) | ((V)(t) << 3) | 3)
#define IS_LI(v, t) (((v) & 0xFFFF00000000FFFFull) == (LI_HI | ((V)(t) << 3) | 3))
#define LI_V(v) ((V)(uint32_t)((v) >> 16))
#define LI_F(v, i) LI_V(v)
// A node's tag word holds its tag (below 2^20) and two flags (see "Freeing
// on match"): shared, and its fields marked shared too.
#define BEND_SH ((V)1 << 20)
#define BEND_DEEP ((V)1 << 21)
#define BEND_SH_BITS (BEND_SH | BEND_DEEP)
// What a D_ function's node holds where its hole is, until it is filled: a
// word no pointer can be, that the collector looks for (gc_rem).
#define BEND_HOLE IMM(0x7ffff)
// Keeps the compiler from reordering the stores around it (a thread stopped
// by a collection is seen in its program order).
#define BEND_BARRIER() __asm__ volatile("" ::: "memory")
#define FLD(v, i) (((V *)(v))[(i) + 1])
#define BOOL(b) ((b) ? IMM(1) : IMM(0))
// A word's structural view built back: WCon{head, tail} (see Gen.pat.word).
#define word_con(b, r) ((V)(U32)(((U32)(r) << 1) | ((b) == IMM(1))))
#define UNIT IMM(0)
// A call that must compile to a jump (a D_ function's tail call, which
// would otherwise grow the stack by one frame per list element).
#if defined(__has_attribute)
#if __has_attribute(musttail)
#define BEND_MUSTTAIL __attribute__((musttail))
#endif
#endif
#ifndef BEND_MUSTTAIL
#define BEND_MUSTTAIL
#endif
#define LIKELY(x) __builtin_expect(!!(x), 1)
#define UNLIKELY(x) __builtin_expect(!!(x), 0)
// A def's U_ function (a flat result, stored through o) is inlined into its
// callers, where o is then registers. (GCC refuses always_inline on a
// recursive function; tcc has no inlining.)
#if defined(__clang__)
#define BEND_UINL static inline __attribute__((always_inline))
#elif defined(__TINYC__)
#define BEND_UINL static
#else
#define BEND_UINL static inline
#endif

#ifdef BEND_DEBUG_FREE
#include <execinfo.h>
// The call stack of each free, by its number (a ring of the last 2^20).
extern void *bend_debug_stk[1 << 20][12];
void bend_debug_record(uint64_t n);
void bend_debug_show(uint64_t n);
static inline V TAG(V v) {
  if (v & 1) return v >> 3;
  V t = ((V *)v)[0];
  if ((t >> 48) == 0xDEAD) {
    fprintf(stderr, "bend: a node freed at line %u (free number %llu, thread %02x) is used by thread %02x\n",
      (unsigned)(t & 0xfffff), (unsigned long long)((t >> 20) & 0xfffff), (unsigned)((t >> 40) & 0xff),
      (unsigned)(((uintptr_t)pthread_self() >> 12) & 0xff));
    bend_debug_show((t >> 20) & 0xfffff);
    abort();
  }
  return (V)(uint32_t)t & ~BEND_SH_BITS;
}
#define IS_N(v, t) (!((v) & 1) && TAG(v) == (t))
#else
// (The low half of a node's first word: its reference count is above.)
static inline V TAG(V v) { return (v & 1) ? (v >> 3) : (V)(uint32_t)((V *)v)[0] & ~BEND_SH_BITS; }
// A match's test for a constructor with fields: an immediate (a nullary
// constructor) never is one, and a node's tag word is loaded without a
// select, so a match's cases share one load.
static inline int IS_N(V v, V t) { return !(v & 1) && ((V)(uint32_t)((V *)v)[0] & ~BEND_SH_BITS) == t; }
#endif

__attribute__((noreturn)) void bend_fail(const char *msg);

// Garbage collector
// =================
//
// The heap is one reserved region cut into 64 KB blocks. A small block holds
// slots of one size class; a large object takes whole blocks. Each block
// starts with a header holding an allocation and a mark bitmap. Every word
// of a live object, of a thread's stack and of the registered roots is read
// as a possible pointer; pointers into the middle of an object keep it too.
// A thread allocates from a private free list; the block behind that list
// is not swept until the thread moves on to another one.

#define GC_BLK_SHIFT 16
#define GC_BLK ((uintptr_t)1 << GC_BLK_SHIFT)
#define GC_MAXBLK ((uintptr_t)1 << 22)
#define GC_HDR 64
#define GC_SMALL 2052
#define GC_NCLS 43
#define GC_MAXTHR 256
#define GC_SIG SIGUSR2

typedef struct GcBlk {
  uint32_t words;    // slot size (small) or object size (large), in words
  uint32_t nobj;     // slots in the block (1 for a large object)
  uint32_t nblk;     // blocks spanned
  uint8_t atomic;    // holds no pointers: never scanned
  uint8_t large;
  uint8_t owned;     // in a thread's cache (or being made): not swept, not claimed
  uint8_t cls;
  struct GcBlk *next;
} GcBlk;

// What matches and the collector read most, by block index, in dense tables
// (a block's own header is a page away from most of its objects): a block's
// allocation and mark bits (gc_abits, gc_mbits: 64 words a block), and:
typedef struct GcMeta {
  uint32_t recip;    // 2^32 / slot bytes, rounded up: a slot's index by multiplying
  uint8_t large, cls;
  uint16_t words;    // slot size in words (small blocks; 0 for a large object)
} GcMeta;
_Static_assert(sizeof(GcBlk) <= GC_HDR, "GC_HDR holds a block header");

// A thread's allocation cache for one size class: a fresh block is handed out
// by bumping; a partly free one by the free bits of its bitmap, a word at a
// time (the slots are not touched until they are handed out).
// The first seven fields are read and written by native code too (its
// allocation fast path; see rt/native.c): their offsets and the struct's
// size are fixed there.
typedef struct GcCache {
  V *bump; V *end;
  uint64_t *abits;  // GC_ALLOC(blk)
  uint32_t idx;     // the slot bump points at
  uint32_t j;
  uint64_t bits;    // free slots of word j
  V *objs;
  uint32_t nj;
  uint8_t reuse;    // the block came from the reuse queue: its slots are not new memory
  GcBlk *blk;
} GcCache;

struct PDeque;

// Classes of up to 16 words (nodes) reuse the slots matches free.
#define GC_RQCLS 15
#define ARR_SPARES 8

typedef struct Thr {
  GcCache cache[2][GC_NCLS];
  uint32_t rcur[GC_NCLS];   // where the next search for a reuse block starts
  V *rcs; size_t rcn, rccap; // reference counting: the objects rc_free_obj has yet to free
  uintptr_t top;
  volatile uintptr_t sp;
  pthread_t id;
  volatile int live;
  struct PDeque *dq;
  uint32_t rng;
  // Claiming a reuse block (gc_refill): a stop signal that comes meanwhile
  // is deferred (deferred is set) until the claim is over.
  volatile sig_atomic_t claiming, deferred;
  // Arrays the program is done with (arr_dead), for the next Array.new of
  // their class; a collection forgets them (arr_hook).
  V spare[ARR_SPARES];
  uint32_t nspare;
} Thr;

void gc_park(Thr *t);
void gc_join(void);

typedef struct { V *p; size_t n; } GcRange;
typedef struct { uint32_t at, len; } GcRun;

extern const uint16_t gc_cls_w[GC_NCLS];
extern uint8_t gc_cls_of[GC_SMALL + 1];

extern char *gc_base;
extern uint64_t *gc_abits;
extern uint64_t *gc_mbits;
extern GcMeta *gc_meta;
extern uintptr_t gc_top;
extern uint8_t *gc_kind;
extern uint32_t *gc_back;
extern GcRun *gc_runs;
extern size_t gc_nruns;
extern pthread_mutex_t gc_lock;
extern GcBlk *gc_partial[2][GC_NCLS];
extern _Atomic size_t gc_since;
extern size_t gc_limit;
extern size_t gc_limit_min;
// (Read at start: libc's number parsing takes a lock a stopped thread may hold.)
extern double gc_minor_k;
extern size_t gc_slack;
extern size_t gc_live_bytes;
extern size_t gc_major_live;
extern int gc_minor;
extern int gc_rooting;
extern int gc_all_major;
extern size_t gc_count;
extern size_t gc_epoch;
extern int gc_stats;
extern Thr *gc_thrs[GC_MAXTHR];
extern int gc_nthr;
// Nodes with an open hole (BEND_HOLE) that a thread's stack or registers
// pointed to at the last collection, which the next minor collection
// rescans: the only objects written after they are made are the nodes D_
// functions build with a hole, and a node whose hole was open at a
// collection was reachable from a root then (by dst, or, just made, by a
// register of a thread the collection stopped).
extern V *gc_rem;
extern size_t gc_nrem;
extern size_t gc_caprem;
extern V *gc_rem_prev;
extern size_t gc_nprev;
extern size_t gc_capprev;
// Per class, a bit per block: matches freed slots in it (GC_CANDW words a
// class).
#define GC_CANDW (GC_MAXBLK / 64)
extern uint64_t *gc_cand;
// More than one thread runs Bend code (frees must then be atomic).
extern int gc_mt;
// Set by a program compiled with BEND_RC=1 before it starts (see "Reference
// counting").
extern int bend_rc_req;
// What bend_take and bend_share read, together (one address to load).
typedef struct GcHot {
  uintptr_t base, span;  // the heap: gc_base, and gc_top in bytes
  uint64_t *abits, *cand;
  int mt;
  int rc;  // reference counting (a program compiled with BEND_RC=1): no collections
  int rcmt; // rc and mt: a slot's allocation bit is set atomically
} GcHot;
extern GcHot gc_hot;
extern GcRange *gc_roots;
extern size_t gc_nroots;
extern size_t gc_caproots;
extern void (*gc_hooks[16])(void);
extern int gc_nhooks;
extern _Atomic int gc_stopping;
extern _Atomic int gc_acks;
extern _Atomic int gc_inside;
#ifdef __TINYC__
// tcc has no thread-local storage on every target (none in Mach-O): a
// pthread key holds each thread's slots, and the names stay lvalues.
typedef struct { void *self; int par_depth; } TlsSlots;
extern pthread_key_t tls_key;
extern pthread_once_t tls_once;
void tls_init(void);
TlsSlots *tls_get(void);
#define thr_self (*(Thr **)&tls_get()->self)
#define par_depth (tls_get()->par_depth)
#define thr_set(t) (thr_self = (t))
#elif defined(__APPLE__) && defined(__aarch64__)
// A Mach-O thread-local is reached through a call (every allocation reads
// thr_self); a pthread key's slot is one load off the thread's TSD base,
// which is what pthread_getspecific reads.
// (The key is made before main: a thread not registered reads NULL.)
extern pthread_key_t thr_key;
__attribute__((constructor)) void thr_key_init(void);
static inline Thr *thr_get(void) {
  uintptr_t tsd;
  __asm__("mrs %0, tpidrro_el0" : "=r"(tsd));
  return ((Thr **)(tsd & ~(uintptr_t)7))[thr_key];
}
#define thr_self (thr_get())
#define thr_set(t) pthread_setspecific(thr_key, (t))
#else
extern __thread Thr *thr_self;
#define thr_set(t) (thr_self = (t))
#endif

typedef struct { V *p; size_t n; } GcItem;
extern GcItem *gc_stk;
// Per block: an Array in it got a pointer stored since the last collection
// (see arr_put), so a minor one rescans the block's old objects.
extern uint8_t *gc_dirty;
extern size_t gc_sp;
extern size_t gc_cap;

void *gc_reserve(size_t bytes, void *hint);

void gc_init(void);

static inline GcBlk *gc_blk(uintptr_t i) { return (GcBlk *)(gc_base + (i << GC_BLK_SHIFT)); }
static inline uintptr_t gc_bi(const GcBlk *b) { return ((uintptr_t)b - (uintptr_t)gc_base) >> GC_BLK_SHIFT; }
#define GC_ALLOC(b) (gc_abits + gc_bi(b) * 64)
#define GC_MARK(b) (gc_mbits + gc_bi(b) * 64)
#define GC_META(b) (&gc_meta[gc_bi(b)])
static inline V *gc_objs(GcBlk *b) { return (V *)((char *)b + GC_HDR); }

// Takes n contiguous free blocks (gc_lock held).
uintptr_t gc_take_blocks(size_t n);

void gc_collect_locked(void);

GcBlk *gc_new_small(int atomic, unsigned c);

// Sets a slot's allocation bit. Under reference counting other threads free
// slots of the block as it is handed out, so with threads running the bit
// is set in one instruction (a plain one could lose their frees).
static inline void gc_setbit(uint64_t *w, uint64_t bit) {
  if (UNLIKELY(gc_hot.rcmt)) __atomic_fetch_or(w, bit, __ATOMIC_RELAXED);
  else *w |= bit;
}

// The next word of free bits in the cache's block; 0 when none is left.
// The free slots' marks go here too: a slot handed out is young (bend_take_at
// leaves a freed slot's mark when other threads run), or a minor collection
// would take the new object for an old one and not trace what it holds.
static inline uint64_t gc_next_bits(GcCache *k) {
  GcBlk *b = k->blk;
  while (++k->j < k->nj) {
    uint64_t f = ~__atomic_load_n(&GC_ALLOC(b)[k->j], __ATOMIC_RELAXED);
    if (k->j == (b->nobj >> 6)) f &= (1ull << (b->nobj & 63)) - 1;
    if (f) {
      uint64_t *m = &GC_MARK(b)[k->j];
      if (__atomic_load_n(m, __ATOMIC_RELAXED) & f) __atomic_fetch_and(m, ~f, __ATOMIC_RELAXED);
      return f;
    }
  }
  return 0;
}

// Slow path: the rest of the block's free words, or another block.
__attribute__((noinline)) V *gc_refill(GcCache *k, int atomic, unsigned c);

__attribute__((noinline)) V *gc_alloc_large(size_t w, int atomic);

// A slot is not cleared when freed: the words of a class slot past the
// object's own are cleared here, so stale words never look like pointers.
// hole: a D_ node (a constant): its tag word holds BEND_HOLE before the slot
// is allocated, so no collection sees it without (see gc_rem).
static inline V *gc_alloc_x(size_t w, int atomic, int hole) {
  if (UNLIKELY(w > GC_SMALL)) return gc_alloc_large(w, atomic);
  unsigned c = w >= 2 && w <= 16 ? (unsigned)w - 2 : gc_cls_of[w];
  GcCache *k = &thr_self->cache[atomic][c];
  V *p;
  if (k->bump < k->end) {
    p = k->bump;
    k->bump += gc_cls_w[c];
    uint32_t i = k->idx++;
    if (hole) { p[0] = BEND_HOLE; BEND_BARRIER(); }
    gc_setbit(&k->abits[i >> 6], 1ull << (i & 63));
  } else if (k->bits) {
    int t = __builtin_ctzll(k->bits);
    k->bits &= k->bits - 1;
    uint32_t i = k->j * 64 + (uint32_t)t;
    p = k->objs + (size_t)i * gc_cls_w[c];
    if (hole) { p[0] = BEND_HOLE; BEND_BARRIER(); }
    gc_setbit(&k->abits[i >> 6], 1ull << (i & 63));
  } else {
    p = gc_refill(k, atomic, c);
  }
  if (!hole) p[0] = 0;
  p[1] = 0;
  if (!(w >= 2 && w <= 16))
    for (size_t j = w; j < gc_cls_w[c]; j++) p[j] = 0;
  return p;
}

static inline V *gc_alloc(size_t w, int atomic) { return gc_alloc_x(w, atomic, 0); }
static inline V *halloc(size_t words) { return gc_alloc_x(words, 0, 0); }
static inline V *halloc_hole(size_t words) { return gc_alloc_x(words, 0, 1); }

// Freeing on match
// ----------------
//
// Bend values are affine: a value has one owner unless it went through a
// variable used more than once. Generated code marks such values shared
// (bend_share) where the variable is bound, and a match that opens a node
// hands it to bend_take: a shared node stays (and the fields it hands out
// become shared too), any other is dead once its fields are read, so its slot
// goes on the thread's free list, and the next allocation of its size takes
// it. A reused slot's mark is cleared: it holds a young object for minor
// collections. The free lists are roots, so a collection keeps them.

// The small block and slot index of a heap object, or 0 when v is not one.
static inline GcBlk *gc_slot(V v, uint32_t *idx) {
  uintptr_t off = (uintptr_t)v - (uintptr_t)gc_base;
  if (UNLIKELY(off >= (gc_top << GC_BLK_SHIFT))) return NULL;
  uintptr_t bi = off >> GC_BLK_SHIFT;
  if (UNLIKELY(gc_kind[bi] != 1)) return NULL;
  GcBlk *b = gc_blk(bi);
  *idx = (uint32_t)(((uint64_t)((uintptr_t)v - (uintptr_t)gc_objs(b)) * GC_META(b)->recip) >> 32);
  return b;
}

// Marks a value shared: a node by its tag word, a closure by its captured
// values (calling it twice hands them out twice). Anything else (a number
// that falls in the heap, say) is left alone: the value must be the start of
// an allocated object.
__attribute__((noinline)) void bend_share_slow(V v);

// Numbers, characters and nullary constructors are below 2^32, and the heap
// above (gc_init); a node already shared says so in its tag word (reading any
// heap address is safe; writing needs the checks above).
static inline void bend_share(V v) {
  // A word first, on its own branch (the heap bounds are then not loaded).
  if (LIKELY(v < ((V)1 << 32))) return;
  if ((uintptr_t)v - gc_hot.base >= gc_hot.span) return;
  V w0 = __atomic_load_n((V *)v, __ATOMIC_RELAXED);
  if ((w0 & BEND_SH) && w0 < ((V)1 << 22)) return;
  bend_share_slow(v);
}

// A shared node's fields, marked shared once: after them, the node's
// BEND_DEEP (a thread that sees it sees them marked).
__attribute__((noinline)) void bend_deep(V v, unsigned w);

// A match opened node v, of w words, after reading its fields: 1 when it is
// shared (its fields are then shared too), else 0 and its slot is freed, and
// its block a reuse candidate for its class (gc_refill takes it when a 5th of
// it is free). Nodes of up to 16 words are in small blocks whose slots are
// exactly their size; larger ones are never freed.
static inline void bend_free_slot(V v, unsigned w, unsigned line);
static inline int bend_take_at(V v, unsigned w, unsigned line) {
  const GcHot *h = &gc_hot;
  V w0 = h->mt ? __atomic_load_n((V *)v, __ATOMIC_ACQUIRE) : __atomic_load_n((V *)v, __ATOMIC_RELAXED);
  if (w0 & BEND_SH) {
    if (!(w0 & BEND_DEEP)) bend_deep(v, w);
    return 1;
  }
  if (UNLIKELY((uintptr_t)v - h->base >= h->span || w > 16)) { bend_deep(v, w); return 1; }
  bend_free_slot(v, w, line);
  return 0;
}

// Frees the slot of an unshared node v of w (2 to 16) words in the heap.
static inline void bend_free_slot(V v, unsigned w, unsigned line) {
  const GcHot *h = &gc_hot;
  uintptr_t off = (uintptr_t)v - h->base;
  uintptr_t bi = off >> GC_BLK_SHIFT;
  uint32_t i = (uint32_t)(((off & (GC_BLK - 1)) - GC_HDR) / (w * sizeof(V)));
  uint64_t bit = 1ull << (i & 63);
  uint64_t *aw = &h->abits[bi * 64 + (i >> 6)];
#ifdef BEND_DEBUG_FREE
  // Debugging: the node is poisoned with the line that freed it and the
  // free's number, and kept. BEND_DEBUG_FREE_AT=n aborts at free number n.
  {
    static uint64_t nfreed;
    static long stop = -2;
    if (stop == -2) stop = getenv("BEND_DEBUG_FREE_AT") ? atol(getenv("BEND_DEBUG_FREE_AT")) : -1;
    nfreed++;
    if ((long)nfreed == stop) abort();
    V who = (V)(((uintptr_t)pthread_self() >> 12) & 0xff);
    bend_debug_record(nfreed & 0xfffff);
    for (unsigned j = 0; j < w; j++) ((V *)v)[j] = ((V)0xDEAD << 48) | (who << 40) | ((nfreed & 0xfffff) << 20) | line;
    (void)bit; (void)aw;
  }
  return;
#endif
  (void)line;
  uint64_t *cw = &h->cand[(size_t)(w - 2) * GC_CANDW + (bi >> 6)];
  // A freed slot is young when it is handed out again. On one thread its
  // mark goes here; when other threads run, the thread that hands the slot
  // out clears it (gc_next_bits): cleared here, after the allocation bit, it
  // could be the mark of the object another thread made in the slot since
  // and a collection marked old, which the next minor collection would then
  // not trace from (tests/par_reuse.bend).
  uint64_t *mw = &gc_mbits[bi * 64 + (i >> 6)];
  if (UNLIKELY(h->mt)) {
    __atomic_fetch_and(aw, ~bit, __ATOMIC_RELAXED);
    // (a sample of the frees keeps the shared candidate words cool)
    if ((i & 15) == 0 && !(*cw & (1ull << (bi & 63))))
      __atomic_fetch_or(cw, 1ull << (bi & 63), __ATOMIC_RELAXED);
  } else {
    *aw &= ~bit;
    *mw &= ~bit;
    *cw |= 1ull << (bi & 63);
  }
}

// With BEND_DEBUG_FREE, a freed node records the generated C line that
// freed it, and TAG reports a read of one.
#ifdef BEND_DEBUG_FREE
#define bend_take(v, w) bend_take_at(v, w, __LINE__)
#else
#define bend_take(v, w) bend_take_at(v, w, 0)
#endif

static inline void rc_take(V v, unsigned w);
// A flat result (a def's U_ function): node t's k fields go out through o,
// then t is taken when matches free or counts (a shared node shares its
// fields, or gives each a reference).
static inline void bend_open(V t, V *o, unsigned k, int take) {
  for (unsigned i = 0; i < k; i++) o[i] = FLD(t, i);
  if (gc_hot.rc) rc_take(t, k + 1);
  else if (take) bend_take(t, k + 1);
}

// Reference counting
// ------------------
//
// A program compiled with BEND_RC=1 counts references instead (Perceus:
// Reinking et al., PLDI 2021), and the collector never runs. An object's
// count of references past its first sits in bits 48 to 61 of its first word
// (above a node's tag, a closure's function or an array's header), so a new
// object, whose first word is written whole, has one reference. Bit 62 makes
// an object immortal (a cached string literal, or a count that reached 2^14):
// its count is never changed again. Generated code adds references where a
// variable is used more than once (rc_dupn), drops them on the paths that do
// not use it (rc_drop), and a match that opens a node takes it (rc_take): a
// node with one reference is freed there, its fields moving to the pattern's
// variables; a shared one gives each field a reference and loses one. Bit
// 63 marks an object other threads may reach (RC_TS), and only a marked
// object's count changes atomically. A fork's closure is marked before
// another thread can take its task, as is a value stored into a marked
// array, and so is every object they reach (rc_publish): an object may be
// held by the forking thread too, even below a node with one reference
// (whose taker gets its fields as they are). So everything a marked object
// reaches is marked, and marking stops at a marked object. A new object,
// its first word written whole, is unmarked. Values are acyclic, so
// dropping the last reference to each
// object frees everything, and a Nat equal to the address of a live object
// is the one word taken for a reference that is not one.
#define RC_ONE ((V)1 << 48)
#define RC_STICKY ((V)1 << 62)
#define RC_TS ((V)1 << 63)
#define RC_ADDR (RC_ONE - 1)
// The count and the immortal bit: 0 for an object with one reference.
#define RC_REFS(w0) (((w0) >> 48) & 0x7fff)

// off (from the heap's base) is the start of an allocated object.
static inline int rc_valid(uintptr_t off) {
  uintptr_t bi = off >> GC_BLK_SHIFT;
  uint64_t o = off & (GC_BLK - 1);
  uint32_t i = 0;
  uint8_t kd = gc_kind[bi];
  if (LIKELY(kd == 1)) {
    const GcMeta *m = &gc_meta[bi];
    if (o < GC_HDR) return 0;
    i = (uint32_t)(((o - GC_HDR) * m->recip) >> 32);
    if (o - GC_HDR != (uint64_t)i * m->words * sizeof(V)) return 0;
  } else if (kd != 2 || o != GC_HDR) {
    return 0;
  }
  return (int)((gc_abits[bi * 64 + (i >> 6)] >> (i & 63)) & 1);
}

// v is a reference: the start of an object in the heap (numbers,
// characters and nullary constructors are below 2^32, the heap above).
static inline int rc_obj(V v) {
  uintptr_t off = (uintptr_t)v - gc_hot.base;
  if (v < ((V)1 << 32) || (v & 7) || off >= gc_hot.span) return 0;
  return rc_valid(off);
}

static inline void rc_dup_obj(V v, V n) {
  V *p = (V *)v;
  V w0 = __atomic_load_n(p, __ATOMIC_RELAXED);
  if (w0 & RC_STICKY) return;
  if (UNLIKELY(n >= 0x2000)) { __atomic_fetch_or(p, RC_STICKY, __ATOMIC_RELAXED); return; }
  if (w0 & RC_TS) __atomic_fetch_add(p, n * RC_ONE, __ATOMIC_RELAXED);
  else *p = w0 + n * RC_ONE;
}

// n more references to v.
static inline void rc_dupn(V v, V n) { if (rc_obj(v)) rc_dup_obj(v, n); }

void rc_publish(V v);
// A reference more to x, read out of an object that is marked when ts is
// not 0 (see RC_TS): x is marked first, with its reach. (A marked object's
// reach is marked already; the mark here is for a holder that is not one.)
static inline void rc_dup_in(V x, V ts) {
  if (!rc_obj(x)) return;
  if (ts && !(__atomic_load_n((V *)x, __ATOMIC_RELAXED) & (RC_TS | RC_STICKY))) rc_publish(x);
  rc_dup_obj(x, 1);
}
// ALeaf{x} = a (counted): x gets a reference.
static inline void rc_dup_leaf(V a) { rc_dup_in(((V *)a)[1], ((V *)a)[0] & RC_TS); }
// A reference more to a borrowed value (see Bor in bendc.bend): its own
// mark says whether other threads reach it, as everything a marked object
// reaches is marked (rc_publish).
#define rc_bmark() 0
// A temporary node (see RC.tmp in bendc.bend): a constructor built where
// its callee only reads it, on the stack (RC_TMP), or for a loop's next
// argument in the one of its two buffers b not the current one (RC_TB).
// It is not in the heap, so references to it are not counted.
#define RC_TMP(...) ((V)(V[]){__VA_ARGS__})
#define RC_TB(b, i, ...) ((i) ^= 1, (V)memcpy((b)[i], (V[]){__VA_ARGS__}, sizeof((V[]){__VA_ARGS__})))
#define rc_bdupFLD(p, i) rc_dup_in(FLD(p, i), rc_bmark())
#define rc_bdup(x) rc_dup_in((x), rc_bmark())
static inline void rc_dup(V v) { rc_dupn(v, 1); }
static inline V rc_dupv(V v) { rc_dup(v); return v; }

// Gives up a reference to object v: 1 when it was the last (v must then be
// freed).
static inline int rc_release(V v) {
  V *p = (V *)v;
  V w0 = __atomic_load_n(p, __ATOMIC_RELAXED);
  if (RC_REFS(w0) == 0) {
    // (the frees of the other holders' writes happen before this one's)
    if (w0 & RC_TS) atomic_thread_fence(memory_order_acquire);
    return 1;
  }
  if (w0 & RC_STICKY) return 0;
  if (!(w0 & RC_TS)) { *p = w0 - RC_ONE; return 0; }
  // (another holder may have let go since the load: then this one is last)
  return RC_REFS(__atomic_fetch_sub(p, RC_ONE, __ATOMIC_ACQ_REL)) == 0;
}

// Frees a small slot (block bi, slot i, of class c) or a large object.
static inline void rc_free_slot(uintptr_t bi, uint32_t i, unsigned c) {
  uint64_t bit = 1ull << (i & 63);
  uint64_t *aw = &gc_abits[bi * 64 + (i >> 6)];
  uint64_t *cw = &gc_cand[(size_t)c * GC_CANDW + (bi >> 6)];
  uint64_t cb = 1ull << (bi & 63);
  if (gc_hot.mt) {
    __atomic_fetch_and(aw, ~bit, __ATOMIC_RELEASE);
    if (!(__atomic_load_n(cw, __ATOMIC_RELAXED) & cb)) __atomic_fetch_or(cw, cb, __ATOMIC_RELAXED);
  } else {
    *aw &= ~bit;
    *cw |= cb;
  }
}

__attribute__((noinline)) void rc_free_large(uintptr_t bi);

#ifdef BEND_DEBUG_FREE
// Debugging: a freed object is poisoned with its free's number, and kept
// (see bend_take_at); BEND_DEBUG_FREE_AT=n aborts at free number n.
void rc_poison(V v, unsigned w);
#endif

// Frees object v (valid, of w words when w is not 0), whose fields were
// moved out.
static inline void rc_free_at(V v, unsigned w) {
  uintptr_t off = (uintptr_t)v - gc_hot.base;
  uintptr_t bi = off >> GC_BLK_SHIFT;
#ifdef BEND_DEBUG_FREE
  rc_poison(v, w ? w : gc_kind[bi] == 1 ? gc_meta[bi].words : 1);
  return;
#endif
  if (UNLIKELY(gc_kind[bi] != 1)) { rc_free_large(bi); return; }
  uint64_t o = (off & (GC_BLK - 1)) - GC_HDR;
  if (w >= 2 && w <= 16) rc_free_slot(bi, (uint32_t)(o / (w * sizeof(V))), w - 2);
  else rc_free_slot(bi, (uint32_t)((o * gc_meta[bi].recip) >> 32), gc_meta[bi].cls);
}

void rc_push(Thr *t, V v);

// Frees v, whose last reference went, and drops its fields: every word but
// the first that is a reference (a closure's arity and count are numbers,
// the words of a slot past its object zero). Iterative: the first field
// that dies next, the others on the thread's stack.
__attribute__((noinline)) void rc_free_obj(V v);

// Drops a reference to v.
static inline void rc_drop(V v) {
  if (rc_obj(v) && rc_release(v)) rc_free_obj(v);
}

// Drops n references to v (a case that uses v fewer times than another).
static inline void rc_dropn(V v, V n) {
  if (!rc_obj(v)) return;
  V *p = (V *)v;
  // (all but the last at once: v outlives them)
  V w0 = __atomic_load_n(p, __ATOMIC_RELAXED);
  if (n > 1 && !(w0 & RC_STICKY)) {
    if (w0 & RC_TS) __atomic_fetch_sub(p, (n - 1) * RC_ONE, __ATOMIC_RELEASE);
    else *p = w0 - (n - 1) * RC_ONE;
  }
  if (rc_release(v)) rc_free_obj(v);
}

// A shared node of w words opened: its fields get a reference each, then it
// loses one (freed, fields and all, when that was the last).
__attribute__((noinline)) void rc_take_shared(V v, unsigned w);

static inline int rc_unique(V v) {
  V w0 = __atomic_load_n((V *)v, __ATOMIC_RELAXED);
  if (RC_REFS(w0)) return 0;
  if (w0 & RC_TS) atomic_thread_fence(memory_order_acquire);
  return 1;
}

// A match opened node v, of w words, after reading its fields: its fields
// are the pattern's now.
static inline void rc_take(V v, unsigned w) {
  if (UNLIKELY((uintptr_t)v - gc_hot.base >= gc_hot.span)) return;
  if (LIKELY(rc_unique(v))) rc_free_at(v, w);
  else rc_take_shared(v, w);
}

// As rc_take, but a node with one reference is not freed: its slot is
// answered, for the case's constructor of the same size to be built in
// (reuse, see RU); 0 when the node was shared.
static inline V rc_take_ru(V v, unsigned w) {
  if (UNLIKELY((uintptr_t)v - gc_hot.base >= gc_hot.span)) return 0;
  if (LIKELY(rc_unique(v))) {
#ifdef BEND_DEBUG_FREE
    rc_free_at(v, w);
    return 0;
#endif
    return v;
  }
  rc_take_shared(v, w);
  return 0;
}

// As rc_take and rc_take_ru, for a case that uses only the fields in keep
// (bit i for FLD i): the others are dropped with a node that had one
// reference, and get none from a shared one (see RC.dead in bendc.bend).
static inline int rc_kept(V keep, unsigned j) { return j > 64 || ((keep >> (j - 1)) & 1); }
__attribute__((noinline)) void rc_take_shared_d(V v, unsigned w, V keep);
static inline void rc_drop_unkept(V v, unsigned w, V keep) {
  for (unsigned j = 1; j < w; j++)
    if (!rc_kept(keep, j)) rc_drop(((V *)v)[j]);
}
static inline void rc_take_d(V v, unsigned w, V keep) {
  if (UNLIKELY((uintptr_t)v - gc_hot.base >= gc_hot.span)) { rc_drop_unkept(v, w, keep); return; }
  if (LIKELY(rc_unique(v))) { rc_drop_unkept(v, w, keep); rc_free_at(v, w); }
  else rc_take_shared_d(v, w, keep);
}
static inline V rc_take_ru_d(V v, unsigned w, V keep) {
  if (UNLIKELY((uintptr_t)v - gc_hot.base >= gc_hot.span)) { rc_drop_unkept(v, w, keep); return 0; }
  if (LIKELY(rc_unique(v))) {
    rc_drop_unkept(v, w, keep);
#ifdef BEND_DEBUG_FREE
    rc_free_at(v, w);
    return 0;
#endif
    return v;
  }
  rc_take_shared_d(v, w, keep);
  return 0;
}

// The fields of object v, w words, were copied out (a closure applied): as
// rc_take, for any object.
static inline void rc_let_go(V v, unsigned w) {
  if (rc_unique(v)) rc_free_at(v, 0);
  else rc_take_shared(v, w);
}

// A reuse slot of w words (rc_take_ru's), or a new one.
#define RU(tok, w) ((tok) ? (V *)(tok) : halloc(w))

// Marks v and everything it reaches immortal (before other threads see it).
void rc_immortal(V v);

// Marks v reachable by other threads (RC_TS), and everything it reaches,
// stopping at marked and immortal objects (whose reach is marked). Not only
// through objects with more than one reference: a node with one, reached
// only through v, may hold one the forking thread holds too, and the thread
// that takes the node gets that one without a mark.
__attribute__((noinline)) void rc_publish(V v);

// A value used once more (by the runtime): a reference, or shared.
static inline void bend_dup(V v) {
  if (gc_hot.rc) rc_dup(v);
  else bend_share(v);
}

// The runtime is done with v (a reference counted program's only).
static inline void bend_drop(V v) {
  if (gc_hot.rc) rc_drop(v);
}

// Objects allocated and not freed (BEND_RC_STATS=1, at exit).
size_t rc_live(void);

// Registers words that hold values (a global cache, say) as roots.
void gc_root_add_locked(V *p, size_t n);

void gc_root_add(V *p, size_t n);

void gc_hook(void (*f)(void));

// Whether a root's object may still get written: it holds BEND_HOLE, an open
// hole of a D_ node (or it is still being made: see gc_alloc and C2).
int gc_rem_wants(GcBlk *b, uint32_t i, uint64_t bit, uintptr_t o);

static inline void gc_mark(V w) {
  uintptr_t a = (uintptr_t)(w & 0x7fffffffffffffffull);
  uintptr_t off = a - (uintptr_t)gc_base;
  if (off >= (gc_top << GC_BLK_SHIFT)) return;
  uintptr_t bi = off >> GC_BLK_SHIFT;
  uint8_t kd = gc_kind[bi];
  if (kd == 0) return;
  if (kd == 3) bi -= gc_back[bi];
  GcBlk *b = gc_blk(bi);
  uintptr_t o = (uintptr_t)gc_objs(b);
  // A large object's header counts as the object: gc_alloc_large returns
  // gc_objs(b) after it unlocks, so a thread stopped in the unlock holds b.
  if (a < o && !b->large) return;
  size_t i = 0;
  if (b->large) {
    if (a >= o + (uintptr_t)b->words * sizeof(V)) return;
  } else {
    i = (a - o) / ((uintptr_t)b->words * sizeof(V));
    if (i >= b->nobj) return;
  }
  uint64_t bit = 1ull << (i & 63);
  if (!(GC_ALLOC(b)[i >> 6] & bit)) return;
  if (gc_rooting == 1 && !b->atomic && !b->large && gc_rem_wants(b, i, bit, o)) {
    if (gc_nrem == gc_caprem) {
      gc_caprem = gc_caprem ? gc_caprem * 2 : 256;
      gc_rem = realloc(gc_rem, gc_caprem * sizeof(V));
    }
    gc_rem[gc_nrem++] = (V)(o + i * (uintptr_t)b->words * sizeof(V));
  }
  // A minor collection scans an old object met from a root once more: its
  // fields may have been written after it got old.
  if ((GC_MARK(b)[i >> 6] & bit) && !(gc_minor && gc_rooting)) return;
  GC_MARK(b)[i >> 6] |= bit;
  if (b->atomic) return;
  if (gc_sp == gc_cap) bend_fail("the collector's mark stack overflowed");
  gc_stk[gc_sp++] = (GcItem){(V *)(o + i * (uintptr_t)b->words * sizeof(V)), b->words};
}

void gc_scan(const void *lo, const void *hi);

void gc_drain(void);

// Parallel marking: the threads a collection stopped help drain the mark
// stack, which is then a shared pool (under gc_pool_lock). A helper takes a
// chunk into its own stack, marks with an atomic or (two helpers may reach
// one object), and gives half its stack back when the pool runs dry. The
// marking is over when the pool is empty and no helper holds work, both read
// under the lock. Only the collector's own lock: a helper runs in a signal
// handler, and no thread the collector stopped can hold it.
#define GC_CHUNK 64
#define GC_MKCAP ((size_t)1 << 16)
typedef struct { GcItem *stk; size_t sp; } GcMk;
extern GcMk gc_mks[GC_MAXTHR + 1];
extern int gc_nmks;
#ifdef __TINYC__
// (tcc's compare-and-swap is not atomic on arm64: two threads can both win.
// The mutex is taken only by the collector and the threads it stopped.)
extern pthread_mutex_t gc_pool_mx;
#else
extern int gc_pool_lock;
#endif
extern size_t gc_active;
extern _Atomic int gc_marking;
extern _Atomic unsigned gc_mark_gen;
extern _Atomic int gc_helpers;
extern _Atomic int gc_in_help;

#ifdef __TINYC__
static inline void gc_pool_acquire(void) { pthread_mutex_lock(&gc_pool_mx); }
static inline void gc_pool_release(void) { pthread_mutex_unlock(&gc_pool_mx); }
#else
static inline void gc_pool_acquire(void) {
  for (int k = 0;; k++) {
    int z = 0;
    if (__atomic_compare_exchange_n(&gc_pool_lock, &z, 1, 1, __ATOMIC_ACQUIRE, __ATOMIC_RELAXED)) return;
    if (k > 64) sched_yield();
  }
}

static inline void gc_pool_release(void) { __atomic_store_n(&gc_pool_lock, 0, __ATOMIC_RELEASE); }
#endif

// Half of a helper's stack back to the pool.
void gc_share(GcMk *m);

static inline void gc_mark_par(V w, GcMk *m) {
  uintptr_t a = (uintptr_t)(w & 0x7fffffffffffffffull);
  uintptr_t off = a - (uintptr_t)gc_base;
  if (off >= (gc_top << GC_BLK_SHIFT)) return;
  uintptr_t bi = off >> GC_BLK_SHIFT;
  uint8_t kd = gc_kind[bi];
  if (kd == 0) return;
  if (kd == 3) bi -= gc_back[bi];
  GcBlk *b = gc_blk(bi);
  uintptr_t o = (uintptr_t)gc_objs(b);
  if (a < o && !b->large) return;
  size_t i = 0;
  if (b->large) {
    if (a >= o + (uintptr_t)b->words * sizeof(V)) return;
  } else {
    i = (a - o) / ((uintptr_t)b->words * sizeof(V));
    if (i >= b->nobj) return;
  }
  uint64_t bit = 1ull << (i & 63);
  if (!(GC_ALLOC(b)[i >> 6] & bit)) return;
  uint64_t *mw = &GC_MARK(b)[i >> 6];
  if (__atomic_load_n(mw, __ATOMIC_RELAXED) & bit) return;
  if (__atomic_fetch_or(mw, bit, __ATOMIC_RELAXED) & bit) return;
  if (b->atomic) return;
  if (m->sp == GC_MKCAP) gc_share(m);
  m->stk[m->sp++] = (GcItem){(V *)(o + i * (uintptr_t)b->words * sizeof(V)), b->words};
}

void gc_help(GcMk *m);

// A stopped thread, when the pool opens.
void gc_join(void);

// Drains the mark stack, with the n stopped threads' help.
void gc_drain_par(int n);

// A thread stopped for a collection: its registers on its stack, it waits.
__attribute__((noinline)) void gc_park(Thr *t);

void gc_handler(int sig);

void gc_sweep(void);

int gc_rem_cmp(const void *a, const void *b);

// A stack holds many pointers to the same objects: each is kept once.
void gc_rem_unique(void);

// The old objects of blocks an Array store dirtied, rescanned by a minor
// collection (a major one scans everything live); the marks are cleared.
// A store marks its block before it writes, so a collection that stops the
// thread in between rescans the block, and the value about to be stored is
// in the thread's registers or stack: marked then, and old after.
void gc_rescan_dirty(void);

__attribute__((noinline)) void gc_collect_locked(void);

// Collects now (from a thread that runs Bend code).
void gc_collect(void);

struct PDeque *pdq_new(void);

// Registers the calling thread; top is an address near the base of its stack.
// A fault (a deep recursion past the machine stack, most likely) reports
// as the official runtime does, not as a bare signal; it runs on a stack
// of its own, since the thread's is the one that ran out.
void bend_fault(int sig);

void fault_stack(void);

void fault_init(void);

// A thread that runs Bend code has a stack the runtime maps itself, at a
// multiple of BEND_STK: the first word of that region holds the thread's Thr,
// so native code finds its allocation caches from sp alone (see rt/native.c).
// A guard page lies between that word and the stack.
#define BEND_STK ((uintptr_t)1 << 32)

void thr_stack(pthread_attr_t *attr);

void thr_register(uintptr_t top);

// Constructors and closures
// =========================

static inline V C1(V t, V a) { V *p = halloc(2); p[0] = t; p[1] = a; return (V)p; }
static inline V C2(V t, V a, V b) { V *p = halloc(3); p[0] = t; p[1] = a; p[2] = b; return (V)p; }
static inline V C3(V t, V a, V b, V c) { V *p = halloc(4); p[0] = t; p[1] = a; p[2] = b; p[3] = c; return (V)p; }
static inline V C4(V t, V a, V b, V c, V d) {
  V *p = halloc(5); p[0] = t; p[1] = a; p[2] = b; p[3] = c; p[4] = d; return (V)p;
}
static inline V CN(V t, int n, const V *xs) {
  V *p = halloc(n + 1); p[0] = t;
  for (int i = 0; i < n; i++) p[i + 1] = xs[i];
  return (V)p;
}

// A D_ node (one field is BEND_HOLE): its tag word holds BEND_HOLE from
// before the slot is allocated until its fields, the hole among them, are
// stored, so a collection that stops the thread in between sees the hole.
static inline V CH1(V t, V a) { V *p = halloc_hole(2); p[1] = a; BEND_BARRIER(); p[0] = t; return (V)p; }
static inline V CH2(V t, V a, V b) { V *p = halloc_hole(3); p[1] = a; p[2] = b; BEND_BARRIER(); p[0] = t; return (V)p; }
static inline V CH3(V t, V a, V b, V c) {
  V *p = halloc_hole(4); p[1] = a; p[2] = b; p[3] = c; BEND_BARRIER(); p[0] = t; return (V)p;
}
static inline V CH4(V t, V a, V b, V c, V d) {
  V *p = halloc_hole(5); p[1] = a; p[2] = b; p[3] = c; p[4] = d; BEND_BARRIER(); p[0] = t; return (V)p;
}
static inline V CHN(V t, int n, const V *xs) {
  V *p = halloc_hole(n + 1);
  for (int i = 0; i < n; i++) p[i + 1] = xs[i];
  BEND_BARRIER();
  p[0] = t;
  return (V)p;
}

// Reuse (counted programs): a constructor built where a match freed a node
// of its size takes that node's slot, tok (rc_take_ru's: 0 when the node was
// shared, then a new slot). A case that does not build in its token frees
// it (RUF, with its size in words).
static inline V CR1(V u, V t, V a) { V *p = RU(u, 2); p[0] = t; p[1] = a; return (V)p; }
static inline V CR2(V u, V t, V a, V b) { V *p = RU(u, 3); p[0] = t; p[1] = a; p[2] = b; return (V)p; }
static inline V CR3(V u, V t, V a, V b, V c) {
  V *p = RU(u, 4); p[0] = t; p[1] = a; p[2] = b; p[3] = c; return (V)p;
}
static inline V CR4(V u, V t, V a, V b, V c, V d) {
  V *p = RU(u, 5); p[0] = t; p[1] = a; p[2] = b; p[3] = c; p[4] = d; return (V)p;
}
static inline V CRN(V u, V t, int n, const V *xs) {
  V *p = RU(u, n + 1); p[0] = t;
  for (int i = 0; i < n; i++) p[i + 1] = xs[i];
  return (V)p;
}
// (a D_ node: no collector runs to see its hole)
static inline V CRH1(V u, V t, V a) { return CR1(u, t, a); }
static inline V CRH2(V u, V t, V a, V b) { return CR2(u, t, a, b); }
static inline V CRH3(V u, V t, V a, V b, V c) { return CR3(u, t, a, b, c); }
static inline V CRH4(V u, V t, V a, V b, V c, V d) { return CR4(u, t, a, b, c, d); }
static inline V CRHN(V u, V t, int n, const V *xs) { return CRN(u, t, n, xs); }
#define RUF(u, w) do { if (u) rc_free_at(u, w); } while (0)

// Reuse under the collector (matches free, not counted): bend_take_ru is
// bend_take, but a node that was not shared keeps its slot, answered as the
// token (0 when it was shared), where a constructor gets built (CG1 and the
// like). The build makes the slot young first: its mark is cleared, as a
// slot handed out again has it cleared (a collection marked the node, or
// marked it between the match and the build, reached from the stack), so
// minor collections trace from it. Only this thread holds the slot, so
// clearing its mark races with no one. Before the first collection no mark
// is set (gc_epoch is 0), and the build skips it. (A collection that stops
// this thread between that check and the build's stores marks the values
// stored too: they are in its registers.)
// RUFG frees a token no constructor took.
static inline V bend_take_ru(V v, unsigned w) {
  const GcHot *h = &gc_hot;
  V w0 = h->mt ? __atomic_load_n((V *)v, __ATOMIC_ACQUIRE) : __atomic_load_n((V *)v, __ATOMIC_RELAXED);
  if (w0 & BEND_SH) {
    if (!(w0 & BEND_DEEP)) bend_deep(v, w);
    return 0;
  }
  if (UNLIKELY((uintptr_t)v - h->base >= h->span || w > 16)) { bend_deep(v, w); return 0; }
#ifdef BEND_DEBUG_FREE
  bend_take(v, w);
  return 0;
#endif
  return v;
}
static inline V *bend_ru_young(V u, unsigned w) {
  uintptr_t off = (uintptr_t)u - gc_hot.base;
  uintptr_t bi = off >> GC_BLK_SHIFT;
  uint32_t i = (uint32_t)(((off & (GC_BLK - 1)) - GC_HDR) / (w * sizeof(V)));
  uint64_t bit = 1ull << (i & 63);
  uint64_t *mw = &gc_mbits[bi * 64 + (i >> 6)];
  if (UNLIKELY(gc_hot.mt)) {
    if (__atomic_load_n(mw, __ATOMIC_RELAXED) & bit) __atomic_fetch_and(mw, ~bit, __ATOMIC_RELAXED);
  } else {
    *mw &= ~bit;
  }
  return (V *)u;
}
#define RUG(tok, w) ((tok) ? (UNLIKELY(__atomic_load_n(&gc_epoch, __ATOMIC_RELAXED)) ? bend_ru_young(tok, w) : (V *)(tok)) : halloc(w))
static inline V CG1(V u, V t, V a) { V *p = RUG(u, 2); p[0] = t; p[1] = a; return (V)p; }
static inline V CG2(V u, V t, V a, V b) { V *p = RUG(u, 3); p[0] = t; p[1] = a; p[2] = b; return (V)p; }
static inline V CG3(V u, V t, V a, V b, V c) {
  V *p = RUG(u, 4); p[0] = t; p[1] = a; p[2] = b; p[3] = c; return (V)p;
}
static inline V CG4(V u, V t, V a, V b, V c, V d) {
  V *p = RUG(u, 5); p[0] = t; p[1] = a; p[2] = b; p[3] = c; p[4] = d; return (V)p;
}
static inline V CGN(V u, V t, int n, const V *xs) {
  V *p = RUG(u, n + 1); p[0] = t;
  for (int i = 0; i < n; i++) p[i + 1] = xs[i];
  return (V)p;
}
#define RUFG(u, w) do { if (u) bend_free_slot((u), (w), 0); } while (0)

// Arrays
// ------
//
// An Array is one node {ARR_HDR(c), 2^c cells}, as the official runtime's
// flat block: Array.get/set/swap and the atomics work on it in place, so
// the handles a share (Array.fork, a +a) makes are one array, and a write
// through one is read through the other. A match on ANode copies the
// halves; ANode{l, r} copies both into a new array; ALeaf{x} is a 1-cell
// one. A shared array's cells are shared as they are copied.
#define ARR_TAG ((V)0xFFF00)
#define ARR_HDR(c) (ARR_TAG | (V)(c))
static inline unsigned arr_cls(V a) { return (unsigned)(((const uint32_t *)a)[0] & 31); }
static inline V *arr_cells(V a) { return (V *)a + 1; }
static inline int arr_shared(V a) {
  V w0 = __atomic_load_n((V *)a, __ATOMIC_RELAXED);
  return gc_hot.rc ? RC_REFS(w0) != 0 : (w0 & BEND_SH) != 0;
}

// Marks a's block dirty before a pointer is stored in it (gc_rescan_dirty).
static inline void arr_dirty(V a) {
  if (gc_hot.rc) return;
  uintptr_t bi = ((uintptr_t)a - (uintptr_t)gc_base) >> GC_BLK_SHIFT;
  if (!__atomic_load_n(&gc_dirty[bi], __ATOMIC_RELAXED)) __atomic_store_n(&gc_dirty[bi], 1, __ATOMIC_RELAXED);
  BEND_BARRIER();
}
static inline void arr_put(V a, V *p, V v) {
  if (v >= ((V)1 << 32)) {
    arr_dirty(a);
    if (gc_hot.rc && (((V *)a)[0] & RC_TS)) rc_publish(v);
  }
  *p = v;
}

// An array whose cells were copied out loses a reference: freed (not its
// cells) when it had one, else its cells get one each.
void rc_let_go_arr(V a);

V arr_alloc(unsigned c);

// Traced, an unshared array no path of the program uses any more (see
// bend_dead) is one of the thread's spares (the oldest goes when all
// ARR_SPARES are taken), which arr_alloc hands out again (its header is
// ARR_HDR(c): not shared). The spares are no roots: a
// collection forgets them before it traces (a thread stopped between
// taking one and clearing its slot holds it in a register, which the stack
// scan sees).
void arr_dead(V a);

void arr_hook(void);

// The program is done with v (traced: a variable that no path of its scope
// uses, or that a case does not use and another case of its match does). An
// unshared array goes to arr_dead; anything else is the collector's.
static inline void bend_dead(V v) {
  if (LIKELY(v < ((V)1 << 32))) return;
  if ((uintptr_t)v - gc_hot.base >= gc_hot.span) return;
  V w0 = gc_hot.mt ? __atomic_load_n((V *)v, __ATOMIC_ACQUIRE) : __atomic_load_n((V *)v, __ATOMIC_RELAXED);
  if ((w0 | 31) == (ARR_TAG | 31)) arr_dead(v);
}

// 2^c cells from src (a shared source's are shared) into a new array.
// (ts: the source is marked, see RC_TS)
V arr_copy(unsigned c, const V *src, int share, V ts);

V arr_new(V depth, V v);

static inline V arr_leaf(V x) { return arr_new(0, x); }

V arr_node(V l, V r);

// (Counted, the cells get a reference each: the match drops the array.)
V arr_half(V a, unsigned hi);

static inline V *arr_at(V a, V i) { return arr_cells(a) + ((uint32_t)i & (((V)1 << arr_cls(a)) - 1)); }

static inline V F_Array_dsize(V a) { return C2(0, a, (V)((uint64_t)1 << arr_cls(a))); }
// The checker's memo cells (check.bend's memo.*): an array of a cell's
// term and, once it is evaluated, its value. The value is stored before
// the term, so a reader that finds the term finds the value.
static inline V F_Chk_dmemo_dnew(V t) {
  bend_drop(t);
  V a = arr_alloc(1);
  arr_cells(a)[0] = arr_cells(a)[1] = 0;
  return a;
}
static inline V F_Chk_dmemo_dhas(V m, V v) {
  V k = __atomic_load_n(&arr_cells(m)[0], __ATOMIC_ACQUIRE);
  bend_drop(m);
  bend_drop(v);
  return BOOL(k != 0 && k == v);
}
static inline V F_Chk_dmemo_dget(V m) {
  V x = arr_cells(m)[1];
  if (gc_hot.rc) rc_dup_in(x, ((V *)m)[0] & RC_TS);
  else bend_share(x);
  bend_drop(m);
  return x;
}
// (Counted, the cell keeps its term, so no other term takes its address
// while the memo lives.)
static inline V F_Chk_dmemo_dset(V m, V v, V x) {
  bend_dup(x);
  arr_put(m, &arr_cells(m)[1], x);
  arr_dirty(m);
  __atomic_store_n(&arr_cells(m)[0], v, __ATOMIC_RELEASE);
  bend_drop(m);
  return x;
}
// x, read out of array a, is the array's and the reader's now.
BEND_UINL void arr_got(V a, V x) {
  if (gc_hot.rc) rc_dup_in(x, ((V *)a)[0] & RC_TS);
  else bend_share(x);
}
BEND_UINL V F_Array_dget(V a, V i) {
  V x = *arr_at(a, i);
  arr_got(a, x);
  return C2(0, a, x);
}
BEND_UINL V F_Array_dswap(V a, V i, V v) {
  V *p = arr_at(a, i);
  V old = *p;
  arr_put(a, p, v);
  return C2(0, a, old);
}
BEND_UINL V F_Array_dset(V a, V i, V v) {
  V *p = arr_at(a, i);
  bend_drop(*p);
  arr_put(a, p, v);
  return a;
}
// Array.get, Array.set and Array.swap on cells of a scalar type (U32, F32,
// Bool, Char; see Arrw in bendc.bend): the cells are words, with no
// reference to take or drop, in either build.
BEND_UINL V F_Array_dget_x37w(V a, V i) { return C2(0, a, *arr_at(a, i)); }
BEND_UINL V F_Array_dset_x37w(V a, V i, V v) { *arr_at(a, i) = v; return a; }
BEND_UINL V F_Array_dswap_x37w(V a, V i, V v) {
  V *p = arr_at(a, i);
  V old = *p;
  *p = v;
  return C2(0, a, old);
}
static inline V F_Array_dnew(V d, V v) { return arr_new(d, v); }
static inline V F_Array_dclone(V a) { return C2(0, a, arr_copy(arr_cls(a), arr_cells(a), 1, ((V *)a)[0] & RC_TS)); }

// The atomics, on a cell's U32 (its low half: the cell is a U32 below 2^32).
static inline uint32_t *arr_word(V a, V i) { return (uint32_t *)arr_at(a, i); }
#define ARR_ATOMIC(name, op) static inline V F_Array_datomic_d##name(V a, V i, V v) { return C2(0, a, (V)__atomic_##op(arr_word(a, i), (uint32_t)v, __ATOMIC_SEQ_CST)); }
ARR_ATOMIC(add, fetch_add)
ARR_ATOMIC(and, fetch_and)
ARR_ATOMIC(or, fetch_or)
ARR_ATOMIC(xor, fetch_xor)
#ifdef __TINYC__
// tcc lowers __atomic_exchange_n to a call its libtcc1 lacks: a CAS loop.
static inline V F_Array_datomic_dexch(V a, V i, V v) {
  uint32_t *w = arr_word(a, i), o = __atomic_load_n(w, __ATOMIC_RELAXED);
  while (!__atomic_compare_exchange_n(w, &o, (uint32_t)v, 1, __ATOMIC_SEQ_CST, __ATOMIC_RELAXED)) {}
  return C2(0, a, (V)o);
}
#else
ARR_ATOMIC(exch, exchange_n)
#endif
static inline V arr_rmw(V a, V i, V v, int k) {
  uint32_t *w = arr_word(a, i);
  uint32_t o = __atomic_load_n(w, __ATOMIC_RELAXED), n;
  for (;;) {
    union { uint32_t u; float f; } x = {o}, y = {(uint32_t)v};
    if (k == 0) n = o < (uint32_t)v ? o : (uint32_t)v;
    else if (k == 1) n = o > (uint32_t)v ? o : (uint32_t)v;
    else { x.f = x.f + y.f; n = x.u; }
    if (__atomic_compare_exchange_n(w, &o, n, 1, __ATOMIC_SEQ_CST, __ATOMIC_RELAXED)) break;
  }
  return C2(0, a, (V)o);
}
static inline V F_Array_datomic_dmin(V a, V i, V v) { return arr_rmw(a, i, v, 0); }
static inline V F_Array_datomic_dmax(V a, V i, V v) { return arr_rmw(a, i, v, 1); }
static inline V F_Array_datomic_dfadd(V a, V i, V v) { return arr_rmw(a, i, v, 2); }
static inline V F_Array_datomic_dcas(V a, V i, V x, V v) {
  uint32_t o = (uint32_t)x;
  __atomic_compare_exchange_n(arr_word(a, i), &o, (uint32_t)v, 0, __ATOMIC_SEQ_CST, __ATOMIC_SEQ_CST);
  return C2(0, a, (V)o);
}

static inline V mk_clo(Fn f, V arity, V n, const V *args) {
  V *p = halloc(3 + n);
  p[0] = (V)f; p[1] = arity; p[2] = n;
  for (V i = 0; i < n; i++) p[3 + i] = args[i];
  return (V)p;
}

// Applying a closure takes it: counted, its captured values move to the
// call when it had one reference, and get one each when it was shared.
V apply(V f, V x);

// Strings (cons lists of code points)
// -----------------------------------

#define SNIL IMM(0)
#define SCONS(h, t) C2(1, (h), (t))
#define NIL IMM(0)
#define CONS(h, t) C2(1, (h), (t))

// Builds a String from UTF-8 bytes. Strings are built from the end, so no
// cell is written after it is made (minor collections rely on that).
V mk_str(const char *s, size_t n);

#define MKS(lit) mk_str(lit, sizeof(lit) - 1)
// The acquire pairs with str_cache's release: a thread that sees the string
// sees it shared.
#define STRC(c, lit) (__atomic_load_n(&(c), __ATOMIC_ACQUIRE) ? (c) : str_cache(&(c), lit, sizeof(lit) - 1))
#define mk_str_heap mk_str

// A string literal, built once (slot is its cache, a root).
__attribute__((noinline)) V str_cache(V *slot, const char *s, size_t n);

// A constant (a constructor of literals, see Gen.konst in bendc.bend),
// built once as a string literal is (slot is its cache, a root).
__attribute__((noinline)) V konst_cache(V *slot, V v);
#define KONST(c, e) (__atomic_load_n(&(c), __ATOMIC_ACQUIRE) ? (c) : konst_cache(&(c), (e)))

// Encodes a String as a malloc'd UTF-8 buffer.
char *str_to_c(V s, size_t *len);

// Natives: Nat
// -------------

// A Nat is a word up to NAT_IMM = 2^48 - 1, as the official runtime's
// immediate: a result past it stops the program, as there. A foreign
// effect's word past it matches as a successor; only results are checked.
#define NAT_IMM (((V)1 << 48) - 1)
__attribute__((noreturn, cold, noinline)) void nat_wall(void);
static inline V nat_chk(V x) { if (UNLIKELY(x > NAT_IMM)) nat_wall(); return x; }
static inline V nat_add(V a, V b) { return nat_chk(a + b); }
static inline V nat_sub(V a, V b) { return a > b ? a - b : 0; }
static inline V nat_mul(V a, V b) {
  return b != 0 && a > NAT_IMM / b ? (nat_wall(), 0) : a * b;
}
static inline int nat_cmp3(V a, V b) { return a < b ? -1 : a > b; }
static inline void nat_divmod2(V a, V b, V *qo, V *ro) {
  if (b == 0) { *qo = 0; *ro = a; } else { *qo = a / b; *ro = a % b; }
}
V nat_pow(V a, V n);
// Base's Nat.show rebuilds each quotient as a successor, so a word whose
// first quotient is past the cap stops there.
char *nat_digits(V x);

static inline V nat_addk(V x, V k) { return LIKELY(x + k <= NAT_IMM) ? x + k : (nat_wall(), 0); }
static inline V nat_subk(V x, V k) { return x - k; }
static inline int nat_ge(V x, V k) { return x >= k; }

static inline V F_Nat_ddouble(V a) { return nat_add(a, a); }
static inline V F_Nat_dadd(V a, V b) { return nat_add(a, b); }
static inline V F_Nat_dsub(V a, V b) { return nat_sub(a, b); }
static inline V F_Nat_dmul(V a, V b) { return nat_mul(a, b); }
static inline V F_Nat_ddivmod(V a, V b) { V q, r; nat_divmod2(a, b, &q, &r); return C2(0, q, r); }
static inline V F_Nat_ddiv(V a, V b) { V q, r; nat_divmod2(a, b, &q, &r); return q; }
static inline V F_Nat_dmod(V a, V b) { V q, r; nat_divmod2(a, b, &q, &r); return r; }
static inline V F_Nat_dcmp(V a, V b) { int c = nat_cmp3(a, b); return c < 0 ? IMM(0) : c == 0 ? IMM(1) : IMM(2); }
static inline V F_Nat_dis__eq(V a, V b) { return BOOL(a == b); }
static inline V F_Nat_dis__ne(V a, V b) { return BOOL(a != b); }
static inline V F_Nat_dis__lt(V a, V b) { return BOOL(a < b); }
static inline V F_Nat_dis__le(V a, V b) { return BOOL(a <= b); }
static inline V F_Nat_dis__gt(V a, V b) { return BOOL(a > b); }
static inline V F_Nat_dis__ge(V a, V b) { return BOOL(a >= b); }
static inline V F_Nat_dmin(V a, V b) { return a < b ? a : b; }
static inline V F_Nat_dmax(V a, V b) { return a < b ? b : a; }
static inline V F_Nat_dpow(V a, V n) { return nat_pow(a, n); }
V F_Nat_dshow(V a);

// Map.bit(key, pos): bit pos of key as Base's tries read it (char pos / 33;
// offset 0 is "the char exists", offset 1 + b is bit 31 - b of its code),
// with the key handed back. Base rebuilds the key's prefix to hand it back;
// here the key is shared, so a lookup allocates nothing.
#ifdef BEND_NATIVE_MAP_BIT
static inline V F_Map_dbit(V key, V pos) {
  if (pos >> 63) return C2(0, key, IMM(0));
  V ci = pos / 33, off = pos % 33, s = key;
  for (;;) {
    if (s == SNIL) return C2(0, key, IMM(0));
    if (ci == 0) break;
    s = ((V *)s)[2];
    ci--;
  }
  V x = ((V *)s)[1];
  return C2(0, key, off == 0 ? IMM(1) : (((uint32_t)x >> (32 - off)) & 1) ? IMM(1) : IMM(0));
}
#endif

// String.cmp(a, b) and String.eq(a, b), by code point. Base's String.cmp
// rebuilds both strings to hand them back, which copies a shared string
// (and, counted, frees the copy right after); here the strings themselves
// go back, and String.eq borrows them (counted, its callers keep their
// references: see Bor in bendc.bend).
#ifdef BEND_NATIVE_STR
static inline V str_cmp(V a, V b) {
  for (;;) {
    if (a == SNIL) return b == SNIL ? IMM(1) : IMM(0);
    if (b == SNIL) return IMM(2);
    uint32_t x = (uint32_t)((V *)a)[1], y = (uint32_t)((V *)b)[1];
    if (x != y) return x < y ? IMM(0) : IMM(2);
    a = ((V *)a)[2];
    b = ((V *)b)[2];
  }
}
static inline V F_String_dcmp(V a, V b) { return C2(0, C2(0, a, b), str_cmp(a, b)); }
static inline V F_String_deq(V a, V b) { return BOOL(str_cmp(a, b) == IMM(1)); }
#endif

// Map.get(d, m, key) and Map.has(m, key): Base's walk the trie rebuilding
// the path (and, through Map.bit, the key) to hand the map back; here the
// map itself goes back, and a lookup allocates only its pair. (MTip is
// IMM(0), MLeaf{key, val} tag 1, MNode{pos, lo, hi} tag 2.)
#ifdef BEND_NATIVE_MAP
static inline int map_bitv(V key, V pos) {
  if (pos >> 63) return 0;
  V ci = pos / 33, off = pos % 33, s = key;
  for (;;) {
    if (s == SNIL) return 0;
    if (ci == 0) break;
    s = ((V *)s)[2];
    ci--;
  }
  return off == 0 || (((uint32_t)((V *)s)[1] >> (32 - off)) & 1);
}
// The leaf of m with key (0 when none).
static inline V map_leaf(V m, V key) {
  for (;;) {
    if (m & 1) return 0;
    V t = TAG(m);
    if (t == 1) return str_cmp(key, FLD(m, 0)) == IMM(1) ? m : 0;
    if (t != 2) return 0;
    m = map_bitv(key, FLD(m, 0)) ? FLD(m, 2) : FLD(m, 1);
  }
}
static inline V F_Map_dget(V d, V m, V key) {
  V leaf = map_leaf(m, key), r = d;
  if (leaf) {
    r = FLD(leaf, 1);
    // (the value is the map's and the answer's now)
    if (gc_hot.rc) rc_dup(r);
    else bend_share(r);
    bend_drop(d);
  }
  bend_drop(key);
  return C2(0, m, r);
}
static inline V F_Map_dhas(V m, V key) {
  V r = BOOL(map_leaf(m, key) != 0);
  bend_drop(key);
  return C2(0, m, r);
}
#endif

// Natives: U32
// ------------

#define U(x) ((uint32_t)(x))
static inline V nat_low32(V n) { return U(n); }
static inline uint32_t F_U32_dinc(V a) { return U(U(a) + 1u); }
static inline uint32_t F_U32_dadd(V a, V b) { return U(U(a) + U(b)); }
static inline uint32_t F_U32_dsub(V a, V b) { return U(U(a) - U(b)); }
static inline uint32_t F_U32_dmul(V a, V b) { return U(U(a) * U(b)); }
static inline uint32_t F_U32_ddiv(V a, V b) { return b == 0 ? 0 : U(a) / U(b); }
static inline uint32_t F_U32_dmod(V a, V b) { return b == 0 ? a : U(a) % U(b); }
static inline uint32_t F_U32_dnot(V a) { return U(~U(a)); }
static inline uint32_t F_U32_dand(V a, V b) { return U(a) & U(b); }
static inline uint32_t F_U32_dor(V a, V b) { return U(a) | U(b); }
static inline uint32_t F_U32_dxor(V a, V b) { return U(a) ^ U(b); }
static inline uint32_t F_U32_dshl(V a) { return U(U(a) << 1); }
static inline uint32_t F_U32_dshr(V a) { return U(a) >> 1; }
static inline uint32_t F_U32_dshln(V a, V n) { return n >= 32 ? 0 : U(U(a) << U(n)); }
static inline uint32_t F_U32_dshrn(V a, V n) { return n >= 32 ? 0 : U(a) >> U(n); }
static inline V F_U32_dcmp(V a, V b) { return a < b ? IMM(0) : a == b ? IMM(1) : IMM(2); }
static inline uint32_t F_U32_dis__eq(V a, V b) { return BOOL(U(a) == U(b)); }
static inline uint32_t F_U32_dis__ne(V a, V b) { return BOOL(U(a) != U(b)); }
static inline uint32_t F_U32_dis__lt(V a, V b) { return BOOL(U(a) < U(b)); }
static inline uint32_t F_U32_dis__le(V a, V b) { return BOOL(U(a) <= U(b)); }
static inline uint32_t F_U32_dis__gt(V a, V b) { return BOOL(U(a) > U(b)); }
static inline uint32_t F_U32_dis__ge(V a, V b) { return BOOL(U(a) >= U(b)); }
static inline uint32_t F_U32_dis__zero(V a) { return BOOL(U(a) == 0); }
static inline uint32_t F_U32_dis__even(V a) { return BOOL((a & 1) == 0); }
static inline V F_U32_dto__nat(V a) { return a; }
static inline uint32_t F_U32_dfrom__nat(V n) { return nat_low32(n); }
static inline uint32_t F_U32_dmin(V a, V b) { return U(a) < U(b) ? U(a) : U(b); }
static inline uint32_t F_U32_dmax(V a, V b) { return U(a) < U(b) ? U(b) : U(a); }
static inline V F_U32_dpow(V a, V n) {
  // a^n mod 2^32; an odd a has an order dividing 2^30, an even one reaches 0.
  V e = n;
  uint32_t r = 1, b = U(a);
  for (; e; e >>= 1) { if (e & 1) r *= b; b *= b; }
  return r;
}
static inline V F_U32_dlog2(V n) {
  V d = 0;
  while (n > 1) { d++; n >>= 1; }
  return d;
}

// Natives: F32 (stored as IEEE bits)
// ----------------------------------

static inline float FV(V v) { union { uint32_t u; float f; } x; x.u = U(v); return x.f; }
static inline V VF(float f) { union { uint32_t u; float f; } x; x.f = f; return x.u; }
#define F2(name, expr) static inline V F_F32_d##name(V a, V b) { float x = FV(a), y = FV(b); return expr; }
#define F1(name, expr) static inline V F_F32_d##name(V a) { float x = FV(a); return expr; }
F2(add, VF(x + y))
F2(sub, VF(x - y))
F2(mul, VF(x * y))

// x * k + b for a literal k (bendc emits it for F32.add(F32.mul(x, k), b)):
// one fma when k is a power of two and x * k a normal float, for then the
// product is exact and fma rounds once where the two operations would
// round the same sum; else the two, as written. A loop like
// x = x * x * 0.5 + c then waits on two operations a step, not three.
// (The other case is a call, so the compiler branches to it rather than
// computing both and selecting, which would put both on the loop's path.)
__attribute__((noinline, cold)) float F32_mul_add(float x, float k, float c);
static inline V F32_mulk_add(V a, V kv, V b) {
  float x = FV(a), k = FV(kv);
  uint32_t e = (U(kv) >> 23) & 0xff;
  float p = fabsf(x * k);
  if ((U(kv) & 0x7fffff) == 0 && e != 0 && e != 0xff && p >= 0x1p-126f && p <= 0x1.fffffep127f) {
    return VF(fmaf(x, k, FV(b)));
  }
  return VF(F32_mul_add(x, k, FV(b)));
}
F2(div, VF(x / y))
F2(mod, VF((float)fmod(x, y)))
F2(pow, VF((float)pow(x, y)))
F2(atan2, VF((float)atan2(x, y)))
F2(is__eq, BOOL(x == y))
F2(is__ne, BOOL(x != y))
F2(is__lt, BOOL(x < y))
F2(is__le, BOOL(x <= y))
F2(is__gt, BOOL(x > y))
F2(is__ge, BOOL(x >= y))
F1(neg, VF(-x))
F1(abs, VF(fabsf(x)))
F1(sqrt, VF(sqrtf(x)))
F1(exp, VF((float)exp(x)))
F1(log, VF((float)log(x)))
F1(log2, VF((float)log2(x)))
F1(log10, VF((float)log10(x)))
F1(sin, VF((float)sin(x)))
F1(cos, VF((float)cos(x)))
F1(tan, VF((float)tan(x)))
F1(asin, VF((float)asin(x)))
F1(acos, VF((float)acos(x)))
F1(atan, VF((float)atan(x)))
F1(sinh, VF((float)sinh(x)))
F1(cosh, VF((float)cosh(x)))
F1(tanh, VF((float)tanh(x)))
F1(floor, VF(floorf(x)))
F1(ceil, VF(ceilf(x)))
F1(trunc, VF(truncf(x)))
static inline V F_F32_dbits(V a) { return U(a); }
static inline V F_F32_dto__u32(V a) { float x = FV(a); return !(x > 0) ? 0 : x >= 4294967296.0f ? 0 : (uint32_t)x; }
static inline V F_U32_dto__f32(V a) { return VF((float)U(a)); }
// The shortest text that reads back, spelled as JavaScript spells a number
// (the official f32_text): plain digits from 1e-6 to 1e21, else d.ddde+x.
int f32_text(float v, char *buf, size_t n);
V F_F32_dshow(V a);
V F_F32_dread(V s);

// Parallel calls
// ==============
//
// A parallel let `a b = f(x) g(y)` forks every value but the last as a task
// (a closure applied to a dummy argument), evaluates the last one, then joins
// the tasks in reverse. Each thread owns a Chase-Lev deque: it pushes and
// pops at the bottom, idle threads steal from the top. A task nobody stole
// runs inline at its join, so a fork costs little more than a closure.
// Reference counted, a task is queued held (P_HELD): marking what its
// closure reaches (rc_publish) is paid for the tasks that are stolen only.
// A thief that finds the oldest task held asks its owner (want), which
// marks it and lets it go (P_QUEUED) at its next fork or join.

#define P_LOCAL 0
#define P_QUEUED 1
#define P_DONE 2
#define P_HELD 3

typedef struct PTask { V clo; V res; V state; V depth; } PTask;

// The fork depth of the running code, and the frontier past which a def
// with a sequential clone (S_name, see bendc) runs its parallel lets in
// order: below it, forking costs more than it balances.
#ifndef __TINYC__
extern __thread int par_depth;
#endif
extern int par_front;

typedef struct PDeque {
  _Atomic long top;
  _Atomic long bot;
  _Atomic int want;
  long mask;
  PTask **buf;
} PDeque;

extern int par_nthreads;
// The pool's size as effect sources name it (IO.thread_count).
#define pool_size ((u32)par_nthreads)
extern _Atomic int par_started;
extern pthread_mutex_t par_mu;
extern pthread_cond_t par_cv;
extern _Atomic int par_sleepers;

PDeque *pdq_new(void);

PTask *pdq_pop(PDeque *d);

PTask *pdq_steal(PDeque *d);

void par_exec(PTask *t);

PTask *par_steal(void);

static inline void cpu_relax(void) {
#if defined(__TINYC__)
  // tcc has no pause/yield: a plain spin
#elif defined(__x86_64__)
  __builtin_ia32_pause();
#elif defined(__aarch64__)
  __asm__ __volatile__("yield");
#endif
}

void *par_worker(void *arg);

void par_hook(void);

void par_start(void);

// A thief asked (want): the oldest held task in this thread's deque d is
// marked and let go.
__attribute__((noinline)) void par_serve(PDeque *d);
static inline void par_serve_if(PDeque *d) {
  if (UNLIKELY(atomic_load_explicit(&d->want, memory_order_relaxed))) par_serve(d);
}

// Forks clo (a closure taking one dummy argument); returns the task. Only a
// thread whose deque is nearly empty queues it (the oldest tasks, which
// thieves take, are the big ones); otherwise the fork is the closure itself,
// tagged with bit 1, and its join just applies it.
V par_fork(V clo);

// Waits for a forked task and returns its value.
V par_join(V tv);

int cpu_count(void);

// Effects
// =======
//
// An effect def compiles to a request node {cid | n << 24, args..., k}. The
// event loop runs each computation's pure code up to its next request, runs
// the effect's host function, then resumes k with the answer. The host
// functions use the official runtime's names and conventions: see
// EFFECTS.md in the Bend guide. A CID encodes how a constructor is laid out
// here: kind << 16 | tag, where kind 0 is a node, 1 a nullary constructor,
// 2 a single-field single-constructor type (the field itself), and 3 an
// effect (its tag is its row in io_eff_rows).

#ifndef CID_TUPLE
#define CID_TUPLE 0u
#endif
#ifndef CID_DONE
#define CID_DONE 1u
#endif
#ifndef CID_FAIL
#define CID_FAIL 0u
#endif
#ifndef CID_SOME
#define CID_SOME 1u
#endif
#ifndef CID_NONE
#define CID_NONE ((1u << 16) | 0u)
#endif
#ifndef CID_TRUE
#define CID_TRUE ((1u << 16) | 1u)
#endif
#ifndef CID_FALSE
#define CID_FALSE ((1u << 16) | 0u)
#endif
#ifndef CID_UNIT
#define CID_UNIT ((1u << 16) | 0u)
#endif

// A request node for effect cid with n fields (its arguments, then k).
static inline V io_req(u64 cid, int n, const V *xs) { return CN(cid | ((V)n << 24), n, xs); }

typedef struct { int unused; } Env;
typedef pthread_mutex_t lock;
#define OUTLINE __attribute__((noinline))
#define IO_READ 1
#define IO_TIME 2
#define IO_HELP 64
extern V io_hole_cell;
#define TERM_HOLE ((Term)(uintptr_t)&io_hole_cell)
#define IO_PARK TERM_HOLE
#define io_hand(v) ((Term)(v))
#define io_hand_v(t) ((u64)(t))
#define CID_KIND(c) ((u32)(c) >> 16)
#define CID_TAG(c) ((u32)(c) & 0xffff)

__attribute__((noreturn)) void err_fail(const char *msg);

static inline Term term_pak(u64 cid, Term v) {
  switch (CID_KIND(cid)) {
    case 1: return IMM(CID_TAG(cid));
    case 2: return v;
    case 7: return LI(CID_TAG(cid), v);
    default: return C1(CID_TAG(cid), v);
  }
}

// The CID of a constructor value (a node's or a nullary one's).
static inline u64 term_aux(Term t) { return (t & 1) ? ((t & 2) ? ((7u << 16) | (u32)((t & 0xffff) >> 3)) : ((1u << 16) | (u32)(t >> 3))) : (V)(uint32_t)((V *)t)[0] & ~BEND_SH_BITS; }
#define term_drop(e, t) ((void)(e), bend_drop(t))
#define term_sink(e, t) ((void)(e), bend_drop(t))
#define cls_fit(n) 0
#define spare_free(e, c, x) ((void)(e), (void)(c), (void)(x))
#define f32_unbox(t) FV(t)
static inline int ctr_take(Env e, Term t, u32 n, Term *fb) {
  (void)e;
  for (u32 i = 0; i < n; i++) fb[i] = FLD(t, i);
  return 0;
}

struct IoWork;
typedef void (*IoCall)(struct IoWork *w);
typedef Term (*IoPack)(Env e, struct IoWork *w);

typedef struct IoWork {
  intptr_t hand;
  intptr_t made;
  u32 word;
  u64 size;
  char *data;
  char *text;
  u32 code;
  u64 time;
  IoCall call;
  IoPack pack;
} IoWork;

typedef Term (*Effect)(Env e, Term *f, IoWork *w);

typedef struct {
  Effect run;
  u32 ask;
} IoEff;

extern IoEff io_eff_rows[1 << 16];
extern u32 io_live;
extern int io_argc;
extern char **io_argv;

void io_eff(u32 cid, Effect run, u32 need);

u64 io_tick(void);

OUTLINE void *io_mem(void *mem);

int io_sys_addr(const char *host, u32 port, struct sockaddr_in *at);

u64 io_sys_end(IoWork *w, ssize_t n);

// One computation: cont applied to item is its next request. Leading work
// permits IoWork* to IoAct* casts. Every live act is on a list the collector
// reads.
typedef struct IoAct {
  IoWork work;
  Term cont;
  Term item;
  short evts;
  struct IoAct *next;
  struct IoAct *gprev, *gnext;
} IoAct;

typedef struct {
  IoAct *head;
  IoAct *last;
} IoQue;

extern IoQue io_runs;
extern IoQue io_park;
extern IoQue io_jobs;
extern IoAct *io_acts;

void io_push(IoQue *q, IoAct *a);

IoAct *io_pop(IoQue *q);

IoAct *io_act_new(void);

void io_act_free(IoAct *a);

V io_start_fn(V *a);
V io_emit_fn(V *a);

// Starts m (an IO) as a new computation.
void io_spawn(Term m);

// Parks until evts (POLLIN/POLLOUT; 0 ignores fd) or time (0: no deadline).
// The loop calls more: a value resumes, IO_PARK re-parks.
Term io_wait_on(IoWork *w, int fd, short evts, u64 time, IoPack more);

u64 io_wait_time(IoWork *w);

OUTLINE void io_out(FILE *h, const char *data, u64 len);

OUTLINE void io_sync(void);

u64 io_utf8(char *buf, u64 c);

// (Counted, the string is dropped once read, as are io_cbuf's bytes.)
OUTLINE char *io_cstr(Env e, Term s, u64 *len);

// A List of bytes (0..255) as they are, with no UTF-8: NULL if a value is
// past 255. (Strings go through io_cstr: a String's cons and a List's have
// one id here, so cons says nothing.)
OUTLINE char *io_cbuf(Env e, Term s, u64 *len, u64 cons);

OUTLINE void io_errs(Env e, Term s);

#define io_nul(s, n) (strlen(s) != (n))

Term io_box(Env e, u64 cid, Term v);

Term io_node(Env e, u64 cid, Term a, Term b);

// Decodes UTF-8 as WHATWG does: a byte that breaks a sequence yields one
// U+FFFD and is read again as a lead.
Term io_str(Env e, const char *p, u64 n);

// Bytes cross as they are (0..255), one List cell each (Con, tag 1, on
// Nil), with no UTF-8.
Term io_list(Env e, const char *p, u64 n);

#define io_tup(e, a, b) io_node(e, CID_TUPLE, a, b)
#define io_done(e, v) io_box(e, CID_DONE, v)

Term io_fail(Env e, u32 code, const char *text);

extern pthread_mutex_t io_gate;
extern pthread_cond_t io_bell;
extern u32 io_busy;
extern u32 io_size;
extern int io_wake_fd[2];

void io_take(Env e);

void *io_help(void *arg);

// Runs call on a helper thread, then pack on the loop to resume the effect.
Term io_work(IoWork *w, IoCall call, IoPack pack);

// Takes cont's request node apart; the effect returns a value or IO_PARK.
Term io_exec(Env e, IoWork *w);

// macOS poll misses FIFO EOF, so the loop waits with select.
bool io_bit(u8 *set, int fd, bool put);

void io_wait(Env e);

// Runs a computation up to its next park; returns an exit code on a Halt.
int io_step(Env e, IoAct *a);

// Chan
// ----

typedef struct {
  u32 gen;
  u32 next;
  u32 room;
  u32 size;
  u32 head;
  u32 live;
  u32 shut;
  Term *ring;
  IoQue wait;
} ChanRow;

extern ChanRow *chan_rows;
extern u32 chan_len;
extern u32 chan_idle;

#define chan_some(e, v) io_box(e, CID_SOME, v)
#define chan_bool(b) term_pak((b) ? CID_TRUE : CID_FALSE, 0)

Term chan_open(u32 room);

ChanRow *chan_at(Term t);

// Parks the effect's activation on row with item: a sent value, or
// TERM_HOLE for a receiver.
Term chan_park(ChanRow *row, IoWork *w, Term item);

Term chan_wake(ChanRow *row, Term x);

Term chan_take(ChanRow *row);

void chan_free(ChanRow *row);

void chan_shut(Env e, ChanRow *row);

void io_hook(void);

int io_loop(Term m);

// Value printing (for a main that is not IO), in Bend syntax
// ==========================================================

void pr_s(const char *s);
void pr_u32(V v);
void pr_nat(V v);
void pr_f32(V v);
// As the official term_show spells a character.
void pr_cp(uint32_t cp, char quote);
void pr_char(V v);
void pr_str(V v);

// Entry points
// ============

extern V (*bend_main_fn)(void);
extern void (*bend_print_fn)(V);
extern int bend_exit;

void *bend_thread(void *arg);

extern int bend_gpu;
// --gpu SIZE: the device arena's first size in MB (0: the default), so a
// call that needs it does not first fill a smaller one.
extern long bend_gpu_mb;

extern const char *CLI_HELP;

void cli_fail(const char *msg);

int bend_start(int argc, char **argv, V (*m)(void), int value);

int bend_run_value(int argc, char **argv, V (*m)(void), void (*p)(V));

int bend_run(int argc, char **argv, V (*m)(void));

#endif

// The runtime was built with these ids of Base's types.
_Static_assert(CID_TUPLE == 0u && CID_DONE == 1u && CID_FAIL == 0u && CID_SOME == 1u &&
  CID_NONE == ((1u << 16) | 0u) && CID_TRUE == ((1u << 16) | 1u) && CID_FALSE == ((1u << 16) | 0u) &&
  CID_UNIT == ((1u << 16) | 0u), "Base's constructor ids differ from the runtime's: build without -DBEND_RT_SPLIT");
