// bendrt.h: runtime for C code generated by bendc (the Bend compiler written in Bend).
//
// Values are 64-bit words:
//  - numbers (U32, Char, F32 bits, Nat) are stored raw;
//  - nullary constructors are IMM(tag) = (tag << 3) | 1;
//  - other constructors are pointers to heap nodes {tag, fields...};
//  - closures are pointers to {fn, arity, nargs, args...}.
// A type with one constructor of one field is represented by that field.
// Memory comes from a bump arena that is never freed.

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <pthread.h>
#include <unistd.h>
#include <fcntl.h>
#include <time.h>
#include <sys/mman.h>
#include <sys/stat.h>

typedef uint64_t V;
typedef V (*Fn)(V *);

#define IMM(t) ((((V)(t)) << 3) | 1)
#define FLD(v, i) (((V *)(v))[(i) + 1])
#define BOOL(b) ((b) ? IMM(1) : IMM(0))
#define UNIT IMM(0)

static inline V TAG(V v) { return (v & 1) ? (v >> 3) : ((V *)v)[0]; }

// Heap
// ----

static char *heap_ptr;
static char *heap_end;

static void heap_init(void) {
  size_t size = (size_t)1 << 36;
  void *p = mmap(NULL, size, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANON | MAP_NORESERVE, -1, 0);
  if (p == MAP_FAILED) { perror("mmap"); exit(1); }
  heap_ptr = (char *)p;
  heap_end = heap_ptr + size;
}

static inline V *halloc(size_t words) {
  V *p = (V *)heap_ptr;
  heap_ptr += words * sizeof(V);
  if (__builtin_expect(heap_ptr > heap_end, 0)) { fputs("bend: out of memory\n", stderr); exit(1); }
  return p;
}

static inline V C1(V t, V a) { V *p = halloc(2); p[0] = t; p[1] = a; return (V)p; }
static inline V C2(V t, V a, V b) { V *p = halloc(3); p[0] = t; p[1] = a; p[2] = b; return (V)p; }
static inline V C3(V t, V a, V b, V c) { V *p = halloc(4); p[0] = t; p[1] = a; p[2] = b; p[3] = c; return (V)p; }
static inline V C4(V t, V a, V b, V c, V d) {
  V *p = halloc(5); p[0] = t; p[1] = a; p[2] = b; p[3] = c; p[4] = d; return (V)p;
}
static inline V CN(V t, int n, const V *xs) {
  V *p = halloc(n + 1); p[0] = t;
  for (int i = 0; i < n; i++) p[i + 1] = xs[i];
  return (V)p;
}

// Closures
// --------

static inline V mk_clo(Fn f, V arity, V n, const V *args) {
  V *p = halloc(3 + n);
  p[0] = (V)f; p[1] = arity; p[2] = n;
  for (V i = 0; i < n; i++) p[3 + i] = args[i];
  return (V)p;
}

static V apply(V f, V x) {
  V *c = (V *)f;
  V ar = c[1], n = c[2];
  if (n + 1 == ar) {
    V a[n + 1];
    for (V i = 0; i < n; i++) a[i] = c[3 + i];
    a[n] = x;
    return ((Fn)c[0])(a);
  }
  V *p = halloc(4 + n);
  p[0] = c[0]; p[1] = ar; p[2] = n + 1;
  for (V i = 0; i < n; i++) p[3 + i] = c[3 + i];
  p[3 + n] = x;
  return (V)p;
}

__attribute__((noreturn)) static void bend_fail(const char *msg) {
  fprintf(stderr, "bend: %s\n", msg);
  exit(1);
}

// Strings (cons lists of code points)
// -----------------------------------

#define SNIL IMM(0)
#define SCONS(h, t) C2(1, (h), (t))
#define NIL IMM(0)
#define CONS(h, t) C2(1, (h), (t))

// Builds a String from UTF-8 bytes.
static V mk_str(const char *s, size_t n) {
  V cps[n + 1];
  size_t k = 0;
  for (size_t i = 0; i < n;) {
    unsigned char c = (unsigned char)s[i];
    uint32_t cp; int len;
    if (c < 0x80) { cp = c; len = 1; }
    else if ((c >> 5) == 6 && i + 1 < n) { cp = c & 0x1f; len = 2; }
    else if ((c >> 4) == 14 && i + 2 < n) { cp = c & 0x0f; len = 3; }
    else if ((c >> 3) == 30 && i + 3 < n) { cp = c & 0x07; len = 4; }
    else { cp = c; len = 1; }
    for (int j = 1; j < len; j++) cp = (cp << 6) | ((unsigned char)s[i + j] & 0x3f);
    cps[k++] = cp;
    i += len;
  }
  V r = SNIL;
  while (k > 0) { k--; r = SCONS(cps[k], r); }
  return r;
}

#define MKS(lit) mk_str(lit, sizeof(lit) - 1)

// Builds a String from a large buffer without a big stack array.
static V mk_str_heap(const char *s, size_t n) {
  V r = SNIL;
  V *tail = &r;
  for (size_t i = 0; i < n;) {
    unsigned char c = (unsigned char)s[i];
    uint32_t cp; int len;
    if (c < 0x80) { cp = c; len = 1; }
    else if ((c >> 5) == 6 && i + 1 < n) { cp = c & 0x1f; len = 2; }
    else if ((c >> 4) == 14 && i + 2 < n) { cp = c & 0x0f; len = 3; }
    else if ((c >> 3) == 30 && i + 3 < n) { cp = c & 0x07; len = 4; }
    else { cp = c; len = 1; }
    for (int j = 1; j < len; j++) cp = (cp << 6) | ((unsigned char)s[i + j] & 0x3f);
    V cell = SCONS(cp, SNIL);
    *tail = cell;
    tail = &FLD(cell, 1);
    i += len;
  }
  return r;
}

// Encodes a String as a malloc'd UTF-8 buffer.
static char *str_to_c(V s, size_t *len) {
  size_t cap = 64, n = 0;
  char *buf = malloc(cap);
  while (TAG(s) == 1) {
    uint32_t cp = (uint32_t)FLD(s, 0);
    if (n + 5 > cap) { cap *= 2; buf = realloc(buf, cap); }
    if (cp < 0x80) buf[n++] = (char)cp;
    else if (cp < 0x800) { buf[n++] = 0xc0 | (cp >> 6); buf[n++] = 0x80 | (cp & 0x3f); }
    else if (cp < 0x10000) {
      buf[n++] = 0xe0 | (cp >> 12); buf[n++] = 0x80 | ((cp >> 6) & 0x3f); buf[n++] = 0x80 | (cp & 0x3f);
    } else {
      buf[n++] = 0xf0 | (cp >> 18); buf[n++] = 0x80 | ((cp >> 12) & 0x3f);
      buf[n++] = 0x80 | ((cp >> 6) & 0x3f); buf[n++] = 0x80 | (cp & 0x3f);
    }
    s = FLD(s, 1);
  }
  buf[n] = 0;
  if (len) *len = n;
  return buf;
}

// Natives: U32
// ------------

#define U(x) ((uint32_t)(x))
static inline V F_U32_dinc(V a) { return U(a + 1); }
static inline V F_U32_dadd(V a, V b) { return U(a + b); }
static inline V F_U32_dsub(V a, V b) { return U(a - b); }
static inline V F_U32_dmul(V a, V b) { return U(U(a) * U(b)); }
static inline V F_U32_ddiv(V a, V b) { return b == 0 ? 0 : U(a) / U(b); }
static inline V F_U32_dmod(V a, V b) { return b == 0 ? a : U(a) % U(b); }
static inline V F_U32_dnot(V a) { return U(~a); }
static inline V F_U32_dand(V a, V b) { return a & b; }
static inline V F_U32_dor(V a, V b) { return a | b; }
static inline V F_U32_dxor(V a, V b) { return a ^ b; }
static inline V F_U32_dshl(V a) { return U(a << 1); }
static inline V F_U32_dshr(V a) { return a >> 1; }
static inline V F_U32_dshln(V a, V n) { return n >= 32 ? 0 : U(a << n); }
static inline V F_U32_dshrn(V a, V n) { return n >= 32 ? 0 : a >> n; }
static inline V F_U32_dcmp(V a, V b) { return a < b ? IMM(0) : a == b ? IMM(1) : IMM(2); }
static inline V F_U32_dis__eq(V a, V b) { return BOOL(a == b); }
static inline V F_U32_dis__ne(V a, V b) { return BOOL(a != b); }
static inline V F_U32_dis__lt(V a, V b) { return BOOL(a < b); }
static inline V F_U32_dis__le(V a, V b) { return BOOL(a <= b); }
static inline V F_U32_dis__gt(V a, V b) { return BOOL(a > b); }
static inline V F_U32_dis__ge(V a, V b) { return BOOL(a >= b); }
static inline V F_U32_dis__zero(V a) { return BOOL(a == 0); }
static inline V F_U32_dis__even(V a) { return BOOL((a & 1) == 0); }
static inline V F_U32_dto__nat(V a) { return a; }
static inline V F_U32_dfrom__nat(V n) { return U(n); }
static inline V F_U32_dmin(V a, V b) { return a < b ? a : b; }
static inline V F_U32_dmax(V a, V b) { return a < b ? b : a; }
static inline V F_U32_dpow(V a, V n) {
  uint32_t r = 1;
  for (V i = 0; i < n; i++) r *= U(a);
  return r;
}
static inline V F_U32_dlog2(V n) {
  V d = 0;
  while (n > 1) { d++; n >>= 1; }
  return d;
}

// Natives: Nat (u64)
// ------------------

static inline V F_Nat_ddouble(V a) { return a * 2; }
static inline V F_Nat_dadd(V a, V b) { return a + b; }
static inline V F_Nat_dsub(V a, V b) { return a > b ? a - b : 0; }
static inline V F_Nat_dmul(V a, V b) { return a * b; }
static inline V F_Nat_ddivmod(V a, V b) { return b == 0 ? C2(0, 0, a) : C2(0, a / b, a % b); }
static inline V F_Nat_ddiv(V a, V b) { return b == 0 ? 0 : a / b; }
static inline V F_Nat_dmod(V a, V b) { return b == 0 ? a : a % b; }
static inline V F_Nat_dcmp(V a, V b) { return a < b ? IMM(0) : a == b ? IMM(1) : IMM(2); }
static inline V F_Nat_dis__eq(V a, V b) { return BOOL(a == b); }
static inline V F_Nat_dis__ne(V a, V b) { return BOOL(a != b); }
static inline V F_Nat_dis__lt(V a, V b) { return BOOL(a < b); }
static inline V F_Nat_dis__le(V a, V b) { return BOOL(a <= b); }
static inline V F_Nat_dis__gt(V a, V b) { return BOOL(a > b); }
static inline V F_Nat_dis__ge(V a, V b) { return BOOL(a >= b); }
static inline V F_Nat_dmin(V a, V b) { return a < b ? a : b; }
static inline V F_Nat_dmax(V a, V b) { return a < b ? b : a; }
static inline V F_Nat_dpow(V a, V n) {
  V r = 1;
  for (V i = 0; i < n; i++) r *= a;
  return r;
}

// Natives: F32 (stored as IEEE bits)
// ----------------------------------

static inline float FV(V v) { union { uint32_t u; float f; } x; x.u = U(v); return x.f; }
static inline V VF(float f) { union { uint32_t u; float f; } x; x.f = f; return x.u; }
#define F2(name, expr) static inline V F_F32_d##name(V a, V b) { float x = FV(a), y = FV(b); return expr; }
#define F1(name, expr) static inline V F_F32_d##name(V a) { float x = FV(a); return expr; }
F2(add, VF(x + y))
F2(sub, VF(x - y))
F2(mul, VF(x * y))
F2(div, VF(x / y))
F2(mod, VF(fmodf(x, y)))
F2(pow, VF(powf(x, y)))
F2(atan2, VF(atan2f(x, y)))
F2(is__eq, BOOL(x == y))
F2(is__ne, BOOL(x != y))
F2(is__lt, BOOL(x < y))
F2(is__le, BOOL(x <= y))
F2(is__gt, BOOL(x > y))
F2(is__ge, BOOL(x >= y))
F1(neg, VF(-x))
F1(abs, VF(fabsf(x)))
F1(sqrt, VF(sqrtf(x)))
F1(exp, VF(expf(x)))
F1(log, VF(logf(x)))
F1(log2, VF(log2f(x)))
F1(log10, VF(log10f(x)))
F1(sin, VF(sinf(x)))
F1(cos, VF(cosf(x)))
F1(tan, VF(tanf(x)))
F1(asin, VF(asinf(x)))
F1(acos, VF(acosf(x)))
F1(atan, VF(atanf(x)))
F1(sinh, VF(sinhf(x)))
F1(cosh, VF(coshf(x)))
F1(tanh, VF(tanhf(x)))
F1(floor, VF(floorf(x)))
F1(ceil, VF(ceilf(x)))
F1(trunc, VF(truncf(x)))
static inline V F_F32_dbits(V a) { return U(a); }
static inline V F_F32_dto__u32(V a) { float x = FV(a); return x <= 0 ? 0 : x >= 4294967295.0f ? 0xffffffffu : (uint32_t)x; }
static inline V F_U32_dto__f32(V a) { return VF((float)U(a)); }
static V F_F32_dshow(V a) {
  char buf[64];
  snprintf(buf, sizeof buf, "%g", FV(a));
  return mk_str(buf, strlen(buf));
}
static V F_F32_dread(V s) {
  char *c = str_to_c(s, NULL);
  char *end;
  float f = strtof(c, &end);
  int ok = *c && !*end;
  free(c);
  return ok ? C1(1, VF(f)) : IMM(0);
}

// Host effects
// ------------
// Results follow Base: Result = Fail{error} (tag 0) | Done{value} (tag 1);
// errors are (U32 & String); a pair is Tuple{fst, snd} (tag 0).

static int bend_argc;
static char **bend_argv;

static V ok(V x) { return C1(1, x); }
static V fail(uint32_t code, const char *msg) { return C1(0, C2(0, code, mk_str(msg, strlen(msg)))); }

static void out_str(FILE *f, V s, int nl) {
  size_t n;
  char *c = str_to_c(s, &n);
  fwrite(c, 1, n, f);
  if (nl) fputc('\n', f);
  free(c);
}

static V H_io_print(V s) { out_str(stdout, s, 1); return UNIT; }
static V H_io_write(V s) { out_str(stdout, s, 0); fflush(stdout); return UNIT; }
static V H_io_print_err(V s) { fflush(stdout); out_str(stderr, s, 1); return UNIT; }

static V H_io_args(void) {
  V r = NIL;
  for (int i = bend_argc - 1; i >= 1; i--) r = CONS(mk_str(bend_argv[i], strlen(bend_argv[i])), r);
  return r;
}

static V H_io_get_env(V name) {
  char *c = str_to_c(name, NULL);
  char *v = getenv(c);
  free(c);
  if (!v) return fail(1, "unset variable");
  return ok(mk_str(v, strlen(v)));
}

static V H_io_now(void) {
  struct timespec ts;
  clock_gettime(CLOCK_MONOTONIC, &ts);
  return (V)ts.tv_sec * 1000 + ts.tv_nsec / 1000000;
}

static V H_io_sleep(V ms) { usleep((useconds_t)ms * 1000); return UNIT; }

static V H_io_random_u32(void) { return ok(U(arc4random())); }

static V H_file_open(V path, V mode) {
  char *p = str_to_c(path, NULL), *m = str_to_c(mode, NULL);
  int flags = O_RDONLY;
  if (m[0] == 'w') flags = O_WRONLY | O_CREAT | O_TRUNC;
  if (m[0] == 'a') flags = O_WRONLY | O_CREAT | O_APPEND;
  if (m[0] == 'r' && m[1] == '+') flags = O_RDWR;
  int fd = open(p, flags, 0644);
  free(p); free(m);
  if (fd < 0) return fail(2, "cannot open file");
  return ok((V)fd);
}

static V H_file_read(V file, V max) {
  size_t cap = 1 << 16, n = 0;
  char *buf = malloc(cap);
  while (n < max) {
    if (n == cap) { cap *= 2; buf = realloc(buf, cap); }
    size_t want = cap - n;
    if (want > max - n) want = max - n;
    ssize_t r = read((int)file, buf + n, want);
    if (r < 0) { free(buf); return C2(0, file, fail(3, "read error")); }
    if (r == 0) break;
    n += (size_t)r;
  }
  V s = mk_str_heap(buf, n);
  free(buf);
  return C2(0, file, ok(s));
}

static V H_file_write(V file, V data) {
  size_t n;
  char *c = str_to_c(data, &n);
  size_t off = 0;
  while (off < n) {
    ssize_t w = write((int)file, c + off, n - off);
    if (w <= 0) { free(c); return C2(0, file, fail(4, "write error")); }
    off += (size_t)w;
  }
  free(c);
  return C2(0, file, ok(UNIT));
}

static V H_file_size(V file) {
  struct stat st;
  if (fstat((int)file, &st) != 0) return C2(0, file, fail(5, "stat error"));
  return C2(0, file, ok(U(st.st_size)));
}

static V H_file_close(V file) { close((int)file); return UNIT; }

// Concurrency: a spawned computation runs to completion right away (a
// sequential scheduler); channels are unbounded FIFO queues.

static V k_emit(V *a);

typedef struct Chan { V *items; size_t head, len, cap; int closed; } Chan;

static V H_chan_new(V room) {
  (void)room;
  Chan *c = calloc(1, sizeof(Chan));
  return (V)c;
}

static V H_chan_send(V chan, V value) {
  Chan *c = (Chan *)chan;
  if (c->closed) return BOOL(0);
  if (c->head + c->len == c->cap) {
    c->cap = c->cap ? c->cap * 2 : 4;
    c->items = realloc(c->items, c->cap * sizeof(V));
  }
  c->items[c->head + c->len++] = value;
  return BOOL(1);
}

static V H_chan_recv(V chan) {
  Chan *c = (Chan *)chan;
  if (c->len == 0) return IMM(0);
  V v = c->items[c->head++];
  c->len--;
  return C1(1, v);
}

static V H_chan_close(V chan) { ((Chan *)chan)->closed = 1; return UNIT; }

static V H_io_spawn(V act) {
  V r = apply(apply(act, 0), mk_clo(k_emit, 1, 0, NULL));
  if (TAG(r) == 1) {
    fflush(stdout);
    out_str(stderr, FLD(r, 1), 1);
    exit((int)FLD(r, 0));
  }
  return UNIT;
}

// Entry point
// -----------
// main() returns an IO: a function R => k => IO.OP. It is run with the
// continuation Emit (tag 0); Halt{code, message} (tag 1) aborts.

// Value printing (for a main that is not IO), in Bend syntax.

static void pr_s(const char *s) { fputs(s, stdout); }
static void pr_u32(V v) { printf("%u", U(v)); }
static void pr_nat(V v) { printf("%llun", (unsigned long long)v); }
static void pr_f32(V v) {
  float f = FV(v);
  char buf[64];
  for (int p = 1; p <= 9; p++) {
    snprintf(buf, sizeof buf, "%.*g", p, f);
    if (strtof(buf, NULL) == f) break;
  }
  fputs(buf, stdout);
  if (!strpbrk(buf, ".eEna")) fputs(".0", stdout);
}
static void pr_cp(uint32_t cp, char quote) {
  switch (cp) {
    case '\n': pr_s("\\n"); return;
    case '\t': pr_s("\\t"); return;
    case '\r': pr_s("\\r"); return;
    case '\\': pr_s("\\\\"); return;
  }
  if (cp == (uint32_t)quote) { putchar('\\'); putchar(quote); return; }
  V s = SCONS(cp, SNIL);
  out_str(stdout, s, 0);
}
static void pr_char(V v) { putchar('\''); pr_cp(U(v), '\''); putchar('\''); }
static void pr_str(V v) {
  putchar('"');
  while (TAG(v) == 1) { pr_cp(U(FLD(v, 0)), '"'); v = FLD(v, 1); }
  putchar('"');
}

static V (*bend_main_fn)(void);
static void (*bend_print_fn)(V);
static int bend_exit;

static V k_emit(V *a) { return C1(0, a[0]); }

static void *bend_thread(void *arg) {
  (void)arg;
  V io = bend_main_fn();
  V r = apply(apply(io, 0), mk_clo(k_emit, 1, 0, NULL));
  fflush(stdout);
  if (TAG(r) == 1) {
    out_str(stderr, FLD(r, 1), 1);
    bend_exit = (int)FLD(r, 0);
  }
  return NULL;
}

static void *bend_thread_value(void *arg) {
  (void)arg;
  bend_print_fn(bend_main_fn());
  putchar('\n');
  fflush(stdout);
  return NULL;
}

static int bend_start(int argc, char **argv, V (*m)(void), void *(*body)(void *)) {
  bend_argc = argc;
  bend_argv = argv;
  bend_main_fn = m;
  heap_init();
  pthread_attr_t attr;
  pthread_attr_init(&attr);
  pthread_attr_setstacksize(&attr, (size_t)1 << 32);
  pthread_t th;
  if (pthread_create(&th, &attr, body, NULL) != 0) { perror("pthread_create"); return 1; }
  pthread_join(th, NULL);
  fflush(stdout);
  return bend_exit;
}

static int bend_run_value(int argc, char **argv, V (*m)(void), void (*p)(V)) {
  bend_print_fn = p;
  return bend_start(argc, argv, m, bend_thread_value);
}

static int bend_run(int argc, char **argv, V (*m)(void)) {
  return bend_start(argc, argv, m, bend_thread);
}
