// bendrt.h: runtime for C code generated by bendc (the Bend compiler written in Bend).
//
// Values are 64-bit words:
//  - numbers (U32, Char, F32 bits) are stored raw;
//  - a Nat below 2^63 is stored raw; a larger one is (1 << 63) | pointer to
//    a bignum {limb count, limbs...};
//  - nullary constructors are IMM(tag) = (tag << 3) | 1;
//  - other constructors are pointers to heap nodes {tag, fields...};
//  - closures are pointers to {fn, arity, nargs, args...}.
// A type with one constructor of one field is represented by that field.
//
// Memory is managed by a conservative, non-moving mark-sweep collector. The
// threads that run Bend code (the main thread and the fork-join workers) are
// stopped with a signal while it runs. Parallel lets fork onto a
// work-stealing pool. Effects follow the official Bend runtime's effect ABI
// (Term, Env, IoWork, io_eff, CID_*), so effect sources written for the
// official compiler (Base's own effs/*.c included) compile unchanged.

#ifndef BENDRT_H
#define BENDRT_H

#ifdef __linux__
#define _GNU_SOURCE
#endif
#include <stdint.h>
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
#include <pthread.h>
#include <unistd.h>
#include <fcntl.h>
#include <time.h>
#include <errno.h>
#include <setjmp.h>
#include <signal.h>
#include <sched.h>
#include <poll.h>
#include <stdatomic.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/time.h>
#include <sys/select.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <arpa/inet.h>

typedef uint64_t V;
typedef V (*Fn)(V *);
typedef uint64_t u64;
typedef uint32_t u32;
typedef uint16_t u16;
typedef uint8_t u8;
typedef int64_t i64;
typedef int32_t i32;
typedef uint32_t U32;
typedef uint64_t Term;

#define IMM(t) ((((V)(t)) << 3) | 1)
#define FLD(v, i) (((V *)(v))[(i) + 1])
#define BOOL(b) ((b) ? IMM(1) : IMM(0))
#define UNIT IMM(0)
#define LIKELY(x) __builtin_expect(!!(x), 1)
#define UNLIKELY(x) __builtin_expect(!!(x), 0)

static inline V TAG(V v) { return (v & 1) ? (v >> 3) : ((V *)v)[0]; }

__attribute__((noreturn)) static void bend_fail(const char *msg) {
  fflush(stdout);
  fprintf(stderr, "bend: %s\n", msg);
  exit(1);
}

// Garbage collector
// =================
//
// The heap is one reserved region cut into 64 KB blocks. A small block holds
// slots of one size class; a large object takes whole blocks. Each block
// starts with a header holding an allocation and a mark bitmap. Every word
// of a live object, of a thread's stack and of the registered roots is read
// as a possible pointer; pointers into the middle of an object keep it too.
// A thread allocates from a private free list; the block behind that list
// is not swept until the thread moves on to another one.

#define GC_BLK_SHIFT 16
#define GC_BLK ((uintptr_t)1 << GC_BLK_SHIFT)
#define GC_MAXBLK ((uintptr_t)1 << 22)
#define GC_HDR 1056
#define GC_SMALL 256
#define GC_NCLS 31
#define GC_MAXTHR 256
#define GC_SIG SIGUSR2

typedef struct GcBlk {
  uint32_t words;    // slot size (small) or object size (large), in words
  uint32_t nobj;     // slots in the block (1 for a large object)
  uint32_t nblk;     // blocks spanned
  uint8_t atomic;    // holds no pointers: never scanned
  uint8_t large;
  uint8_t owned;     // behind a thread's free list: not swept
  uint8_t cls;
  struct GcBlk *next;
  uint64_t alloc[64];
  uint64_t mark[64];
} GcBlk;

typedef struct GcCache { V *free; V *bump; V *end; GcBlk *blk; uint32_t idx; } GcCache;

struct PDeque;

typedef struct Thr {
  GcCache cache[2][GC_NCLS];
  uintptr_t top;
  volatile uintptr_t sp;
  pthread_t id;
  volatile int live;
  struct PDeque *dq;
  uint32_t rng;
} Thr;

typedef struct { V *p; size_t n; } GcRange;
typedef struct { uint32_t at, len; } GcRun;

static const uint16_t gc_cls_w[GC_NCLS] = {
  2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,
  20, 24, 28, 32, 40, 48, 56, 64, 80, 96, 112, 128, 160, 192, 224, 256};
static uint8_t gc_cls_of[GC_SMALL + 1];

static char *gc_base;
static uintptr_t gc_top;                // blocks in use (high-water mark)
static uint8_t *gc_kind;                // per block: 0 free, 1 small, 2 large head, 3 large tail
static uint32_t *gc_back;               // large tail: distance back to its head
static GcRun *gc_runs;                  // free block runs below gc_top
static size_t gc_nruns;
static pthread_mutex_t gc_lock = PTHREAD_MUTEX_INITIALIZER;
static GcBlk *gc_partial[2][GC_NCLS];
static _Atomic size_t gc_since;         // bytes handed out since the last collection
static size_t gc_limit = (size_t)256 << 20;
static size_t gc_limit_min = (size_t)256 << 20;
static size_t gc_live_bytes;
static size_t gc_major_live;
static int gc_minor;       // this collection keeps the marks of old objects
static int gc_rooting;     // marking from roots (not from objects)
static int gc_all_major;   // BEND_GC_MAJOR: every collection is a major one
static size_t gc_count;
static int gc_stats;
static Thr *gc_thrs[GC_MAXTHR];
static int gc_nthr;
static GcRange *gc_roots;
static size_t gc_nroots, gc_caproots;
static void (*gc_hooks[16])(void);
static int gc_nhooks;
static _Atomic int gc_stopping, gc_acks, gc_inside;
static __thread Thr *thr_self;

typedef struct { V *p; size_t n; } GcItem;
static GcItem *gc_stk;
static size_t gc_sp, gc_cap;

static void *gc_reserve(size_t bytes, void *hint) {
  void *p = mmap(hint, bytes, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANON | MAP_NORESERVE, -1, 0);
  if (p == MAP_FAILED) { perror("bend: mmap"); exit(1); }
  return p;
}

static void gc_init(void) {
  // A high address keeps small numbers from looking like heap pointers.
  gc_base = gc_reserve(GC_MAXBLK << GC_BLK_SHIFT, (void *)((uintptr_t)1 << 44));
  gc_kind = gc_reserve(GC_MAXBLK, NULL);
  gc_back = gc_reserve(GC_MAXBLK * sizeof(uint32_t), NULL);
  gc_runs = gc_reserve(GC_MAXBLK / 2 * sizeof(GcRun) + 64, NULL);
  gc_cap = ((size_t)1 << 33) / sizeof(GcItem);
  gc_stk = gc_reserve(gc_cap * sizeof(GcItem), NULL);
  for (size_t w = 0, c = 0; w <= GC_SMALL; w++) {
    while (gc_cls_w[c] < w) c++;
    gc_cls_of[w] = (uint8_t)c;
  }
  const char *s = getenv("BEND_GC_STATS");
  gc_stats = s && *s;
  gc_all_major = getenv("BEND_GC_MAJOR") != NULL;
  const char *m = getenv("BEND_GC_MIN_MB");
  if (m && atol(m) > 0) gc_limit = gc_limit_min = (size_t)atol(m) << 20;
}

static inline GcBlk *gc_blk(uintptr_t i) { return (GcBlk *)(gc_base + (i << GC_BLK_SHIFT)); }
static inline V *gc_objs(GcBlk *b) { return (V *)((char *)b + GC_HDR); }

// Takes n contiguous free blocks (gc_lock held).
static uintptr_t gc_take_blocks(size_t n) {
  for (size_t i = 0; i < gc_nruns; i++) {
    if (gc_runs[i].len >= n) {
      uintptr_t at = gc_runs[i].at;
      gc_runs[i].at += (uint32_t)n;
      gc_runs[i].len -= (uint32_t)n;
      if (gc_runs[i].len == 0) gc_runs[i] = gc_runs[--gc_nruns];
      return at;
    }
  }
  if (gc_top + n > GC_MAXBLK) bend_fail("out of memory");
  uintptr_t at = gc_top;
  gc_top += n;
  return at;
}

static void gc_collect_locked(void);

static GcBlk *gc_new_small(int atomic, unsigned c) {
  uintptr_t at = gc_take_blocks(1);
  GcBlk *b = gc_blk(at);
  memset(b, 0, sizeof(GcBlk));
  b->words = gc_cls_w[c];
  b->nobj = (uint32_t)((GC_BLK - GC_HDR) / (b->words * 8));
  b->nblk = 1;
  b->atomic = (uint8_t)atomic;
  b->cls = (uint8_t)c;
  gc_kind[at] = 1;
  return b;
}

__attribute__((noinline)) static V *gc_refill(GcCache *k, int atomic, unsigned c) {
  pthread_mutex_lock(&gc_lock);
  if (k->blk) { k->blk->owned = 0; k->blk = NULL; }
  if (gc_since >= gc_limit) gc_collect_locked();
  GcBlk *b = gc_partial[atomic][c];
  int fresh = b == NULL;
  if (b) gc_partial[atomic][c] = b->next;
  else b = gc_new_small(atomic, c);
  b->owned = 1;
  k->blk = b;
  pthread_mutex_unlock(&gc_lock);
  // A slot's allocation bit is set when the slot is handed out, never
  // before: a stale pointer must not mark a slot that is still free.
  V *objs = gc_objs(b);
  size_t sw = b->words;
  if (fresh) {
    // A fresh block is handed out by bumping a pointer.
    atomic_fetch_add_explicit(&gc_since, (size_t)b->nobj * sw * sizeof(V), memory_order_relaxed);
    k->free = NULL;
    k->bump = objs + sw;
    k->end = objs + (size_t)b->nobj * sw;
    k->idx = 1;
    b->alloc[0] |= 1;
    return objs;
  }
  // Otherwise: a free list of the unallocated slots, each holding its index.
  V *head = NULL;
  size_t n = 0;
  for (int j = (int)((b->nobj + 63) >> 6) - 1; j >= 0; j--) {
    uint64_t freebits = ~b->alloc[j];
    if (j == (int)(b->nobj >> 6)) freebits &= (1ull << (b->nobj & 63)) - 1;
    while (freebits) {
      int t = 63 - __builtin_clzll(freebits);
      freebits &= ~(1ull << t);
      V *p = objs + (size_t)(j * 64 + t) * sw;
      p[0] = (V)head;
      p[1] = (V)(j * 64 + t);
      head = p;
      n++;
    }
  }
  atomic_fetch_add_explicit(&gc_since, n * sw * sizeof(V), memory_order_relaxed);
  k->bump = k->end = NULL;
  k->free = (V *)head[0];
  uint32_t i = (uint32_t)head[1];
  b->alloc[i >> 6] |= 1ull << (i & 63);
  return head;
}

__attribute__((noinline)) static V *gc_alloc_large(size_t w, int atomic) {
  size_t n = (GC_HDR + w * sizeof(V) + GC_BLK - 1) >> GC_BLK_SHIFT;
  pthread_mutex_lock(&gc_lock);
  if (gc_since >= gc_limit) gc_collect_locked();
  uintptr_t at = gc_take_blocks(n);
  GcBlk *b = gc_blk(at);
  memset(b, 0, sizeof(GcBlk));
  b->words = (uint32_t)w;
  b->nobj = 1;
  b->nblk = (uint32_t)n;
  b->atomic = (uint8_t)atomic;
  b->large = 1;
  b->alloc[0] = 1;
  gc_kind[at] = 2;
  for (size_t j = 1; j < n; j++) { gc_kind[at + j] = 3; gc_back[at + j] = (uint32_t)j; }
  atomic_fetch_add_explicit(&gc_since, n * GC_BLK, memory_order_relaxed);
  pthread_mutex_unlock(&gc_lock);
  V *p = gc_objs(b);
  memset(p, 0, w * sizeof(V));
  return p;
}

// A slot is not cleared when freed: the words of a class slot past the
// object's own are cleared here, so stale words never look like pointers.
static inline V *gc_alloc(size_t w, int atomic) {
  if (UNLIKELY(w > GC_SMALL)) return gc_alloc_large(w, atomic);
  unsigned c = gc_cls_of[w];
  GcCache *k = &thr_self->cache[atomic][c];
  V *p = k->free;
  if (p != NULL) {
    k->free = (V *)p[0];
    uint32_t i = (uint32_t)p[1];
    k->blk->alloc[i >> 6] |= 1ull << (i & 63);
  } else if (k->bump < k->end) {
    p = k->bump;
    k->bump += gc_cls_w[c];
    uint32_t i = k->idx++;
    k->blk->alloc[i >> 6] |= 1ull << (i & 63);
  } else {
    p = gc_refill(k, atomic, c);
  }
  p[0] = 0;
  p[1] = 0;
  for (size_t j = w; j < gc_cls_w[c]; j++) p[j] = 0;
  return p;
}

static inline V *halloc(size_t words) { return gc_alloc(words, 0); }

// Registers words that hold values (a global cache, say) as roots.
static void gc_root_add_locked(V *p, size_t n) {
  if (gc_nroots == gc_caproots) {
    gc_caproots = gc_caproots ? gc_caproots * 2 : 256;
    gc_roots = realloc(gc_roots, gc_caproots * sizeof(GcRange));
  }
  gc_roots[gc_nroots++] = (GcRange){p, n};
}

static void gc_root_add(V *p, size_t n) {
  pthread_mutex_lock(&gc_lock);
  gc_root_add_locked(p, n);
  pthread_mutex_unlock(&gc_lock);
}

static void gc_hook(void (*f)(void)) { gc_hooks[gc_nhooks++] = f; }

static inline void gc_mark(V w) {
  uintptr_t a = (uintptr_t)(w & 0x7fffffffffffffffull);
  uintptr_t off = a - (uintptr_t)gc_base;
  if (off >= (gc_top << GC_BLK_SHIFT)) return;
  uintptr_t bi = off >> GC_BLK_SHIFT;
  uint8_t kd = gc_kind[bi];
  if (kd == 0) return;
  if (kd == 3) bi -= gc_back[bi];
  GcBlk *b = gc_blk(bi);
  uintptr_t o = (uintptr_t)gc_objs(b);
  if (a < o) return;
  size_t i = 0;
  if (b->large) {
    if (a >= o + (uintptr_t)b->words * sizeof(V)) return;
  } else {
    i = (a - o) / ((uintptr_t)b->words * sizeof(V));
    if (i >= b->nobj) return;
  }
  uint64_t bit = 1ull << (i & 63);
  if (!(b->alloc[i >> 6] & bit)) return;
  // A minor collection scans an old object met from a root once more: its
  // fields may have been written after it got old.
  if ((b->mark[i >> 6] & bit) && !(gc_minor && gc_rooting)) return;
  b->mark[i >> 6] |= bit;
  if (b->atomic) return;
  if (gc_sp == gc_cap) bend_fail("the collector's mark stack overflowed");
  gc_stk[gc_sp++] = (GcItem){(V *)(o + i * (uintptr_t)b->words * sizeof(V)), b->words};
}

static void gc_scan(const void *lo, const void *hi) {
  uintptr_t a = ((uintptr_t)lo + 7) & ~(uintptr_t)7;
  for (const V *p = (const V *)a; (const void *)p < hi; p++) gc_mark(*p);
}

static void gc_drain(void) {
  while (gc_sp > 0) {
    GcItem it = gc_stk[--gc_sp];
    for (size_t j = 0; j < it.n; j++) gc_mark(it.p[j]);
  }
}

static void gc_handler(int sig) {
  (void)sig;
  int saved = errno;
  Thr *t = thr_self;
  if (t != NULL && atomic_load(&gc_stopping)) {
    jmp_buf jb;
    setjmp(jb);
    atomic_fetch_add(&gc_inside, 1);
    t->sp = (uintptr_t)&jb;
    atomic_fetch_add(&gc_acks, 1);
    while (atomic_load(&gc_stopping)) sched_yield();
    atomic_fetch_sub(&gc_inside, 1);
  }
  errno = saved;
}

static void gc_sweep(void) {
  memset(gc_partial, 0, sizeof gc_partial);
  size_t live = 0;
  for (uintptr_t bi = 0; bi < gc_top; bi++) {
    uint8_t kd = gc_kind[bi];
    if (kd == 1) {
      GcBlk *b = gc_blk(bi);
      if (b->owned) {
        live += GC_BLK;
        continue;
      }
      // What survives stays marked: it is old for the next minor collection.
      size_t used = 0;
      int words = (int)((b->nobj + 63) >> 6);
      for (int j = 0; j < words; j++) {
        b->alloc[j] &= b->mark[j];
        used += (size_t)__builtin_popcountll(b->alloc[j]);
      }
      if (used == 0) {
        gc_kind[bi] = 0;
      } else {
        live += used * b->words * sizeof(V);
        if (used < b->nobj) {
          b->next = gc_partial[b->atomic][b->cls];
          gc_partial[b->atomic][b->cls] = b;
        }
      }
    } else if (kd == 2) {
      GcBlk *b = gc_blk(bi);
      if (b->mark[0] & 1) {
        live += (size_t)b->nblk * GC_BLK;
      } else {
        for (uint32_t j = 0; j < b->nblk; j++) gc_kind[bi + j] = 0;
      }
      bi += b->nblk - 1;
    }
  }
  // Free runs, rebuilt from the block kinds.
  while (gc_top > 0 && gc_kind[gc_top - 1] == 0) gc_top--;
  gc_nruns = 0;
  for (uintptr_t bi = 0; bi < gc_top;) {
    if (gc_kind[bi] != 0) { bi++; continue; }
    uintptr_t at = bi;
    while (bi < gc_top && gc_kind[bi] == 0) bi++;
    gc_runs[gc_nruns++] = (GcRun){(uint32_t)at, (uint32_t)(bi - at)};
    // Hand the pages of long runs back to the system when the heap is far
    // larger than what lives in it.
    if (bi - at >= 256 && ((gc_top - bi + at) << GC_BLK_SHIFT) > 4 * live + ((size_t)1 << 30))
      madvise(gc_base + (at << GC_BLK_SHIFT), (bi - at) << GC_BLK_SHIFT, MADV_DONTNEED);
  }
  gc_live_bytes = live;
}

__attribute__((noinline)) static void gc_collect_locked(void) {
  Thr *me = thr_self;
  struct timespec t0, t1;
  if (gc_stats) clock_gettime(CLOCK_MONOTONIC, &t0);
  atomic_store(&gc_acks, 0);
  atomic_store(&gc_stopping, 1);
  int n = 0;
  for (int i = 0; i < gc_nthr; i++) {
    Thr *t = gc_thrs[i];
    if (t != me && t->live) {
      if (pthread_kill(t->id, GC_SIG) == 0) n++;
    }
  }
  while (atomic_load(&gc_acks) < n) sched_yield();
  jmp_buf jb;
  setjmp(jb);
  me->sp = (uintptr_t)&jb;
  // A major collection forgets every mark; a minor one keeps the old
  // objects' (the heap is written only while an object is built, and the
  // exceptions are reached from roots).
  gc_minor = !gc_all_major && gc_major_live > 0 && gc_live_bytes < 2 * gc_major_live + ((size_t)64 << 20);
  if (!gc_minor) {
    for (uintptr_t bi = 0; bi < gc_top; bi++) {
      if (gc_kind[bi] == 1 || gc_kind[bi] == 2) memset(gc_blk(bi)->mark, 0, sizeof(gc_blk(bi)->mark));
    }
  }
  gc_rooting = 1;
  for (int i = 0; i < gc_nthr; i++) {
    Thr *t = gc_thrs[i];
    if (t->live) gc_scan((const void *)t->sp, (const void *)t->top);
  }
  for (size_t i = 0; i < gc_nroots; i++) gc_scan(gc_roots[i].p, gc_roots[i].p + gc_roots[i].n);
  for (int i = 0; i < gc_nhooks; i++) gc_hooks[i]();
  gc_rooting = 0;
  gc_drain();
  gc_sweep();
  atomic_store(&gc_stopping, 0);
  while (atomic_load(&gc_inside) > 0) sched_yield();
  if (!gc_minor) gc_major_live = gc_live_bytes ? gc_live_bytes : 1;
  gc_limit = gc_limit_min;
  gc_since = 0;
  gc_count++;
  if (gc_stats) {
    clock_gettime(CLOCK_MONOTONIC, &t1);
    fprintf(stderr, "[gc %zu %s] live %zu MB, heap %zu MB, next at +%zu MB, %.1f ms\n", gc_count,
      gc_minor ? "minor" : "major", gc_live_bytes >> 20, (size_t)(gc_top << GC_BLK_SHIFT) >> 20, gc_limit >> 20,
      (t1.tv_sec - t0.tv_sec) * 1e3 + (t1.tv_nsec - t0.tv_nsec) / 1e6);
  }
}

// Collects now (from a thread that runs Bend code).
static void gc_collect(void) {
  pthread_mutex_lock(&gc_lock);
  gc_collect_locked();
  pthread_mutex_unlock(&gc_lock);
}

static struct PDeque *pdq_new(void);

// Registers the calling thread; top is an address near the base of its stack.
static void thr_register(uintptr_t top) {
  Thr *t = calloc(1, sizeof(Thr));
  t->top = top;
  t->id = pthread_self();
  t->live = 1;
  t->rng = (uint32_t)(uintptr_t)t ^ 0x9e3779b9u;
  t->dq = pdq_new();
  thr_self = t;
  pthread_mutex_lock(&gc_lock);
  if (gc_nthr == GC_MAXTHR) bend_fail("too many threads");
  gc_thrs[gc_nthr] = t;
  __atomic_store_n(&gc_nthr, gc_nthr + 1, __ATOMIC_RELEASE);
  pthread_mutex_unlock(&gc_lock);
}

// Constructors and closures
// =========================

static inline V C1(V t, V a) { V *p = halloc(2); p[0] = t; p[1] = a; return (V)p; }
static inline V C2(V t, V a, V b) { V *p = halloc(3); p[0] = t; p[1] = a; p[2] = b; return (V)p; }
static inline V C3(V t, V a, V b, V c) { V *p = halloc(4); p[0] = t; p[1] = a; p[2] = b; p[3] = c; return (V)p; }
static inline V C4(V t, V a, V b, V c, V d) {
  V *p = halloc(5); p[0] = t; p[1] = a; p[2] = b; p[3] = c; p[4] = d; return (V)p;
}
static inline V CN(V t, int n, const V *xs) {
  V *p = halloc(n + 1); p[0] = t;
  for (int i = 0; i < n; i++) p[i + 1] = xs[i];
  return (V)p;
}

static inline V mk_clo(Fn f, V arity, V n, const V *args) {
  V *p = halloc(3 + n);
  p[0] = (V)f; p[1] = arity; p[2] = n;
  for (V i = 0; i < n; i++) p[3 + i] = args[i];
  return (V)p;
}

static V apply(V f, V x) {
  V *c = (V *)f;
  V ar = c[1], n = c[2];
  if (n + 1 == ar) {
    V a[n + 1];
    for (V i = 0; i < n; i++) a[i] = c[3 + i];
    a[n] = x;
    return ((Fn)c[0])(a);
  }
  V *p = halloc(4 + n);
  p[0] = c[0]; p[1] = ar; p[2] = n + 1;
  for (V i = 0; i < n; i++) p[3 + i] = c[3 + i];
  p[3 + n] = x;
  return (V)p;
}

// Strings (cons lists of code points)
// -----------------------------------

#define SNIL IMM(0)
#define SCONS(h, t) C2(1, (h), (t))
#define NIL IMM(0)
#define CONS(h, t) C2(1, (h), (t))

// Builds a String from UTF-8 bytes. Strings are built from the end, so no
// cell is written after it is made (minor collections rely on that).
static V mk_str(const char *s, size_t n) {
  uint32_t small[256];
  uint32_t *cps = n <= 256 ? small : malloc(n * sizeof(uint32_t));
  size_t k = 0;
  for (size_t i = 0; i < n;) {
    unsigned char c = (unsigned char)s[i];
    uint32_t cp; int len;
    if (c < 0x80) { cp = c; len = 1; }
    else if ((c >> 5) == 6 && i + 1 < n) { cp = c & 0x1f; len = 2; }
    else if ((c >> 4) == 14 && i + 2 < n) { cp = c & 0x0f; len = 3; }
    else if ((c >> 3) == 30 && i + 3 < n) { cp = c & 0x07; len = 4; }
    else { cp = c; len = 1; }
    for (int j = 1; j < len; j++) cp = (cp << 6) | ((unsigned char)s[i + j] & 0x3f);
    cps[k++] = cp;
    i += len;
  }
  V r = SNIL;
  while (k > 0) { k--; r = SCONS(cps[k], r); }
  if (cps != small) free(cps);
  return r;
}

#define MKS(lit) mk_str(lit, sizeof(lit) - 1)
#define STRC(c, lit) ((c) ? (c) : str_cache(&(c), lit, sizeof(lit) - 1))
#define mk_str_heap mk_str

// A string literal, built once (slot is its cache, a root).
__attribute__((noinline)) static V str_cache(V *slot, const char *s, size_t n) {
  V v = mk_str(s, n);
  pthread_mutex_lock(&gc_lock);
  if (*slot == 0) {
    __atomic_store_n(slot, v, __ATOMIC_RELEASE);
    gc_root_add_locked(slot, 1);
  }
  v = *slot;
  pthread_mutex_unlock(&gc_lock);
  return v;
}

// Encodes a String as a malloc'd UTF-8 buffer.
static char *str_to_c(V s, size_t *len) {
  size_t cap = 64, n = 0;
  char *buf = malloc(cap);
  while (TAG(s) == 1) {
    uint32_t cp = (uint32_t)FLD(s, 0);
    if (n + 5 > cap) { cap *= 2; buf = realloc(buf, cap); }
    if (cp < 0x80) buf[n++] = (char)cp;
    else if (cp < 0x800) { buf[n++] = 0xc0 | (cp >> 6); buf[n++] = 0x80 | (cp & 0x3f); }
    else if (cp < 0x10000) {
      buf[n++] = 0xe0 | (cp >> 12); buf[n++] = 0x80 | ((cp >> 6) & 0x3f); buf[n++] = 0x80 | (cp & 0x3f);
    } else {
      buf[n++] = 0xf0 | (cp >> 18); buf[n++] = 0x80 | ((cp >> 12) & 0x3f);
      buf[n++] = 0x80 | ((cp >> 6) & 0x3f); buf[n++] = 0x80 | (cp & 0x3f);
    }
    s = FLD(s, 1);
  }
  buf[n] = 0;
  if (len) *len = n;
  return buf;
}

// Natives: Nat (unbounded)
// ------------------------

#define NAT_BIG ((V)1 << 63)
static inline V *nat_p(V x) { return (V *)(uintptr_t)(x & ~NAT_BIG); }

// The limbs of x (little-endian); a small x is written to *buf.
static inline const V *nat_limbs(V x, V *buf, size_t *n) {
  if (x >> 63) { V *p = nat_p(x); *n = (size_t)p[0]; return p + 1; }
  *buf = x;
  *n = x ? 1 : 0;
  return buf;
}

// A Nat from n limbs (normalized; small when it fits).
static V nat_make(const V *d, size_t n) {
  while (n > 0 && d[n - 1] == 0) n--;
  if (n == 0) return 0;
  if (n == 1 && !(d[0] >> 63)) return d[0];
  V *p = gc_alloc(n + 1, 1);
  p[0] = n;
  memcpy(p + 1, d, n * sizeof(V));
  return (V)(uintptr_t)p | NAT_BIG;
}

static int nat_cmp3(V a, V b) {
  if (!((a | b) >> 63)) return a < b ? -1 : a > b;
  V ba, bb;
  size_t na, nb;
  const V *x = nat_limbs(a, &ba, &na), *y = nat_limbs(b, &bb, &nb);
  if (na != nb) return na < nb ? -1 : 1;
  for (size_t i = na; i-- > 0;) if (x[i] != y[i]) return x[i] < y[i] ? -1 : 1;
  return 0;
}

static V nat_add(V a, V b) {
  if (!((a | b) >> 63)) {
    V s = a + b;
    if (!(s >> 63)) return s;
    return nat_make(&s, 1);
  }
  V ba, bb;
  size_t na, nb;
  const V *x = nat_limbs(a, &ba, &na), *y = nat_limbs(b, &bb, &nb);
  if (na < nb) { const V *t = x; x = y; y = t; size_t u = na; na = nb; nb = u; }
  V *r = malloc((na + 1) * sizeof(V));
  unsigned __int128 c = 0;
  for (size_t i = 0; i < na; i++) {
    c += (unsigned __int128)x[i] + (i < nb ? y[i] : 0);
    r[i] = (V)c;
    c >>= 64;
  }
  r[na] = (V)c;
  V v = nat_make(r, na + 1);
  free(r);
  return v;
}

// a - b, or 0 when b >= a.
static V nat_sub(V a, V b) {
  if (!((a | b) >> 63)) return a > b ? a - b : 0;
  if (nat_cmp3(a, b) <= 0) return 0;
  V ba, bb;
  size_t na, nb;
  const V *x = nat_limbs(a, &ba, &na), *y = nat_limbs(b, &bb, &nb);
  V *r = malloc(na * sizeof(V));
  V borrow = 0;
  for (size_t i = 0; i < na; i++) {
    unsigned __int128 d = (unsigned __int128)x[i] - (i < nb ? y[i] : 0) - borrow;
    r[i] = (V)d;
    borrow = (V)(d >> 64) ? 1 : 0;
  }
  V v = nat_make(r, na);
  free(r);
  return v;
}

static V nat_mul(V a, V b) {
  if (!((a | b) >> 63)) {
    unsigned __int128 p = (unsigned __int128)a * b;
    if (!(p >> 63)) return (V)p;
    V d[2] = {(V)p, (V)(p >> 64)};
    return nat_make(d, 2);
  }
  V ba, bb;
  size_t na, nb;
  const V *x = nat_limbs(a, &ba, &na), *y = nat_limbs(b, &bb, &nb);
  if (na == 0 || nb == 0) return 0;
  V *r = calloc(na + nb, sizeof(V));
  for (size_t i = 0; i < na; i++) {
    unsigned __int128 c = 0;
    for (size_t j = 0; j < nb; j++) {
      c += (unsigned __int128)x[i] * y[j] + r[i + j];
      r[i + j] = (V)c;
      c >>= 64;
    }
    r[i + nb] = (V)c;
  }
  V v = nat_make(r, na + nb);
  free(r);
  return v;
}

// Divides u (m limbs) by v (n >= 2 limbs, m >= n): Knuth's algorithm D.
static void nat_divlimbs(const V *u, size_t m, const V *v, size_t n, V *q, V *r) {
  int s = __builtin_clzll(v[n - 1]);
  V *vn = malloc(n * sizeof(V)), *un = malloc((m + 1) * sizeof(V));
  for (size_t i = n - 1; i > 0; i--) vn[i] = (v[i] << s) | (s ? v[i - 1] >> (64 - s) : 0);
  vn[0] = v[0] << s;
  un[m] = s ? u[m - 1] >> (64 - s) : 0;
  for (size_t i = m - 1; i > 0; i--) un[i] = (u[i] << s) | (s ? u[i - 1] >> (64 - s) : 0);
  un[0] = u[0] << s;
  for (size_t jj = m - n + 1; jj-- > 0;) {
    size_t j = jj;
    unsigned __int128 num = ((unsigned __int128)un[j + n] << 64) | un[j + n - 1];
    unsigned __int128 qhat = num / vn[n - 1], rhat = num % vn[n - 1];
    while ((qhat >> 64) || qhat * vn[n - 2] > ((rhat << 64) | un[j + n - 2])) {
      qhat--;
      rhat += vn[n - 1];
      if (rhat >> 64) break;
    }
    V borrow = 0, carry = 0;
    for (size_t i = 0; i < n; i++) {
      unsigned __int128 p = qhat * vn[i] + carry;
      carry = (V)(p >> 64);
      unsigned __int128 d = (unsigned __int128)un[i + j] - (V)p - borrow;
      un[i + j] = (V)d;
      borrow = (V)(d >> 64) ? 1 : 0;
    }
    unsigned __int128 d = (unsigned __int128)un[j + n] - carry - borrow;
    un[j + n] = (V)d;
    if ((V)(d >> 64)) {
      qhat--;
      unsigned __int128 c = 0;
      for (size_t i = 0; i < n; i++) {
        c += (unsigned __int128)un[i + j] + vn[i];
        un[i + j] = (V)c;
        c >>= 64;
      }
      un[j + n] += (V)c;
    }
    q[j] = (V)qhat;
  }
  for (size_t i = 0; i < n; i++) r[i] = (un[i] >> s) | (s && i + 1 <= n ? (V)((unsigned __int128)un[i + 1] << (64 - s)) : 0);
  free(vn);
  free(un);
}

// (a / b, a % b); dividing by 0 gives (0, a), as Base's Nat.divmod does.
static void nat_divmod2(V a, V b, V *qo, V *ro) {
  if (b == 0) { *qo = 0; *ro = a; return; }
  if (!((a | b) >> 63)) { *qo = a / b; *ro = a % b; return; }
  if (nat_cmp3(a, b) < 0) { *qo = 0; *ro = a; return; }
  V ba, bb;
  size_t na, nb;
  const V *x = nat_limbs(a, &ba, &na), *y = nat_limbs(b, &bb, &nb);
  V *q = calloc(na + 1, sizeof(V)), *r = calloc(nb + 1, sizeof(V));
  if (nb == 1) {
    unsigned __int128 rem = 0;
    for (size_t i = na; i-- > 0;) {
      rem = (rem << 64) | x[i];
      q[i] = (V)(rem / y[0]);
      rem %= y[0];
    }
    r[0] = (V)rem;
  } else {
    nat_divlimbs(x, na, y, nb, q, r);
  }
  *qo = nat_make(q, na);
  *ro = nat_make(r, nb);
  free(q);
  free(r);
}

static V nat_pow(V a, V n) {
  if (a <= 1) return n == 0 ? 1 : a;
  V bn;
  size_t nn;
  const V *e = nat_limbs(n, &bn, &nn);
  if (nn > 1) bend_fail("out of memory (a Nat.pow result too large)");
  V r = 1, b = a;
  for (V k = nn ? e[0] : 0; k; k >>= 1) {
    if (k & 1) r = nat_mul(r, b);
    if (k > 1) b = nat_mul(b, b);
  }
  return r;
}

// Decimal digits of x (malloc'd, NUL-terminated).
static char *nat_digits(V x) {
  if (!(x >> 63)) {
    char *s = malloc(24);
    snprintf(s, 24, "%llu", (unsigned long long)x);
    return s;
  }
  V bx;
  size_t n;
  const V *d = nat_limbs(x, &bx, &n);
  V *t = malloc(n * sizeof(V));
  memcpy(t, d, n * sizeof(V));
  size_t cap = n * 20 + 2, k = cap - 1;
  char *out = malloc(cap);
  out[k] = 0;
  const V TEN19 = 10000000000000000000ull;
  while (n > 0) {
    unsigned __int128 rem = 0;
    for (size_t i = n; i-- > 0;) {
      rem = (rem << 64) | t[i];
      t[i] = (V)(rem / TEN19);
      rem %= TEN19;
    }
    while (n > 0 && t[n - 1] == 0) n--;
    V chunk = (V)rem;
    for (int j = 0; j < 19 && (n > 0 || chunk > 0); j++) { out[--k] = (char)('0' + chunk % 10); chunk /= 10; }
  }
  free(t);
  char *s = strdup(out + k);
  free(out);
  return s;
}

static inline V nat_addk(V x, V k) { return LIKELY(!(x >> 63)) && x + k < NAT_BIG ? x + k : nat_add(x, k); }
static inline V nat_subk(V x, V k) { return LIKELY(!(x >> 63)) ? x - k : nat_sub(x, k); }
static inline int nat_ge(V x, V k) { return (x >> 63) || x >= k; }

static inline V F_Nat_ddouble(V a) { return nat_add(a, a); }
static inline V F_Nat_dadd(V a, V b) { return nat_add(a, b); }
static inline V F_Nat_dsub(V a, V b) { return nat_sub(a, b); }
static inline V F_Nat_dmul(V a, V b) { return nat_mul(a, b); }
static inline V F_Nat_ddivmod(V a, V b) { V q, r; nat_divmod2(a, b, &q, &r); return C2(0, q, r); }
static inline V F_Nat_ddiv(V a, V b) { V q, r; nat_divmod2(a, b, &q, &r); return q; }
static inline V F_Nat_dmod(V a, V b) { V q, r; nat_divmod2(a, b, &q, &r); return r; }
static inline V F_Nat_dcmp(V a, V b) { int c = nat_cmp3(a, b); return c < 0 ? IMM(0) : c == 0 ? IMM(1) : IMM(2); }
static inline V F_Nat_dis__eq(V a, V b) { return BOOL(nat_cmp3(a, b) == 0); }
static inline V F_Nat_dis__ne(V a, V b) { return BOOL(nat_cmp3(a, b) != 0); }
static inline V F_Nat_dis__lt(V a, V b) { return BOOL(nat_cmp3(a, b) < 0); }
static inline V F_Nat_dis__le(V a, V b) { return BOOL(nat_cmp3(a, b) <= 0); }
static inline V F_Nat_dis__gt(V a, V b) { return BOOL(nat_cmp3(a, b) > 0); }
static inline V F_Nat_dis__ge(V a, V b) { return BOOL(nat_cmp3(a, b) >= 0); }
static inline V F_Nat_dmin(V a, V b) { return nat_cmp3(a, b) < 0 ? a : b; }
static inline V F_Nat_dmax(V a, V b) { return nat_cmp3(a, b) < 0 ? b : a; }
static inline V F_Nat_dpow(V a, V n) { return nat_pow(a, n); }
static V F_Nat_dshow(V a) {
  char *s = nat_digits(a);
  V r = mk_str(s, strlen(s));
  free(s);
  return r;
}

// Natives: U32
// ------------

#define U(x) ((uint32_t)(x))
static inline V nat_low32(V n) { return (n >> 63) ? U(nat_p(n)[1]) : U(n); }
static inline V F_U32_dinc(V a) { return U(a + 1); }
static inline V F_U32_dadd(V a, V b) { return U(a + b); }
static inline V F_U32_dsub(V a, V b) { return U(a - b); }
static inline V F_U32_dmul(V a, V b) { return U(U(a) * U(b)); }
static inline V F_U32_ddiv(V a, V b) { return b == 0 ? 0 : U(a) / U(b); }
static inline V F_U32_dmod(V a, V b) { return b == 0 ? a : U(a) % U(b); }
static inline V F_U32_dnot(V a) { return U(~a); }
static inline V F_U32_dand(V a, V b) { return a & b; }
static inline V F_U32_dor(V a, V b) { return a | b; }
static inline V F_U32_dxor(V a, V b) { return a ^ b; }
static inline V F_U32_dshl(V a) { return U(a << 1); }
static inline V F_U32_dshr(V a) { return a >> 1; }
static inline V F_U32_dshln(V a, V n) { return n >= 32 ? 0 : U(a << n); }
static inline V F_U32_dshrn(V a, V n) { return n >= 32 ? 0 : a >> n; }
static inline V F_U32_dcmp(V a, V b) { return a < b ? IMM(0) : a == b ? IMM(1) : IMM(2); }
static inline V F_U32_dis__eq(V a, V b) { return BOOL(a == b); }
static inline V F_U32_dis__ne(V a, V b) { return BOOL(a != b); }
static inline V F_U32_dis__lt(V a, V b) { return BOOL(a < b); }
static inline V F_U32_dis__le(V a, V b) { return BOOL(a <= b); }
static inline V F_U32_dis__gt(V a, V b) { return BOOL(a > b); }
static inline V F_U32_dis__ge(V a, V b) { return BOOL(a >= b); }
static inline V F_U32_dis__zero(V a) { return BOOL(a == 0); }
static inline V F_U32_dis__even(V a) { return BOOL((a & 1) == 0); }
static inline V F_U32_dto__nat(V a) { return a; }
static inline V F_U32_dfrom__nat(V n) { return nat_low32(n); }
static inline V F_U32_dmin(V a, V b) { return a < b ? a : b; }
static inline V F_U32_dmax(V a, V b) { return a < b ? b : a; }
static inline V F_U32_dpow(V a, V n) {
  // a^n mod 2^32; an odd a has an order dividing 2^30, an even one reaches 0.
  V e;
  if (n >> 63) { if (!(a & 1)) return 0; e = nat_p(n)[1] & ((1u << 30) - 1); }
  else e = n;
  uint32_t r = 1, b = U(a);
  for (; e; e >>= 1) { if (e & 1) r *= b; b *= b; }
  return r;
}
static inline V F_U32_dlog2(V n) {
  V d = 0;
  while (n > 1) { d++; n >>= 1; }
  return d;
}

// Natives: F32 (stored as IEEE bits)
// ----------------------------------

static inline float FV(V v) { union { uint32_t u; float f; } x; x.u = U(v); return x.f; }
static inline V VF(float f) { union { uint32_t u; float f; } x; x.f = f; return x.u; }
#define F2(name, expr) static inline V F_F32_d##name(V a, V b) { float x = FV(a), y = FV(b); return expr; }
#define F1(name, expr) static inline V F_F32_d##name(V a) { float x = FV(a); return expr; }
F2(add, VF(x + y))
F2(sub, VF(x - y))
F2(mul, VF(x * y))
F2(div, VF(x / y))
F2(mod, VF(fmodf(x, y)))
F2(pow, VF(powf(x, y)))
F2(atan2, VF(atan2f(x, y)))
F2(is__eq, BOOL(x == y))
F2(is__ne, BOOL(x != y))
F2(is__lt, BOOL(x < y))
F2(is__le, BOOL(x <= y))
F2(is__gt, BOOL(x > y))
F2(is__ge, BOOL(x >= y))
F1(neg, VF(-x))
F1(abs, VF(fabsf(x)))
F1(sqrt, VF(sqrtf(x)))
F1(exp, VF(expf(x)))
F1(log, VF(logf(x)))
F1(log2, VF(log2f(x)))
F1(log10, VF(log10f(x)))
F1(sin, VF(sinf(x)))
F1(cos, VF(cosf(x)))
F1(tan, VF(tanf(x)))
F1(asin, VF(asinf(x)))
F1(acos, VF(acosf(x)))
F1(atan, VF(atanf(x)))
F1(sinh, VF(sinhf(x)))
F1(cosh, VF(coshf(x)))
F1(tanh, VF(tanhf(x)))
F1(floor, VF(floorf(x)))
F1(ceil, VF(ceilf(x)))
F1(trunc, VF(truncf(x)))
static inline V F_F32_dbits(V a) { return U(a); }
static inline V F_F32_dto__u32(V a) { float x = FV(a); return x <= 0 ? 0 : x >= 4294967295.0f ? 0xffffffffu : (uint32_t)x; }
static inline V F_U32_dto__f32(V a) { return VF((float)U(a)); }
static V F_F32_dshow(V a) {
  char buf[64];
  snprintf(buf, sizeof buf, "%g", FV(a));
  return mk_str(buf, strlen(buf));
}
static V F_F32_dread(V s) {
  char *c = str_to_c(s, NULL);
  char *end;
  float f = strtof(c, &end);
  int ok = *c && !*end;
  free(c);
  return ok ? C1(1, VF(f)) : IMM(0);
}

// Parallel calls
// ==============
//
// A parallel let `a b = f(x) g(y)` forks every value but the last as a task
// (a closure applied to a dummy argument), evaluates the last one, then joins
// the tasks in reverse. Each thread owns a Chase-Lev deque: it pushes and
// pops at the bottom, idle threads steal from the top. A task nobody stole
// runs inline at its join, so a fork costs little more than a closure.

#define P_LOCAL 0
#define P_QUEUED 1
#define P_DONE 2

typedef struct PTask { V clo; V res; V state; } PTask;

typedef struct PDeque {
  _Atomic long top;
  _Atomic long bot;
  long mask;
  PTask **buf;
} PDeque;

static int par_nthreads = 1;
static _Atomic int par_started;
static pthread_mutex_t par_mu = PTHREAD_MUTEX_INITIALIZER;
static pthread_cond_t par_cv = PTHREAD_COND_INITIALIZER;
static _Atomic int par_sleepers;

static PDeque *pdq_new(void) {
  PDeque *d = calloc(1, sizeof(PDeque));
  d->mask = (1 << 16) - 1;
  d->buf = calloc((size_t)d->mask + 1, sizeof(PTask *));
  return d;
}

static PTask *pdq_pop(PDeque *d) {
  long b = atomic_load_explicit(&d->bot, memory_order_relaxed) - 1;
  atomic_store_explicit(&d->bot, b, memory_order_relaxed);
  atomic_thread_fence(memory_order_seq_cst);
  long t = atomic_load_explicit(&d->top, memory_order_relaxed);
  if (t <= b) {
    PTask *x = __atomic_load_n(&d->buf[b & d->mask], __ATOMIC_RELAXED);
    if (t == b) {
      if (!atomic_compare_exchange_strong_explicit(&d->top, &t, t + 1, memory_order_seq_cst,
            memory_order_relaxed))
        x = NULL;
      atomic_store_explicit(&d->bot, b + 1, memory_order_relaxed);
    }
    return x;
  }
  atomic_store_explicit(&d->bot, b + 1, memory_order_relaxed);
  return NULL;
}

static PTask *pdq_steal(PDeque *d) {
  long t = atomic_load_explicit(&d->top, memory_order_acquire);
  atomic_thread_fence(memory_order_seq_cst);
  long b = atomic_load_explicit(&d->bot, memory_order_acquire);
  if (t < b) {
    PTask *x = __atomic_load_n(&d->buf[t & d->mask], __ATOMIC_RELAXED);
    if (!atomic_compare_exchange_strong_explicit(&d->top, &t, t + 1, memory_order_seq_cst,
          memory_order_relaxed))
      return NULL;
    return x;
  }
  return NULL;
}

static void par_exec(PTask *t) {
  V r = apply(t->clo, 0);
  t->res = r;
  __atomic_store_n(&t->state, P_DONE, __ATOMIC_RELEASE);
}

static PTask *par_steal(void) {
  Thr *me = thr_self;
  int n = __atomic_load_n(&gc_nthr, __ATOMIC_ACQUIRE);
  if (n <= 1) return NULL;
  me->rng = me->rng * 1664525u + 1013904223u;
  int s = (int)(me->rng >> 8) % n;
  for (int i = 0; i < n; i++) {
    Thr *t = gc_thrs[(s + i) % n];
    if (t == me || !t->live || !t->dq) continue;
    PTask *x = pdq_steal(t->dq);
    if (x) return x;
  }
  return NULL;
}

static inline void cpu_relax(void) {
#if defined(__x86_64__)
  __builtin_ia32_pause();
#elif defined(__aarch64__)
  __asm__ __volatile__("yield");
#endif
}

static void *par_worker(void *arg) {
  (void)arg;
  thr_register((uintptr_t)__builtin_frame_address(0) + 16);
  for (int spins = 0;;) {
    PTask *t = par_steal();
    if (t) { par_exec(t); spins = 0; continue; }
    if (++spins < 512) { cpu_relax(); continue; }
    pthread_mutex_lock(&par_mu);
    atomic_fetch_add(&par_sleepers, 1);
    struct timeval now;
    gettimeofday(&now, NULL);
    struct timespec until = {now.tv_sec, now.tv_usec * 1000 + 2000000};
    if (until.tv_nsec >= 1000000000) { until.tv_sec++; until.tv_nsec -= 1000000000; }
    pthread_cond_timedwait(&par_cv, &par_mu, &until);
    atomic_fetch_sub(&par_sleepers, 1);
    pthread_mutex_unlock(&par_mu);
    spins = 0;
  }
  return NULL;
}

static void par_hook(void) {
  for (int i = 0; i < gc_nthr; i++) {
    PDeque *d = gc_thrs[i]->dq;
    if (d) gc_scan(d->buf, d->buf + d->mask + 1);
  }
}

static void par_start(void) {
  pthread_mutex_lock(&par_mu);
  if (!atomic_load(&par_started)) {
    for (int i = 1; i < par_nthreads; i++) {
      pthread_attr_t attr;
      pthread_attr_init(&attr);
      pthread_attr_setstacksize(&attr, (size_t)1 << 31);
      pthread_t th;
      if (pthread_create(&th, &attr, par_worker, NULL) == 0) pthread_detach(th);
      pthread_attr_destroy(&attr);
    }
    atomic_store(&par_started, 1);
  }
  pthread_mutex_unlock(&par_mu);
}

// Forks clo (a closure taking one dummy argument); returns the task. Only a
// thread whose deque is nearly empty queues it (the oldest tasks, which
// thieves take, are the big ones); otherwise the fork is the closure itself,
// tagged with bit 1, and its join just applies it.
static V par_fork(V clo) {
  if (par_nthreads <= 1) return clo | 2;
  PDeque *d = thr_self->dq;
  long b = atomic_load_explicit(&d->bot, memory_order_relaxed);
  long tp = atomic_load_explicit(&d->top, memory_order_relaxed);
  if (b - tp >= 4) return clo | 2;
  if (UNLIKELY(!atomic_load_explicit(&par_started, memory_order_relaxed))) par_start();
  PTask *t = (PTask *)halloc(3);
  t->clo = clo;
  t->state = P_QUEUED;
  __atomic_store_n(&d->buf[b & d->mask], t, __ATOMIC_RELAXED);
  atomic_thread_fence(memory_order_release);
  atomic_store_explicit(&d->bot, b + 1, memory_order_relaxed);
  if (atomic_load_explicit(&par_sleepers, memory_order_relaxed) > 0) pthread_cond_signal(&par_cv);
  return (V)t;
}

// Waits for a forked task and returns its value.
static V par_join(V tv) {
  if (tv & 2) return apply(tv & ~(V)2, 0);
  PTask *t = (PTask *)tv;
  PTask *p = pdq_pop(thr_self->dq);
  if (p == t) return apply(t->clo, 0);
  if (p) par_exec(p);
  while (__atomic_load_n(&t->state, __ATOMIC_ACQUIRE) != P_DONE) {
    PTask *o = par_steal();
    if (o) par_exec(o);
    else cpu_relax();
  }
  return t->res;
}

static int cpu_count(void) {
  long n = sysconf(_SC_NPROCESSORS_ONLN);
  return n < 1 ? 1 : n > 128 ? 128 : (int)n;
}

// Effects
// =======
//
// An effect def compiles to a request node {cid | n << 24, args..., k}. The
// event loop runs each computation's pure code up to its next request, runs
// the effect's host function, then resumes k with the answer. The host
// functions use the official runtime's names and conventions: see
// EFFECTS.md in the Bend guide. A CID encodes how a constructor is laid out
// here: kind << 16 | tag, where kind 0 is a node, 1 a nullary constructor,
// 2 a single-field single-constructor type (the field itself), and 3 an
// effect (its tag is its row in io_eff_rows).

#ifndef CID_TUPLE
#define CID_TUPLE 0u
#endif
#ifndef CID_DONE
#define CID_DONE 1u
#endif
#ifndef CID_FAIL
#define CID_FAIL 0u
#endif
#ifndef CID_SOME
#define CID_SOME 1u
#endif
#ifndef CID_NONE
#define CID_NONE ((1u << 16) | 0u)
#endif
#ifndef CID_TRUE
#define CID_TRUE ((1u << 16) | 1u)
#endif
#ifndef CID_FALSE
#define CID_FALSE ((1u << 16) | 0u)
#endif
#ifndef CID_UNIT
#define CID_UNIT ((1u << 16) | 0u)
#endif

// A request node for effect cid with n fields (its arguments, then k).
static inline V io_req(u64 cid, int n, const V *xs) { return CN(cid | ((V)n << 24), n, xs); }

typedef struct { int unused; } Env;
typedef pthread_mutex_t lock;
#define OUTLINE __attribute__((noinline))
#define IO_READ 1
#define IO_TIME 2
#define IO_HELP 64
static V io_hole_cell;
#define TERM_HOLE ((Term)(uintptr_t)&io_hole_cell)
#define IO_PARK TERM_HOLE
#define io_hand(v) ((Term)(v))
#define io_hand_v(t) ((u64)(t))
#define CID_KIND(c) ((u32)(c) >> 16)
#define CID_TAG(c) ((u32)(c) & 0xffff)

__attribute__((noreturn)) static void err_fail(const char *msg) { bend_fail(msg); }

static inline Term term_pak(u64 cid, Term v) {
  switch (CID_KIND(cid)) {
    case 1: return IMM(CID_TAG(cid));
    case 2: return v;
    default: return C1(CID_TAG(cid), v);
  }
}

// The CID of a constructor value (a node's or a nullary one's).
static inline u64 term_aux(Term t) { return (t & 1) ? ((1u << 16) | (u32)(t >> 3)) : ((V *)t)[0]; }
#define term_drop(e, t) ((void)(e), (void)(t))
#define term_sink(e, t) ((void)(e), (void)(t))
#define cls_fit(n) 0
#define spare_free(e, c, x) ((void)(e), (void)(c), (void)(x))
static inline int ctr_take(Env e, Term t, u32 n, Term *fb) {
  (void)e;
  for (u32 i = 0; i < n; i++) fb[i] = FLD(t, i);
  return 0;
}

struct IoWork;
typedef void (*IoCall)(struct IoWork *w);
typedef Term (*IoPack)(Env e, struct IoWork *w);

typedef struct IoWork {
  intptr_t hand;
  intptr_t made;
  u32 word;
  u64 size;
  char *data;
  char *text;
  u32 code;
  IoCall call;
  IoPack pack;
} IoWork;

typedef Term (*Effect)(Env e, Term *f, IoWork *w);

typedef struct {
  Effect run;
  u32 ask;
} IoEff;

static IoEff io_eff_rows[1 << 16];
static u32 io_live;
static int io_argc;
static char **io_argv;

static void io_eff(u32 cid, Effect run, u32 need) { io_eff_rows[CID_TAG(cid)] = (IoEff){run, need}; }

static u64 io_tick(void) {
  struct timespec ts;
  clock_gettime(CLOCK_MONOTONIC, &ts);
  return (u64)ts.tv_sec * 1000000000ull + (u64)ts.tv_nsec;
}

OUTLINE void *io_mem(void *mem) {
  if (mem == NULL) err_fail("host allocation failed");
  return mem;
}

static int io_sys_addr(const char *host, u32 port, struct sockaddr_in *at) {
  memset(at, 0, sizeof(*at));
  at->sin_family = AF_INET;
  at->sin_port = htons((uint16_t)port);
  for (const char *p = host; *p != 0; p += 1) {
    bool zero = *p == '0' && p[1] >= '0' && p[1] <= '9';
    if ((p == host || p[-1] == '.') && zero) return -1;
  }
  return port > 65535 || inet_pton(AF_INET, host, &at->sin_addr) != 1 ? -1 : 0;
}

static u64 io_sys_end(IoWork *w, ssize_t n) {
  w->code = n < 0 ? (u32)errno : 0;
  return n < 0 ? 0 : (u64)n;
}

// One computation: cont applied to item is its next request. Leading work
// permits IoWork* to IoAct* casts. Every live act is on a list the collector
// reads.
typedef struct IoAct {
  IoWork work;
  Term cont;
  Term item;
  u64 time;
  short evts;
  struct IoAct *next;
  struct IoAct *gprev, *gnext;
} IoAct;

typedef struct {
  IoAct *head;
  IoAct *last;
} IoQue;

static IoQue io_runs;
static IoQue io_park;
static IoQue io_jobs;
static IoAct *io_acts;

static void io_push(IoQue *q, IoAct *a) {
  a->next = NULL;
  *(q->head == NULL ? &q->head : &q->last->next) = a;
  q->last = a;
}

static IoAct *io_pop(IoQue *q) {
  IoAct *a = q->head;
  q->head = a->next;
  return a;
}

static IoAct *io_act_new(void) {
  IoAct *a = io_mem(calloc(1, sizeof(IoAct)));
  pthread_mutex_lock(&gc_lock);
  a->gnext = io_acts;
  if (io_acts) io_acts->gprev = a;
  io_acts = a;
  pthread_mutex_unlock(&gc_lock);
  return a;
}

static void io_act_free(IoAct *a) {
  pthread_mutex_lock(&gc_lock);
  if (a->gprev) a->gprev->gnext = a->gnext;
  else io_acts = a->gnext;
  if (a->gnext) a->gnext->gprev = a->gprev;
  pthread_mutex_unlock(&gc_lock);
  free(a);
}

static V io_start_fn(V *a) { return apply(apply(a[0], 0), a[1]); }
static V io_emit_fn(V *a) { return C1(0, a[0]); }

// Starts m (an IO) as a new computation.
static void io_spawn(Term m) {
  IoAct *a = io_act_new();
  a->cont = mk_clo(io_start_fn, 2, 1, &m);
  a->item = mk_clo(io_emit_fn, 1, 0, NULL);
  io_push(&io_runs, a);
  io_live += 1;
}

// Parks until evts (POLLIN/POLLOUT; 0 ignores fd) or time (0: no deadline).
// The loop calls more: a value resumes, IO_PARK re-parks.
static Term io_wait_on(IoWork *w, int fd, short evts, u64 time, IoPack more) {
  IoAct *a = (IoAct *)w;
  a->work.word = (u32)fd;
  a->work.pack = more;
  a->time = time;
  a->evts = evts;
  io_push(&io_park, a);
  return IO_PARK;
}

static u64 io_wait_time(IoWork *w) { return ((IoAct *)w)->time; }

OUTLINE void io_out(FILE *h, const char *data, u64 len) {
  if (fwrite(data, 1, len, h) != len) err_fail("a short write on a standard stream");
}

OUTLINE void io_sync(void) {
  if (fflush(stdout) != 0) err_fail("a short write on a standard stream");
}

static u64 io_utf8(char *buf, u64 c) {
  u64 k = c < 0x80 ? 1 : c < 0x800 ? 2 : c < 0x10000 ? 3 : 4;
  for (u64 i = k; i > 1; i -= 1) {
    buf[i - 1] = (char)(0x80 | (c & 0x3F));
    c >>= 6;
  }
  buf[0] = (char)(k == 1 ? c : (0xF00 >> k) | c);
  return k;
}

OUTLINE char *io_cstr(Env e, Term s, u64 *len) {
  (void)e;
  u64 cap = 64, n = 0;
  char *buf = io_mem(malloc(cap));
  while (!(s & 1) && TAG(s) == 1) {
    if (n + 5 > cap) {
      cap *= 2;
      buf = io_mem(realloc(buf, cap));
    }
    n += io_utf8(buf + n, FLD(s, 0));
    s = FLD(s, 1);
  }
  buf[n] = 0;
  *len = n;
  return buf;
}

OUTLINE void io_errs(Env e, Term s) {
  u64 n = 0;
  char *text = io_cstr(e, s, &n);
  io_sync();
  io_out(stderr, text, n);
  io_out(stderr, "\n", 1);
  free(text);
}

#define io_nul(s, n) (strlen(s) != (n))

static Term io_box(Env e, u64 cid, Term v) {
  (void)e;
  switch (CID_KIND(cid)) {
    case 1: return IMM(CID_TAG(cid));
    case 2: return v;
    default: return C1(CID_TAG(cid), v);
  }
}

static Term io_node(Env e, u64 cid, Term a, Term b) {
  (void)e;
  return C2(CID_TAG(cid), a, b);
}

// Decodes UTF-8 as WHATWG does: a byte that breaks a sequence yields one
// U+FFFD and is read again as a lead.
static Term io_str(Env e, const char *p, u64 n) {
  (void)e;
  u32 *cps = io_mem(malloc((n + 1) * sizeof(u32)));
  u64 k = 0;
  u64 c = 0, need = 0, lo = 0x80, hi = 0xBF;
  for (u64 i = 0; i < n || need > 0; i += 1) {
    u64 b = i < n ? (uint8_t)p[i] : 0x100;
    if (need > 0 && (b < lo || b > hi)) {
      need = 0;
      c = 0xFFFD;
      i -= 1;
    } else if (need > 0) {
      lo = 0x80;
      hi = 0xBF;
      c = (c << 6) | (b & 0x3F);
      if (--need > 0) continue;
    } else if (b < 0x80) {
      c = b;
    } else if (b < 0xC2 || b > 0xF4) {
      c = 0xFFFD;
    } else {
      need = b < 0xE0 ? 1 : b < 0xF0 ? 2 : 3;
      lo = b == 0xE0 ? 0xA0 : b == 0xF0 ? 0x90 : 0x80;
      hi = b == 0xED ? 0x9F : b == 0xF4 ? 0x8F : 0xBF;
      c = b & (0x3F >> need);
      continue;
    }
    cps[k++] = (u32)c;
  }
  Term s = SNIL;
  while (k > 0) { k--; s = SCONS(cps[k], s); }
  free(cps);
  return s;
}

#define io_tup(e, a, b) io_node(e, CID_TUPLE, a, b)
#define io_done(e, v) io_box(e, CID_DONE, v)

static Term io_fail(Env e, u32 code, const char *text) {
  const char *s = text != NULL ? text : strerror((int)code);
  Term t = io_tup(e, code, io_str(e, s, strlen(s)));
  return io_box(e, CID_FAIL, t);
}

static pthread_mutex_t io_gate = PTHREAD_MUTEX_INITIALIZER;
static pthread_cond_t io_bell = PTHREAD_COND_INITIALIZER;
static u32 io_busy;
static u32 io_size;
static int io_wake_fd[2];

static void io_take(Env e) {
  IoAct *acts[64];
  ssize_t n;
  while ((n = read(io_wake_fd[0], acts, sizeof acts)) > 0) {
    for (u32 i = 0; i < (u32)n / sizeof(IoAct *); i += 1) {
      IoAct *a = acts[i];
      a->item = a->work.pack(e, &a->work);
      io_push(&io_runs, a);
      io_busy -= 1;
    }
  }
}

static void *io_help(void *arg) {
  (void)arg;
  for (;;) {
    pthread_mutex_lock(&io_gate);
    while (io_jobs.head == NULL) pthread_cond_wait(&io_bell, &io_gate);
    IoAct *a = io_pop(&io_jobs);
    pthread_mutex_unlock(&io_gate);
    a->work.call(&a->work);
    while (write(io_wake_fd[1], &a, sizeof a) != sizeof a) {
    }
  }
  return NULL;
}

// Runs call on a helper thread, then pack on the loop to resume the effect.
static Term io_work(IoWork *w, IoCall call, IoPack pack) {
  w->call = call;
  w->pack = pack;
  io_busy += 1;
  if (io_busy > io_size && io_size < IO_HELP) {
    pthread_t tid;
    if (pthread_create(&tid, NULL, io_help, NULL)) err_fail("pthread_create");
    pthread_detach(tid);
    io_size += 1;
  }
  pthread_mutex_lock(&io_gate);
  io_push(&io_jobs, (IoAct *)w);
  pthread_cond_signal(&io_bell);
  pthread_mutex_unlock(&io_gate);
  return IO_PARK;
}

// Takes cont's request node apart; the effect returns a value or IO_PARK.
static Term io_exec(Env e, IoWork *w) {
  IoAct *a = (IoAct *)w;
  Term fs[256];
  u64 tg = TAG(a->cont);
  u32 n = (u32)(tg >> 24);
  for (u32 i = 0; i < n; i++) fs[i] = FLD(a->cont, i);
  a->cont = fs[n - 1];
  return io_eff_rows[CID_TAG(tg)].run(e, fs, w);
}

// macOS poll misses FIFO EOF, so the loop waits with select.
static bool io_bit(u8 *set, int fd, bool put) {
  u8 *at = set + fd / 8;
  *at |= put << fd % 8;
  return *at >> fd % 8 & 1;
}

static void io_wait(Env e) {
  int top = io_wake_fd[0];
  u64 soon = 0;
  for (IoAct *a = io_park.head; a != NULL; a = a->next) {
    if (a->time != 0 && (soon == 0 || a->time < soon)) soon = a->time;
    if (a->evts != 0 && (int)a->work.word > top) top = (int)a->work.word;
  }
  u64 len = (u64)top / 64 * 8 + 8;
  u8 *set[2] = {io_mem(calloc(2, len)), NULL};
  set[1] = set[0] + len;
  io_bit(set[0], io_wake_fd[0], true);
  for (IoAct *a = io_park.head; a != NULL; a = a->next) {
    if (a->evts != 0) io_bit(set[a->evts == POLLOUT], (int)a->work.word, true);
  }
  u64 tick = io_tick();
  u64 ms = soon > tick ? (soon - tick) / 1000000 + 1 : 0;
  struct timeval tv = {(time_t)(ms / 1000), (suseconds_t)(ms % 1000 * 1000)};
  io_sync();
  while (select(top + 1, (fd_set *)set[0], (fd_set *)set[1], NULL, soon == 0 ? NULL : &tv) < 0) {
    if (errno != EINTR) err_fail("the poller failed");
  }
  if (io_bit(set[0], io_wake_fd[0], false)) io_take(e);
  u64 now = io_tick();
  IoQue todo = io_park;
  io_park = (IoQue){0};
  while (todo.head != NULL) {
    IoAct *a = io_pop(&todo);
    bool due = (a->evts != 0 && io_bit(set[a->evts == POLLOUT], (int)a->work.word, false)) ||
      (a->time != 0 && a->time <= now);
    if (!due) {
      io_push(&io_park, a);
      continue;
    }
    Term x = a->work.pack(e, &a->work);
    if (x != IO_PARK) {
      a->item = x;
      io_push(&io_runs, a);
    }
  }
  free(set[0]);
}

// Runs a computation up to its next park; returns an exit code on a Halt.
static int io_step(Env e, IoAct *a) {
  for (;;) {
    Term req = apply(a->cont, a->item);
    u64 tg = TAG(req);
    if (tg == 0) {
      io_act_free(a);
      io_live -= 1;
      return -1;
    }
    if (tg == 1) {
      io_errs(e, FLD(req, 1));
      return (int)(u32)FLD(req, 0);
    }
    if (CID_KIND(tg & 0xffffff) != 3 || io_eff_rows[CID_TAG(tg)].run == NULL) err_fail("an alien request");
    u32 need = io_eff_rows[CID_TAG(tg)].ask;
    a->cont = req;
    if (need != 0) {
      Term f0 = FLD(req, 0);
      u32 word = (u32)(need & IO_READ ? io_hand_v(f0) : f0);
      io_wait_on(&a->work, (int)word, need & IO_READ ? POLLIN : 0,
        need & IO_TIME ? io_tick() + (u64)word * 1000000ull : 0, io_exec);
      return -1;
    }
    Term x = io_exec(e, &a->work);
    if (x == IO_PARK) return -1;
    a->item = x;
  }
}

// Chan
// ----

typedef struct {
  u32 gen;
  u32 next;
  u32 room;
  u32 size;
  u32 head;
  u32 live;
  u32 shut;
  Term *ring;
  IoQue wait;
} ChanRow;

static ChanRow *chan_rows;
static u32 chan_len;
static u32 chan_idle = ~0u;

#define chan_some(e, v) io_box(e, CID_SOME, v)
#define chan_bool(b) term_pak((b) ? CID_TRUE : CID_FALSE, 0)

static Term chan_open(u32 room) {
  pthread_mutex_lock(&gc_lock);
  u32 i = chan_idle;
  if (i != ~0u) {
    chan_idle = chan_rows[i].next;
  } else {
    if (chan_len == 1u << 24) err_fail("more than 16777216 channels at once");
    if ((chan_len & (chan_len - 1)) == 0)
      chan_rows = io_mem(realloc(chan_rows, (chan_len == 0 ? 1 : 2 * chan_len) * sizeof(ChanRow)));
    i = chan_len;
    chan_len += 1;
    chan_rows[i].gen = 0;
  }
  ChanRow *row = &chan_rows[i];
  row->gen += 1;
  row->room = room;
  row->size = 0;
  row->head = 0;
  row->shut = 0;
  row->ring = room == 0 ? NULL : io_mem(calloc(room, sizeof(Term)));
  row->wait.head = NULL;
  row->wait.last = NULL;
  row->live = 1;
  pthread_mutex_unlock(&gc_lock);
  return io_hand(((u64)row->gen << 24) | i);
}

static ChanRow *chan_at(Term t) {
  u64 v = io_hand_v(t);
  u32 i = (u32)v & 0xFFFFFF;
  ChanRow *row = i < chan_len ? &chan_rows[i] : NULL;
  return row != NULL && row->live && row->gen == (u32)(v >> 24) ? row : NULL;
}

// Parks the effect's activation on row with item: a sent value, or
// TERM_HOLE for a receiver.
static Term chan_park(ChanRow *row, IoWork *w, Term item) {
  IoAct *a = (IoAct *)w;
  a->item = item;
  io_push(&row->wait, a);
  return IO_PARK;
}

static Term chan_wake(ChanRow *row, Term x) {
  IoAct *a = io_pop(&row->wait);
  Term item = a->item;
  a->item = x;
  io_push(&io_runs, a);
  return item;
}

static Term chan_take(ChanRow *row) {
  Term v = row->ring[row->head];
  row->head = (row->head + 1) % row->room;
  row->size -= 1;
  if (row->wait.head != NULL) {
    Term item = chan_wake(row, chan_bool(true));
    row->ring[(row->head + row->size) % row->room] = item;
    row->size += 1;
  }
  return v;
}

static void chan_free(ChanRow *row) {
  pthread_mutex_lock(&gc_lock);
  free(row->ring);
  row->ring = NULL;
  row->live = 0;
  row->next = chan_idle;
  chan_idle = (u32)(row - chan_rows);
  pthread_mutex_unlock(&gc_lock);
}

static void chan_shut(Env e, ChanRow *row) {
  row->shut = 1;
  while (row->wait.head != NULL) {
    bool rcv = row->wait.head->item == TERM_HOLE;
    Term x = rcv ? term_pak(CID_NONE, 0) : chan_bool(false);
    term_sink(e, chan_wake(row, x));
  }
  if (row->size == 0) chan_free(row);
}

static void io_hook(void) {
  for (IoAct *a = io_acts; a != NULL; a = a->gnext) {
    gc_mark(a->cont);
    gc_mark(a->item);
  }
  for (u32 i = 0; i < chan_len; i++) {
    ChanRow *row = &chan_rows[i];
    if (row->live && row->ring) gc_scan(row->ring, row->ring + row->room);
  }
}

static int io_loop(Term m) {
  Env e = {0};
  signal(SIGPIPE, SIG_IGN);
  if (pipe(io_wake_fd) | fcntl(io_wake_fd[0], F_SETFL, O_NONBLOCK)) err_fail("the event loop failed to open");
  io_spawn(m);
  for (u32 n = 0;; n += 1) {
    if (io_runs.head == NULL) {
      if (io_live == 0) return 0;
      if (io_park.head == NULL && io_busy == 0) {
        io_sync();
        fprintf(stderr, "bend: deadlock: every computation waits on a channel\n");
        return 1;
      }
      io_wait(e);
      continue;
    }
    if ((n & 63) == 0 && io_busy != 0) io_take(e);
    int code = io_step(e, io_pop(&io_runs));
    if (code >= 0) return code;
  }
}

// Value printing (for a main that is not IO), in Bend syntax
// ==========================================================

static void pr_s(const char *s) { fputs(s, stdout); }
static void pr_u32(V v) { printf("%u", U(v)); }
static void pr_nat(V v) {
  char *s = nat_digits(v);
  fputs(s, stdout);
  putchar('n');
  free(s);
}
static void pr_f32(V v) {
  float f = FV(v);
  char buf[64];
  for (int p = 1; p <= 9; p++) {
    snprintf(buf, sizeof buf, "%.*g", p, f);
    if (strtof(buf, NULL) == f) break;
  }
  fputs(buf, stdout);
  if (!strpbrk(buf, ".eEna")) fputs(".0", stdout);
}
// As the official term_show spells a character.
static void pr_cp(uint32_t cp, char quote) {
  int k = cp == 10 ? 'n' : cp == 9 ? 't' : cp == 13 ? 'r' : cp == 0 ? '0'
    : cp == 92 || cp == (uint32_t)quote ? (int)cp : 0;
  if (k != 0) {
    printf("\\%c", k);
  } else if (cp < 32 || cp == 127 || (cp >= 0xD800 && cp <= 0xDFFF) || cp > 0x10FFFF) {
    printf("\\u{%x}", cp);
  } else {
    char b[4];
    fwrite(b, 1, io_utf8(b, cp), stdout);
  }
}
static void pr_char(V v) { putchar('\''); pr_cp(U(v), '\''); putchar('\''); }
static void pr_str(V v) {
  putchar('"');
  while (TAG(v) == 1) { pr_cp(U(FLD(v, 0)), '"'); v = FLD(v, 1); }
  putchar('"');
}

// Entry points
// ============

static V (*bend_main_fn)(void);
static void (*bend_print_fn)(V);
static int bend_exit;

static void *bend_thread(void *arg) {
  thr_register((uintptr_t)__builtin_frame_address(0) + 16);
  if (arg) {
    bend_print_fn(bend_main_fn());
    putchar('\n');
  } else {
    bend_exit = io_loop(bend_main_fn());
  }
  fflush(stdout);
  return NULL;
}

static int bend_gpu = 1;

static const char *CLI_HELP =
  "usage: %s [options] [arguments]\n"
  "  --threads N       worker threads, 1 to 128 (default: the CPU count)\n"
  "  --gpu on|off|4GB  where ! calls run: the GPU (the default) or the CPU threads\n"
  "  --help            show this text\n"
  "  --                the rest are the program's arguments (IO.args)\n";

static void cli_fail(const char *msg) {
  fprintf(stderr, "bend: %s\n", msg);
  exit(1);
}

static int bend_start(int argc, char **argv, V (*m)(void), int value) {
  bend_main_fn = m;
  io_argv = calloc((size_t)argc + 1, sizeof(char *));
  long thr = 0;
  for (int i = 1; i < argc; i++) {
    const char *a = argv[i];
    const char *v = i + 1 < argc ? argv[i + 1] : NULL;
    if (strcmp(a, "--") == 0) {
      while (i + 1 < argc) io_argv[io_argc++] = argv[++i];
    } else if (strcmp(a, "--help") == 0) {
      printf(CLI_HELP, argv[0]);
      return 0;
    } else if (strcmp(a, "--threads") == 0) {
      char *end = NULL;
      thr = v != NULL ? strtol(v, &end, 10) : 0;
      if (thr < 1 || thr > 128 || end == NULL || *end != '\0') cli_fail("expected a thread count of 1 or more after --threads");
      i++;
    } else if (strcmp(a, "--gpu") == 0) {
      if (v == NULL) cli_fail("expected on, off or a size like 4GB after --gpu");
      bend_gpu = strcmp(v, "off") != 0;
      i++;
    } else {
      io_argv[io_argc++] = argv[i];
    }
  }
  par_nthreads = thr > 0 ? (int)thr : cpu_count();
  gc_init();
  struct sigaction sa;
  memset(&sa, 0, sizeof sa);
  sa.sa_handler = gc_handler;
  sa.sa_flags = SA_RESTART;
  sigemptyset(&sa.sa_mask);
  sigaction(GC_SIG, &sa, NULL);
  gc_hook(par_hook);
  gc_hook(io_hook);
  pthread_attr_t attr;
  pthread_attr_init(&attr);
  pthread_attr_setstacksize(&attr, (size_t)1 << 32);
  pthread_t th;
  if (pthread_create(&th, &attr, bend_thread, value ? (void *)1 : NULL) != 0) {
    perror("pthread_create");
    return 1;
  }
  pthread_join(th, NULL);
  fflush(stdout);
  return bend_exit;
}

static int bend_run_value(int argc, char **argv, V (*m)(void), void (*p)(V)) {
  bend_print_fn = p;
  return bend_start(argc, argv, m, 1);
}

static int bend_run(int argc, char **argv, V (*m)(void)) { return bend_start(argc, argv, m, 0); }

#endif
