// Generated by tools/rtsplit.py from rt/bendrt.h: do not edit.
// The runtime's declarations, for a program linked with build/bendrt.o.
#define BEND_RT_SPLIT_HEADER 1
// bendrt.h: runtime for C code generated by bendc (the Bend compiler written in Bend).
//
// Values are 64-bit words:
//  - numbers (U32, Char, F32 bits) are stored raw;
//  - a Nat below 2^63 is stored raw; a larger one is (1 << 63) | pointer to
//    a bignum {limb count, limbs...};
//  - nullary constructors are IMM(tag) = (tag << 3) | 1;
//  - other constructors are pointers to heap nodes {tag, fields...};
//  - closures are pointers to {fn, arity, nargs, args...}.
// A type with one constructor of one field is represented by that field.
//
// Memory is managed by a conservative, non-moving mark-sweep collector. The
// threads that run Bend code (the main thread and the fork-join workers) are
// stopped with a signal while it runs. Parallel lets fork onto a
// work-stealing pool. Effects follow the official Bend runtime's effect ABI
// (Term, Env, IoWork, io_eff, CID_*), so effect sources written for the
// official compiler (Base's own effs/*.c included) compile unchanged.

#ifndef BENDRT_H
#define BENDRT_H

#ifdef __linux__
#define _GNU_SOURCE
#endif
#include <stdint.h>
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
#include <pthread.h>
#include <unistd.h>
#include <fcntl.h>
#include <time.h>
#include <errno.h>
#include <setjmp.h>
#include <signal.h>
#include <sched.h>
#include <poll.h>
#include <stdatomic.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/time.h>
#include <sys/select.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <arpa/inet.h>

typedef uint64_t V;
typedef V (*Fn)(V *);
typedef uint64_t u64;
typedef uint32_t u32;
typedef uint16_t u16;
typedef uint8_t u8;
typedef int64_t i64;
typedef int32_t i32;
typedef uint32_t U32;
typedef uint64_t Term;

#define IMM(t) ((((V)(t)) << 3) | 1)
// A node's tag word holds its tag (below 2^20) and two flags (see "Freeing
// on match"): shared, and its fields marked shared too.
#define BEND_SH ((V)1 << 20)
#define BEND_DEEP ((V)1 << 21)
#define BEND_SH_BITS (BEND_SH | BEND_DEEP)
// What a D_ function's node holds where its hole is, until it is filled: a
// word no pointer can be, that the collector looks for (gc_rem).
#define BEND_HOLE IMM(0x7ffff)
// Keeps the compiler from reordering the stores around it (a thread stopped
// by a collection is seen in its program order).
#define BEND_BARRIER() __asm__ volatile("" ::: "memory")
#define FLD(v, i) (((V *)(v))[(i) + 1])
#define BOOL(b) ((b) ? IMM(1) : IMM(0))
#define UNIT IMM(0)
// A call that must compile to a jump (a D_ function's tail call, which
// would otherwise grow the stack by one frame per list element).
#if defined(__has_attribute)
#if __has_attribute(musttail)
#define BEND_MUSTTAIL __attribute__((musttail))
#endif
#endif
#ifndef BEND_MUSTTAIL
#define BEND_MUSTTAIL
#endif
#define LIKELY(x) __builtin_expect(!!(x), 1)
#define UNLIKELY(x) __builtin_expect(!!(x), 0)

#ifdef BEND_DEBUG_FREE
#include <execinfo.h>
// The call stack of each free, by its number (a ring of the last 2^20).
extern void *bend_debug_stk[1 << 20][12];
void bend_debug_record(uint64_t n);
void bend_debug_show(uint64_t n);
static inline V TAG(V v) {
  if (v & 1) return v >> 3;
  V t = ((V *)v)[0];
  if ((t >> 48) == 0xDEAD) {
    fprintf(stderr, "bend: a node freed at line %u (free number %llu, thread %02x) is used by thread %02x\n",
      (unsigned)(t & 0xfffff), (unsigned long long)((t >> 20) & 0xfffff), (unsigned)((t >> 40) & 0xff),
      (unsigned)(((uintptr_t)pthread_self() >> 12) & 0xff));
    bend_debug_show((t >> 20) & 0xfffff);
    abort();
  }
  return t & ~BEND_SH_BITS;
}
#else
static inline V TAG(V v) { return (v & 1) ? (v >> 3) : ((V *)v)[0] & ~BEND_SH_BITS; }
#endif

__attribute__((noreturn)) void bend_fail(const char *msg);

// Garbage collector
// =================
//
// The heap is one reserved region cut into 64 KB blocks. A small block holds
// slots of one size class; a large object takes whole blocks. Each block
// starts with a header holding an allocation and a mark bitmap. Every word
// of a live object, of a thread's stack and of the registered roots is read
// as a possible pointer; pointers into the middle of an object keep it too.
// A thread allocates from a private free list; the block behind that list
// is not swept until the thread moves on to another one.

#define GC_BLK_SHIFT 16
#define GC_BLK ((uintptr_t)1 << GC_BLK_SHIFT)
#define GC_MAXBLK ((uintptr_t)1 << 22)
#define GC_HDR 64
#define GC_SMALL 256
#define GC_NCLS 31
#define GC_MAXTHR 256
#define GC_SIG SIGUSR2

typedef struct GcBlk {
  uint32_t words;    // slot size (small) or object size (large), in words
  uint32_t nobj;     // slots in the block (1 for a large object)
  uint32_t nblk;     // blocks spanned
  uint8_t atomic;    // holds no pointers: never scanned
  uint8_t large;
  uint8_t owned;     // in a thread's cache: not swept
  uint8_t cls;
  struct GcBlk *next;
} GcBlk;

// What matches and the collector read most, by block index, in dense tables
// (a block's own header is a page away from most of its objects): a block's
// allocation and mark bits (gc_abits, gc_mbits: 64 words a block), and:
typedef struct GcMeta {
  uint32_t recip;    // 2^32 / slot bytes, rounded up: a slot's index by multiplying
  uint8_t large, pad[3];
} GcMeta;
_Static_assert(sizeof(GcBlk) <= GC_HDR, "GC_HDR holds a block header");

// A thread's allocation cache for one size class: a fresh block is handed out
// by bumping; a partly free one by the free bits of its bitmap, a word at a
// time (the slots are not touched until they are handed out).
typedef struct GcCache {
  V *bump; V *end; GcBlk *blk; V *objs;
  uint8_t reuse;    // the block came from the reuse queue: its slots are not new memory
  uint64_t bits;    // free slots of word j
  uint32_t idx, j, nj;
} GcCache;

struct PDeque;

// Classes of up to 16 words (nodes) reuse the slots matches free.
#define GC_RQCLS 15

typedef struct Thr {
  GcCache cache[2][GC_NCLS];
  uint32_t rcur[GC_RQCLS];  // where the next search for a reuse block starts
  uintptr_t top;
  volatile uintptr_t sp;
  pthread_t id;
  volatile int live;
  struct PDeque *dq;
  uint32_t rng;
} Thr;

typedef struct { V *p; size_t n; } GcRange;
typedef struct { uint32_t at, len; } GcRun;

extern const uint16_t gc_cls_w[GC_NCLS];
extern uint8_t gc_cls_of[GC_SMALL + 1];

extern char *gc_base;
extern uint64_t *gc_abits;
extern uint64_t *gc_mbits;
extern GcMeta *gc_meta;
extern uintptr_t gc_top;
extern uint8_t *gc_kind;
extern uint32_t *gc_back;
extern GcRun *gc_runs;
extern size_t gc_nruns;
extern pthread_mutex_t gc_lock;
extern GcBlk *gc_partial[2][GC_NCLS];
extern _Atomic size_t gc_since;
extern size_t gc_limit;
extern size_t gc_limit_min;
// (Read at start: libc's number parsing takes a lock a stopped thread may hold.)
extern double gc_minor_k;
extern size_t gc_slack;
extern size_t gc_live_bytes;
extern size_t gc_major_live;
extern int gc_minor;
extern int gc_rooting;
extern int gc_all_major;
extern size_t gc_count;
extern int gc_stats;
extern Thr *gc_thrs[GC_MAXTHR];
extern int gc_nthr;
// Nodes with an open hole (BEND_HOLE) that a thread's stack or registers
// pointed to at the last collection, which the next minor collection
// rescans: the only objects written after they are made are the nodes D_
// functions build with a hole, and a node whose hole was open at a
// collection was reachable from a root then (by dst, or, just made, by a
// register of a thread the collection stopped).
extern V *gc_rem;
extern size_t gc_nrem;
extern size_t gc_caprem;
extern V *gc_rem_prev;
extern size_t gc_nprev;
extern size_t gc_capprev;
// Per class, a bit per block: matches freed slots in it (GC_CANDW words a
// class).
#define GC_CANDW (GC_MAXBLK / 64)
extern uint64_t *gc_cand;
// More than one thread runs Bend code (frees must then be atomic).
extern int gc_mt;
// What bend_take and bend_share read, together (one address to load).
typedef struct GcHot {
  uintptr_t base, span;  // the heap: gc_base, and gc_top in bytes
  uint64_t *abits, *cand;
  int mt;
} GcHot;
extern GcHot gc_hot;
extern GcRange *gc_roots;
extern size_t gc_nroots;
extern size_t gc_caproots;
extern void (*gc_hooks[16])(void);
extern int gc_nhooks;
extern _Atomic int gc_stopping;
extern _Atomic int gc_acks;
extern _Atomic int gc_inside;
extern __thread Thr *thr_self;

typedef struct { V *p; size_t n; } GcItem;
extern GcItem *gc_stk;
extern size_t gc_sp;
extern size_t gc_cap;

void *gc_reserve(size_t bytes, void *hint);

void gc_init(void);

static inline GcBlk *gc_blk(uintptr_t i) { return (GcBlk *)(gc_base + (i << GC_BLK_SHIFT)); }
static inline uintptr_t gc_bi(const GcBlk *b) { return ((uintptr_t)b - (uintptr_t)gc_base) >> GC_BLK_SHIFT; }
#define GC_ALLOC(b) (gc_abits + gc_bi(b) * 64)
#define GC_MARK(b) (gc_mbits + gc_bi(b) * 64)
#define GC_META(b) (&gc_meta[gc_bi(b)])
static inline V *gc_objs(GcBlk *b) { return (V *)((char *)b + GC_HDR); }

// Takes n contiguous free blocks (gc_lock held).
uintptr_t gc_take_blocks(size_t n);

void gc_collect_locked(void);

GcBlk *gc_new_small(int atomic, unsigned c);

// The next word of free bits in the cache's block; 0 when none is left.
static inline uint64_t gc_next_bits(GcCache *k) {
  GcBlk *b = k->blk;
  while (++k->j < k->nj) {
    uint64_t f = ~GC_ALLOC(b)[k->j];
    if (k->j == (b->nobj >> 6)) f &= (1ull << (b->nobj & 63)) - 1;
    if (f) return f;
  }
  return 0;
}

// Slow path: the rest of the block's free words, or another block.
__attribute__((noinline)) V *gc_refill(GcCache *k, int atomic, unsigned c);

__attribute__((noinline)) V *gc_alloc_large(size_t w, int atomic);

// A slot is not cleared when freed: the words of a class slot past the
// object's own are cleared here, so stale words never look like pointers.
// hole: a D_ node (a constant): its tag word holds BEND_HOLE before the slot
// is allocated, so no collection sees it without (see gc_rem).
static inline V *gc_alloc_x(size_t w, int atomic, int hole) {
  if (UNLIKELY(w > GC_SMALL)) return gc_alloc_large(w, atomic);
  unsigned c = w >= 2 && w <= 16 ? (unsigned)w - 2 : gc_cls_of[w];
  GcCache *k = &thr_self->cache[atomic][c];
  V *p;
  if (k->bump < k->end) {
    p = k->bump;
    k->bump += gc_cls_w[c];
    uint32_t i = k->idx++;
    if (hole) { p[0] = BEND_HOLE; BEND_BARRIER(); }
    GC_ALLOC(k->blk)[i >> 6] |= 1ull << (i & 63);
  } else if (k->bits) {
    int t = __builtin_ctzll(k->bits);
    k->bits &= k->bits - 1;
    uint32_t i = k->j * 64 + (uint32_t)t;
    p = k->objs + (size_t)i * gc_cls_w[c];
    if (hole) { p[0] = BEND_HOLE; BEND_BARRIER(); }
    GC_ALLOC(k->blk)[i >> 6] |= 1ull << (i & 63);
  } else {
    p = gc_refill(k, atomic, c);
  }
  if (!hole) p[0] = 0;
  p[1] = 0;
  if (!(w >= 2 && w <= 16))
    for (size_t j = w; j < gc_cls_w[c]; j++) p[j] = 0;
  return p;
}

static inline V *gc_alloc(size_t w, int atomic) { return gc_alloc_x(w, atomic, 0); }
static inline V *halloc(size_t words) { return gc_alloc_x(words, 0, 0); }
static inline V *halloc_hole(size_t words) { return gc_alloc_x(words, 0, 1); }

// Freeing on match
// ----------------
//
// Bend values are affine: a value has one owner unless it went through a
// variable used more than once. Generated code marks such values shared
// (bend_share) where the variable is bound, and a match that opens a node
// hands it to bend_take: a shared node stays (and the fields it hands out
// become shared too), any other is dead once its fields are read, so its slot
// goes on the thread's free list, and the next allocation of its size takes
// it. A freed slot's mark is cleared: reused, it is a young object for minor
// collections. The free lists are roots, so a collection keeps them.

// The small block and slot index of a heap object, or 0 when v is not one.
static inline GcBlk *gc_slot(V v, uint32_t *idx) {
  uintptr_t off = (uintptr_t)v - (uintptr_t)gc_base;
  if (UNLIKELY(off >= (gc_top << GC_BLK_SHIFT))) return NULL;
  uintptr_t bi = off >> GC_BLK_SHIFT;
  if (UNLIKELY(gc_kind[bi] != 1)) return NULL;
  GcBlk *b = gc_blk(bi);
  *idx = (uint32_t)(((uint64_t)((uintptr_t)v - (uintptr_t)gc_objs(b)) * GC_META(b)->recip) >> 32);
  return b;
}

// Marks a value shared: a node by its tag word, a closure by its captured
// values (calling it twice hands them out twice). Anything else (a number
// that falls in the heap, say) is left alone: the value must be the start of
// an allocated object.
__attribute__((noinline)) void bend_share_slow(V v);

// Numbers, characters and nullary constructors are below 2^32, and the heap
// above (gc_init); a node already shared says so in its tag word (reading any
// heap address is safe; writing needs the checks above).
static inline void bend_share(V v) {
  if (v < ((V)1 << 32) || (uintptr_t)v - gc_hot.base >= gc_hot.span) return;
  V w0 = __atomic_load_n((V *)v, __ATOMIC_RELAXED);
  if ((w0 & BEND_SH) && w0 < ((V)1 << 22)) return;
  bend_share_slow(v);
}

// A shared node's fields, marked shared once: after them, the node's
// BEND_DEEP (a thread that sees it sees them marked).
__attribute__((noinline)) void bend_deep(V v, unsigned w);

// A match opened node v, of w words, after reading its fields: 1 when it is
// shared (its fields are then shared too), else 0 and its slot is freed, and
// its block a reuse candidate for its class (gc_refill takes it when a 5th of
// it is free). Nodes of up to 16 words are in small blocks whose slots are
// exactly their size; larger ones are never freed.
static inline int bend_take_at(V v, unsigned w, unsigned line) {
  const GcHot *h = &gc_hot;
  V w0 = h->mt ? __atomic_load_n((V *)v, __ATOMIC_ACQUIRE) : __atomic_load_n((V *)v, __ATOMIC_RELAXED);
  if (w0 & BEND_SH) {
    if (!(w0 & BEND_DEEP)) bend_deep(v, w);
    return 1;
  }
  uintptr_t off = (uintptr_t)v - h->base;
  if (UNLIKELY(off >= h->span || w > 16)) { bend_deep(v, w); return 1; }
  uintptr_t bi = off >> GC_BLK_SHIFT;
  uint32_t i = (uint32_t)(((off & (GC_BLK - 1)) - GC_HDR) / (w * sizeof(V)));
  uint64_t bit = 1ull << (i & 63);
  uint64_t *aw = &h->abits[bi * 64 + (i >> 6)];
#ifdef BEND_DEBUG_FREE
  // Debugging: the node is poisoned with the line that freed it and the
  // free's number, and kept. BEND_DEBUG_FREE_AT=n aborts at free number n.
  {
    static uint64_t nfreed;
    static long stop = -2;
    if (stop == -2) stop = getenv("BEND_DEBUG_FREE_AT") ? atol(getenv("BEND_DEBUG_FREE_AT")) : -1;
    nfreed++;
    if ((long)nfreed == stop) abort();
    V who = (V)(((uintptr_t)pthread_self() >> 12) & 0xff);
    bend_debug_record(nfreed & 0xfffff);
    for (unsigned j = 0; j < w; j++) ((V *)v)[j] = ((V)0xDEAD << 48) | (who << 40) | ((nfreed & 0xfffff) << 20) | line;
    (void)bit; (void)aw;
  }
  return 0;
#endif
  (void)line;
  uint64_t *cw = &h->cand[(size_t)(w - 2) * GC_CANDW + (bi >> 6)];
  // A freed slot is young when it is handed out again: its mark goes too,
  // after its allocation bit (no collection marks it then), and in one
  // instruction when other threads run (a collection may stop this one
  // anywhere and set other marks of the word).
  uint64_t *mw = &gc_mbits[bi * 64 + (i >> 6)];
  if (UNLIKELY(h->mt)) {
    __atomic_fetch_and(aw, ~bit, __ATOMIC_RELAXED);
    if (UNLIKELY(*mw & bit)) __atomic_fetch_and(mw, ~bit, __ATOMIC_RELAXED);
    // (a sample of the frees keeps the shared candidate words cool)
    if ((i & 15) == 0 && !(*cw & (1ull << (bi & 63))))
      __atomic_fetch_or(cw, 1ull << (bi & 63), __ATOMIC_RELAXED);
  } else {
    *aw &= ~bit;
    *mw &= ~bit;
    *cw |= 1ull << (bi & 63);
  }
  return 0;
}

// With BEND_DEBUG_FREE, a freed node records the generated C line that
// freed it, and TAG reports a read of one.
#ifdef BEND_DEBUG_FREE
#define bend_take(v, w) bend_take_at(v, w, __LINE__)
#else
#define bend_take(v, w) bend_take_at(v, w, 0)
#endif

// Registers words that hold values (a global cache, say) as roots.
void gc_root_add_locked(V *p, size_t n);

void gc_root_add(V *p, size_t n);

void gc_hook(void (*f)(void));

// Whether a root's object may still get written: it holds BEND_HOLE, an open
// hole of a D_ node (or it is still being made: see gc_alloc and C2).
int gc_rem_wants(GcBlk *b, uint32_t i, uint64_t bit, uintptr_t o);

static inline void gc_mark(V w) {
  uintptr_t a = (uintptr_t)(w & 0x7fffffffffffffffull);
  uintptr_t off = a - (uintptr_t)gc_base;
  if (off >= (gc_top << GC_BLK_SHIFT)) return;
  uintptr_t bi = off >> GC_BLK_SHIFT;
  uint8_t kd = gc_kind[bi];
  if (kd == 0) return;
  if (kd == 3) bi -= gc_back[bi];
  GcBlk *b = gc_blk(bi);
  uintptr_t o = (uintptr_t)gc_objs(b);
  if (a < o) return;
  size_t i = 0;
  if (b->large) {
    if (a >= o + (uintptr_t)b->words * sizeof(V)) return;
  } else {
    i = (a - o) / ((uintptr_t)b->words * sizeof(V));
    if (i >= b->nobj) return;
  }
  uint64_t bit = 1ull << (i & 63);
  if (!(GC_ALLOC(b)[i >> 6] & bit)) return;
  if (gc_rooting == 1 && !b->atomic && !b->large && gc_rem_wants(b, i, bit, o)) {
    if (gc_nrem == gc_caprem) {
      gc_caprem = gc_caprem ? gc_caprem * 2 : 256;
      gc_rem = realloc(gc_rem, gc_caprem * sizeof(V));
    }
    gc_rem[gc_nrem++] = (V)(o + i * (uintptr_t)b->words * sizeof(V));
  }
  // A minor collection scans an old object met from a root once more: its
  // fields may have been written after it got old.
  if ((GC_MARK(b)[i >> 6] & bit) && !(gc_minor && gc_rooting)) return;
  GC_MARK(b)[i >> 6] |= bit;
  if (b->atomic) return;
  if (gc_sp == gc_cap) bend_fail("the collector's mark stack overflowed");
  gc_stk[gc_sp++] = (GcItem){(V *)(o + i * (uintptr_t)b->words * sizeof(V)), b->words};
}

void gc_scan(const void *lo, const void *hi);

void gc_drain(void);

void gc_handler(int sig);

void gc_sweep(void);

int gc_rem_cmp(const void *a, const void *b);

// A stack holds many pointers to the same objects: each is kept once.
void gc_rem_unique(void);

__attribute__((noinline)) void gc_collect_locked(void);

// Collects now (from a thread that runs Bend code).
void gc_collect(void);

struct PDeque *pdq_new(void);

// Registers the calling thread; top is an address near the base of its stack.
void thr_register(uintptr_t top);

// Constructors and closures
// =========================

static inline V C1(V t, V a) { V *p = halloc(2); p[0] = t; p[1] = a; return (V)p; }
static inline V C2(V t, V a, V b) { V *p = halloc(3); p[0] = t; p[1] = a; p[2] = b; return (V)p; }
static inline V C3(V t, V a, V b, V c) { V *p = halloc(4); p[0] = t; p[1] = a; p[2] = b; p[3] = c; return (V)p; }
static inline V C4(V t, V a, V b, V c, V d) {
  V *p = halloc(5); p[0] = t; p[1] = a; p[2] = b; p[3] = c; p[4] = d; return (V)p;
}
static inline V CN(V t, int n, const V *xs) {
  V *p = halloc(n + 1); p[0] = t;
  for (int i = 0; i < n; i++) p[i + 1] = xs[i];
  return (V)p;
}

// A D_ node (one field is BEND_HOLE): its tag word holds BEND_HOLE from
// before the slot is allocated until its fields, the hole among them, are
// stored, so a collection that stops the thread in between sees the hole.
static inline V CH1(V t, V a) { V *p = halloc_hole(2); p[1] = a; BEND_BARRIER(); p[0] = t; return (V)p; }
static inline V CH2(V t, V a, V b) { V *p = halloc_hole(3); p[1] = a; p[2] = b; BEND_BARRIER(); p[0] = t; return (V)p; }
static inline V CH3(V t, V a, V b, V c) {
  V *p = halloc_hole(4); p[1] = a; p[2] = b; p[3] = c; BEND_BARRIER(); p[0] = t; return (V)p;
}
static inline V CH4(V t, V a, V b, V c, V d) {
  V *p = halloc_hole(5); p[1] = a; p[2] = b; p[3] = c; p[4] = d; BEND_BARRIER(); p[0] = t; return (V)p;
}
static inline V CHN(V t, int n, const V *xs) {
  V *p = halloc_hole(n + 1);
  for (int i = 0; i < n; i++) p[i + 1] = xs[i];
  BEND_BARRIER();
  p[0] = t;
  return (V)p;
}

static inline V mk_clo(Fn f, V arity, V n, const V *args) {
  V *p = halloc(3 + n);
  p[0] = (V)f; p[1] = arity; p[2] = n;
  for (V i = 0; i < n; i++) p[3 + i] = args[i];
  return (V)p;
}

V apply(V f, V x);

// Strings (cons lists of code points)
// -----------------------------------

#define SNIL IMM(0)
#define SCONS(h, t) C2(1, (h), (t))
#define NIL IMM(0)
#define CONS(h, t) C2(1, (h), (t))

// Builds a String from UTF-8 bytes. Strings are built from the end, so no
// cell is written after it is made (minor collections rely on that).
V mk_str(const char *s, size_t n);

#define MKS(lit) mk_str(lit, sizeof(lit) - 1)
// The acquire pairs with str_cache's release: a thread that sees the string
// sees it shared.
#define STRC(c, lit) (__atomic_load_n(&(c), __ATOMIC_ACQUIRE) ? (c) : str_cache(&(c), lit, sizeof(lit) - 1))
#define mk_str_heap mk_str

// A string literal, built once (slot is its cache, a root).
__attribute__((noinline)) V str_cache(V *slot, const char *s, size_t n);

// Encodes a String as a malloc'd UTF-8 buffer.
char *str_to_c(V s, size_t *len);

// Natives: Nat (unbounded)
// ------------------------

#define NAT_BIG ((V)1 << 63)
static inline V *nat_p(V x) { return (V *)(uintptr_t)(x & ~NAT_BIG); }

// The limbs of x (little-endian); a small x is written to *buf.
static inline const V *nat_limbs(V x, V *buf, size_t *n) {
  if (x >> 63) { V *p = nat_p(x); *n = (size_t)p[0]; return p + 1; }
  *buf = x;
  *n = x ? 1 : 0;
  return buf;
}

// A Nat from n limbs (normalized; small when it fits).
V nat_make(const V *d, size_t n);

int nat_cmp3(V a, V b);

V nat_add(V a, V b);

// a - b, or 0 when b >= a.
V nat_sub(V a, V b);

V nat_mul(V a, V b);

// Divides u (m limbs) by v (n >= 2 limbs, m >= n): Knuth's algorithm D.
void nat_divlimbs(const V *u, size_t m, const V *v, size_t n, V *q, V *r);

// (a / b, a % b); dividing by 0 gives (0, a), as Base's Nat.divmod does.
void nat_divmod2(V a, V b, V *qo, V *ro);

V nat_pow(V a, V n);

// Decimal digits of x (malloc'd, NUL-terminated).
char *nat_digits(V x);

static inline V nat_addk(V x, V k) { return LIKELY(!(x >> 63)) && x + k < NAT_BIG ? x + k : nat_add(x, k); }
static inline V nat_subk(V x, V k) { return LIKELY(!(x >> 63)) ? x - k : nat_sub(x, k); }
static inline int nat_ge(V x, V k) { return (x >> 63) || x >= k; }

static inline V F_Nat_ddouble(V a) { return nat_add(a, a); }
static inline V F_Nat_dadd(V a, V b) { return nat_add(a, b); }
static inline V F_Nat_dsub(V a, V b) { return nat_sub(a, b); }
static inline V F_Nat_dmul(V a, V b) { return nat_mul(a, b); }
static inline V F_Nat_ddivmod(V a, V b) { V q, r; nat_divmod2(a, b, &q, &r); return C2(0, q, r); }
static inline V F_Nat_ddiv(V a, V b) { V q, r; nat_divmod2(a, b, &q, &r); return q; }
static inline V F_Nat_dmod(V a, V b) { V q, r; nat_divmod2(a, b, &q, &r); return r; }
static inline V F_Nat_dcmp(V a, V b) { int c = nat_cmp3(a, b); return c < 0 ? IMM(0) : c == 0 ? IMM(1) : IMM(2); }
static inline V F_Nat_dis__eq(V a, V b) { return BOOL(nat_cmp3(a, b) == 0); }
static inline V F_Nat_dis__ne(V a, V b) { return BOOL(nat_cmp3(a, b) != 0); }
static inline V F_Nat_dis__lt(V a, V b) { return BOOL(nat_cmp3(a, b) < 0); }
static inline V F_Nat_dis__le(V a, V b) { return BOOL(nat_cmp3(a, b) <= 0); }
static inline V F_Nat_dis__gt(V a, V b) { return BOOL(nat_cmp3(a, b) > 0); }
static inline V F_Nat_dis__ge(V a, V b) { return BOOL(nat_cmp3(a, b) >= 0); }
static inline V F_Nat_dmin(V a, V b) { return nat_cmp3(a, b) < 0 ? a : b; }
static inline V F_Nat_dmax(V a, V b) { return nat_cmp3(a, b) < 0 ? b : a; }
static inline V F_Nat_dpow(V a, V n) { return nat_pow(a, n); }
V F_Nat_dshow(V a);

// Map.bit(key, pos): bit pos of key as Base's tries read it (char pos / 33;
// offset 0 is "the char exists", offset 1 + b is bit 31 - b of its code),
// with the key handed back. Base rebuilds the key's prefix to hand it back;
// here the key is shared, so a lookup allocates nothing.
#ifdef BEND_NATIVE_MAP_BIT
static inline V F_Map_dbit(V key, V pos) {
  if (pos >> 63) return C2(0, key, IMM(0));
  V ci = pos / 33, off = pos % 33, s = key;
  for (;;) {
    if (s == SNIL) return C2(0, key, IMM(0));
    if (ci == 0) break;
    s = ((V *)s)[2];
    ci--;
  }
  V x = ((V *)s)[1];
  return C2(0, key, off == 0 ? IMM(1) : (((uint32_t)x >> (32 - off)) & 1) ? IMM(1) : IMM(0));
}
#endif

// Natives: U32
// ------------

#define U(x) ((uint32_t)(x))
static inline V nat_low32(V n) { return (n >> 63) ? U(nat_p(n)[1]) : U(n); }
static inline V F_U32_dinc(V a) { return U(a + 1); }
static inline V F_U32_dadd(V a, V b) { return U(a + b); }
static inline V F_U32_dsub(V a, V b) { return U(a - b); }
static inline V F_U32_dmul(V a, V b) { return U(U(a) * U(b)); }
static inline V F_U32_ddiv(V a, V b) { return b == 0 ? 0 : U(a) / U(b); }
static inline V F_U32_dmod(V a, V b) { return b == 0 ? a : U(a) % U(b); }
static inline V F_U32_dnot(V a) { return U(~a); }
static inline V F_U32_dand(V a, V b) { return a & b; }
static inline V F_U32_dor(V a, V b) { return a | b; }
static inline V F_U32_dxor(V a, V b) { return a ^ b; }
static inline V F_U32_dshl(V a) { return U(a << 1); }
static inline V F_U32_dshr(V a) { return a >> 1; }
static inline V F_U32_dshln(V a, V n) { return n >= 32 ? 0 : U(a << n); }
static inline V F_U32_dshrn(V a, V n) { return n >= 32 ? 0 : a >> n; }
static inline V F_U32_dcmp(V a, V b) { return a < b ? IMM(0) : a == b ? IMM(1) : IMM(2); }
static inline V F_U32_dis__eq(V a, V b) { return BOOL(a == b); }
static inline V F_U32_dis__ne(V a, V b) { return BOOL(a != b); }
static inline V F_U32_dis__lt(V a, V b) { return BOOL(a < b); }
static inline V F_U32_dis__le(V a, V b) { return BOOL(a <= b); }
static inline V F_U32_dis__gt(V a, V b) { return BOOL(a > b); }
static inline V F_U32_dis__ge(V a, V b) { return BOOL(a >= b); }
static inline V F_U32_dis__zero(V a) { return BOOL(a == 0); }
static inline V F_U32_dis__even(V a) { return BOOL((a & 1) == 0); }
static inline V F_U32_dto__nat(V a) { return a; }
static inline V F_U32_dfrom__nat(V n) { return nat_low32(n); }
static inline V F_U32_dmin(V a, V b) { return a < b ? a : b; }
static inline V F_U32_dmax(V a, V b) { return a < b ? b : a; }
static inline V F_U32_dpow(V a, V n) {
  // a^n mod 2^32; an odd a has an order dividing 2^30, an even one reaches 0.
  V e;
  if (n >> 63) { if (!(a & 1)) return 0; e = nat_p(n)[1] & ((1u << 30) - 1); }
  else e = n;
  uint32_t r = 1, b = U(a);
  for (; e; e >>= 1) { if (e & 1) r *= b; b *= b; }
  return r;
}
static inline V F_U32_dlog2(V n) {
  V d = 0;
  while (n > 1) { d++; n >>= 1; }
  return d;
}

// Natives: F32 (stored as IEEE bits)
// ----------------------------------

static inline float FV(V v) { union { uint32_t u; float f; } x; x.u = U(v); return x.f; }
static inline V VF(float f) { union { uint32_t u; float f; } x; x.f = f; return x.u; }
#define F2(name, expr) static inline V F_F32_d##name(V a, V b) { float x = FV(a), y = FV(b); return expr; }
#define F1(name, expr) static inline V F_F32_d##name(V a) { float x = FV(a); return expr; }
F2(add, VF(x + y))
F2(sub, VF(x - y))
F2(mul, VF(x * y))
F2(div, VF(x / y))
F2(mod, VF(fmodf(x, y)))
F2(pow, VF(powf(x, y)))
F2(atan2, VF(atan2f(x, y)))
F2(is__eq, BOOL(x == y))
F2(is__ne, BOOL(x != y))
F2(is__lt, BOOL(x < y))
F2(is__le, BOOL(x <= y))
F2(is__gt, BOOL(x > y))
F2(is__ge, BOOL(x >= y))
F1(neg, VF(-x))
F1(abs, VF(fabsf(x)))
F1(sqrt, VF(sqrtf(x)))
F1(exp, VF(expf(x)))
F1(log, VF(logf(x)))
F1(log2, VF(log2f(x)))
F1(log10, VF(log10f(x)))
F1(sin, VF(sinf(x)))
F1(cos, VF(cosf(x)))
F1(tan, VF(tanf(x)))
F1(asin, VF(asinf(x)))
F1(acos, VF(acosf(x)))
F1(atan, VF(atanf(x)))
F1(sinh, VF(sinhf(x)))
F1(cosh, VF(coshf(x)))
F1(tanh, VF(tanhf(x)))
F1(floor, VF(floorf(x)))
F1(ceil, VF(ceilf(x)))
F1(trunc, VF(truncf(x)))
static inline V F_F32_dbits(V a) { return U(a); }
static inline V F_F32_dto__u32(V a) { float x = FV(a); return x <= 0 ? 0 : x >= 4294967295.0f ? 0xffffffffu : (uint32_t)x; }
static inline V F_U32_dto__f32(V a) { return VF((float)U(a)); }
V F_F32_dshow(V a);
V F_F32_dread(V s);

// Parallel calls
// ==============
//
// A parallel let `a b = f(x) g(y)` forks every value but the last as a task
// (a closure applied to a dummy argument), evaluates the last one, then joins
// the tasks in reverse. Each thread owns a Chase-Lev deque: it pushes and
// pops at the bottom, idle threads steal from the top. A task nobody stole
// runs inline at its join, so a fork costs little more than a closure.

#define P_LOCAL 0
#define P_QUEUED 1
#define P_DONE 2

typedef struct PTask { V clo; V res; V state; V depth; } PTask;

// The fork depth of the running code, and the frontier past which a def
// with a sequential clone (S_name, see bendc) runs its parallel lets in
// order: below it, forking costs more than it balances.
extern __thread int par_depth;
extern int par_front;

typedef struct PDeque {
  _Atomic long top;
  _Atomic long bot;
  long mask;
  PTask **buf;
} PDeque;

extern int par_nthreads;
extern _Atomic int par_started;
extern pthread_mutex_t par_mu;
extern pthread_cond_t par_cv;
extern _Atomic int par_sleepers;

PDeque *pdq_new(void);

PTask *pdq_pop(PDeque *d);

PTask *pdq_steal(PDeque *d);

void par_exec(PTask *t);

PTask *par_steal(void);

static inline void cpu_relax(void) {
#if defined(__x86_64__)
  __builtin_ia32_pause();
#elif defined(__aarch64__)
  __asm__ __volatile__("yield");
#endif
}

void *par_worker(void *arg);

void par_hook(void);

void par_start(void);

// Forks clo (a closure taking one dummy argument); returns the task. Only a
// thread whose deque is nearly empty queues it (the oldest tasks, which
// thieves take, are the big ones); otherwise the fork is the closure itself,
// tagged with bit 1, and its join just applies it.
V par_fork(V clo);

// Waits for a forked task and returns its value.
V par_join(V tv);

int cpu_count(void);

// Effects
// =======
//
// An effect def compiles to a request node {cid | n << 24, args..., k}. The
// event loop runs each computation's pure code up to its next request, runs
// the effect's host function, then resumes k with the answer. The host
// functions use the official runtime's names and conventions: see
// EFFECTS.md in the Bend guide. A CID encodes how a constructor is laid out
// here: kind << 16 | tag, where kind 0 is a node, 1 a nullary constructor,
// 2 a single-field single-constructor type (the field itself), and 3 an
// effect (its tag is its row in io_eff_rows).

#ifndef CID_TUPLE
#define CID_TUPLE 0u
#endif
#ifndef CID_DONE
#define CID_DONE 1u
#endif
#ifndef CID_FAIL
#define CID_FAIL 0u
#endif
#ifndef CID_SOME
#define CID_SOME 1u
#endif
#ifndef CID_NONE
#define CID_NONE ((1u << 16) | 0u)
#endif
#ifndef CID_TRUE
#define CID_TRUE ((1u << 16) | 1u)
#endif
#ifndef CID_FALSE
#define CID_FALSE ((1u << 16) | 0u)
#endif
#ifndef CID_UNIT
#define CID_UNIT ((1u << 16) | 0u)
#endif

// A request node for effect cid with n fields (its arguments, then k).
static inline V io_req(u64 cid, int n, const V *xs) { return CN(cid | ((V)n << 24), n, xs); }

typedef struct { int unused; } Env;
typedef pthread_mutex_t lock;
#define OUTLINE __attribute__((noinline))
#define IO_READ 1
#define IO_TIME 2
#define IO_HELP 64
extern V io_hole_cell;
#define TERM_HOLE ((Term)(uintptr_t)&io_hole_cell)
#define IO_PARK TERM_HOLE
#define io_hand(v) ((Term)(v))
#define io_hand_v(t) ((u64)(t))
#define CID_KIND(c) ((u32)(c) >> 16)
#define CID_TAG(c) ((u32)(c) & 0xffff)

__attribute__((noreturn)) void err_fail(const char *msg);

static inline Term term_pak(u64 cid, Term v) {
  switch (CID_KIND(cid)) {
    case 1: return IMM(CID_TAG(cid));
    case 2: return v;
    default: return C1(CID_TAG(cid), v);
  }
}

// The CID of a constructor value (a node's or a nullary one's).
static inline u64 term_aux(Term t) { return (t & 1) ? ((1u << 16) | (u32)(t >> 3)) : ((V *)t)[0] & ~BEND_SH_BITS; }
#define term_drop(e, t) ((void)(e), (void)(t))
#define term_sink(e, t) ((void)(e), (void)(t))
#define cls_fit(n) 0
#define spare_free(e, c, x) ((void)(e), (void)(c), (void)(x))
static inline int ctr_take(Env e, Term t, u32 n, Term *fb) {
  (void)e;
  for (u32 i = 0; i < n; i++) fb[i] = FLD(t, i);
  return 0;
}

struct IoWork;
typedef void (*IoCall)(struct IoWork *w);
typedef Term (*IoPack)(Env e, struct IoWork *w);

typedef struct IoWork {
  intptr_t hand;
  intptr_t made;
  u32 word;
  u64 size;
  char *data;
  char *text;
  u32 code;
  IoCall call;
  IoPack pack;
} IoWork;

typedef Term (*Effect)(Env e, Term *f, IoWork *w);

typedef struct {
  Effect run;
  u32 ask;
} IoEff;

extern IoEff io_eff_rows[1 << 16];
extern u32 io_live;
extern int io_argc;
extern char **io_argv;

void io_eff(u32 cid, Effect run, u32 need);

u64 io_tick(void);

OUTLINE void *io_mem(void *mem);

int io_sys_addr(const char *host, u32 port, struct sockaddr_in *at);

u64 io_sys_end(IoWork *w, ssize_t n);

// One computation: cont applied to item is its next request. Leading work
// permits IoWork* to IoAct* casts. Every live act is on a list the collector
// reads.
typedef struct IoAct {
  IoWork work;
  Term cont;
  Term item;
  u64 time;
  short evts;
  struct IoAct *next;
  struct IoAct *gprev, *gnext;
} IoAct;

typedef struct {
  IoAct *head;
  IoAct *last;
} IoQue;

extern IoQue io_runs;
extern IoQue io_park;
extern IoQue io_jobs;
extern IoAct *io_acts;

void io_push(IoQue *q, IoAct *a);

IoAct *io_pop(IoQue *q);

IoAct *io_act_new(void);

void io_act_free(IoAct *a);

V io_start_fn(V *a);
V io_emit_fn(V *a);

// Starts m (an IO) as a new computation.
void io_spawn(Term m);

// Parks until evts (POLLIN/POLLOUT; 0 ignores fd) or time (0: no deadline).
// The loop calls more: a value resumes, IO_PARK re-parks.
Term io_wait_on(IoWork *w, int fd, short evts, u64 time, IoPack more);

u64 io_wait_time(IoWork *w);

OUTLINE void io_out(FILE *h, const char *data, u64 len);

OUTLINE void io_sync(void);

u64 io_utf8(char *buf, u64 c);

OUTLINE char *io_cstr(Env e, Term s, u64 *len);

OUTLINE void io_errs(Env e, Term s);

#define io_nul(s, n) (strlen(s) != (n))

Term io_box(Env e, u64 cid, Term v);

Term io_node(Env e, u64 cid, Term a, Term b);

// Decodes UTF-8 as WHATWG does: a byte that breaks a sequence yields one
// U+FFFD and is read again as a lead.
Term io_str(Env e, const char *p, u64 n);

#define io_tup(e, a, b) io_node(e, CID_TUPLE, a, b)
#define io_done(e, v) io_box(e, CID_DONE, v)

Term io_fail(Env e, u32 code, const char *text);

extern pthread_mutex_t io_gate;
extern pthread_cond_t io_bell;
extern u32 io_busy;
extern u32 io_size;
extern int io_wake_fd[2];

void io_take(Env e);

void *io_help(void *arg);

// Runs call on a helper thread, then pack on the loop to resume the effect.
Term io_work(IoWork *w, IoCall call, IoPack pack);

// Takes cont's request node apart; the effect returns a value or IO_PARK.
Term io_exec(Env e, IoWork *w);

// macOS poll misses FIFO EOF, so the loop waits with select.
bool io_bit(u8 *set, int fd, bool put);

void io_wait(Env e);

// Runs a computation up to its next park; returns an exit code on a Halt.
int io_step(Env e, IoAct *a);

// Chan
// ----

typedef struct {
  u32 gen;
  u32 next;
  u32 room;
  u32 size;
  u32 head;
  u32 live;
  u32 shut;
  Term *ring;
  IoQue wait;
} ChanRow;

extern ChanRow *chan_rows;
extern u32 chan_len;
extern u32 chan_idle;

#define chan_some(e, v) io_box(e, CID_SOME, v)
#define chan_bool(b) term_pak((b) ? CID_TRUE : CID_FALSE, 0)

Term chan_open(u32 room);

ChanRow *chan_at(Term t);

// Parks the effect's activation on row with item: a sent value, or
// TERM_HOLE for a receiver.
Term chan_park(ChanRow *row, IoWork *w, Term item);

Term chan_wake(ChanRow *row, Term x);

Term chan_take(ChanRow *row);

void chan_free(ChanRow *row);

void chan_shut(Env e, ChanRow *row);

void io_hook(void);

int io_loop(Term m);

// Value printing (for a main that is not IO), in Bend syntax
// ==========================================================

void pr_s(const char *s);
void pr_u32(V v);
void pr_nat(V v);
void pr_f32(V v);
// As the official term_show spells a character.
void pr_cp(uint32_t cp, char quote);
void pr_char(V v);
void pr_str(V v);

// Entry points
// ============

extern V (*bend_main_fn)(void);
extern void (*bend_print_fn)(V);
extern int bend_exit;

void *bend_thread(void *arg);

extern int bend_gpu;

extern const char *CLI_HELP;

void cli_fail(const char *msg);

int bend_start(int argc, char **argv, V (*m)(void), int value);

int bend_run_value(int argc, char **argv, V (*m)(void), void (*p)(V));

int bend_run(int argc, char **argv, V (*m)(void));

#endif

// The runtime was built with these ids of Base's types.
_Static_assert(CID_TUPLE == 0u && CID_DONE == 1u && CID_FAIL == 0u && CID_SOME == 1u &&
  CID_NONE == ((1u << 16) | 0u) && CID_TRUE == ((1u << 16) | 1u) && CID_FALSE == ((1u << 16) | 0u) &&
  CID_UNIT == ((1u << 16) | 0u), "Base's constructor ids differ from the runtime's: build without -DBEND_RT_SPLIT");
