#!/usr/bin/env python3
"""Writes the runtime files bendc emits into its output as Bend strings:
rt/rtjs.bend (rt/bendrt.js, for --js) and rt/gpuh.bend (rt/gpu.h, the device
code of !-calls). Run after editing either."""
import os
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def esc(line):
    out = ''
    for ch in line:
        c = ord(ch)
        if ch == '"': out += '\\"'
        elif ch == '\\': out += '\\\\'
        elif ch == '\t': out += '\\t'
        elif 32 <= c < 127: out += ch
        else: out += '\\u{%x}' % c
    return out

def bend_str(text):
    lines = text.split('\n')
    return ' ++\n  '.join('"%s\\n"' % esc(l) for l in lines)

def c_lit(text):
    # text as the lines of a C string literal
    out = []
    for l in text.split('\n'):
        out.append('"' + l.replace('\\', '\\\\').replace('"', '\\"') + '\\n"')
    return '\n'.join(out) + '\n'

CHUNK = 60  # lines a def: a C compiler nests one call per line

def write(name, source, defs):
    out = 'import Base\n\n# Generated by tools/embed.py from rt/%s: do not edit.\n' % source
    for d, text in defs:
        lines = text.split('\n')
        parts = ['\n'.join(lines[i:i + CHUNK]) for i in range(0, len(lines), CHUNK)]
        for k, part in enumerate(parts):
            out += '\ndef %s.p%d() -> String:\n  %s\n' % (d, k, bend_str(part))
        out += '\ndef %s() -> String:\n  %s\n' % (d, ' ++ '.join('%s.p%d()' % (d, k) for k in range(len(parts))))
    open(os.path.join(root, 'rt', name), 'w').write(out)

js = open(os.path.join(root, 'rt', 'bendrt.js')).read()
write('rtjs.bend', 'bendrt.js', [('src', js)])

gpu = open(os.path.join(root, 'rt', 'gpu.h')).read()
head, rest = gpu.split('//@TABLES\n')
mid, tail = rest.split('//@CASES\n')
write('gpuh.bend', 'gpu.h', [('head', head), ('mid', mid), ('tail', tail),
  ('head_lit', c_lit(head)), ('mid_lit', c_lit(mid)), ('tail_lit', c_lit(tail))])
