#!/usr/bin/env python3
"""Writes rt/rtjs.bend: rt/bendrt.js as a Bend string, so bendc --js emits
a self-contained program. Run after editing rt/bendrt.js."""
import os
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = open(os.path.join(root, 'rt', 'bendrt.js')).read()
def esc(line):
    out = ''
    for ch in line:
        c = ord(ch)
        if ch == '"': out += '\\"'
        elif ch == '\\': out += '\\\\'
        elif ch == '\t': out += '\\t'
        elif 32 <= c < 127: out += ch
        else: out += '\\u{%x}' % c
    return out
lines = src.split('\n')
body = ' ++\n  '.join('"%s\\n"' % esc(l) for l in lines)
out = '''import Base

# Generated by tools/embed_js.py from rt/bendrt.js: do not edit.

def src() -> String:
  ''' + body + '\n'
open(os.path.join(root, 'rt', 'rtjs.bend'), 'w').write(out)
