#!/usr/bin/env python3
"""Verify descriptor-flow ABI and writes; optionally compare all16 benchmarks.
BENDC BASE [--tests DIR] [--all16 SOURCE_DIR --baseline-dir DIR]
Baseline directory contains NAME-baseline.c, generated by a pinned prior compiler.
No runtime timing or source modifications are performed.
"""
import argparse,os,re,subprocess,json
from pathlib import Path
ap=argparse.ArgumentParser(description=__doc__)
ap.add_argument('bendc');ap.add_argument('base');ap.add_argument('--tests',default='tests')
ap.add_argument('--all16',type=Path);ap.add_argument('--baseline-dir',type=Path)
ap.add_argument('--receipt',type=Path)
a=ap.parse_args()
def gen(path,tail=False):
 env=dict(os.environ)
 if tail:env['BEND_OPT']='i..spfwh'
 r=subprocess.run([a.bendc,a.base,str(path)],text=True,capture_output=True,env=env,timeout=45)
 if r.returncode:raise SystemExit(r.stderr)
 return r.stdout
def code(s):return '\n'.join(line for line in s.splitlines() if not line.startswith('"'))
f=code(gen(Path(a.tests)/'gpu_array_flow.bend'))
assert len(re.findall(r'k_aiset\(c, ki0, am\d+, ki1, ki2\)',f))==2,'narrow+wide lexical writes missing'
assert 'k_aiget(c,' in f,'flow reads missing'
for family in ['word_dbridge','read_dbridge']:
 assert re.search(r'KX_'+family+r'[^\n]*\(c,[^\n]*, 0, 0, 0, 0\)',f),'unknown caller must pass zeros: '+family
t=code(gen(Path(a.tests)/'gpu_array_flow_tail.bend',True))
assert re.search(r'KW mi\d+ = \(x\d+_\d+ == a\d+ \? am\d+ : 0\)',t),'changed flow-only pointer must clear descriptor'
assert re.search(r'KX_descend_x37u\(c,[^\n]*, 0, 0, 0, 0\)',t),'unknown self-tail entry must pass zeros'
rows=[]
if a.all16:
 if not a.baseline_dir:ap.error('--all16 requires --baseline-dir')
 sources=sorted(a.all16.glob('*/main.bend'))
 assert len(sources)==16,'expected16 pinned benchmark sources'
 for src in sources:
  name=src.parent.name;before=(a.baseline_dir/(name+'-baseline.c')).read_text();after=gen(src)
  same=before==after
  assert same==(name!='editdist'),'unexpected codegen scope: '+name
  if name=='editdist':
   gpu=code(after);assert gpu.count('k_aiset(c,')==2,'editdist should have exactlytwo maskedwrite sites'
   for helper in ['init','gen']:
    m=re.search(r'K(?:NO)?INLINE [^\n]+ KX_'+helper+r'\([^\n]*\)[^{]*\{.*?(?=\nK(?:NO)?INLINE|\Z)',gpu,re.S)
    if m:assert 'k_aiset(c,' not in m.group(),'unqualified helper gained descriptor: '+helper
  rows.append(dict(benchmark=name,whole_C_unchanged=same))
if a.receipt:a.receipt.write_text(json.dumps(dict(focused='passed',all16=rows),indent=2)+'\n')
print('ok')
