#!/usr/bin/env python3
"""Splits rt/bendrt.h into rt/bendrt_split.h and rt/bendrt_impl.c, so the
runtime compiles once (make builds build/bendrt.o) and a program's C only
compiles its own code:

  clang -O2 -DBEND_RT_SPLIT -I rt prog.c build/bendrt.o -o prog

The header keeps the types, macros and static inline functions, and declares
the rest: a function's prototype, a variable as extern. The .c file defines
them. Preprocessor lines go to both, so conditionals hold in both. The runtime
reads the constructor ids of Base's types, which are the same in every
program: the split header checks them. Run after editing rt/bendrt.h."""
import os
import re

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = open(os.path.join(root, 'rt', 'bendrt.h')).read().split('\n')

hdr, impl = [], []
FN = re.compile(r'^(__attribute__\(\([^)]*\)\) )?static (?!inline)(?!const char \*CLI)([^=;]*?)\b(\w+)\(([^;]*)$')
i = 0
n = len(src)


def statement(i):
    """The lines of a top-level declaration ending with ';' at depth 0."""
    out = []
    depth = 0
    while i < n:
        line = src[i]
        out.append(line)
        code = strip_comment(line)
        depth += code.count('{') + code.count('(') - code.count('}') - code.count(')')
        i += 1
        if depth <= 0 and code.rstrip().endswith(';'):
            break
    return out, i


def strip_comment(line):
    """line without a trailing // comment (outside string literals)."""
    out, q = [], False
    for j, ch in enumerate(line):
        if ch == '"' and (j == 0 or line[j - 1] != '\\'):
            q = not q
        if not q and line.startswith('//', j):
            break
        out.append(ch)
    return ''.join(out)


def body(i):
    """The lines of a function definition from its first line."""
    out = []
    depth = 0
    started = False
    while i < n:
        line = src[i]
        out.append(line)
        depth += line.count('{') - line.count('}')
        if '{' in line:
            started = True
        i += 1
        if started and depth == 0:
            break
    return out, i


def is_function(i):
    """Whether the declaration at line i defines a function: the first '{' or
    ';' outside parentheses is a '{', after a parameter list."""
    depth = 0
    seen_paren = False
    while i < n:
        for ch in strip_comment(src[i]):
            if ch == '(':
                depth += 1
                seen_paren = True
            elif ch == ')':
                depth -= 1
            elif depth == 0 and ch == '=':
                return False
            elif depth == 0 and ch == ';':
                return False
            elif depth == 0 and ch == '{':
                return seen_paren
        i += 1
    return False


def extern_of(decl):
    """extern declarations for a static variable definition."""
    text = ' '.join(strip_comment(l).strip() for l in decl)
    text = re.sub(r'^static ', '', text)
    head = text.split('=')[0].rstrip(' ;')
    # several declarators: static int a, b;
    m = re.match(r'^((?:const |_Atomic |volatile |__thread |unsigned |struct )*[\w]+[\s\*]*)(.*)$', head)
    base, names = m.group(1), m.group(2)
    if '=' not in text and ',' in names and '(' not in names:
        return ['extern %s%s;' % (base, n.strip()) for n in names.split(',')]
    return ['extern %s;' % head]


while i < n:
    line = src[i]
    if line.startswith('#'):
        hdr.append(line)
        impl.append(line)
        i += 1
        continue
    if re.match(r'^static inline ', line) or re.match(r'^__attribute__\(\([^)]*\)\) static inline ', line):
        b, i = body(i) if line.rstrip().endswith('{') or '{' in line else statement(i)
        hdr.extend(b)
        continue
    if (line.startswith('static ') or line.startswith('__attribute__') or line.startswith('OUTLINE ')) and \
        'static inline' not in line and is_function(i):
        b, i = body(i)
        sig = ' '.join(l.strip() for l in b).split('{')[0].strip()
        sig = re.sub(r'^static ', '', re.sub(r'^(__attribute__\(\([^)]*\)\) )static ', r'\1', sig))
        hdr.append(sig + ';')
        impl.extend([re.sub(r'\bstatic ', '', b[0], count=1)] + b[1:])
        continue
    if re.match(r'^static ', line):
        # a variable (or a function prototype)
        d, i = statement(i)
        text = ' '.join(strip_comment(l).strip() for l in d)
        if re.match(r'^static [^=]*\w+\([^)]*\)\s*;$', text) and '(*' not in text:
            hdr.append(re.sub(r'^static ', '', text))
            continue
        hdr.extend(extern_of(d))
        impl.extend([re.sub(r'^static ', '', d[0])] + d[1:])
        continue
    hdr.append(line)
    i += 1

guard = '''// Generated by tools/rtsplit.py from rt/bendrt.h: do not edit.
// The runtime's declarations, for a program linked with build/bendrt.o.
#define BEND_RT_SPLIT_HEADER 1
'''
check = '''
// The runtime was built with these ids of Base's types.
_Static_assert(CID_TUPLE == 0u && CID_DONE == 1u && CID_FAIL == 0u && CID_SOME == 1u &&
  CID_NONE == ((1u << 16) | 0u) && CID_TRUE == ((1u << 16) | 1u) && CID_FALSE == ((1u << 16) | 0u) &&
  CID_UNIT == ((1u << 16) | 0u), "Base's constructor ids differ from the runtime's: build without -DBEND_RT_SPLIT");
'''
open(os.path.join(root, 'rt', 'bendrt_split.h'), 'w').write(guard + '\n'.join(hdr) + check)
open(os.path.join(root, 'rt', 'bendrt_impl.c'), 'w').write(
  '// Generated by tools/rtsplit.py from rt/bendrt.h: do not edit.\n'
  '// The runtime\'s definitions: make builds build/bendrt.o from this.\n'
  '#include "bendrt_split.h"\n' + '\n'.join(
    '#if 1' if l.startswith('#ifndef BENDRT_H') else l for l in impl
    if not l.startswith('#include') and not l.startswith('#define BENDRT_H')) + '\n')
